package contract

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	contractcheck "github.com/lycaon/lycaon/test/contract/internal/check"
)

// The shell holds no command catalog: commands, strata, default chords, and
// menu placements come from the frame. A static table that agrees with the
// declarations passes every behavior test until an extension contributes a
// command it has never heard of, so absence is asserted structurally.

// staticCatalogExports name the exported shapes of a static command catalog.
var staticCatalogExports = []*regexp.Regexp{
	regexp.MustCompile(`export const COMMANDS\b`),
	regexp.MustCompile(`export const COMMAND_BY_ID\b`),
	regexp.MustCompile(`export const APP_MENU_LAYOUT\b`),
	regexp.MustCompile(`export const APP_MENU_EXCLUDED\b`),
	regexp.MustCompile(`export const CROSSBAR_EXCLUDED\b`),
	regexp.MustCompile(`export (?:const|function) sharedDefaults\b`),
	regexp.MustCompile(`export (?:const|function) platformDefaults\b`),
	regexp.MustCompile(`export (?:const|function) defaultKeymap\b`),
	regexp.MustCompile(`export type CommandId\b`),
}

func TestShellHoldsNoCommandCatalog(t *testing.T) {
	t.Parallel()
	den := filepath.Join(contractcheck.RepoRoot(t), "lycaon-den")

	walkDenSources(t, den, func(rel string, body []byte) {
		text := string(body)
		for _, pattern := range staticCatalogExports {
			if pattern.MatchString(text) {
				t.Errorf("%s exports %s — that shape belongs to the contribution frame", rel, pattern)
			}
		}
	})
}

// A fallback that ran a handler by command name would keep working with no
// declaration behind it, so the inventory guard is the only registration seam.
func TestShellRegistersHandlersThroughOneSeam(t *testing.T) {
	t.Parallel()
	den := filepath.Join(contractcheck.RepoRoot(t), "lycaon-den")

	guard := readDenFile(t, den, "src/shortcuts/dispatcher.ts")
	if !strings.Contains(guard, "isNativeUIHandlerId(id)") {
		t.Error("registerCommandHandler does not check the generated handler inventory")
	}

	// The generated inventory is derived from the declarations; a hand-edited
	// one would let an undeclared handler register.
	inventory := readDenFile(t, den, "src/contributions/native-ui-handlers.generated.ts")
	if !strings.Contains(inventory, "Generated by cmd/codegen-contribution-inventory") {
		t.Error("the handler inventory is not generated from the declarations")
	}
}

func walkDenSources(t *testing.T, den string, visit func(rel string, body []byte)) {
	t.Helper()
	src := filepath.Join(den, "src")
	err := filepath.WalkDir(src, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		ext := filepath.Ext(path)
		if ext != ".ts" && ext != ".tsx" {
			return nil
		}
		name := d.Name()
		if strings.Contains(name, ".test.") || strings.Contains(name, ".generated.") {
			return nil
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(den, path)
		if err != nil {
			return err
		}
		visit(filepath.ToSlash(rel), body)
		return nil
	})
	contractcheck.FailErr(t, "walk Den sources", err)
}

func readDenFile(t *testing.T, den, rel string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(den, rel))
	contractcheck.FailErr(t, "read "+rel, err)
	return string(body)
}
