// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/SessionStatus.yaml

import type { SessionStatus } from "./types.ts";

/** `satisfies` makes a value added to the vocab without transitions a type error. */
const SESSION_STATUS_TRANSITIONS = {
  preparing: ["idle", "error"],
  idle: ["busy", "error"],
  busy: ["idle", "error"],
  error: ["idle", "busy"],
} as const satisfies Record<SessionStatus, readonly SessionStatus[]>;

/** States some transition leads to; the rest can only be a first state. */
const SESSION_STATUS_ENTERABLE = new Set<SessionStatus>(
  Object.values(SESSION_STATUS_TRANSITIONS).flat(),
);

/**
 * Whether the machine can enter `value` from another state. False means an
 * update carrying it arrived after the one that left it — a stale read.
 */
export function isEnterableSessionStatus(value: SessionStatus): boolean {
  return SESSION_STATUS_ENTERABLE.has(value);
}
