import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  openAPISchemaProperties,
  parseOpenAPIEnums,
  parseTSEnumUnions,
  readOpenAPIBundle,
  sortedSetEqual,
} from "./openapi-sync.ts";

const typesPath = join(dirname(fileURLToPath(import.meta.url)), "types.ts");

describe("OpenAPI enum sync", () => {
  it("generated types.ts enums match bundled OpenAPI schemas", () => {
    const yaml = readOpenAPIBundle();
    const tsSource = readFileSync(typesPath, "utf8");
    expect(tsSource).toMatch(/GENERATED by \.\/task codegen:den-types — DO NOT EDIT/);
    expect(tsSource).toContain('export type Session = components["schemas"]["Session"]');
    const tsEnums = parseTSEnumUnions(tsSource);
    const oapiEnums = parseOpenAPIEnums(yaml);

    expect(tsEnums.size).toBeGreaterThan(0);
    expect(tsEnums.get("SessionStatus")).toEqual([
      "preparing",
      "idle",
      "busy",
      "error",
    ]);
    for (const [name, tsVals] of tsEnums) {
      const oapiVals = oapiEnums.get(name);
      expect(oapiVals, `missing OpenAPI enum ${name}`).toBeDefined();
      expect(sortedSetEqual(tsVals, oapiVals!)).toBe(true);
    }
    // Every OpenAPI string enum appears in generated types.
    for (const [name, oapiVals] of oapiEnums) {
      const tsVals = tsEnums.get(name);
      expect(tsVals, `missing generated enum ${name}`).toBeDefined();
      expect(sortedSetEqual(oapiVals, tsVals!)).toBe(true);
    }
  });
});

describe("workflow span DTO contract", () => {
  it("Message includes workflow_run_id, kind, workflow_boundary, visibility", () => {
    const yaml = readOpenAPIBundle();
    const props = openAPISchemaProperties(yaml, "Message");
    for (const field of [
      "workflow_run_id",
      "workflow_boundary",
      "kind",
      "visibility",
    ]) {
      expect(props).toContain(field);
    }
    const ts = readFileSync(typesPath, "utf8");
    expect(ts).toMatch(/export type Message = components\["schemas"\]\["Message"\]/);
    expect(ts).toMatch(/workflow_run_id\?:/);
    expect(ts).toMatch(/workflow_boundary\?:/);
    expect(ts).toMatch(/\bkind\?:/);
    expect(ts).toMatch(/visibility\?:/);
  });

  it("Session has no blueprint_path", () => {
    const yaml = readOpenAPIBundle();
    const props = openAPISchemaProperties(yaml, "Session");
    expect(props).not.toContain("blueprint_path");
    const ts = readFileSync(typesPath, "utf8");
    expect(ts).toMatch(/export type Session = components\["schemas"\]\["Session"\]/);
    const sessionIdx = ts.indexOf("        Session: {");
    expect(sessionIdx).toBeGreaterThanOrEqual(0);
    const slice = ts.slice(sessionIdx, sessionIdx + 2500);
    expect(slice).not.toMatch(/blueprint_path/);
  });

  it("WorkflowRun includes span message ids", () => {
    const yaml = readOpenAPIBundle();
    const props = openAPISchemaProperties(yaml, "WorkflowRun");
    expect(props).toContain("start_message_id");
    expect(props).toContain("end_message_id");
    expect(props).toContain("blueprint_path");
  });
});

describe("tool result DTO contract", () => {
  it("ToolResult includes outcome, codes, ui_visibility, and file_edit", () => {
    const yaml = readOpenAPIBundle();
    const props = openAPISchemaProperties(yaml, "ToolResult");
    for (const field of ["outcome", "codes", "ui_visibility", "file_edit"]) {
      expect(props).toContain(field);
    }
    const snapshotProps = openAPISchemaProperties(yaml, "FileEditSnapshot");
    for (const field of ["path", "before", "after"]) {
      expect(snapshotProps).toContain(field);
    }
  });
});
