// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/FindingLedgerState.yaml

import type { FindingLedgerState } from "../api/types.ts";

/**
 * Chip labels for the ledger's state vocabulary.
 */
export const FINDING_LEDGER_STATE_LABELS = {
  open: "Open",
  reopened: "Reopened",
  fixed: "Fixed",
  not_observed: "Not observed",
  ignored: "Ignored",
  unverified: "Unverified",
} as const satisfies Record<FindingLedgerState, string>;
