// Generated by cmd/codegen-den-fonts from lycaon-den/fonts.yaml.

export type DenFontRole = "ui" | "mono";

export type DenBundledFont = {
  /** CSS family name — also the OFL reserved font name. */
  family: string;
  role: DenFontRole;
  /** One line, shown under the family in Settings. */
  description: string;
  /** The family followed by the platform fallbacks. */
  stack: string;
};

/** Platform fonts supply the system option and missing glyphs. */
export const DEN_FONT_FALLBACKS: Readonly<Record<DenFontRole, string>> = {
  ui: "system-ui, -apple-system, \"Segoe UI\", sans-serif",
  mono: "ui-monospace, \"SF Mono\", Consolas, monospace",
};

/** The family each role starts from on a fresh install. */
export const DEN_FONT_DEFAULTS: Readonly<Record<DenFontRole, string>> = {
  ui: "Inter",
  mono: "JetBrains Mono",
};

export const DEN_BUNDLED_FONTS: readonly DenBundledFont[] = [
  {
    family: "Inter",
    role: "ui",
    description: "Neutral and quiet at interface sizes.",
    stack: "\"Inter\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
  },
  {
    family: "IBM Plex Sans",
    role: "ui",
    description: "A grotesque with slab-adjacent detail; more voice than Inter.",
    stack: "\"IBM Plex Sans\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
  },
  {
    family: "Source Sans 3",
    role: "ui",
    description: "Humanist, open apertures — the most forgiving at small sizes.",
    stack: "\"Source Sans 3\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
  },
  {
    family: "DM Sans",
    role: "ui",
    description: "Geometric and low-contrast; roomy in dense chrome.",
    stack: "\"DM Sans\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
  },
  {
    family: "Space Grotesk",
    role: "ui",
    description: "Geometric with tightened, slightly odd forms. Distinctive.",
    stack: "\"Space Grotesk\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
  },
  {
    family: "Literata",
    role: "ui",
    description: "A serif drawn for screen reading, if you would rather not read a sans.",
    stack: "\"Literata\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
  },
  {
    family: "JetBrains Mono",
    role: "mono",
    description: "Tall x-height and wide glyphs, drawn for code.",
    stack: "\"JetBrains Mono\", ui-monospace, \"SF Mono\", Consolas, monospace",
  },
];
