package contract

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lycaon/lycaon/internal/extpacks"
	"github.com/lycaon/lycaon/internal/guidance"
	"github.com/lycaon/lycaon/internal/hintregistry"
	"github.com/lycaon/lycaon/internal/projectroot"
	"github.com/lycaon/lycaon/internal/tools"
	"github.com/lycaon/lycaon/internal/toolschema"
	contractcheck "github.com/lycaon/lycaon/test/contract/internal/check"
	"gopkg.in/yaml.v3"
)

type toolCommandEquivalenceFile struct {
	Entries []toolCommandEquivalenceEntry `yaml:"entries"`
}

type toolCommandEquivalenceEntry struct {
	Native             string   `yaml:"native"`
	RedirectCode       string   `yaml:"redirect_code"`
	ReplacementExample string   `yaml:"replacement_example"`
	Profiles           []string `yaml:"profiles"`
	CommandGrammar     []struct {
		Program string `yaml:"program"`
		Grammar string `yaml:"grammar"`
	} `yaml:"command_grammar"`
}

func loadToolCommandEquivalenceYAML(t *testing.T) toolCommandEquivalenceFile {
	t.Helper()
	root := contractcheck.RepoRoot(t)
	data, err := os.ReadFile(filepath.Join(root, "lycaon", "config", "packs", "painted-wolf", "platform", "tools", "tool-command-equivalence.yaml"))
	contractcheck.FailErr(t, "read tool-command-equivalence.yaml", err)
	var eq toolCommandEquivalenceFile
	contractcheck.FailErr(t, "unmarshal tool-command-equivalence.yaml", yaml.Unmarshal(data, &eq))
	if len(eq.Entries) == 0 {
		t.Fatal("tool-command-equivalence.yaml: expected entries")
	}
	return eq
}

func TestToolCommandEquivalenceYAMLMatchesNativeManifest(t *testing.T) {
	t.Parallel()
	eq := loadToolCommandEquivalenceYAML(t)
	manifest := loadNativeToolsManifestFlat(t)
	manifestSet := map[string]bool{}
	for _, name := range manifest {
		manifestSet[name] = true
	}
	root := contractcheck.RepoRoot(t)
	schemas, err := toolschema.LoadSchemaDir(filepath.Join(root, "lycaon", "config", "packs", "painted-wolf", "platform", "tools", "schemas"))
	contractcheck.FailErr(t, "LoadSchemaDir", err)
	for _, entry := range eq.Entries {
		if manifestSet[entry.Native] {
			continue
		}
		if _, ok := schemas.ToolMeta(entry.Native); ok {
			continue
		}
		t.Fatalf("equivalence native %q missing from native-tools.yaml and tools/schemas", entry.Native)
	}
}

func TestToolCommandEquivalenceRedirectCodesRegistered(t *testing.T) {
	t.Parallel()
	eq := loadToolCommandEquivalenceYAML(t)
	cfg, err := guidance.LoadValidatedHintConfig(extpacks.Bundled(hintregistry.DefaultDir))
	contractcheck.FailErr(t, "LoadValidatedHintConfig", err)
	for _, entry := range eq.Entries {
		if entry.RedirectCode == "" {
			continue // Advisory equivalences do not redirect command execution.
		}
		h, ok := cfg.HintCodes[entry.RedirectCode]
		if !ok {
			t.Fatalf("hint registry missing redirect %q for native %q", entry.RedirectCode, entry.Native)
		}
		view := guidance.NormalizeRejectCodeView(entry.RedirectCode, h)
		if strings.TrimSpace(view.What) == "" || strings.TrimSpace(view.Fix) == "" {
			t.Fatalf("hint %q missing enriched what/fix", entry.RedirectCode)
		}
		if len(h.Scenarios) == 0 {
			t.Fatalf("hint %q missing scenarios", entry.RedirectCode)
		}
	}
}

func TestToolCommandEquivalenceGeneratedMatcherPresent(t *testing.T) {
	t.Parallel()
	root := contractcheck.RepoRoot(t)
	genPath := filepath.Join(root, "lycaon", "internal", "tools", "command_equivalence_gen.go")
	data, err := os.ReadFile(genPath)
	contractcheck.FailErr(t, "read command_equivalence_gen.go", err)
	text := string(data)
	if !strings.Contains(text, "Code generated by cmd/codegen-tool-command-equivalence") {
		t.Fatal("command_equivalence_gen.go missing codegen header")
	}
	eq := loadToolCommandEquivalenceYAML(t)
	for _, entry := range eq.Entries {
		if !strings.Contains(text, entry.RedirectCode) {
			t.Fatalf("generated matcher missing redirect code %q", entry.RedirectCode)
		}
	}
}

func TestToolCommandEquivalenceMatchFindRedirect(t *testing.T) {
	t.Parallel()
	assertExactCommandReplacement(t, "tree -L 2 src", "USE_FIND_NOT_COMMAND", "find")
}

func TestToolCommandEquivalenceExactReplacementData(t *testing.T) {
	t.Parallel()
	cases := []struct {
		command string
		code    string
		tool    string
	}{
		{"cp source.txt destination.txt", "USE_COPY_NATIVE", "copy"},
		{"curl -X POST -d payload https://api.example.test/v1", "USE_HTTP_REQUEST_NATIVE", "http_request"},
	}
	for _, c := range cases {
		assertExactCommandReplacement(t, c.command, c.code, c.tool)
	}
}

func TestHTTPRequestEquivalenceFeedbackIsFirstClass(t *testing.T) {
	t.Parallel()
	eq := loadToolCommandEquivalenceYAML(t)
	for _, entry := range eq.Entries {
		if entry.Native != "http_request" {
			continue
		}
		if entry.RedirectCode != "USE_HTTP_REQUEST_NATIVE" {
			t.Fatalf("http_request redirect code = %q", entry.RedirectCode)
		}
		if !strings.Contains(entry.ReplacementExample, "http_request") || strings.Contains(strings.ToLower(entry.ReplacementExample), "curl") {
			t.Fatalf("http_request replacement example is not first-class: %q", entry.ReplacementExample)
		}
		return
	}
	t.Fatal("missing http_request equivalence entry")
}

// A redirection has no native form, so the command keeps its own execution.
func TestExactReplacementLeavesRedirectedCommandsToCommand(t *testing.T) {
	t.Parallel()
	exec := securityNativeExecutor(t)
	for _, command := range []string{"cp source.txt destination.txt 2> copy.log", "ls > listing.txt"} {
		_, err := exec.Invoke(context.Background(), "command", map[string]any{"command": command}, tools.ToolContext{
			Roots: []projectroot.RootRef{{ID: "r1", Label: "root", Path: t.TempDir(), IsPrimary: true}}, ActiveRootID: "r1", Agent: "implement",
		})
		if refusal, ok := guidance.RefusalFromError(err); ok && strings.HasPrefix(refusal.Code(), "USE_") {
			t.Fatalf("command %q redirected to %s despite its redirection", command, refusal.Code())
		}
	}
}

func assertExactCommandReplacement(t *testing.T, command, code, tool string) {
	t.Helper()
	exec := securityNativeExecutor(t)
	root := t.TempDir()
	_, err := exec.Invoke(context.Background(), "command", map[string]any{"command": command}, tools.ToolContext{
		Roots: []projectroot.RootRef{{ID: "r1", Label: "root", Path: root, IsPrimary: true}}, ActiveRootID: "r1", Agent: "implement",
	})
	refusal, ok := guidance.RefusalFromError(err)
	if err == nil || !ok {
		t.Fatalf("command %q error = %v, want structured replacement %q", command, err, code)
	}
	var details map[string]any
	if len(refusal.Facts.Feedback) > 0 {
		details = refusal.Facts.Feedback[0].Details
	}
	if refusal.Code() != code || details["suggested_tool"] != tool {
		t.Fatalf("command %q refusal = %+v, want code=%q tool=%q", command, refusal.Facts, code, tool)
	}
}

// commandEquivalenceExceptions lists native tools exempt from command redirects.
var commandEquivalenceExceptions = map[string]string{
	"git_compare":       "composite graph comparison with frozen tips, counts and all merge bases; no single command redirect",
	"write":             "no detectable command prefix (shell > / tee redirection)",
	"replace_lines":     "line-range edit; line addressing redirects via edit",
	"jq_edit":           "structured document rewrite; in-place jq/yq habits have no exact native form",
	"request_tools":     "meta tool; no command analog",
	"secret_generate":   "host-generated opaque value; no safe command analog",
	"secret_list":       "host capability metadata; no command analog",
	"secret_revoke":     "host capability lifecycle; no command analog",
	"complete_leg":      "worker closeout envelope; no command analog",
	"verify":            "host-side test runner with host-managed verdict; not a command-habit redirect",
	"survey_repo":       "composite catalog probes; no single command habit",
	"skills_read":       "catalog read; no command analog",
	"surface_note":      "transcript communication; no command analog",
	"recall":            "reads the recorded index, not the filesystem; no command analog",
	"source_history":    "reads host source ledger; distinct from commit history",
	"restore_version":   "restores retained file version from source ledger",
	"summarize":         "off-hot-path lite briefing over gathered material; no command analog",
	"render_view":       "host-rasterized visual mockup; no command analog",
	"view_image":        "host visual perception tool; no command analog",
	"view_video":        "host visual perception tool; no command analog",
	"capture_page":      "host-driven page capture; no command analog",
	"measure_page":      "host-driven page geometry probe; no command analog",
	"page_open":         "host-driven persistent page open; no command analog",
	"page_act":          "host-driven persistent page act; no command analog",
	"page_snapshot":     "host-driven persistent page snapshot; no command analog",
	"page_close":        "host-driven persistent page close; no command analog",
	"terminal_open":     "pty interactive open; command-class floor but not a habit redirect",
	"terminal_send":     "pty handle send; no command habit redirect",
	"terminal_read":     "pty handle read; no command habit redirect",
	"terminal_snapshot": "pty vt grid snapshot; no command habit redirect",
	"terminal_close":    "pty handle close; no command habit redirect",
	"process_list":      "host process discovery; command-class floor but not a habit redirect",
	"process_signal":    "host process signaling; command-class floor but not a habit redirect",
}

// TestToolCommandEquivalenceCoversEveryNativeTool asserts every native tool
// is either mapped to a redirect or explicitly excepted without overlap.
func TestToolCommandEquivalenceCoversEveryNativeTool(t *testing.T) {
	t.Parallel()
	eq := loadToolCommandEquivalenceYAML(t)
	manifest := loadNativeToolsManifestFlat(t)

	mapped := map[string]bool{}
	for _, entry := range eq.Entries {
		mapped[entry.Native] = true
	}
	manifestSet := map[string]bool{}
	for _, name := range manifest {
		manifestSet[name] = true
	}

	for _, name := range manifest {
		_, excepted := commandEquivalenceExceptions[name]
		if !mapped[name] && !excepted {
			t.Errorf("native tool %q has no command-equivalence mapping and is not in commandEquivalenceExceptions — add a tool-command-equivalence.yaml entry or except it with a reason", name)
		}
		if mapped[name] && excepted {
			t.Errorf("native tool %q is both mapped and excepted — drop it from commandEquivalenceExceptions", name)
		}
	}

	for name := range commandEquivalenceExceptions {
		if !manifestSet[name] {
			t.Errorf("commandEquivalenceExceptions lists %q which is not in native-tools.yaml — remove the stale exception", name)
		}
	}
}
