// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/CoordinatorBatchPhase.yaml

import type { CoordinatorBatchPhase } from "../../api/types.ts";

/**
 * Human labels for the coordinator's batch phases. The Progress strip chip and
 * the composer activity lane both read this table.
 */
export const BATCH_PHASE_LABELS = {
  dispatch: "Starting workers",
  integrate: "Combining results",
  synthesize: "Putting it together",
  closed: "Working on your request",
} as const satisfies Record<CoordinatorBatchPhase, string>;
