/** Completed-tool payloads for structured-output invariant tests. */
const OK = JSON.stringify({ ok: true, status: "completed" });
const GIT_STATE = { branch: "main", head: "a".repeat(40), index: "b".repeat(40), dirty: false, conflicts: [], conflicts_total: 0, conflicts_truncated: false };
const GIT_OPERATION = {
  available: true, status: "completed", attempted: true, exit_code: 0,
  before: GIT_STATE, after: GIT_STATE, after_observed: true,
  reviewed_paths: [], reviewed_paths_total: 0, reviewed_paths_truncated: false,
  diagnostics_truncated: false,
};
export const GIT_UNAVAILABLE_OUTPUT_FIXTURE = JSON.stringify({
  available: false,
  error: "not a git repository",
});

const CATALOG_OK_TOOLS = [
  "state_update",
  "state_close",
  "state_start",
  "state_query",
  "delegate_init",
  "delegate_decompose",
  "delegate_status",
  "scan_pack",
  "scan_list",
  "scan_summary",
  "scan_query",
  "scan_compare",
  "workflow_compose",
  "workflow_compose_from_template",
  "workflow_catalog_summaries",
  "workflow_persist",
  "workflow_user_feedback",
  "workflow_advance",
  "workflow_transition",
  "fanout_plan",
  "submit_verdict",
  "skills_read",
  "plan_append_review_evidence",
  "parse_extract_json",
  "parse_validate",
  "parse_evaluation",
  "parse_decomposition",
  "parse_delegation_plan",
  "wait",
  "worker_cancel",
  "answer_decision",
] as const;

export const TOOL_STRUCTURED_OUTPUT_FIXTURES: Record<string, string> = {
  read: JSON.stringify({
    path: "README.md",
    mode: "content",
    content: "1\t# Hello\n2\t\n3\tWorld\n",
    total_lines: 3,
    truncated: false,
  }),
  write: "ok",
  edit: "ok",
  replace_lines: JSON.stringify({ path: "main.go", replaced: 1 }),
  restore_version: "Restored main.go to version 0190a3c4-5b6d-7e8f-9a0b-1c2d3e4f5a6b (482 bytes)",
  jq_edit: "Wrote 1 json document(s) to config/settings.json (212 bytes)",
  code_rewrite: JSON.stringify({
    pattern: "fmt.Println($A)",
    dry_run: false,
    file_count: 1,
    total_matches: 1,
    changed: [{ path: "main.go", language: "go", matches: 1 }],
  }),
  request_tools: JSON.stringify({
    need: "decode and hash helpers",
    loaded: ["decode", "hash"],
    note: "Loaded schemas are on the next model call; this turn continues automatically.",
  }),
  // The result acknowledges the report carried in tool_args.
  complete_leg: JSON.stringify({
    recorded: true,
    leg_status: "complete",
    findings_recorded: 1,
  }),
  find: JSON.stringify({
    results: [
      { path: "src/main.go", type: "file", size: 420 },
      { path: "internal", type: "dir" },
    ],
    highlights: [{ path: "src/main.go", why: "entrypoint" }],
    digest: "find path=. total=2\n- src/main.go (file)\n- internal (dir)",
    truncated: false,
  }),
  grep: JSON.stringify({
    matches: [
      {
        path: "main.go",
        line: 1,
        content: "// TODO",
        context_before: ["package main"],
        context_after: ["func main() {}"],
      },
    ],
    digest: "grep pattern=TODO total=1\n- main.go:1",
    truncated: false,
  }),
  skills_read:
    "# Verify a change\n\nRun the scoped checks.\n\nSkill directory: /tmp/skills/verify-a-change\nFiles: references/FORMAT.md\n",
  survey_repo: JSON.stringify({
    bundle: "ssot_drift",
    path: ".",
    view: "digest",
    digest: "survey bundle=ssot_drift path=. total=1\n- env_reads (grep): 1 candidates",
    selected: 0,
    total: 1,
    probes_run: 1,
    note: "Optional highlights: curate(source=survey#N, task=<what to rank>)",
    snapshot: [
      {
        handle: "snap#1",
        kind: "grep",
        path: "main.go",
        line: 1,
        body: "[env_reads] 1: Getenv",
      },
    ],
  }),
  summarize: JSON.stringify({
    task: "how config env vars are loaded",
    pack: {
      identity: [
        { path: "internal/config/env.go", kind: "file", line_count: 120, parse_health: "ok" },
        { path: "cmd/serve/main.go", kind: "file", line_count: 60, parse_health: "ok" },
      ],
      skeleton: [
        { path: "internal/config/env.go", kind: "function", name: "FromEnv", line: 42 },
      ],
      substance: [
        {
          path: "internal/config/env.go",
          start_line: 42,
          end_line: 44,
          symbol: "FromEnv",
          body: "42: func FromEnv() Config {\n43:   return Config{Key: os.Getenv(\"LYCAON_KEY\")}\n44: }",
        },
      ],
    },
    anchors: [
      { handle: "summarize#1", path: "internal/config/env.go", line: 42, excerpt: "os.Getenv(\"LYCAON_\")" },
      { handle: "summarize#2", path: "cmd/serve/main.go", line: 18, excerpt: "cfg.FromEnv()" },
    ],
    next_actions: [
      { tool: "read", path: "internal/config/env.go", lines: "30-60", why: "see every env key parsed" },
    ],
    sources_touched: ["internal/config/env.go", "cmd/serve/main.go"],
    selected: 2,
    total: 12,
    truncated: false,
  }),
  stat: JSON.stringify({
    results: [{ path: "go.mod", mode: "644", size: 42, is_dir: false }],
  }),
  wc: JSON.stringify({
    results: [{ path: "main.go", lines: 10, bytes: 120, words: 20 }],
  }),
  list_dir: JSON.stringify({
    path: "internal",
    entries: [{ name: "api", type: "dir", mode: "755" }],
    tree: "internal\n└── api/",
    total_entries: 1,
    truncated: false,
  }),
  chmod: JSON.stringify({ paths: ["script.sh"], mode: "+x" }),
  delete: JSON.stringify({ paths: ["tmp.txt"], deleted: 1 }),
  copy: JSON.stringify({
    copies: [{ from: "a.txt", to: "b.txt", bytes: 12 }],
  }),
  move: JSON.stringify({
    moves: [{ from: "old.go", to: "new.go" }],
  }),
  mkdir: JSON.stringify({ paths: ["internal/newpkg"], created: 1 }),
  chown: JSON.stringify({ paths: ["run.sh"], owner: "current" }),
  diff: JSON.stringify({
    path_a: "old.go",
    path_b: "new.go",
    diff: "@@ -1 +1 @@\n-old\n+new\n",
    context_lines: 3,
    truncated: false,
  }),
  jq: JSON.stringify({
    path: "package.json",
    format: "json",
    query: ".scripts",
    values: [{ test: "vitest", build: "tsc" }],
    truncated: false,
  }),
  extract_archive: JSON.stringify({
    path: "vendor/sdk.zip",
    dest: "vendor/sdk",
    entries: 4,
  }),
  command: JSON.stringify({
    stages: [{ command: "go test ./...", exit_code: 0 }],
    exit_code: 0,
    tail: "ok\n",
    ok: true,
  }),
  command_output: JSON.stringify({
    handle: "handle-1",
    cursor: 0,
    next_cursor: 5,
    chunks: [
      { cursor: 0, stream: "stdout", text: "ok\n" },
      { cursor: 1, stream: "stderr", text: "warn\n" },
    ],
    running: true,
  }),
  command_stop: JSON.stringify({
    handle: "handle-1",
    stop_requested: true,
    running: false,
    exit_code: 0,
  }),
  held_result: JSON.stringify({
    handle: "held-1",
    tool: "grep",
    state: "settled",
    elapsed_ms: 1840,
    outcome: "ok",
    result: { matches: [{ path: "main.go", line: 12, text: "func main() {" }] },
  }),
  held_stop: JSON.stringify({
    handle: "held-1",
    stop_requested: true,
    running: true,
  }),
  process_list: JSON.stringify({
    processes: [
      {
        reference: "proc-ref-1",
        pid: 4242,
        parent_pid: 1,
        uid: 501,
        name: "node",
        executable: "/usr/local/bin/node",
        instance: "4242-1726000000",
      },
    ],
    next_after_pid: 0,
    unavailable: 0,
    snapshot_complete: true,
  }),
  process_signal: JSON.stringify({
    results: [
      { pid: 4242, instance: "4242-1726000000", signal: "TERM", delivered: true },
    ],
  }),
  verify: JSON.stringify({
    stages: [{ command: "./task check-fast", exit_code: 0 }],
    exit_code: 0,
    outcome: "passed",
    declared_command_match: true,
    tail: "ok\n",
  }),
  git_status: JSON.stringify({
    available: true,
    branch: "main",
    dirty: true,
    staged_count: 1,
    unstaged_count: 0,
    files: [{ path: "main.go", status: "M" }],
  }),
  git_diff: JSON.stringify({
    available: true,
    diff: "@@ -1 +1 @@\n-old\n+new\n",
  }),
  git_compare: JSON.stringify({
    base_ref: "main", head_ref: "HEAD", base_oid: "a".repeat(40), head_oid: "c".repeat(40),
    ahead: 2, behind: 0, merge_bases: ["a".repeat(40)],
  }),
  git_checkout: JSON.stringify({ ...GIT_OPERATION, after: { ...GIT_STATE, branch: "feature" } }),
  git_merge: JSON.stringify({ ...GIT_OPERATION, after: { ...GIT_STATE, head: "c".repeat(40) } }),
  git_stash: JSON.stringify({ ...GIT_OPERATION, after: { ...GIT_STATE, stash_oid: "d".repeat(40) } }),
  git_stash_list: JSON.stringify({
    available: true,
    stashes: [{ ref: "stash@{0}", oid: "d".repeat(40), subject: "Work in progress" }],
  }),
  git_log: JSON.stringify({
    available: true,
    commits: [
      {
        hash: "abc123",
        subject: "fix tests",
        author: "dev",
        date: "2026-01-01T00:00:00Z",
      },
    ],
  }),
  git_show: JSON.stringify({
    available: true,
    show: { ref: "HEAD", kind: "commit", content: "fix tests\n" },
  }),
  git_blame: JSON.stringify({
    available: true,
    lines: [{ line: 1, commit: "abc123", author: "dev", content: "package main" }],
  }),
  source_history: JSON.stringify({
    mode: "effects",
    path: "main.go",
    recorded: true,
    tip: { state: "content", sha256_12: "abc123def456", version_id: "v-1" },
    effects: [
      { actor: "user", op: "write", at: "2026-08-26 14:02 UTC", ordinal: 9 },
    ],
  }),
  git_restore: JSON.stringify({
    available: true,
    restored: ["main.go"],
  }),
  git_ref: JSON.stringify({
    available: true,
    refs: [{ ref: "HEAD", sha: "abc123def456" }],
  }),
  git_branches: JSON.stringify({
    available: true,
    branches: [{ name: "main", current: true }],
  }),
  git_commit: JSON.stringify({
    available: true,
    hash: "abc123",
    paths: ["main.go"],
  }),
  web_search: JSON.stringify({
    results: [
      {
        title: "Example",
        url: "https://example.com",
        snippet: "An example domain used in documentation.",
      },
    ],
  }),
  fetch_url: JSON.stringify({
    url: "https://example.com",
    content: "Example page",
    truncated: false,
  }),
  http_request: JSON.stringify({
    status: 202,
    final_url: "https://api.example.com/v1/jobs",
    headers: [{ name: "Content-Type", value: "application/json" }],
    duration_ms: 84,
    bytes: 17,
    sha256: "06e8c52a8a8ecdb6245df133c5e4a108b0667368acc8b3a01dfab7b42406f060",
    content_type: "application/json",
    body: '{"accepted":true}',
    body_encoding: "utf-8",
  }),
  secret_generate: JSON.stringify({
    created: true,
    value_disclosed: false,
    secret: {
      reference: "{{paintedwolf-secret:11111111-1111-4111-8111-111111111111}}",
      name: "Webhook signing key",
      scope: "chat",
      format: "base64url",
      entropy_bits: 256,
      created_at: "2026-08-31T12:00:00Z",
      state: "active",
    },
    usage: "Use the reference token in a supported outbound tool field.",
  }),
  secret_list: JSON.stringify({
    count: 1,
    values_disclosed: false,
    items: [{
      reference: "{{paintedwolf-secret:11111111-1111-4111-8111-111111111111}}",
      name: "Webhook signing key",
      scope: "chat",
      format: "base64url",
      entropy_bits: 256,
      created_at: "2026-08-31T12:00:00Z",
      state: "active",
    }],
  }),
  secret_revoke: JSON.stringify({
    revoked: true,
    value_disclosed: false,
    secret: {
      reference: "{{paintedwolf-secret:11111111-1111-4111-8111-111111111111}}",
      name: "Webhook signing key",
      scope: "chat",
      format: "base64url",
      entropy_bits: 256,
      created_at: "2026-08-31T12:00:00Z",
      state: "revoked",
    },
  }),
  handoff_init: OK,
  handoff_reserve: JSON.stringify({ paths: ["internal/foo.go"], reserved: 1 }),
  handoff_release: JSON.stringify({ paths: ["internal/foo.go"], released: 1 }),
  handoff_release_all: JSON.stringify({ released: 2 }),
  handoff_health: JSON.stringify({ healthy: true, conflicts: [] }),
  promote_overlay: JSON.stringify({
    job_id: "overlay-1",
    merge_status: "merged",
    applied: ["main.go", "util.go"],
    clean_paths: ["main.go", "util.go"],
  }),
  reject_overlay: JSON.stringify({
    ok: true,
    overlay_id: "overlay-1",
    status: "rejected",
  }),
  preview_overlay: JSON.stringify({
    job_id: "overlay-1",
    merge_status: "pending",
    path_status: [{ path: "main.go", status: "clean" }],
    clean_paths: ["main.go"],
    ready_resolutions: [
      {
        path: "util.go",
        status: "conflict",
        conflict_tier: "overlapping_edit",
        action: "keep_both",
        needs_review: false,
      },
    ],
  }),
  request_decision: JSON.stringify({
    status: "decision_requested",
    options: 2,
  }),
  extend_worker_budget: JSON.stringify({
    job_id: "job-1",
    child_session_id: "child-1",
    previous_max: 40,
    new_max: 80,
    requested_max: 60,
    tool_loops_used: 32,
  }),
  request_budget: JSON.stringify({
    status: "requested",
    max_tool_loops: 40,
    requested_max: 60,
    tool_loops_used: 32,
  }),
  decline_worker_budget: JSON.stringify({
    job_id: "job-1",
    max_tool_loops: 40,
    requested_max: 60,
    tool_loops_used: 32,
  }),
  record_finding: JSON.stringify({ status: "appended", kind: "note" }),
  recall: JSON.stringify({
    resolution: "matched",
    scope_stated: "this session and its worker legs",
    query_stated: "tool:read AND env",
    count: { value: 2, relation: "exact" },
    hits: [
      {
        handle: "read#3",
        hit_id: "hit-1",
        kind: "evidence",
        tool: "read",
        agent_type: "path-explorer",
        observed_at: "2026-08-19T20:51:31Z",
        path: "internal/config/env.go",
        line: 42,
        snippet: "FromEnv reads LYCAON_CONFIG_DIR",
        body: ["func FromEnv() Config {"],
      },
      {
        hit_id: "hit-2",
        kind: "note",
        mine: true,
        observed_at: "2026-08-19T20:52:04Z",
        snippet: "config dir resolves before the store opens",
      },
    ],
    receipt: {
      tool: "recall",
      paths_touched: 1,
      bytes_returned: 412,
      truncated: false,
      scope_hash: "9f2c1a",
    },
  }),
  update_progress: JSON.stringify({ status: "updated" }),
  pack_board: "| Phase | Status |\n| --- | --- |\n| build | active |",
  render_view: JSON.stringify({
    mime: "image/png",
    canvas: {
      fit: "content",
      width: 1280,
      height: 2127,
      frame_height: 720,
      content_height: 2127,
      complete: true,
      scale: 0.96,
    },
    caption: "Login mockup",
  }),
  view_image: JSON.stringify({
    path: "assets/logo.svg",
    mime: "image/svg+xml",
    width: 400,
    height: 300,
    scale: 1,
  }),
  view_video: JSON.stringify({
    path: "prompt-attachments/ab/bug.mp4",
    mime: "video/mp4",
    duration_ms: 12400,
    width: 1920,
    height: 1080,
    frames: [
      { at_ms: 4000, label: "0:04.0" },
      { at_ms: 4500, label: "0:04.5" },
    ],
    crop: { x: 0, y: 0, width: 960, height: 540 },
  }),
  capture_page: JSON.stringify({
    state: { url: "http://127.0.0.1:9/", title: "Clean", busy: false },
    snapshot: { url: "http://127.0.0.1:9/", title: "Clean", tree: { role: "body" } },
    log: [],
    network: [
      { method: "GET", url: "http://127.0.0.1:9/api/items", type: "fetch", failure: "net::ERR_CONNECTION_REFUSED", served_by: "route", route: 0, at_ms: 180 },
      { method: "GET", url: "http://127.0.0.1:9/", type: "document", status: 200, duration_ms: 12.5, bytes: 2048, served_by: "network", at_ms: 3 },
    ],
    errors: [{ message: "Uncaught Error: status 500", source: "http://127.0.0.1:9/app.js:12:3", at_ms: 190 }],
    routes_active: 1,
    mime: "image/png",
    width: 800,
    height: 600,
    caption: "Home",
    final_url: "http://127.0.0.1:9/",
  }),
  page_open: JSON.stringify({
    id: "page-1",
    final_url: "http://127.0.0.1:9/",
    live_pages: ["page-1"],
    max_pages: 2,
  }),
  page_act: JSON.stringify({
    id: "page-1",
    action_results: [{ ok: true, type: "click", point: { x: 80, y: 20 }, target: { tag: "button", id: "go" }, reach: { state: "receives", points_receiving: 5, points_sampled: 5 } }],
    log: [],
    network: [{ method: "GET", url: "http://127.0.0.1:9/api/items", type: "fetch", status: 500, duration_ms: 31.2, served_by: "route", route: 0, at_ms: 140 }],
    routes_active: 1,
    timeline: {
      duration_ms: 1500,
      frame_count: 24,
      visually_stable_at_ms: 900,
      visual_changes: [{ at_ms: 900, fraction: 0.31 }],
      layout_shift: { total: 0.18, count: 1, worst: { at_ms: 900, value: 0.18 }, after_input: { total: 0.01, count: 1 } },
      long_tasks: { count: 0, total_ms: 0, max_ms: 0 },
      watch: [{ selector: "#content", present: true, max_displacement_px: 120, jumps: [{ at_ms: 900, dy: 120 }], settled_at_ms: 900 }],
      requests: 1,
      failed_requests: 1,
      sheet: [{ at_ms: 0, frame: 0, why: "start" }, { at_ms: 900, frame: 11, why: "last change" }],
      actions: [{ index: 0, type: "click", label: "click #go", start_ms: 100, end_ms: 140, ok: true }],
    },
    live_pages: ["page-1"],
  }),
  page_snapshot: JSON.stringify({
    id: "page-1",
    state: { url: "http://127.0.0.1:9/", title: "Clean", busy: false },
    snapshot: { url: "http://127.0.0.1:9/", title: "Clean", tree: { role: "body" } },
    log: [],
    mime: "image/png",
    width: 800,
    height: 600,
    caption: "Held",
    final_url: "http://127.0.0.1:9/",
    live_pages: ["page-1"],
  }),
  page_close: JSON.stringify({
    id: "page-1",
    closed: true,
    live_pages: [],
  }),
  terminal_open: JSON.stringify({
    id: "pty-1",
    command: "python3 -i",
    running: true,
  }),
  terminal_send: JSON.stringify({
    id: "pty-1",
    bytes: 2,
    running: true,
  }),
  terminal_read: JSON.stringify({
    id: "pty-1",
    text: ">>> ",
    truncated: false,
    running: true,
    next_cursor: 4,
  }),
  terminal_snapshot: JSON.stringify({
    id: "pty-1",
    surface: "tui",
    state: {
      cols: 80,
      rows: 24,
      cursor_col: 0,
      cursor_row: 2,
      busy: true,
      alt_screen: true,
      running: true,
    },
    snapshot: {
      cols: 80,
      rows: 24,
      lines: ["TITLE-ROW".padEnd(80, " "), "BODY-ROW".padEnd(80, " ")],
    },
    log: ["TITLE-ROW", "BODY-ROW"],
    caption: "TUI",
    mime: "image/png",
    width: 568,
    height: 320,
  }),
  terminal_close: JSON.stringify({
    id: "pty-1",
    text: "",
    truncated: false,
    closed: true,
  }),
  measure_page: JSON.stringify({
    units: "css_px",
    viewport: { width: 1280, height: 720 },
    elements: [
      {
        selector: "#box-a",
        count: 1,
        rect: { x: 40, y: 40, width: 120, height: 60, top: 40, right: 160, bottom: 100, left: 40 },
        styles: { color: "rgb(255, 255, 255)", "background-color": "rgb(0, 0, 0)" },
        reach: { state: "covered", points_receiving: 0, points_sampled: 5, covered_by: { tag: "div", id: "scrim" } },
      },
    ],
    relations: [
      { kind: "gap", between: ["#box-a", "#box-b"], value: 20 },
      { kind: "pointer_blocked", of: "#box-a" },
    ],
    final_url: "http://127.0.0.1:9/",
  }),
  ask_user: JSON.stringify({
    status: "pending",
    phase_id: "ask-test-1",
    prompt: "Which API style?",
    response_type: "text",
  }),
  surface_note: JSON.stringify({
    status: "noted",
    message_id: "note-1",
  }),
  ...Object.fromEntries(CATALOG_OK_TOOLS.map((tool) => [tool, OK])),
};

/** Wire-compacted tool payloads — mirrors Go chunk compactor residue shapes. */
export const TOOL_COMPACTION_FIXTURES: Record<string, string> = {
  find_spill_list: `[compacted tool_result — list page]\n[find#1]\n${JSON.stringify({
    results: [
      { path: "plans/item_0.md", type: "file" },
      { path: "plans/item_39.md", type: "file" },
      { path: "plans/item_460.md", type: "file" },
      { path: "plans/item_499.md", type: "file" },
    ],
    results_total: 500,
    results_truncated: true,
    results_omitted_range: { from: 40, to: 460 },
    wire_spill_path: "tool-output/find-abc.json",
  })}`,
  summarize_spill_pointer: `[compacted tool_result — summarize pack ~12000 tokens; full pack at wire_spill_path]\n[summarize#1]\n${JSON.stringify({
    wire_spill_path: "tool-output/summarize-abc.json",
    task: "how env vars load",
    selected: 2,
    total: 12,
    truncated: true,
  })}`,
  read_verbatim_head_tail: `[compacted tool_result — original ~8000 tokens; map + verbatim head/tail below are the working set]\n\nverbatim head/tail:\n[read#1]\n${JSON.stringify({
    path: "README.md",
    mode: "content",
    content: "1\t# Demo\n2\t\n3\tExample project readme.\n",
    total_lines: 120,
    truncated: true,
  })}`,
};

/** Spill-path-only payloads (no compaction banner) — overlay promote, etc. */
export const TOOL_SPILL_FIXTURES: Record<string, string> = {
  promote_overlay_spill: JSON.stringify({
    job_id: "overlay-1",
    merge_status: "pending",
    spill_path: "promote-spills/job-mix.json",
    path_status: [{ path: "main.go", status: "conflict", hunk_count: 2 }],
  }),
};

/** Agent guidance rejects use markdown-only presentation (no raw dropdown). */
export const TOOL_GUIDANCE_OUTPUT_FIXTURE =
  "Rejected: COORDINATOR_READ_OUTSIDE_SCOPE\nCode: COORDINATOR_READ_OUTSIDE_SCOPE";
