// Command codegen-tool-presentation emits tool presentation catalogs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"

	"github.com/lycaon/lycaon/internal/toolschema"
)

func main() {
	root := flag.String("root", ".", "lycaon module root (contains config/)")
	outTS := flag.String("out-ts", "", "output path for tool-presentation.generated.ts")
	outGo := flag.String("out-go", "", "output path for visibility.generated.go")
	check := flag.Bool("check", false, "exit 1 if the output is stale")
	flag.Parse()

	if *outTS == "" {
		fatal(fmt.Errorf("--out-ts is required"))
	}
	if *outGo == "" {
		fatal(fmt.Errorf("--out-go is required"))
	}

	absRoot, err := filepath.Abs(*root)
	if err != nil {
		fatal(err)
	}

	schemas, err := toolschema.LoadSchemaDir(schemaDirPath(absRoot))
	if err != nil {
		fatal(err)
	}
	cfg, err := Load(configFilePath(absRoot))
	if err != nil {
		fatal(err)
	}
	if err := cfg.Validate(schemas); err != nil {
		fatal(err)
	}

	tsBody := renderTS(cfg)
	goBody := renderGo(cfg)
	if *check {
		checkGenerated(*outTS, tsBody)
		checkGenerated(*outGo, goBody)
		_, _ = os.Stdout.WriteString("tool presentation codegen OK\n")
		return
	}
	writeGenerated(*outTS, tsBody)
	writeGenerated(*outGo, goBody)
}

func renderTS(cfg Config) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by codegen-tool-presentation. DO NOT EDIT.\n")
	b.WriteString("// Source: lycaon/config/packs/painted-wolf/platform/tools/tool-presentation.yaml\n\n")

	writeStringArray(&b, "FALLBACK_CHICKLET_TITLE_KEYS", cfg.FallbackTitleKeys)
	b.WriteString("\n")

	b.WriteString("export const TOOL_TITLE_FALLBACKS: Readonly<Record<string, string>> = {\n")
	for _, name := range sortedKeys(cfg.Tools) {
		if label := cfg.Tools[name].TitleFallback; label != "" {
			fmt.Fprintf(&b, "%s: %q,\n", tsKey(name), label)
		}
	}
	b.WriteString("};\n\n")
	b.WriteString("/** Ordered arg keys for a one-line tool subtitle. */\n")
	b.WriteString("export const TOOL_CHICKLET_TITLE_KEYS: Readonly<\n")
	b.WriteString("  Record<string, readonly string[]>\n")
	b.WriteString("> = {\n")
	titleKeys := cfg.TitleKeys()
	for _, name := range sortedKeys(titleKeys) {
		b.WriteString("  ")
		b.WriteString(tsKey(name))
		b.WriteString(": [")
		for i, key := range titleKeys[name] {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(key))
		}
		b.WriteString("],\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Card rendering family — omitted tools render as \"generic\". */\n")
	b.WriteString("export const TOOL_CARD_KINDS: Readonly<\n")
	b.WriteString("  Record<string, string>\n")
	b.WriteString("> = {\n")
	kinds := cfg.Kinds()
	for _, name := range sortedKeys(kinds) {
		b.WriteString("  ")
		b.WriteString(tsKey(name))
		b.WriteString(": ")
		b.WriteString(strconv.Quote(string(kinds[name])))
		b.WriteString(",\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Entry kind a tool's path argument addresses; omitted tools declare none. */\n")
	b.WriteString("export const TOOL_PATH_ENTRY_KINDS: Readonly<\n")
	b.WriteString("  Record<string, \"file\" | \"folder\">\n")
	b.WriteString("> = {\n")
	pathEntries := cfg.PathEntries()
	for _, name := range sortedKeys(pathEntries) {
		b.WriteString("  ")
		b.WriteString(tsKey(name))
		b.WriteString(": ")
		b.WriteString(strconv.Quote(string(pathEntries[name])))
		b.WriteString(",\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("/** In-flight label shown while a tool is running. */\n")
	b.WriteString("export const TOOL_CHICKLET_RUNNING_LABELS: Readonly<\n")
	b.WriteString("  Record<string, string>\n")
	b.WriteString("> = {\n")
	labels := cfg.RunningLabels()
	for _, name := range sortedKeys(labels) {
		b.WriteString("  ")
		b.WriteString(tsKey(name))
		b.WriteString(": ")
		b.WriteString(strconv.Quote(labels[name]))
		b.WriteString(",\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Parent-chat hidden tools. */\n")
	writeStringArray(&b, "COORDINATOR_INTERNAL_TOOLS", cfg.ToolsWithVisibility(VisibilityCoordinatorInternal))
	b.WriteString("\n")

	b.WriteString("/** Tools visible throughout execution. */\n")
	writeStringArray(&b, "LONG_RUNNING_COORDINATOR_TOOLS", cfg.ToolsWithVisibility(VisibilityLongRunning))
	b.WriteString("\n")

	b.WriteString("/** Worker-dispatch tools. */\n")
	writeStringArray(&b, "TASK_DISPATCH_TOOLS", cfg.ToolsWithKind(KindTask))
	b.WriteString("\n")

	roles := ActivityRoles()
	b.WriteString("export type ToolActivityRole =\n")
	for i, role := range roles {
		b.WriteString("  | ")
		b.WriteString(strconv.Quote(string(role)))
		if i == len(roles)-1 {
			b.WriteString(";")
		}
		b.WriteString("\n")
	}
	b.WriteString("\n/** Role headline rank by intent specificity; a span keeps its highest tier. */\n")
	b.WriteString("export const ACTIVITY_ROLE_TIERS: Readonly<Record<ToolActivityRole, number>> = {\n")
	for _, role := range roles {
		b.WriteString("  ")
		b.WriteString(tsKey(string(role)))
		b.WriteString(": ")
		b.WriteString(strconv.Itoa(role.Tier()))
		b.WriteString(",\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("export type ToolActivityPresentation = {\n")
	b.WriteString("  headline: string;\n")
	b.WriteString("  weight: number;\n")
	b.WriteString("  role?: ToolActivityRole;\n")
	b.WriteString("};\n\n")
	b.WriteString("/** Weighted headline vote contributed by each tool call. */\n")
	b.WriteString("export const TOOL_ACTIVITY_PRESENTATION: Readonly<\n")
	b.WriteString("  Record<string, ToolActivityPresentation>\n")
	b.WriteString("> = {\n")
	activities := cfg.ActivityPresentations()
	for _, name := range sortedKeys(activities) {
		activity := activities[name]
		b.WriteString("  ")
		b.WriteString(tsKey(name))
		b.WriteString(": { headline: ")
		b.WriteString(strconv.Quote(activity.Headline))
		b.WriteString(", weight: ")
		b.WriteString(strconv.Itoa(activity.Weight()))
		if activity.Role != "" {
			b.WriteString(", role: ")
			b.WriteString(strconv.Quote(string(activity.Role)))
		}
		b.WriteString(" },\n")
	}
	b.WriteString("};\n")

	return b.Bytes()
}

func writeStringArray(b *bytes.Buffer, name string, values []string) {
	b.WriteString("export const ")
	b.WriteString(name)
	b.WriteString(": readonly string[] = [\n")
	for _, value := range values {
		b.WriteString("  ")
		b.WriteString(strconv.Quote(value))
		b.WriteString(",\n")
	}
	b.WriteString("] as const;\n")
}

// tsKey quotes a map key only when it is not a bare JS identifier.
func tsKey(name string) string {
	for i, r := range name {
		isLower := r >= 'a' && r <= 'z'
		isDigit := r >= '0' && r <= '9'
		if isLower || r == '_' || (isDigit && i > 0) {
			continue
		}
		return strconv.Quote(name)
	}
	if name == "" {
		return strconv.Quote(name)
	}
	return name
}

func renderGo(cfg Config) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by codegen-tool-presentation. DO NOT EDIT.\n")
	b.WriteString("// Source: lycaon/config/packs/painted-wolf/platform/tools/tool-presentation.yaml\n\n")
	b.WriteString("package toolpresentation\n\n")
	b.WriteString("import \"strings\"\n\n")
	b.WriteString("var longRunningSet = map[string]struct{}{\n")
	for _, name := range cfg.ToolsWithVisibility(VisibilityLongRunning) {
		b.WriteString("\t")
		b.WriteString(strconv.Quote(name))
		b.WriteString(": {},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// IsLongRunning reports whether tool activity is visible before its result.\n")
	b.WriteString("func IsLongRunning(name string) bool {\n")
	b.WriteString("\t_, ok := longRunningSet[strings.ToLower(strings.TrimSpace(name))]\n")
	b.WriteString("\treturn ok\n")
	b.WriteString("}\n")
	b.WriteString("\nvar activityRoles = map[string]string{\n")
	presentations := cfg.ActivityPresentations()
	for _, name := range sortedKeys(presentations) {
		if role := presentations[name].Role; role != "" {
			fmt.Fprintf(&b, "%q: %q,\n", name, string(role))
		}
	}
	b.WriteString("}\n\n")
	b.WriteString("// Role is the activity role a tool declares, or empty.\n")
	b.WriteString("func Role(name string) string {\n")
	b.WriteString("\treturn activityRoles[strings.ToLower(strings.TrimSpace(name))]\n")
	b.WriteString("}\n")
	b.WriteString("\nvar titleFallbacks = map[string]string{\n")
	for _, name := range sortedKeys(cfg.Tools) {
		if label := cfg.Tools[name].TitleFallback; label != "" {
			fmt.Fprintf(&b, "%q: %q,\n", name, label)
		}
	}
	b.WriteString("}\n")
	b.WriteString("\nvar titleKeys = map[string][]string{\n")
	keys := cfg.TitleKeys()
	for _, name := range sortedKeys(keys) {
		fmt.Fprintf(&b, "%q: {", name)
		for _, key := range keys[name] {
			fmt.Fprintf(&b, "%q,", key)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\nvar fallbackTitleKeys = []string{")
	for _, key := range cfg.FallbackTitleKeys {
		fmt.Fprintf(&b, "%q,", key)
	}
	b.WriteString("}\nvar taskTools = map[string]bool{\n")
	for _, name := range cfg.ToolsWithKind(KindTask) {
		fmt.Fprintf(&b, "%q: true,\n", name)
	}
	b.WriteString("}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fatal(fmt.Errorf("gofmt generated visibility: %w", err))
	}
	return formatted
}

func checkGenerated(path string, body []byte) {
	existing, err := os.ReadFile(path) // #nosec G304 -- path from Taskfile
	if err != nil || !bytes.Equal(existing, body) {
		fatal(fmt.Errorf("stale %s — run ./task codegen:tool-presentation", path))
	}
}

func writeGenerated(path string, body []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(path, body, 0o600); err != nil { // #nosec G306 -- generated artifact
		fatal(err)
	}
	_, _ = os.Stdout.WriteString("wrote " + path + "\n")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
