// Code generated by codegen-operations. DO NOT EDIT.

package api

// contractVersion is the Host API contract this build serves (OpenAPI info.version).
const contractVersion = "1.0.0"

type generatedOperation struct {
	ID     string
	Method string
	Path   string
	// Params are the path parameter names in template order.
	Params []string
	// RecordsPersonAction records each completed call as a person action.
	RecordsPersonAction bool
}

var (
	operationAbortDelegation                    = generatedOperation{ID: "abortDelegation", Method: "POST", Path: "/v1/delegations/{id}/abort", Params: []string{"id"}, RecordsPersonAction: true}
	operationAbortSession                       = generatedOperation{ID: "abortSession", Method: "POST", Path: "/v1/sessions/{id}/abort", Params: []string{"id"}, RecordsPersonAction: true}
	operationAcceptExtensionSuggestions         = generatedOperation{ID: "acceptExtensionSuggestions", Method: "POST", Path: "/v1/extensions/suggestions/accept", RecordsPersonAction: true}
	operationAdvanceWorkflowRun                 = generatedOperation{ID: "advanceWorkflowRun", Method: "POST", Path: "/v1/workflow-runs/{id}/advance", Params: []string{"id"}, RecordsPersonAction: true}
	operationApplyExtensionMetaPack             = generatedOperation{ID: "applyExtensionMetaPack", Method: "POST", Path: "/v1/extensions/meta-packs/{meta_pack_id}/apply", Params: []string{"meta_pack_id"}, RecordsPersonAction: true}
	operationApplyExtensionPackProfile          = generatedOperation{ID: "applyExtensionPackProfile", Method: "POST", Path: "/v1/extensions/packs/{pack_id}/profiles/{profile_name}/apply", Params: []string{"pack_id", "profile_name"}, RecordsPersonAction: true}
	operationApplyExtensionPackUpdate           = generatedOperation{ID: "applyExtensionPackUpdate", Method: "POST", Path: "/v1/extensions/packs/{pack_id}/update", Params: []string{"pack_id"}, RecordsPersonAction: true}
	operationApplySearchReplacement             = generatedOperation{ID: "applySearchReplacement", Method: "POST", Path: "/v1/search/replace/apply", RecordsPersonAction: true}
	operationApplySourceViewIntent              = generatedOperation{ID: "applySourceViewIntent", Method: "POST", Path: "/v1/projects/{id}/source/views/{view_id}/apply", Params: []string{"id", "view_id"}}
	operationApproveBlueprint                   = generatedOperation{ID: "approveBlueprint", Method: "POST", Path: "/v1/projects/{id}/blueprints/{blueprint_id}/approve", Params: []string{"id", "blueprint_id"}, RecordsPersonAction: true}
	operationAssessProjectRemoval               = generatedOperation{ID: "assessProjectRemoval", Method: "GET", Path: "/v1/projects/{id}/removal-assessment", Params: []string{"id"}}
	operationAttachProjectRoot                  = generatedOperation{ID: "attachProjectRoot", Method: "POST", Path: "/v1/projects/{id}/roots", Params: []string{"id"}, RecordsPersonAction: true}
	operationBeginCheckpointUnlockChallenge     = generatedOperation{ID: "beginCheckpointUnlockChallenge", Method: "POST", Path: "/v1/sessions/{id}/checkpoints/{checkpoint_id}/unlock-challenges", Params: []string{"id", "checkpoint_id"}}
	operationBeginProjectManagedSecretReveal    = generatedOperation{ID: "beginProjectManagedSecretReveal", Method: "POST", Path: "/v1/projects/{id}/secrets/{secret_id}/reveal-challenges", Params: []string{"id", "secret_id"}}
	operationBindGitWorktree                    = generatedOperation{ID: "bindGitWorktree", Method: "PUT", Path: "/v1/sessions/{id}/git-worktree", Params: []string{"id"}, RecordsPersonAction: true}
	operationBrowseProjectSource                = generatedOperation{ID: "browseProjectSource", Method: "GET", Path: "/v1/projects/{id}/source/browse", Params: []string{"id"}}
	operationCancelMcpOAuth                     = generatedOperation{ID: "cancelMcpOAuth", Method: "POST", Path: "/v1/mcp/providers/{provider_id}/oauth/cancel", Params: []string{"provider_id"}}
	operationCancelProjectPromotion             = generatedOperation{ID: "cancelProjectPromotion", Method: "DELETE", Path: "/v1/projects/{id}/promotion", Params: []string{"id"}, RecordsPersonAction: true}
	operationCancelSourceOperation              = generatedOperation{ID: "cancelSourceOperation", Method: "POST", Path: "/v1/projects/{id}/source/operations/{operation_id}/cancel", Params: []string{"id", "operation_id"}, RecordsPersonAction: true}
	operationCancelWorker                       = generatedOperation{ID: "cancelWorker", Method: "POST", Path: "/v1/workers/{id}/cancel", Params: []string{"id"}, RecordsPersonAction: true}
	operationCancelWorkflowRun                  = generatedOperation{ID: "cancelWorkflowRun", Method: "POST", Path: "/v1/workflow-runs/{id}/cancel", Params: []string{"id"}, RecordsPersonAction: true}
	operationCheckMcpProviders                  = generatedOperation{ID: "checkMcpProviders", Method: "POST", Path: "/v1/mcp/providers/check"}
	operationCheckScanners                      = generatedOperation{ID: "checkScanners", Method: "POST", Path: "/v1/scanners/check"}
	operationCheckoutGit                        = generatedOperation{ID: "checkoutGit", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/checkout", Params: []string{"id", "repo_id"}, RecordsPersonAction: true}
	operationClearLocalData                     = generatedOperation{ID: "clearLocalData", Method: "POST", Path: "/v1/local-data/clear", RecordsPersonAction: true}
	operationCloneProject                       = generatedOperation{ID: "cloneProject", Method: "POST", Path: "/v1/projects/clone", RecordsPersonAction: true}
	operationCommitGit                          = generatedOperation{ID: "commitGit", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/commit", Params: []string{"id", "repo_id"}, RecordsPersonAction: true}
	operationCompactSession                     = generatedOperation{ID: "compactSession", Method: "POST", Path: "/v1/sessions/{id}/compact", Params: []string{"id"}, RecordsPersonAction: true}
	operationCompleteMcpOAuth                   = generatedOperation{ID: "completeMcpOAuth", Method: "POST", Path: "/v1/mcp/providers/{provider_id}/oauth/complete", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationCompleteProjectManagedSecretReveal = generatedOperation{ID: "completeProjectManagedSecretReveal", Method: "POST", Path: "/v1/projects/{id}/secrets/{secret_id}/reveal-challenges/{challenge_id}/complete", Params: []string{"id", "secret_id", "challenge_id"}, RecordsPersonAction: true}
	operationCompleteProjectSourcePresentation  = generatedOperation{ID: "completeProjectSourcePresentation", Method: "POST", Path: "/v1/projects/{id}/source/seen", Params: []string{"id"}}
	operationComposeWorkflow                    = generatedOperation{ID: "composeWorkflow", Method: "POST", Path: "/v1/sessions/{id}/workflows/compose", Params: []string{"id"}, RecordsPersonAction: true}
	operationComposeWorkflowFromTemplate        = generatedOperation{ID: "composeWorkflowFromTemplate", Method: "POST", Path: "/v1/sessions/{id}/workflows/compose-from-template", Params: []string{"id"}, RecordsPersonAction: true}
	operationCopyProjectSource                  = generatedOperation{ID: "copyProjectSource", Method: "POST", Path: "/v1/projects/{id}/source/copy", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateApprovalGrant                = generatedOperation{ID: "createApprovalGrant", Method: "POST", Path: "/v1/approval-grants", RecordsPersonAction: true}
	operationCreateBlueprint                    = generatedOperation{ID: "createBlueprint", Method: "POST", Path: "/v1/projects/{id}/blueprints", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateComposerSecret               = generatedOperation{ID: "createComposerSecret", Method: "POST", Path: "/v1/sessions/{id}/composer-secrets", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateDelegation                   = generatedOperation{ID: "createDelegation", Method: "POST", Path: "/v1/delegations", RecordsPersonAction: true}
	operationCreateEditorDocumentSnapshot       = generatedOperation{ID: "createEditorDocumentSnapshot", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/snapshots", Params: []string{"id", "document_id"}}
	operationCreateGitRepo                      = generatedOperation{ID: "createGitRepo", Method: "POST", Path: "/v1/projects/{id}/git/repos", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateHistoryProtection            = generatedOperation{ID: "createHistoryProtection", Method: "POST", Path: "/v1/history-storage/protections", RecordsPersonAction: true}
	operationCreateMcpProvider                  = generatedOperation{ID: "createMcpProvider", Method: "POST", Path: "/v1/mcp/providers", RecordsPersonAction: true}
	operationCreateProject                      = generatedOperation{ID: "createProject", Method: "POST", Path: "/v1/projects", RecordsPersonAction: true}
	operationCreateProjectFindingIgnore         = generatedOperation{ID: "createProjectFindingIgnore", Method: "POST", Path: "/v1/projects/{id}/findings/ignores", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateProjectManagedSecret         = generatedOperation{ID: "createProjectManagedSecret", Method: "POST", Path: "/v1/projects/{id}/secrets", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateProjectRemoval               = generatedOperation{ID: "createProjectRemoval", Method: "POST", Path: "/v1/projects/{id}/removals", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateProjectSecretIgnore          = generatedOperation{ID: "createProjectSecretIgnore", Method: "POST", Path: "/v1/projects/{id}/secret-ignores", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateProjectSourceEntry           = generatedOperation{ID: "createProjectSourceEntry", Method: "POST", Path: "/v1/projects/{id}/source", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateProjectSourcePin             = generatedOperation{ID: "createProjectSourcePin", Method: "POST", Path: "/v1/projects/{id}/source/pins", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateProvider                     = generatedOperation{ID: "createProvider", Method: "POST", Path: "/v1/providers", RecordsPersonAction: true}
	operationCreateScanner                      = generatedOperation{ID: "createScanner", Method: "POST", Path: "/v1/scanners", RecordsPersonAction: true}
	operationCreateSession                      = generatedOperation{ID: "createSession", Method: "POST", Path: "/v1/sessions", RecordsPersonAction: true}
	operationCreateSessionArtifact              = generatedOperation{ID: "createSessionArtifact", Method: "POST", Path: "/v1/sessions/{id}/artifacts", Params: []string{"id"}, RecordsPersonAction: true}
	operationCreateSourcePresentation           = generatedOperation{ID: "createSourcePresentation", Method: "POST", Path: "/v1/projects/{id}/source/views/{view_id}/presentations", Params: []string{"id", "view_id"}}
	operationCreateSourceView                   = generatedOperation{ID: "createSourceView", Method: "POST", Path: "/v1/projects/{id}/source/views", Params: []string{"id"}}
	operationDeleteBlueprint                    = generatedOperation{ID: "deleteBlueprint", Method: "DELETE", Path: "/v1/projects/{id}/blueprints/{blueprint_id}", Params: []string{"id", "blueprint_id"}, RecordsPersonAction: true}
	operationDeleteDetectionPack                = generatedOperation{ID: "deleteDetectionPack", Method: "DELETE", Path: "/v1/detection-packs/{pack_id}", Params: []string{"pack_id"}, RecordsPersonAction: true}
	operationDeleteExtensionMetaPack            = generatedOperation{ID: "deleteExtensionMetaPack", Method: "DELETE", Path: "/v1/extensions/meta-packs/{meta_pack_id}", Params: []string{"meta_pack_id"}, RecordsPersonAction: true}
	operationDeleteExtensionPack                = generatedOperation{ID: "deleteExtensionPack", Method: "DELETE", Path: "/v1/extensions/packs/{pack_id}", Params: []string{"pack_id"}, RecordsPersonAction: true}
	operationDeleteGitWorktree                  = generatedOperation{ID: "deleteGitWorktree", Method: "DELETE", Path: "/v1/sessions/{id}/git-worktree", Params: []string{"id"}, RecordsPersonAction: true}
	operationDeleteHistoryProtection            = generatedOperation{ID: "deleteHistoryProtection", Method: "DELETE", Path: "/v1/history-storage/protections/{protection_id}", Params: []string{"protection_id"}, RecordsPersonAction: true}
	operationDeleteMcpProvider                  = generatedOperation{ID: "deleteMcpProvider", Method: "DELETE", Path: "/v1/mcp/providers/{provider_id}", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationDeleteProjectArtifact              = generatedOperation{ID: "deleteProjectArtifact", Method: "DELETE", Path: "/v1/projects/{id}/artifacts/{artifact_id}", Params: []string{"id", "artifact_id"}, RecordsPersonAction: true}
	operationDeleteProjectFindingIgnore         = generatedOperation{ID: "deleteProjectFindingIgnore", Method: "DELETE", Path: "/v1/projects/{id}/findings/ignores/{entry_id}", Params: []string{"id", "entry_id"}, RecordsPersonAction: true}
	operationDeleteProjectSecretIgnore          = generatedOperation{ID: "deleteProjectSecretIgnore", Method: "DELETE", Path: "/v1/projects/{id}/secret-ignores/{entry_id}", Params: []string{"id", "entry_id"}, RecordsPersonAction: true}
	operationDeleteProjectSource                = generatedOperation{ID: "deleteProjectSource", Method: "DELETE", Path: "/v1/projects/{id}/source", Params: []string{"id"}, RecordsPersonAction: true}
	operationDeleteProjectSourcePin             = generatedOperation{ID: "deleteProjectSourcePin", Method: "DELETE", Path: "/v1/projects/{id}/source/pins/{pin_id}", Params: []string{"id", "pin_id"}, RecordsPersonAction: true}
	operationDeleteProvider                     = generatedOperation{ID: "deleteProvider", Method: "DELETE", Path: "/v1/providers/{provider_id}", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationDeleteProviderCredential           = generatedOperation{ID: "deleteProviderCredential", Method: "DELETE", Path: "/v1/providers/{provider_id}/credential", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationDeleteScanner                      = generatedOperation{ID: "deleteScanner", Method: "DELETE", Path: "/v1/scanners/{scanner_id}", Params: []string{"scanner_id"}, RecordsPersonAction: true}
	operationDeleteSession                      = generatedOperation{ID: "deleteSession", Method: "DELETE", Path: "/v1/sessions/{id}", Params: []string{"id"}, RecordsPersonAction: true}
	operationDeleteWebResearchCredential        = generatedOperation{ID: "deleteWebResearchCredential", Method: "DELETE", Path: "/v1/web-research/providers/{provider_id}/credential", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationDetachProjectRoot                  = generatedOperation{ID: "detachProjectRoot", Method: "DELETE", Path: "/v1/projects/{id}/roots/{root_id}", Params: []string{"id", "root_id"}, RecordsPersonAction: true}
	operationDetectFolder                       = generatedOperation{ID: "detectFolder", Method: "GET", Path: "/v1/projects/detect"}
	operationDigestSourceComparisons            = generatedOperation{ID: "digestSourceComparisons", Method: "POST", Path: "/v1/projects/{id}/source/comparison-digests", Params: []string{"id"}}
	operationDiscardEditorDocument              = generatedOperation{ID: "discardEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/discard", Params: []string{"id", "document_id"}, RecordsPersonAction: true}
	operationDiscardGit                         = generatedOperation{ID: "discardGit", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/discard", Params: []string{"id", "repo_id"}, RecordsPersonAction: true}
	operationDismissVerifySettings              = generatedOperation{ID: "dismissVerifySettings", Method: "POST", Path: "/v1/settings/verify/dismiss", RecordsPersonAction: true}
	operationDispatchDelegationLeg              = generatedOperation{ID: "dispatchDelegationLeg", Method: "POST", Path: "/v1/delegations/{id}/dispatch", Params: []string{"id"}, RecordsPersonAction: true}
	operationDraftGitCommitMessage              = generatedOperation{ID: "draftGitCommitMessage", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/commit-message", Params: []string{"id", "repo_id"}}
	operationExitWorkflowRun                    = generatedOperation{ID: "exitWorkflowRun", Method: "POST", Path: "/v1/workflow-runs/{id}/exit", Params: []string{"id"}, RecordsPersonAction: true}
	operationExportBackup                       = generatedOperation{ID: "exportBackup", Method: "GET", Path: "/v1/backup"}
	operationExportCodeScanSARIF                = generatedOperation{ID: "exportCodeScanSARIF", Method: "GET", Path: "/v1/projects/{id}/scans/{scan_id}/sarif", Params: []string{"id", "scan_id"}}
	operationExportDiagnostics                  = generatedOperation{ID: "exportDiagnostics", Method: "GET", Path: "/v1/diagnostics/export"}
	operationExportProjectFindings              = generatedOperation{ID: "exportProjectFindings", Method: "POST", Path: "/v1/projects/{id}/findings/export", Params: []string{"id"}}
	operationExportSearchResults                = generatedOperation{ID: "exportSearchResults", Method: "POST", Path: "/v1/search/export"}
	operationExportSessionTranscript            = generatedOperation{ID: "exportSessionTranscript", Method: "GET", Path: "/v1/sessions/{id}/export", Params: []string{"id"}}
	operationFireWorkflowTransition             = generatedOperation{ID: "fireWorkflowTransition", Method: "POST", Path: "/v1/workflow-runs/{id}/transitions/{transition_id}", Params: []string{"id", "transition_id"}, RecordsPersonAction: true}
	operationGetActiveWorkflowRun               = generatedOperation{ID: "getActiveWorkflowRun", Method: "GET", Path: "/v1/sessions/{id}/workflow-runs/active", Params: []string{"id"}}
	operationGetAgentPresence                   = generatedOperation{ID: "getAgentPresence", Method: "GET", Path: "/v1/projects/{id}/agent-presence", Params: []string{"id"}}
	operationGetApprovalsSettings               = generatedOperation{ID: "getApprovalsSettings", Method: "GET", Path: "/v1/settings/approvals"}
	operationGetAttention                       = generatedOperation{ID: "getAttention", Method: "GET", Path: "/v1/attention"}
	operationGetBackupCapabilities              = generatedOperation{ID: "getBackupCapabilities", Method: "GET", Path: "/v1/backup/capabilities"}
	operationGetBlueprint                       = generatedOperation{ID: "getBlueprint", Method: "GET", Path: "/v1/projects/{id}/blueprints/{blueprint_id}", Params: []string{"id", "blueprint_id"}}
	operationGetBoard                           = generatedOperation{ID: "getBoard", Method: "GET", Path: "/v1/projects/{id}/board", Params: []string{"id"}}
	operationGetChatContent                     = generatedOperation{ID: "getChatContent", Method: "GET", Path: "/v1/sessions/{id}/messages/{message_id}/content", Params: []string{"id", "message_id"}}
	operationGetChatVault                       = generatedOperation{ID: "getChatVault", Method: "GET", Path: "/v1/sessions/{id}/vault", Params: []string{"id"}}
	operationGetCodeScan                        = generatedOperation{ID: "getCodeScan", Method: "GET", Path: "/v1/projects/{id}/scans/{scan_id}", Params: []string{"id", "scan_id"}}
	operationGetContributions                   = generatedOperation{ID: "getContributions", Method: "GET", Path: "/v1/contributions"}
	operationGetCoordinatorContext              = generatedOperation{ID: "getCoordinatorContext", Method: "GET", Path: "/v1/sessions/{id}/coordinator-context", Params: []string{"id"}}
	operationGetCostSummary                     = generatedOperation{ID: "getCostSummary", Method: "GET", Path: "/v1/cost/summary"}
	operationGetDelegation                      = generatedOperation{ID: "getDelegation", Method: "GET", Path: "/v1/delegations/{id}", Params: []string{"id"}}
	operationGetElevatedAccess                  = generatedOperation{ID: "getElevatedAccess", Method: "GET", Path: "/v1/sessions/{id}/elevated-access", Params: []string{"id"}}
	operationGetExtensionPackUpdate             = generatedOperation{ID: "getExtensionPackUpdate", Method: "GET", Path: "/v1/extensions/packs/{pack_id}/update", Params: []string{"pack_id"}}
	operationGetExtensionSuggestions            = generatedOperation{ID: "getExtensionSuggestions", Method: "GET", Path: "/v1/extensions/suggestions"}
	operationGetExtensionUnit                   = generatedOperation{ID: "getExtensionUnit", Method: "GET", Path: "/v1/extensions/units/{unit_id}", Params: []string{"unit_id"}}
	operationGetExtensionsCatalog               = generatedOperation{ID: "getExtensionsCatalog", Method: "GET", Path: "/v1/extensions"}
	operationGetFileBriefing                    = generatedOperation{ID: "getFileBriefing", Method: "GET", Path: "/v1/projects/{id}/source/file-briefings", Params: []string{"id"}}
	operationGetFileSummariesSettings           = generatedOperation{ID: "getFileSummariesSettings", Method: "GET", Path: "/v1/settings/file-summaries"}
	operationGetGitStatus                       = generatedOperation{ID: "getGitStatus", Method: "GET", Path: "/v1/projects/{id}/git/repos/{repo_id}/status", Params: []string{"id", "repo_id"}}
	operationGetGitWorktree                     = generatedOperation{ID: "getGitWorktree", Method: "GET", Path: "/v1/sessions/{id}/git-worktree", Params: []string{"id"}}
	operationGetHealth                          = generatedOperation{ID: "getHealth", Method: "GET", Path: "/health"}
	operationGetHistoryStorage                  = generatedOperation{ID: "getHistoryStorage", Method: "GET", Path: "/v1/history-storage"}
	operationGetHost                            = generatedOperation{ID: "getHost", Method: "GET", Path: "/v1/host"}
	operationGetHostResources                   = generatedOperation{ID: "getHostResources", Method: "GET", Path: "/v1/host-resources"}
	operationGetLimitsSettings                  = generatedOperation{ID: "getLimitsSettings", Method: "GET", Path: "/v1/settings/limits"}
	operationGetLocalData                       = generatedOperation{ID: "getLocalData", Method: "GET", Path: "/v1/local-data"}
	operationGetModelPolicySettings             = generatedOperation{ID: "getModelPolicySettings", Method: "GET", Path: "/v1/settings/model-policy"}
	operationGetPowerSettings                   = generatedOperation{ID: "getPowerSettings", Method: "GET", Path: "/v1/settings/power"}
	operationGetPreflight                       = generatedOperation{ID: "getPreflight", Method: "GET", Path: "/v1/preflight"}
	operationGetPricingSettings                 = generatedOperation{ID: "getPricingSettings", Method: "GET", Path: "/v1/settings/pricing"}
	operationGetProject                         = generatedOperation{ID: "getProject", Method: "GET", Path: "/v1/projects/{id}", Params: []string{"id"}}
	operationGetProjectAgentContext             = generatedOperation{ID: "getProjectAgentContext", Method: "GET", Path: "/v1/projects/{id}/agent-context", Params: []string{"id"}}
	operationGetProjectCostReport               = generatedOperation{ID: "getProjectCostReport", Method: "GET", Path: "/v1/projects/{id}/cost-report", Params: []string{"id"}}
	operationGetProjectRemoval                  = generatedOperation{ID: "getProjectRemoval", Method: "GET", Path: "/v1/projects/{id}/removals/{operation_id}", Params: []string{"id", "operation_id"}}
	operationGetProjectSecurity                 = generatedOperation{ID: "getProjectSecurity", Method: "GET", Path: "/v1/projects/{id}/security", Params: []string{"id"}}
	operationGetProjectSource                   = generatedOperation{ID: "getProjectSource", Method: "GET", Path: "/v1/projects/{id}/source", Params: []string{"id"}}
	operationGetProjectSourceAttribution        = generatedOperation{ID: "getProjectSourceAttribution", Method: "GET", Path: "/v1/projects/{id}/source/attribution", Params: []string{"id"}}
	operationGetProjectSourceComparison         = generatedOperation{ID: "getProjectSourceComparison", Method: "GET", Path: "/v1/projects/{id}/source/comparison", Params: []string{"id"}}
	operationGetProjectSourceEditorConfig       = generatedOperation{ID: "getProjectSourceEditorConfig", Method: "GET", Path: "/v1/projects/{id}/source/editorconfig", Params: []string{"id"}}
	operationGetProjectSourceGitReview          = generatedOperation{ID: "getProjectSourceGitReview", Method: "GET", Path: "/v1/projects/{id}/source/git-changes/{git_change_id}/review", Params: []string{"id", "git_change_id"}}
	operationGetProjectSourceHistory            = generatedOperation{ID: "getProjectSourceHistory", Method: "GET", Path: "/v1/projects/{id}/source/history", Params: []string{"id"}}
	operationGetProjectSourceIndex              = generatedOperation{ID: "getProjectSourceIndex", Method: "GET", Path: "/v1/projects/{id}/source/index", Params: []string{"id"}}
	operationGetProjectSourceRaw                = generatedOperation{ID: "getProjectSourceRaw", Method: "GET", Path: "/v1/projects/{id}/source/raw", Params: []string{"id"}}
	operationGetProjectSourceRevisionReview     = generatedOperation{ID: "getProjectSourceRevisionReview", Method: "GET", Path: "/v1/projects/{id}/source/revisions/review", Params: []string{"id"}}
	operationGetProjectSourceStorage            = generatedOperation{ID: "getProjectSourceStorage", Method: "GET", Path: "/v1/projects/{id}/source/storage", Params: []string{"id"}}
	operationGetProjectSourceWalkSummary        = generatedOperation{ID: "getProjectSourceWalkSummary", Method: "GET", Path: "/v1/projects/{id}/source/walk-summary", Params: []string{"id"}}
	operationGetProjectTrust                    = generatedOperation{ID: "getProjectTrust", Method: "GET", Path: "/v1/projects/{id}/trust", Params: []string{"id"}}
	operationGetReviewSettings                  = generatedOperation{ID: "getReviewSettings", Method: "GET", Path: "/v1/settings/review"}
	operationGetSecretIgnoreCandidate           = generatedOperation{ID: "getSecretIgnoreCandidate", Method: "GET", Path: "/v1/projects/{id}/secret-ignore-candidates/{candidate_id}", Params: []string{"id", "candidate_id"}}
	operationGetSecurityScannersSettings        = generatedOperation{ID: "getSecurityScannersSettings", Method: "GET", Path: "/v1/settings/security-scanners"}
	operationGetSession                         = generatedOperation{ID: "getSession", Method: "GET", Path: "/v1/sessions/{id}", Params: []string{"id"}}
	operationGetSessionArtifact                 = generatedOperation{ID: "getSessionArtifact", Method: "GET", Path: "/v1/sessions/{id}/artifacts/{artifact_id}", Params: []string{"id", "artifact_id"}}
	operationGetSessionBackgroundProcessOutput  = generatedOperation{ID: "getSessionBackgroundProcessOutput", Method: "GET", Path: "/v1/sessions/{id}/background/{process_id}/output", Params: []string{"id", "process_id"}}
	operationGetSessionBootstrap                = generatedOperation{ID: "getSessionBootstrap", Method: "GET", Path: "/v1/sessions/{id}/bootstrap", Params: []string{"id"}}
	operationGetSessionContext                  = generatedOperation{ID: "getSessionContext", Method: "GET", Path: "/v1/sessions/{id}/context", Params: []string{"id"}}
	operationGetSessionFindings                 = generatedOperation{ID: "getSessionFindings", Method: "GET", Path: "/v1/sessions/{id}/findings", Params: []string{"id"}}
	operationGetSessionProgress                 = generatedOperation{ID: "getSessionProgress", Method: "GET", Path: "/v1/sessions/{id}/progress", Params: []string{"id"}}
	operationGetSessionQueue                    = generatedOperation{ID: "getSessionQueue", Method: "GET", Path: "/v1/sessions/{id}/queue", Params: []string{"id"}}
	operationGetSourceOperation                 = generatedOperation{ID: "getSourceOperation", Method: "GET", Path: "/v1/projects/{id}/source/operations/{operation_id}", Params: []string{"id", "operation_id"}}
	operationGetSourceView                      = generatedOperation{ID: "getSourceView", Method: "GET", Path: "/v1/projects/{id}/source/views/{view_id}", Params: []string{"id", "view_id"}}
	operationGetSourceViewRows                  = generatedOperation{ID: "getSourceViewRows", Method: "GET", Path: "/v1/projects/{id}/source/views/{view_id}/presentations/{presentation_id}/rows", Params: []string{"id", "view_id", "presentation_id"}}
	operationGetSourceWorkspace                 = generatedOperation{ID: "getSourceWorkspace", Method: "GET", Path: "/v1/projects/{id}/source/workspace", Params: []string{"id"}}
	operationGetTrustSettings                   = generatedOperation{ID: "getTrustSettings", Method: "GET", Path: "/v1/settings/project-trust"}
	operationGetVerifySettings                  = generatedOperation{ID: "getVerifySettings", Method: "GET", Path: "/v1/settings/verify"}
	operationGetWebResearchIndex                = generatedOperation{ID: "getWebResearchIndex", Method: "GET", Path: "/v1/web-research/index"}
	operationGetWebResearchProviders            = generatedOperation{ID: "getWebResearchProviders", Method: "GET", Path: "/v1/web-research/providers"}
	operationGetWebResearchSettings             = generatedOperation{ID: "getWebResearchSettings", Method: "GET", Path: "/v1/settings/web-research"}
	operationGetWorkerChanges                   = generatedOperation{ID: "getWorkerChanges", Method: "GET", Path: "/v1/workers/{id}/changes", Params: []string{"id"}}
	operationGetWorkflowRun                     = generatedOperation{ID: "getWorkflowRun", Method: "GET", Path: "/v1/workflow-runs/{id}", Params: []string{"id"}}
	operationGetWorkflowRunReport               = generatedOperation{ID: "getWorkflowRunReport", Method: "GET", Path: "/v1/workflow-runs/{id}/report", Params: []string{"id"}}
	operationHoldProjectManagedSecret           = generatedOperation{ID: "holdProjectManagedSecret", Method: "POST", Path: "/v1/projects/{id}/secrets/{secret_id}/hold", Params: []string{"id", "secret_id"}, RecordsPersonAction: true}
	operationImportDetectionPack                = generatedOperation{ID: "importDetectionPack", Method: "POST", Path: "/v1/detection-packs", RecordsPersonAction: true}
	operationInstallExtensionMetaPack           = generatedOperation{ID: "installExtensionMetaPack", Method: "POST", Path: "/v1/extensions/meta-packs", RecordsPersonAction: true}
	operationInstallExtensionPack               = generatedOperation{ID: "installExtensionPack", Method: "POST", Path: "/v1/extensions/packs", RecordsPersonAction: true}
	operationInvokeProjectCommand               = generatedOperation{ID: "invokeProjectCommand", Method: "POST", Path: "/v1/projects/{id}/commands/{command_id}/invoke", Params: []string{"id", "command_id"}, RecordsPersonAction: true}
	operationInvokeSessionCommand               = generatedOperation{ID: "invokeSessionCommand", Method: "POST", Path: "/v1/sessions/{id}/commands/{command_id}/invoke", Params: []string{"id", "command_id"}, RecordsPersonAction: true}
	operationLandGitWorktree                    = generatedOperation{ID: "landGitWorktree", Method: "POST", Path: "/v1/sessions/{id}/git-worktree/land", Params: []string{"id"}, RecordsPersonAction: true}
	operationLaunchBlueprint                    = generatedOperation{ID: "launchBlueprint", Method: "POST", Path: "/v1/projects/{id}/blueprints/{blueprint_id}/launch", Params: []string{"id", "blueprint_id"}, RecordsPersonAction: true}
	operationLeaveEditorDocument                = generatedOperation{ID: "leaveEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/leave", Params: []string{"id", "document_id"}}
	operationListApprovalAsks                   = generatedOperation{ID: "listApprovalAsks", Method: "GET", Path: "/v1/approval-asks"}
	operationListApprovalGrants                 = generatedOperation{ID: "listApprovalGrants", Method: "GET", Path: "/v1/approval-grants"}
	operationListBlueprints                     = generatedOperation{ID: "listBlueprints", Method: "GET", Path: "/v1/projects/{id}/blueprints", Params: []string{"id"}}
	operationListCheckpoints                    = generatedOperation{ID: "listCheckpoints", Method: "GET", Path: "/v1/sessions/{id}/checkpoints", Params: []string{"id"}}
	operationListCodeScans                      = generatedOperation{ID: "listCodeScans", Method: "GET", Path: "/v1/projects/{id}/scans", Params: []string{"id"}}
	operationListDelegationLegs                 = generatedOperation{ID: "listDelegationLegs", Method: "GET", Path: "/v1/delegations/{id}/legs", Params: []string{"id"}}
	operationListDetectionPacks                 = generatedOperation{ID: "listDetectionPacks", Method: "GET", Path: "/v1/detection-packs"}
	operationListDraftVersions                  = generatedOperation{ID: "listDraftVersions", Method: "GET", Path: "/v1/sessions/{id}/drafts/{slot_id}/versions", Params: []string{"id", "slot_id"}}
	operationListEditorDocumentChanges          = generatedOperation{ID: "listEditorDocumentChanges", Method: "GET", Path: "/v1/projects/{id}/editor-documents/{document_id}/changes", Params: []string{"id", "document_id"}}
	operationListGitBranches                    = generatedOperation{ID: "listGitBranches", Method: "GET", Path: "/v1/projects/{id}/git/repos/{repo_id}/branches", Params: []string{"id", "repo_id"}}
	operationListGitChanges                     = generatedOperation{ID: "listGitChanges", Method: "GET", Path: "/v1/projects/{id}/git/repos/{repo_id}/changes", Params: []string{"id", "repo_id"}}
	operationListGitRepos                       = generatedOperation{ID: "listGitRepos", Method: "GET", Path: "/v1/projects/{id}/git/repos", Params: []string{"id"}}
	operationListMcpProviderTools               = generatedOperation{ID: "listMcpProviderTools", Method: "GET", Path: "/v1/mcp/providers/{provider_id}/tools", Params: []string{"provider_id"}}
	operationListMcpProviders                   = generatedOperation{ID: "listMcpProviders", Method: "GET", Path: "/v1/mcp/providers"}
	operationListMcpRecipes                     = generatedOperation{ID: "listMcpRecipes", Method: "GET", Path: "/v1/mcp/recipes"}
	operationListProjectArtifacts               = generatedOperation{ID: "listProjectArtifacts", Method: "GET", Path: "/v1/projects/{id}/artifacts", Params: []string{"id"}}
	operationListProjectFindingIgnores          = generatedOperation{ID: "listProjectFindingIgnores", Method: "GET", Path: "/v1/projects/{id}/findings/ignores", Params: []string{"id"}}
	operationListProjectManagedSecretUses       = generatedOperation{ID: "listProjectManagedSecretUses", Method: "GET", Path: "/v1/projects/{id}/secrets/{secret_id}/uses", Params: []string{"id", "secret_id"}}
	operationListProjectManagedSecrets          = generatedOperation{ID: "listProjectManagedSecrets", Method: "GET", Path: "/v1/projects/{id}/secrets", Params: []string{"id"}}
	operationListProjectScanners                = generatedOperation{ID: "listProjectScanners", Method: "GET", Path: "/v1/projects/{id}/scanners", Params: []string{"id"}}
	operationListProjectSecretIgnores           = generatedOperation{ID: "listProjectSecretIgnores", Method: "GET", Path: "/v1/projects/{id}/secret-ignores", Params: []string{"id"}}
	operationListProjectSessions                = generatedOperation{ID: "listProjectSessions", Method: "GET", Path: "/v1/projects/{id}/sessions", Params: []string{"id"}}
	operationListProjectSourcePins              = generatedOperation{ID: "listProjectSourcePins", Method: "GET", Path: "/v1/projects/{id}/source/pins", Params: []string{"id"}}
	operationListProjectSourceSeen              = generatedOperation{ID: "listProjectSourceSeen", Method: "GET", Path: "/v1/projects/{id}/source/seen", Params: []string{"id"}}
	operationListProjectSourceSymbols           = generatedOperation{ID: "listProjectSourceSymbols", Method: "GET", Path: "/v1/projects/{id}/source/symbols", Params: []string{"id"}}
	operationListProjectSourceVersions          = generatedOperation{ID: "listProjectSourceVersions", Method: "GET", Path: "/v1/projects/{id}/source/versions", Params: []string{"id"}}
	operationListProjectSourceWalk              = generatedOperation{ID: "listProjectSourceWalk", Method: "GET", Path: "/v1/projects/{id}/source/walk", Params: []string{"id"}}
	operationListProjects                       = generatedOperation{ID: "listProjects", Method: "GET", Path: "/v1/projects"}
	operationListProviderKinds                  = generatedOperation{ID: "listProviderKinds", Method: "GET", Path: "/v1/provider-kinds"}
	operationListProviders                      = generatedOperation{ID: "listProviders", Method: "GET", Path: "/v1/providers"}
	operationListScannerCatalog                 = generatedOperation{ID: "listScannerCatalog", Method: "GET", Path: "/v1/scanners/catalog"}
	operationListScanners                       = generatedOperation{ID: "listScanners", Method: "GET", Path: "/v1/scanners"}
	operationListSessionArtifacts               = generatedOperation{ID: "listSessionArtifacts", Method: "GET", Path: "/v1/sessions/{id}/artifacts", Params: []string{"id"}}
	operationListSessionBackgroundProcesses     = generatedOperation{ID: "listSessionBackgroundProcesses", Method: "GET", Path: "/v1/sessions/{id}/background", Params: []string{"id"}}
	operationListSessionInvocations             = generatedOperation{ID: "listSessionInvocations", Method: "GET", Path: "/v1/sessions/{id}/invocations", Params: []string{"id"}}
	operationListSessionMessages                = generatedOperation{ID: "listSessionMessages", Method: "GET", Path: "/v1/sessions/{id}/messages", Params: []string{"id"}}
	operationListSessionPreviews                = generatedOperation{ID: "listSessionPreviews", Method: "GET", Path: "/v1/sessions/{id}/previews", Params: []string{"id"}}
	operationListSessionWorkflowRuns            = generatedOperation{ID: "listSessionWorkflowRuns", Method: "GET", Path: "/v1/sessions/{id}/workflow-runs", Params: []string{"id"}}
	operationListSourceOperations               = generatedOperation{ID: "listSourceOperations", Method: "GET", Path: "/v1/projects/{id}/source/operations", Params: []string{"id"}}
	operationListWorkers                        = generatedOperation{ID: "listWorkers", Method: "GET", Path: "/v1/workers"}
	operationListWorkflowTemplates              = generatedOperation{ID: "listWorkflowTemplates", Method: "GET", Path: "/v1/workflow-templates"}
	operationListWorkflows                      = generatedOperation{ID: "listWorkflows", Method: "GET", Path: "/v1/workflows"}
	operationLocateSourceView                   = generatedOperation{ID: "locateSourceView", Method: "GET", Path: "/v1/projects/{id}/source/views/{view_id}/presentations/{presentation_id}/locate", Params: []string{"id", "view_id", "presentation_id"}}
	operationLockChatVault                      = generatedOperation{ID: "lockChatVault", Method: "POST", Path: "/v1/sessions/{id}/vault/lock", Params: []string{"id"}, RecordsPersonAction: true}
	operationLockVault                          = generatedOperation{ID: "lockVault", Method: "POST", Path: "/v1/vault/lock"}
	operationMakeProjectSourceEditable          = generatedOperation{ID: "makeProjectSourceEditable", Method: "POST", Path: "/v1/projects/{id}/source/editable", Params: []string{"id"}, RecordsPersonAction: true}
	operationMarkEditorSecret                   = generatedOperation{ID: "markEditorSecret", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/secret-spans/mark", Params: []string{"id", "document_id"}, RecordsPersonAction: true}
	operationMarkSessionSeen                    = generatedOperation{ID: "markSessionSeen", Method: "POST", Path: "/v1/sessions/{id}/seen", Params: []string{"id"}}
	operationObserveEditorDocument              = generatedOperation{ID: "observeEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/observe", Params: []string{"id", "document_id"}}
	operationOpenEditorDocument                 = generatedOperation{ID: "openEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents", Params: []string{"id"}}
	operationOpenProjectTrustReview             = generatedOperation{ID: "openProjectTrustReview", Method: "POST", Path: "/v1/projects/{id}/trust/review", Params: []string{"id"}}
	operationPauseWorkflowRun                   = generatedOperation{ID: "pauseWorkflowRun", Method: "POST", Path: "/v1/workflow-runs/{id}/pause", Params: []string{"id"}, RecordsPersonAction: true}
	operationPersistWorkflow                    = generatedOperation{ID: "persistWorkflow", Method: "POST", Path: "/v1/sessions/{id}/workflows/{workflow_id}/persist", Params: []string{"id", "workflow_id"}, RecordsPersonAction: true}
	operationPreviewEditorSecretMark            = generatedOperation{ID: "previewEditorSecretMark", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/secret-spans/preview", Params: []string{"id", "document_id"}}
	operationPreviewHistoryRetention            = generatedOperation{ID: "previewHistoryRetention", Method: "POST", Path: "/v1/history-storage/preview"}
	operationPreviewSearchReplacement           = generatedOperation{ID: "previewSearchReplacement", Method: "POST", Path: "/v1/search/replace/preview"}
	operationPreviewSessionRewind               = generatedOperation{ID: "previewSessionRewind", Method: "POST", Path: "/v1/sessions/{id}/rewind/preview", Params: []string{"id"}}
	operationPromoteProject                     = generatedOperation{ID: "promoteProject", Method: "POST", Path: "/v1/projects/{id}/promotion", Params: []string{"id"}, RecordsPersonAction: true}
	operationPruneHistory                       = generatedOperation{ID: "pruneHistory", Method: "POST", Path: "/v1/history-storage/prune", RecordsPersonAction: true}
	operationPublishEditorDocumentPresence      = generatedOperation{ID: "publishEditorDocumentPresence", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/presence", Params: []string{"id", "document_id"}}
	operationPullGit                            = generatedOperation{ID: "pullGit", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/pull", Params: []string{"id", "repo_id"}, RecordsPersonAction: true}
	operationPushGit                            = generatedOperation{ID: "pushGit", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/push", Params: []string{"id", "repo_id"}, RecordsPersonAction: true}
	operationQueryCodeScan                      = generatedOperation{ID: "queryCodeScan", Method: "POST", Path: "/v1/projects/{id}/scans/{scan_id}/query", Params: []string{"id", "scan_id"}}
	operationQueryProjectFindings               = generatedOperation{ID: "queryProjectFindings", Method: "POST", Path: "/v1/projects/{id}/findings/query", Params: []string{"id"}}
	operationReadEditorDocumentStatuses         = generatedOperation{ID: "readEditorDocumentStatuses", Method: "POST", Path: "/v1/projects/{id}/editor-documents/status", Params: []string{"id"}}
	operationRecordDenPerfEvents                = generatedOperation{ID: "recordDenPerfEvents", Method: "POST", Path: "/v1/debug/den-perf"}
	operationRedoProjectSourceHistory           = generatedOperation{ID: "redoProjectSourceHistory", Method: "POST", Path: "/v1/projects/{id}/source/history/redo", Params: []string{"id"}, RecordsPersonAction: true}
	operationRefreshHostResources               = generatedOperation{ID: "refreshHostResources", Method: "POST", Path: "/v1/host-resources/refresh"}
	operationRefreshMcpProvider                 = generatedOperation{ID: "refreshMcpProvider", Method: "POST", Path: "/v1/mcp/providers/{provider_id}/refresh", Params: []string{"provider_id"}}
	operationRefreshPricingSource               = generatedOperation{ID: "refreshPricingSource", Method: "POST", Path: "/v1/settings/pricing/sources/{source_id}/refresh", Params: []string{"source_id"}}
	operationRefreshProviderModels              = generatedOperation{ID: "refreshProviderModels", Method: "POST", Path: "/v1/providers/{provider_id}/refresh", Params: []string{"provider_id"}}
	operationReleaseSourcePresentation          = generatedOperation{ID: "releaseSourcePresentation", Method: "DELETE", Path: "/v1/projects/{id}/source/views/{view_id}/presentations/{presentation_id}", Params: []string{"id", "view_id", "presentation_id"}}
	operationReleaseSourceView                  = generatedOperation{ID: "releaseSourceView", Method: "DELETE", Path: "/v1/projects/{id}/source/views/{view_id}", Params: []string{"id", "view_id"}}
	operationReleaseSourceViewportInterest      = generatedOperation{ID: "releaseSourceViewportInterest", Method: "DELETE", Path: "/v1/projects/{id}/source/views/{view_id}/interests/{interest_id}", Params: []string{"id", "view_id", "interest_id"}}
	operationReloadEditorDocument               = generatedOperation{ID: "reloadEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/reload", Params: []string{"id", "document_id"}, RecordsPersonAction: true}
	operationReloadExtensionPack                = generatedOperation{ID: "reloadExtensionPack", Method: "POST", Path: "/v1/extensions/packs/{pack_id}/reload", Params: []string{"pack_id"}, RecordsPersonAction: true}
	operationRenameProjectSource                = generatedOperation{ID: "renameProjectSource", Method: "POST", Path: "/v1/projects/{id}/source/rename", Params: []string{"id"}, RecordsPersonAction: true}
	operationReplaceEditorDocument              = generatedOperation{ID: "replaceEditorDocument", Method: "PUT", Path: "/v1/projects/{id}/editor-documents/{document_id}", Params: []string{"id", "document_id"}}
	operationReplaceEditorDocumentRetention     = generatedOperation{ID: "replaceEditorDocumentRetention", Method: "PUT", Path: "/v1/projects/{id}/editor-documents/retention", Params: []string{"id"}}
	operationReplaceProjectManagedSecretValue   = generatedOperation{ID: "replaceProjectManagedSecretValue", Method: "PUT", Path: "/v1/projects/{id}/secrets/{secret_id}/value", Params: []string{"id", "secret_id"}, RecordsPersonAction: true}
	operationReplaceProjectSource               = generatedOperation{ID: "replaceProjectSource", Method: "PUT", Path: "/v1/projects/{id}/source", Params: []string{"id"}, RecordsPersonAction: true}
	operationReplaceProviderCredential          = generatedOperation{ID: "replaceProviderCredential", Method: "PUT", Path: "/v1/providers/{provider_id}/credential", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationReplaceScannerSlot                 = generatedOperation{ID: "replaceScannerSlot", Method: "PUT", Path: "/v1/scanners/slots/{category}", Params: []string{"category"}, RecordsPersonAction: true}
	operationReplaceSourceViewportInterest      = generatedOperation{ID: "replaceSourceViewportInterest", Method: "PUT", Path: "/v1/projects/{id}/source/views/{view_id}/interests/{interest_id}", Params: []string{"id", "view_id", "interest_id"}}
	operationReplaceWebResearchCredential       = generatedOperation{ID: "replaceWebResearchCredential", Method: "PUT", Path: "/v1/web-research/providers/{provider_id}/credential", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationRequestFileBriefing                = generatedOperation{ID: "requestFileBriefing", Method: "POST", Path: "/v1/projects/{id}/source/file-briefings", Params: []string{"id"}}
	operationResetStore                         = generatedOperation{ID: "resetStore", Method: "POST", Path: "/v1/store/reset", RecordsPersonAction: true}
	operationResolveCheckpoint                  = generatedOperation{ID: "resolveCheckpoint", Method: "POST", Path: "/v1/sessions/{id}/checkpoints/{checkpoint_id}", Params: []string{"id", "checkpoint_id"}, RecordsPersonAction: true}
	operationResolveContributionChoices         = generatedOperation{ID: "resolveContributionChoices", Method: "POST", Path: "/v1/projects/{id}/commands/{command_id}/choices/{step_id}", Params: []string{"id", "command_id", "step_id"}}
	operationResolveEditorDocumentConflict      = generatedOperation{ID: "resolveEditorDocumentConflict", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/resolve", Params: []string{"id", "document_id"}, RecordsPersonAction: true}
	operationResolveMessageNavigation           = generatedOperation{ID: "resolveMessageNavigation", Method: "POST", Path: "/v1/sessions/{id}/navigation", Params: []string{"id"}}
	operationResolveProjectSourceDefinition     = generatedOperation{ID: "resolveProjectSourceDefinition", Method: "POST", Path: "/v1/projects/{id}/source/definition", Params: []string{"id"}}
	operationResolveProjectSourceRevisions      = generatedOperation{ID: "resolveProjectSourceRevisions", Method: "GET", Path: "/v1/projects/{id}/source/revisions", Params: []string{"id"}}
	operationResolveSocketGrant                 = generatedOperation{ID: "resolveSocketGrant", Method: "POST", Path: "/v1/approval-grants/resolve-socket"}
	operationResolveWorkflowDecision            = generatedOperation{ID: "resolveWorkflowDecision", Method: "POST", Path: "/v1/workflow-runs/{id}/decisions/{phase_id}", Params: []string{"id", "phase_id"}, RecordsPersonAction: true}
	operationResolveWorkflowFeedback            = generatedOperation{ID: "resolveWorkflowFeedback", Method: "POST", Path: "/v1/workflow-runs/{id}/feedback/{phase_id}", Params: []string{"id", "phase_id"}, RecordsPersonAction: true}
	operationResolveWorkflowSecret              = generatedOperation{ID: "resolveWorkflowSecret", Method: "POST", Path: "/v1/workflow-runs/{id}/feedback/{phase_id}/secret", Params: []string{"id", "phase_id"}, RecordsPersonAction: true}
	operationRestoreBackup                      = generatedOperation{ID: "restoreBackup", Method: "POST", Path: "/v1/backup/restore", RecordsPersonAction: true}
	operationRestoreProjectSourceCommitState    = generatedOperation{ID: "restoreProjectSourceCommitState", Method: "POST", Path: "/v1/projects/{id}/source/commits/{commit_sha}/restore", Params: []string{"id", "commit_sha"}, RecordsPersonAction: true}
	operationRestoreProjectSourceVersion        = generatedOperation{ID: "restoreProjectSourceVersion", Method: "POST", Path: "/v1/projects/{id}/source/versions/{version_id}/restore", Params: []string{"id", "version_id"}, RecordsPersonAction: true}
	operationRestoreRecoverySnapshot            = generatedOperation{ID: "restoreRecoverySnapshot", Method: "POST", Path: "/v1/backup/restore/recovery-snapshot", RecordsPersonAction: true}
	operationResumeWorkflowRun                  = generatedOperation{ID: "resumeWorkflowRun", Method: "POST", Path: "/v1/workflow-runs/{id}/resume", Params: []string{"id"}, RecordsPersonAction: true}
	operationRetrySourceOperation               = generatedOperation{ID: "retrySourceOperation", Method: "POST", Path: "/v1/projects/{id}/source/operations/{operation_id}/retry", Params: []string{"id", "operation_id"}, RecordsPersonAction: true}
	operationRevertEditorDocumentChange         = generatedOperation{ID: "revertEditorDocumentChange", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/changes/{change_id}/revert", Params: []string{"id", "document_id", "change_id"}, RecordsPersonAction: true}
	operationRevokeApprovalGrants               = generatedOperation{ID: "revokeApprovalGrants", Method: "POST", Path: "/v1/approval-grants/revoke", RecordsPersonAction: true}
	operationRevokeElevatedAccess               = generatedOperation{ID: "revokeElevatedAccess", Method: "POST", Path: "/v1/sessions/{id}/elevated-access/revoke", Params: []string{"id"}, RecordsPersonAction: true}
	operationRevokeMcpOAuth                     = generatedOperation{ID: "revokeMcpOAuth", Method: "DELETE", Path: "/v1/mcp/providers/{provider_id}/oauth", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationRevokeProjectManagedSecret         = generatedOperation{ID: "revokeProjectManagedSecret", Method: "DELETE", Path: "/v1/projects/{id}/secrets/{secret_id}", Params: []string{"id", "secret_id"}, RecordsPersonAction: true}
	operationRewindSession                      = generatedOperation{ID: "rewindSession", Method: "POST", Path: "/v1/sessions/{id}/rewind", Params: []string{"id"}, RecordsPersonAction: true}
	operationSaveEditorDocument                 = generatedOperation{ID: "saveEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/save", Params: []string{"id", "document_id"}, RecordsPersonAction: true}
	operationSearch                             = generatedOperation{ID: "search", Method: "POST", Path: "/v1/search"}
	operationSearchChatContent                  = generatedOperation{ID: "searchChatContent", Method: "GET", Path: "/v1/sessions/{id}/messages/{message_id}/content/search", Params: []string{"id", "message_id"}}
	operationSearchContributionSource           = generatedOperation{ID: "searchContributionSource", Method: "POST", Path: "/v1/projects/{id}/contribution-search/{source_id}", Params: []string{"id", "source_id"}}
	operationSearchProjectSource                = generatedOperation{ID: "searchProjectSource", Method: "GET", Path: "/v1/projects/{id}/source/search", Params: []string{"id"}}
	operationSearchSourceView                   = generatedOperation{ID: "searchSourceView", Method: "GET", Path: "/v1/projects/{id}/source/views/{view_id}/presentations/{presentation_id}/search", Params: []string{"id", "view_id", "presentation_id"}}
	operationSendPrompt                         = generatedOperation{ID: "sendPrompt", Method: "POST", Path: "/v1/sessions/{id}/prompts", Params: []string{"id"}, RecordsPersonAction: true}
	operationStartFullScan                      = generatedOperation{ID: "startFullScan", Method: "POST", Path: "/v1/projects/{id}/scans", Params: []string{"id"}, RecordsPersonAction: true}
	operationStartMcpOAuth                      = generatedOperation{ID: "startMcpOAuth", Method: "POST", Path: "/v1/mcp/providers/{provider_id}/oauth/start", Params: []string{"provider_id"}}
	operationStartWorkflowRun                   = generatedOperation{ID: "startWorkflowRun", Method: "POST", Path: "/v1/sessions/{id}/workflow-runs", Params: []string{"id"}, RecordsPersonAction: true}
	operationStashGit                           = generatedOperation{ID: "stashGit", Method: "POST", Path: "/v1/projects/{id}/git/repos/{repo_id}/stash", Params: []string{"id", "repo_id"}, RecordsPersonAction: true}
	operationStopBackgroundProcess              = generatedOperation{ID: "stopBackgroundProcess", Method: "POST", Path: "/v1/sessions/{id}/background/{process_id}/stop", Params: []string{"id", "process_id"}, RecordsPersonAction: true}
	operationStreamSession                      = generatedOperation{ID: "streamSession", Method: "GET", Path: "/v1/sessions/{id}/stream", Params: []string{"id"}}
	operationSubmitEditorDocumentUpdate         = generatedOperation{ID: "submitEditorDocumentUpdate", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/updates", Params: []string{"id", "document_id"}}
	operationSubscribeEvents                    = generatedOperation{ID: "subscribeEvents", Method: "GET", Path: "/v1/events"}
	operationSyncEditorDocument                 = generatedOperation{ID: "syncEditorDocument", Method: "POST", Path: "/v1/projects/{id}/editor-documents/{document_id}/sync", Params: []string{"id", "document_id"}}
	operationTestProvider                       = generatedOperation{ID: "testProvider", Method: "POST", Path: "/v1/providers/{provider_id}/test", Params: []string{"provider_id"}}
	operationTestWebResearchProvider            = generatedOperation{ID: "testWebResearchProvider", Method: "POST", Path: "/v1/web-research/providers/{provider_id}/test", Params: []string{"provider_id"}}
	operationUndoProjectSourceHistory           = generatedOperation{ID: "undoProjectSourceHistory", Method: "POST", Path: "/v1/projects/{id}/source/history/undo", Params: []string{"id"}, RecordsPersonAction: true}
	operationUpdateApprovalsSettings            = generatedOperation{ID: "updateApprovalsSettings", Method: "PATCH", Path: "/v1/settings/approvals", RecordsPersonAction: true}
	operationUpdateBlueprint                    = generatedOperation{ID: "updateBlueprint", Method: "PATCH", Path: "/v1/projects/{id}/blueprints/{blueprint_id}", Params: []string{"id", "blueprint_id"}, RecordsPersonAction: true}
	operationUpdateDetectionPack                = generatedOperation{ID: "updateDetectionPack", Method: "PATCH", Path: "/v1/detection-packs/{pack_id}", Params: []string{"pack_id"}, RecordsPersonAction: true}
	operationUpdateExtensionConfiguration       = generatedOperation{ID: "updateExtensionConfiguration", Method: "PATCH", Path: "/v1/extensions/configuration", RecordsPersonAction: true}
	operationUpdateExtensionMetaPack            = generatedOperation{ID: "updateExtensionMetaPack", Method: "PATCH", Path: "/v1/extensions/meta-packs/{meta_pack_id}", Params: []string{"meta_pack_id"}, RecordsPersonAction: true}
	operationUpdateExtensionPack                = generatedOperation{ID: "updateExtensionPack", Method: "PATCH", Path: "/v1/extensions/packs/{pack_id}", Params: []string{"pack_id"}, RecordsPersonAction: true}
	operationUpdateExtensionUnit                = generatedOperation{ID: "updateExtensionUnit", Method: "PATCH", Path: "/v1/extensions/units/{unit_id}", Params: []string{"unit_id"}, RecordsPersonAction: true}
	operationUpdateFileSummariesSettings        = generatedOperation{ID: "updateFileSummariesSettings", Method: "PATCH", Path: "/v1/settings/file-summaries", RecordsPersonAction: true}
	operationUpdateHistoryStorage               = generatedOperation{ID: "updateHistoryStorage", Method: "PATCH", Path: "/v1/history-storage", RecordsPersonAction: true}
	operationUpdateHostResource                 = generatedOperation{ID: "updateHostResource", Method: "PATCH", Path: "/v1/host-resources/{resource_id}", Params: []string{"resource_id"}, RecordsPersonAction: true}
	operationUpdateLimitsSettings               = generatedOperation{ID: "updateLimitsSettings", Method: "PATCH", Path: "/v1/settings/limits", RecordsPersonAction: true}
	operationUpdateMcpProvider                  = generatedOperation{ID: "updateMcpProvider", Method: "PATCH", Path: "/v1/mcp/providers/{provider_id}", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationUpdateModelPolicySettings          = generatedOperation{ID: "updateModelPolicySettings", Method: "PATCH", Path: "/v1/settings/model-policy", RecordsPersonAction: true}
	operationUpdatePowerSettings                = generatedOperation{ID: "updatePowerSettings", Method: "PATCH", Path: "/v1/settings/power", RecordsPersonAction: true}
	operationUpdatePricingSettings              = generatedOperation{ID: "updatePricingSettings", Method: "PATCH", Path: "/v1/settings/pricing", RecordsPersonAction: true}
	operationUpdateProject                      = generatedOperation{ID: "updateProject", Method: "PATCH", Path: "/v1/projects/{id}", Params: []string{"id"}, RecordsPersonAction: true}
	operationUpdateProjectManagedSecret         = generatedOperation{ID: "updateProjectManagedSecret", Method: "PATCH", Path: "/v1/projects/{id}/secrets/{secret_id}", Params: []string{"id", "secret_id"}, RecordsPersonAction: true}
	operationUpdateProjectRoot                  = generatedOperation{ID: "updateProjectRoot", Method: "PATCH", Path: "/v1/projects/{id}/roots/{root_id}", Params: []string{"id", "root_id"}, RecordsPersonAction: true}
	operationUpdateProjectScanner               = generatedOperation{ID: "updateProjectScanner", Method: "PATCH", Path: "/v1/projects/{id}/scanners/{scanner_id}", Params: []string{"id", "scanner_id"}, RecordsPersonAction: true}
	operationUpdateProjectSourcePin             = generatedOperation{ID: "updateProjectSourcePin", Method: "PATCH", Path: "/v1/projects/{id}/source/pins/{pin_id}", Params: []string{"id", "pin_id"}, RecordsPersonAction: true}
	operationUpdateProjectTrust                 = generatedOperation{ID: "updateProjectTrust", Method: "PATCH", Path: "/v1/projects/{id}/trust", Params: []string{"id"}, RecordsPersonAction: true}
	operationUpdateProvider                     = generatedOperation{ID: "updateProvider", Method: "PATCH", Path: "/v1/providers/{provider_id}", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationUpdateReviewSettings               = generatedOperation{ID: "updateReviewSettings", Method: "PATCH", Path: "/v1/settings/review", RecordsPersonAction: true}
	operationUpdateScanner                      = generatedOperation{ID: "updateScanner", Method: "PATCH", Path: "/v1/scanners/{scanner_id}", Params: []string{"scanner_id"}, RecordsPersonAction: true}
	operationUpdateSecurityScannersSettings     = generatedOperation{ID: "updateSecurityScannersSettings", Method: "PATCH", Path: "/v1/settings/security-scanners", RecordsPersonAction: true}
	operationUpdateSession                      = generatedOperation{ID: "updateSession", Method: "PATCH", Path: "/v1/sessions/{id}", Params: []string{"id"}, RecordsPersonAction: true}
	operationUpdateSessionQueue                 = generatedOperation{ID: "updateSessionQueue", Method: "PATCH", Path: "/v1/sessions/{id}/queue", Params: []string{"id"}, RecordsPersonAction: true}
	operationUpdateTrustSettings                = generatedOperation{ID: "updateTrustSettings", Method: "PATCH", Path: "/v1/settings/project-trust", RecordsPersonAction: true}
	operationUpdateVerifySettings               = generatedOperation{ID: "updateVerifySettings", Method: "PATCH", Path: "/v1/settings/verify", RecordsPersonAction: true}
	operationUpdateWebResearchProvider          = generatedOperation{ID: "updateWebResearchProvider", Method: "PATCH", Path: "/v1/web-research/providers/{provider_id}", Params: []string{"provider_id"}, RecordsPersonAction: true}
	operationUpdateWebResearchSettings          = generatedOperation{ID: "updateWebResearchSettings", Method: "PATCH", Path: "/v1/settings/web-research", RecordsPersonAction: true}
	operationUploadAttachment                   = generatedOperation{ID: "uploadAttachment", Method: "POST", Path: "/v1/projects/{id}/attachments", Params: []string{"id"}, RecordsPersonAction: true}
	operationWatchPreview                       = generatedOperation{ID: "watchPreview", Method: "POST", Path: "/v1/sessions/{id}/previews/watch", Params: []string{"id"}}
	operationWithdrawProjectSourcePresentation  = generatedOperation{ID: "withdrawProjectSourcePresentation", Method: "DELETE", Path: "/v1/projects/{id}/source/seen/{file_id}", Params: []string{"id", "file_id"}}
)

var allGeneratedOperations = []generatedOperation{
	operationAbortDelegation,
	operationAbortSession,
	operationAcceptExtensionSuggestions,
	operationAdvanceWorkflowRun,
	operationApplyExtensionMetaPack,
	operationApplyExtensionPackProfile,
	operationApplyExtensionPackUpdate,
	operationApplySearchReplacement,
	operationApplySourceViewIntent,
	operationApproveBlueprint,
	operationAssessProjectRemoval,
	operationAttachProjectRoot,
	operationBeginCheckpointUnlockChallenge,
	operationBeginProjectManagedSecretReveal,
	operationBindGitWorktree,
	operationBrowseProjectSource,
	operationCancelMcpOAuth,
	operationCancelProjectPromotion,
	operationCancelSourceOperation,
	operationCancelWorker,
	operationCancelWorkflowRun,
	operationCheckMcpProviders,
	operationCheckScanners,
	operationCheckoutGit,
	operationClearLocalData,
	operationCloneProject,
	operationCommitGit,
	operationCompactSession,
	operationCompleteMcpOAuth,
	operationCompleteProjectManagedSecretReveal,
	operationCompleteProjectSourcePresentation,
	operationComposeWorkflow,
	operationComposeWorkflowFromTemplate,
	operationCopyProjectSource,
	operationCreateApprovalGrant,
	operationCreateBlueprint,
	operationCreateComposerSecret,
	operationCreateDelegation,
	operationCreateEditorDocumentSnapshot,
	operationCreateGitRepo,
	operationCreateHistoryProtection,
	operationCreateMcpProvider,
	operationCreateProject,
	operationCreateProjectFindingIgnore,
	operationCreateProjectManagedSecret,
	operationCreateProjectRemoval,
	operationCreateProjectSecretIgnore,
	operationCreateProjectSourceEntry,
	operationCreateProjectSourcePin,
	operationCreateProvider,
	operationCreateScanner,
	operationCreateSession,
	operationCreateSessionArtifact,
	operationCreateSourcePresentation,
	operationCreateSourceView,
	operationDeleteBlueprint,
	operationDeleteDetectionPack,
	operationDeleteExtensionMetaPack,
	operationDeleteExtensionPack,
	operationDeleteGitWorktree,
	operationDeleteHistoryProtection,
	operationDeleteMcpProvider,
	operationDeleteProjectArtifact,
	operationDeleteProjectFindingIgnore,
	operationDeleteProjectSecretIgnore,
	operationDeleteProjectSource,
	operationDeleteProjectSourcePin,
	operationDeleteProvider,
	operationDeleteProviderCredential,
	operationDeleteScanner,
	operationDeleteSession,
	operationDeleteWebResearchCredential,
	operationDetachProjectRoot,
	operationDetectFolder,
	operationDigestSourceComparisons,
	operationDiscardEditorDocument,
	operationDiscardGit,
	operationDismissVerifySettings,
	operationDispatchDelegationLeg,
	operationDraftGitCommitMessage,
	operationExitWorkflowRun,
	operationExportBackup,
	operationExportCodeScanSARIF,
	operationExportDiagnostics,
	operationExportProjectFindings,
	operationExportSearchResults,
	operationExportSessionTranscript,
	operationFireWorkflowTransition,
	operationGetActiveWorkflowRun,
	operationGetAgentPresence,
	operationGetApprovalsSettings,
	operationGetAttention,
	operationGetBackupCapabilities,
	operationGetBlueprint,
	operationGetBoard,
	operationGetChatContent,
	operationGetChatVault,
	operationGetCodeScan,
	operationGetContributions,
	operationGetCoordinatorContext,
	operationGetCostSummary,
	operationGetDelegation,
	operationGetElevatedAccess,
	operationGetExtensionPackUpdate,
	operationGetExtensionSuggestions,
	operationGetExtensionUnit,
	operationGetExtensionsCatalog,
	operationGetFileBriefing,
	operationGetFileSummariesSettings,
	operationGetGitStatus,
	operationGetGitWorktree,
	operationGetHealth,
	operationGetHistoryStorage,
	operationGetHost,
	operationGetHostResources,
	operationGetLimitsSettings,
	operationGetLocalData,
	operationGetModelPolicySettings,
	operationGetPowerSettings,
	operationGetPreflight,
	operationGetPricingSettings,
	operationGetProject,
	operationGetProjectAgentContext,
	operationGetProjectCostReport,
	operationGetProjectRemoval,
	operationGetProjectSecurity,
	operationGetProjectSource,
	operationGetProjectSourceAttribution,
	operationGetProjectSourceComparison,
	operationGetProjectSourceEditorConfig,
	operationGetProjectSourceGitReview,
	operationGetProjectSourceHistory,
	operationGetProjectSourceIndex,
	operationGetProjectSourceRaw,
	operationGetProjectSourceRevisionReview,
	operationGetProjectSourceStorage,
	operationGetProjectSourceWalkSummary,
	operationGetProjectTrust,
	operationGetReviewSettings,
	operationGetSecretIgnoreCandidate,
	operationGetSecurityScannersSettings,
	operationGetSession,
	operationGetSessionArtifact,
	operationGetSessionBackgroundProcessOutput,
	operationGetSessionBootstrap,
	operationGetSessionContext,
	operationGetSessionFindings,
	operationGetSessionProgress,
	operationGetSessionQueue,
	operationGetSourceOperation,
	operationGetSourceView,
	operationGetSourceViewRows,
	operationGetSourceWorkspace,
	operationGetTrustSettings,
	operationGetVerifySettings,
	operationGetWebResearchIndex,
	operationGetWebResearchProviders,
	operationGetWebResearchSettings,
	operationGetWorkerChanges,
	operationGetWorkflowRun,
	operationGetWorkflowRunReport,
	operationHoldProjectManagedSecret,
	operationImportDetectionPack,
	operationInstallExtensionMetaPack,
	operationInstallExtensionPack,
	operationInvokeProjectCommand,
	operationInvokeSessionCommand,
	operationLandGitWorktree,
	operationLaunchBlueprint,
	operationLeaveEditorDocument,
	operationListApprovalAsks,
	operationListApprovalGrants,
	operationListBlueprints,
	operationListCheckpoints,
	operationListCodeScans,
	operationListDelegationLegs,
	operationListDetectionPacks,
	operationListDraftVersions,
	operationListEditorDocumentChanges,
	operationListGitBranches,
	operationListGitChanges,
	operationListGitRepos,
	operationListMcpProviderTools,
	operationListMcpProviders,
	operationListMcpRecipes,
	operationListProjectArtifacts,
	operationListProjectFindingIgnores,
	operationListProjectManagedSecretUses,
	operationListProjectManagedSecrets,
	operationListProjectScanners,
	operationListProjectSecretIgnores,
	operationListProjectSessions,
	operationListProjectSourcePins,
	operationListProjectSourceSeen,
	operationListProjectSourceSymbols,
	operationListProjectSourceVersions,
	operationListProjectSourceWalk,
	operationListProjects,
	operationListProviderKinds,
	operationListProviders,
	operationListScannerCatalog,
	operationListScanners,
	operationListSessionArtifacts,
	operationListSessionBackgroundProcesses,
	operationListSessionInvocations,
	operationListSessionMessages,
	operationListSessionPreviews,
	operationListSessionWorkflowRuns,
	operationListSourceOperations,
	operationListWorkers,
	operationListWorkflowTemplates,
	operationListWorkflows,
	operationLocateSourceView,
	operationLockChatVault,
	operationLockVault,
	operationMakeProjectSourceEditable,
	operationMarkEditorSecret,
	operationMarkSessionSeen,
	operationObserveEditorDocument,
	operationOpenEditorDocument,
	operationOpenProjectTrustReview,
	operationPauseWorkflowRun,
	operationPersistWorkflow,
	operationPreviewEditorSecretMark,
	operationPreviewHistoryRetention,
	operationPreviewSearchReplacement,
	operationPreviewSessionRewind,
	operationPromoteProject,
	operationPruneHistory,
	operationPublishEditorDocumentPresence,
	operationPullGit,
	operationPushGit,
	operationQueryCodeScan,
	operationQueryProjectFindings,
	operationReadEditorDocumentStatuses,
	operationRecordDenPerfEvents,
	operationRedoProjectSourceHistory,
	operationRefreshHostResources,
	operationRefreshMcpProvider,
	operationRefreshPricingSource,
	operationRefreshProviderModels,
	operationReleaseSourcePresentation,
	operationReleaseSourceView,
	operationReleaseSourceViewportInterest,
	operationReloadEditorDocument,
	operationReloadExtensionPack,
	operationRenameProjectSource,
	operationReplaceEditorDocument,
	operationReplaceEditorDocumentRetention,
	operationReplaceProjectManagedSecretValue,
	operationReplaceProjectSource,
	operationReplaceProviderCredential,
	operationReplaceScannerSlot,
	operationReplaceSourceViewportInterest,
	operationReplaceWebResearchCredential,
	operationRequestFileBriefing,
	operationResetStore,
	operationResolveCheckpoint,
	operationResolveContributionChoices,
	operationResolveEditorDocumentConflict,
	operationResolveMessageNavigation,
	operationResolveProjectSourceDefinition,
	operationResolveProjectSourceRevisions,
	operationResolveSocketGrant,
	operationResolveWorkflowDecision,
	operationResolveWorkflowFeedback,
	operationResolveWorkflowSecret,
	operationRestoreBackup,
	operationRestoreProjectSourceCommitState,
	operationRestoreProjectSourceVersion,
	operationRestoreRecoverySnapshot,
	operationResumeWorkflowRun,
	operationRetrySourceOperation,
	operationRevertEditorDocumentChange,
	operationRevokeApprovalGrants,
	operationRevokeElevatedAccess,
	operationRevokeMcpOAuth,
	operationRevokeProjectManagedSecret,
	operationRewindSession,
	operationSaveEditorDocument,
	operationSearch,
	operationSearchChatContent,
	operationSearchContributionSource,
	operationSearchProjectSource,
	operationSearchSourceView,
	operationSendPrompt,
	operationStartFullScan,
	operationStartMcpOAuth,
	operationStartWorkflowRun,
	operationStashGit,
	operationStopBackgroundProcess,
	operationStreamSession,
	operationSubmitEditorDocumentUpdate,
	operationSubscribeEvents,
	operationSyncEditorDocument,
	operationTestProvider,
	operationTestWebResearchProvider,
	operationUndoProjectSourceHistory,
	operationUpdateApprovalsSettings,
	operationUpdateBlueprint,
	operationUpdateDetectionPack,
	operationUpdateExtensionConfiguration,
	operationUpdateExtensionMetaPack,
	operationUpdateExtensionPack,
	operationUpdateExtensionUnit,
	operationUpdateFileSummariesSettings,
	operationUpdateHistoryStorage,
	operationUpdateHostResource,
	operationUpdateLimitsSettings,
	operationUpdateMcpProvider,
	operationUpdateModelPolicySettings,
	operationUpdatePowerSettings,
	operationUpdatePricingSettings,
	operationUpdateProject,
	operationUpdateProjectManagedSecret,
	operationUpdateProjectRoot,
	operationUpdateProjectScanner,
	operationUpdateProjectSourcePin,
	operationUpdateProjectTrust,
	operationUpdateProvider,
	operationUpdateReviewSettings,
	operationUpdateScanner,
	operationUpdateSecurityScannersSettings,
	operationUpdateSession,
	operationUpdateSessionQueue,
	operationUpdateTrustSettings,
	operationUpdateVerifySettings,
	operationUpdateWebResearchProvider,
	operationUpdateWebResearchSettings,
	operationUploadAttachment,
	operationWatchPreview,
	operationWithdrawProjectSourcePresentation,
}
