package api

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/lycaon/lycaon/internal/api/sourceapi"
	"github.com/lycaon/lycaon/internal/configdir"
)

func (s *Server) setupRoutes() {
	s.rateLimits = newRateLimitState()
	registerRootOperation(s.router, operationGetHealth, s.handleHealth)
	s.router.Route("/v1", func(r chi.Router) {
		r.Use(s.requireClientAuth)
		r.Use(s.bindCaller)
		r.Use(s.rejectRestorePending)
		r.Use(s.rejectEmptyPathSegments)
		r.Use(s.markUserPresence)
		s.registerV1Operation(r, operationGetHost, s.Routes.Activity.handleGetHost)
		s.registerV1Operation(r, operationGetPreflight, s.Routes.Activity.handlePreflight)
		s.registerV1Operation(r, operationExportDiagnostics, s.Routes.Activity.handleExportDiagnostics)
		s.registerV1Operation(r, operationCreateSession, s.Admin.SessionAdmin.Lifecycle.HandleCreateSession)
		s.registerV1Operation(r, operationGetSession, s.handleGetSession)
		s.registerV1Operation(r, operationGetSessionBootstrap, s.Admin.SessionAdmin.Bootstrap.HandleSessionBootstrap)
		s.registerV1Operation(r, operationUpdateSession, s.Admin.SessionAdmin.Lifecycle.HandleUpdateSession)
		s.registerV1Operation(r, operationDeleteSession, s.Admin.SessionAdmin.Lifecycle.HandleDeleteSession)
		s.registerV1Operation(r, operationListSessionMessages, s.Admin.SessionAdmin.Transcript.HandleListSessionMessages)
		s.registerV1Operation(r, operationGetChatContent, s.Admin.Prompt.Content.HandleGetChatContent)
		s.registerV1Operation(r, operationSearchChatContent, s.Admin.Prompt.Content.HandleSearchChatContent)
		s.registerV1Operation(r, operationResolveMessageNavigation, s.Admin.SessionAdmin.Navigation.HandleResolveMessageNavigation)
		s.registerV1Operation(r, operationListSessionInvocations, s.Admin.SessionAdmin.Transcript.HandleListSessionInvocations)
		s.registerV1Operation(r, operationExportSessionTranscript, s.Admin.SessionAdmin.Transcript.HandleExportSessionTranscript)
		s.registerV1Operation(r, operationSendPrompt, s.Admin.SessionAdmin.Recovery.WithSessionPanicRecovery(s.Admin.Prompt.Submission.HandlePrompt))
		s.registerV1Operation(r, operationCreateComposerSecret, s.Admin.Prompt.Submission.HandleCreateComposerSecret)
		s.registerV1Operation(r, operationUploadAttachment, s.Admin.Prompt.Attachments.HandleUploadAttachment)
		s.registerContributionRoutes(r)
		s.registerV1Operation(r, operationAbortSession, s.Admin.SessionAdmin.Recovery.WithSessionPanicRecovery(s.Admin.SessionAdmin.Lifecycle.HandleAbortSession))
		s.registerV1Operation(r, operationPreviewSessionRewind, s.Admin.SessionAdmin.Recovery.WithSessionPanicRecovery(s.Admin.SessionAdmin.Rewind.HandlePreviewSessionRewind))
		s.registerV1Operation(r, operationRewindSession, s.Admin.SessionAdmin.Recovery.WithSessionPanicRecovery(s.Admin.SessionAdmin.Rewind.HandleRewindSession))
		s.registerV1Operation(r, operationMarkSessionSeen, s.Admin.SessionAdmin.Transcript.HandleMarkSessionSeen)
		s.registerV1Operation(r, operationStreamSession, s.Routes.Conversation.handleStream)
		s.registerV1Operation(r, operationCompactSession, s.Admin.Prompt.Content.HandleSessionCompact)
		s.registerV1Operation(r, operationGetSessionContext, s.Admin.Prompt.Content.HandleSessionContext)
		s.registerV1Operation(r, operationGetSessionFindings, s.Routes.Conversation.handleSessionFindings)
		s.registerV1Operation(r, operationListDraftVersions, s.Admin.Prompt.Content.HandleListDraftVersions)
		s.registerV1Operation(r, operationGetSessionProgress, s.Routes.Conversation.handleSessionProgress)
		s.registerV1Operation(r, operationListSessionArtifacts, s.Routes.Artifacts.HandleListSessionArtifacts)
		s.registerV1Operation(r, operationCreateSessionArtifact, s.Routes.Artifacts.HandleCreateSessionArtifact)
		s.registerV1Operation(r, operationGetSessionArtifact, s.Routes.Artifacts.HandleSessionArtifact)
		s.registerV1Operation(r, operationListSessionBackgroundProcesses, s.Routes.Conversation.handleListBackgroundProcesses)
		s.registerV1Operation(r, operationGetSessionBackgroundProcessOutput, s.Routes.Conversation.handleGetBackgroundProcessOutput)
		s.registerV1Operation(r, operationStopBackgroundProcess, s.Routes.Conversation.handleStopBackgroundProcess)
		s.registerV1Operation(r, operationListSessionPreviews, s.Routes.Conversation.handleListSessionPreviews)
		s.registerV1Operation(r, operationWatchPreview, s.Routes.Conversation.handleWatchPreview)
		s.registerV1Operation(r, operationGetSessionQueue, s.Admin.Prompt.Queue.HandleGetQueue)
		s.registerV1Operation(r, operationUpdateSessionQueue, s.Admin.Prompt.Queue.HandleUpdateSessionQueue)
		s.registerV1Operation(r, operationGetCoordinatorContext, s.Admin.Prompt.Content.HandleCoordinatorContext)
		s.registerV1Operation(r, operationListCheckpoints, s.Admin.Capabilities.CheckpointActions.HandleListCheckpoints)
		s.registerV1Operation(r, operationResolveCheckpoint, s.Admin.Capabilities.CheckpointActions.HandleResolveCheckpoint)
		s.registerV1Operation(r, operationBeginCheckpointUnlockChallenge, s.Admin.Capabilities.CheckpointActions.HandleBeginUnlockChallenge)
		s.registerV1Operation(r, operationGetChatVault, s.Admin.Capabilities.HeldValues.HandleGetChatVault)
		s.registerV1Operation(r, operationLockChatVault, s.Admin.Capabilities.HeldValues.HandleLockChatVault)
		s.registerV1Operation(r, operationLockVault, s.Admin.Capabilities.HeldValues.HandleLockVault)
		s.registerV1Operation(r, operationListWorkflows, s.Admin.Workflow.RunControl.HandleListWorkflows)
		s.registerV1Operation(r, operationListWorkflowTemplates, s.Admin.Workflow.Composition.HandleListWorkflowTemplates)
		s.registerV1Operation(r, operationComposeWorkflow, s.Admin.Workflow.Composition.HandleComposeWorkflow)
		s.registerV1Operation(r, operationComposeWorkflowFromTemplate, s.Admin.Workflow.Composition.HandleComposeFromTemplate)
		s.registerV1Operation(r, operationPersistWorkflow, s.Admin.Workflow.Composition.HandlePersistWorkflow)
		s.registerV1Operation(r, operationStartWorkflowRun, s.Admin.Workflow.RunControl.HandleStartWorkflowRun)
		s.registerV1Operation(r, operationExitWorkflowRun, s.Admin.Workflow.RunControl.HandleExitWorkflowRun)
		s.registerV1Operation(r, operationListSessionWorkflowRuns, s.Admin.Workflow.RunControl.HandleListSessionWorkflowRuns)
		s.registerV1Operation(r, operationGetActiveWorkflowRun, s.Admin.Workflow.RunControl.HandleGetActiveWorkflowRun)
		s.registerV1Operation(r, operationGetWorkflowRun, s.Admin.Workflow.RunControl.HandleGetWorkflowRun)
		s.registerV1Operation(r, operationGetWorkflowRunReport, s.Admin.Workflow.Reports.HandleGetWorkflowRunReport)
		s.registerV1Operation(r, operationPauseWorkflowRun, s.Admin.Workflow.RunControl.HandlePauseWorkflowRun)
		s.registerV1Operation(r, operationResumeWorkflowRun, s.Admin.Workflow.RunControl.HandleResumeWorkflowRun)
		s.registerV1Operation(r, operationCancelWorkflowRun, s.Admin.Workflow.RunControl.HandleCancelWorkflowRun)
		s.registerV1Operation(r, operationAdvanceWorkflowRun, s.Admin.Workflow.RunControl.HandleAdvanceWorkflowRun)
		s.registerV1Operation(r, operationFireWorkflowTransition, s.Admin.Workflow.RunControl.HandleFireWorkflowTransition)
		s.registerV1Operation(r, operationResolveWorkflowDecision, s.Admin.Workflow.RunControl.HandleResolveWorkflowDecision)
		s.registerV1Operation(r, operationResolveWorkflowFeedback, s.Admin.Workflow.RunControl.HandleResolveWorkflowFeedback)
		s.registerV1Operation(r, operationResolveWorkflowSecret, s.Admin.Workflow.RunControl.HandleResolveWorkflowSecret)

		s.registerV1Operation(r, operationListBlueprints, s.Admin.Workflow.BlueprintRoutes.HandleListBlueprints)
		s.registerV1Operation(r, operationCreateBlueprint, s.Admin.Workflow.BlueprintRoutes.HandleCreateBlueprint)
		s.registerV1Operation(r, operationGetBlueprint, s.Admin.Workflow.BlueprintRoutes.HandleGetBlueprint)
		s.registerV1Operation(r, operationUpdateBlueprint, s.Admin.Workflow.BlueprintRoutes.HandleUpdateBlueprint)
		s.registerV1Operation(r, operationDeleteBlueprint, s.Admin.Workflow.BlueprintRoutes.HandleDeleteBlueprint)
		s.registerV1Operation(r, operationApproveBlueprint, s.Admin.Workflow.BlueprintRoutes.HandleApproveBlueprint)
		s.registerV1Operation(r, operationLaunchBlueprint, s.Admin.Workflow.BlueprintRoutes.HandleLaunchBlueprint)

		s.registerProjectRoutes(r)

		s.registerV1Operation(r, operationListProviders, s.Admin.modelAdmin.ListProviders)
		s.registerV1Operation(r, operationListProviderKinds, s.Admin.modelAdmin.ListProviderKinds)
		s.registerV1Operation(r, operationCreateProvider, s.Admin.modelAdmin.CreateProvider)
		s.registerV1Operation(r, operationUpdateProvider, s.Admin.modelAdmin.UpdateProvider)
		s.registerV1Operation(r, operationDeleteProvider, s.Admin.modelAdmin.DeleteProvider)
		s.registerV1Operation(r, operationReplaceProviderCredential, s.Admin.modelAdmin.SetCredential)
		s.registerV1Operation(r, operationDeleteProviderCredential, s.Admin.modelAdmin.DeleteCredential)
		s.registerV1Operation(r, operationTestProvider, s.Admin.modelAdmin.TestProvider)
		s.registerV1Operation(r, operationRefreshProviderModels, s.Admin.modelAdmin.RefreshModels)
		s.registerV1Operation(r, operationGetModelPolicySettings, s.Admin.modelAdmin.GetPolicy)
		s.registerV1Operation(r, operationUpdateModelPolicySettings, s.Admin.modelAdmin.UpdatePolicy)

		s.registerSettingsRoutes(r)

		s.registerV1Operation(r, operationGetCostSummary, s.Routes.Activity.handleCostSummary)
		s.registerV1Operation(r, operationGetProjectCostReport, s.Routes.Activity.handleProjectCostReport)

		s.registerV1Operation(r, operationCreateDelegation, s.Routes.Workers.handleCreateDelegation)
		s.registerV1Operation(r, operationGetDelegation, s.Routes.Workers.handleGetDelegation)
		s.registerV1Operation(r, operationListDelegationLegs, s.Routes.Workers.handleListDelegationLegs)
		s.registerV1Operation(r, operationDispatchDelegationLeg, s.Routes.Workers.handleDispatchDelegationLeg)
		s.registerV1Operation(r, operationAbortDelegation, s.Routes.Workers.handleAbortDelegation)

		s.registerV1Operation(r, operationListWorkers, s.Routes.Workers.handleListWorkers)
		s.registerV1Operation(r, operationCancelWorker, s.Routes.Workers.handleWorkerCancel)
		s.registerV1Operation(r, operationGetWorkerChanges, s.Sources.History.HandleGetWorkerChanges)

		s.registerV1Operation(r, operationGetBoard, s.Routes.Workers.handleGetBoard)
		s.registerV1Operation(r, operationSearch, s.Search.HandleSearch)
		s.registerV1Operation(r, operationPreviewSearchReplacement, s.Search.HandlePreviewSearchReplacement)
		s.registerV1Operation(r, operationApplySearchReplacement, s.Search.HandleApplySearchReplacement)
		s.registerV1Operation(r, operationExportSearchResults, s.Search.HandleExportSearchResults)
		s.registerV1Operation(r, operationSubscribeEvents, s.Routes.Activity.handleEvents)
		s.registerV1Operation(r, operationGetAttention, s.Routes.Activity.handleGetAttention)

		s.registerScanRoutes(r)
		s.registerMCPRoutes(r)
		s.registerWebResearchRoutes(r)
		s.registerHostResourceRoutes(r)

		s.registerV1Operation(r, operationGetLocalData, s.Routes.LocalData.handleGetLocalData)
		s.registerV1Operation(r, operationGetHistoryStorage, s.Admin.historyAdmin.Status)
		s.registerV1Operation(r, operationUpdateHistoryStorage, s.Admin.historyAdmin.UpdateStorage)
		s.registerV1Operation(r, operationPreviewHistoryRetention, s.Admin.historyAdmin.Preview)
		s.registerV1Operation(r, operationPruneHistory, s.Admin.historyAdmin.Prune)
		s.registerV1Operation(r, operationCreateHistoryProtection, s.Admin.historyAdmin.CreateProtection)
		s.registerV1Operation(r, operationDeleteHistoryProtection, s.Admin.historyAdmin.DeleteProtection)
		s.registerV1Operation(r, operationClearLocalData, s.Routes.LocalData.handleClearLocalData)

		s.registerV1Operation(r, operationExportBackup, s.Routes.Storage.handleBackup)
		s.registerV1Operation(r, operationGetBackupCapabilities, s.Routes.Storage.handleBackupCapabilities)
		s.registerV1Operation(r, operationRestoreBackup, s.Routes.Storage.handleRestoreBackup)
		s.registerV1Operation(r, operationRestoreRecoverySnapshot, s.Routes.Storage.handleRestoreRecoverySnapshot)
		s.registerV1Operation(r, operationResetStore, s.Routes.Storage.handleResetStore)

		s.registerExtensionsRoutes(r)
		s.registerGitRoutes(r)

		s.registerV1Operation(r, operationRecordDenPerfEvents, s.Routes.Activity.handleDenPerfEvents)
	})
	if configdir.IsHarnessChannel() {
		s.Routes.HarnessControl.registerHarnessRoutes()
	}
	s.router.NotFound(s.handleRouteNotFound)
	s.router.MethodNotAllowed(s.handleMethodNotAllowed)
}

// sourceOperations are the routes whose file requests the source handler journals and replays.
var sourceOperations = sourceapi.Operations{
	CopyProjectSource:        toSourceOperation(operationCopyProjectSource),
	CreateProjectSourceEntry: toSourceOperation(operationCreateProjectSourceEntry),
	DeleteProjectSource:      toSourceOperation(operationDeleteProjectSource),
	RedoProjectSourceHistory: toSourceOperation(operationRedoProjectSourceHistory),
	RenameProjectSource:      toSourceOperation(operationRenameProjectSource),
	UndoProjectSourceHistory: toSourceOperation(operationUndoProjectSourceHistory),
}

func toSourceOperation(op generatedOperation) sourceapi.Operation {
	return sourceapi.Operation{ID: op.ID, Method: op.Method, Path: op.Path}
}

func (s *Server) registerContributionRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetContributions, s.Admin.Extensions.Contributions.HandleGetContributions)
	s.registerV1Operation(r, operationInvokeProjectCommand, s.Admin.Extensions.Execution.HandleInvokeProjectCommand)
	s.registerV1Operation(r, operationInvokeSessionCommand, s.Admin.Extensions.Execution.HandleInvokeSessionCommand)
	s.registerV1Operation(r, operationResolveContributionChoices, s.Admin.Extensions.Contributions.HandleContributionChoices)
	s.registerV1Operation(r, operationSearchContributionSource, s.Admin.Extensions.Contributions.HandleContributionSearch)
}

func registerRootOperation(r chi.Router, operation generatedOperation, handler http.HandlerFunc) {
	r.Method(operation.Method, operation.Path, handler)
}

func (s *Server) registerV1Operation(r chi.Router, operation generatedOperation, handler http.HandlerFunc) {
	if !strings.HasPrefix(operation.Path, "/v1/") {
		panic("v1 operation path must start with /v1/")
	}
	r.Method(operation.Method, strings.TrimPrefix(operation.Path, "/v1"),
		s.authorizeOperation(operation, s.rateLimitOperation(operation, s.recordPersonAction(operation, handler)).ServeHTTP))
}

func (s *Server) registerProjectRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetSourceOperation, s.Sources.Mutations.HandleGetSourceOperation)
	s.registerV1Operation(r, operationListSourceOperations, s.Sources.Mutations.HandleListSourceOperations)
	s.registerV1Operation(r, operationCancelSourceOperation, s.Sources.Mutations.HandleCancelSourceOperation)
	s.registerV1Operation(r, operationRetrySourceOperation, s.Sources.Mutations.HandleRetrySourceOperation)
	s.registerV1Operation(r, operationListProjects, s.Admin.Project.Projects.HandleListProjects)
	s.registerV1Operation(r, operationCreateProject, s.Admin.Project.Projects.HandleCreateProject)
	s.registerV1Operation(r, operationCloneProject, s.Admin.Project.Promotion.HandleCloneProject)
	s.registerV1Operation(r, operationDetectFolder, s.Admin.Extensions.Suggestions.HandleDetectFolder)
	s.registerV1Operation(r, operationGetProject, s.Admin.Project.Projects.HandleGetProject)
	s.registerV1Operation(r, operationListProjectSessions, s.Admin.SessionAdmin.Transcript.HandleListProjectSessions)
	s.registerV1Operation(r, operationGetAgentPresence, s.Routes.Activity.handleGetAgentPresence)
	s.registerV1Operation(r, operationUpdateProject, s.Admin.Project.Projects.HandleUpdateProject)
	s.registerV1Operation(r, operationGetProjectTrust, s.Admin.Project.Trust.HandleGetProjectTrust)
	s.registerV1Operation(r, operationOpenProjectTrustReview, s.Admin.Project.Trust.HandleOpenProjectTrustReview)
	s.registerV1Operation(r, operationUpdateProjectTrust, s.Admin.Project.Trust.HandleUpdateProjectTrust)
	s.registerV1Operation(r, operationGetProjectAgentContext, s.Admin.Project.Projects.HandleGetProjectAgentContext)
	s.registerV1Operation(r, operationAssessProjectRemoval, s.Admin.Project.Removal.HandleAssessProjectRemoval)
	s.registerV1Operation(r, operationCreateProjectRemoval, s.Admin.Project.Removal.HandleCreateProjectRemoval)
	s.registerV1Operation(r, operationGetProjectRemoval, s.Admin.Project.Removal.HandleGetProjectRemoval)
	s.registerV1Operation(r, operationListProjectArtifacts, s.Routes.Artifacts.HandleListProjectArtifacts)
	s.registerV1Operation(r, operationDeleteProjectArtifact, s.Routes.Artifacts.HandleDeleteProjectArtifact)
	s.registerV1Operation(r, operationListProjectSecretIgnores, s.Admin.Project.Secrets.HandleListSecretIgnores)
	s.registerV1Operation(r, operationCreateProjectSecretIgnore, s.Admin.Project.Secrets.HandleCreateProjectSecretIgnore)
	s.registerV1Operation(r, operationDeleteProjectSecretIgnore, s.Admin.Project.Secrets.HandleDeleteProjectSecretIgnore)
	s.registerV1Operation(r, operationGetSecretIgnoreCandidate, s.Admin.Project.Secrets.HandleSecretIgnoreCandidate)
	s.registerV1Operation(r, operationListProjectManagedSecrets, s.Admin.Project.Secrets.HandleListProjectManagedSecrets)
	s.registerV1Operation(r, operationCreateProjectManagedSecret, s.Admin.Project.Secrets.HandleCreateProjectManagedSecret)
	s.registerV1Operation(r, operationUpdateProjectManagedSecret, s.Admin.Project.Secrets.HandleUpdateProjectManagedSecret)
	s.registerV1Operation(r, operationReplaceProjectManagedSecretValue, s.Admin.Project.Secrets.HandleReplaceProjectManagedSecretValue)
	s.registerV1Operation(r, operationHoldProjectManagedSecret, s.Admin.Project.Secrets.HandleHoldProjectManagedSecret)
	s.registerV1Operation(r, operationListProjectManagedSecretUses, s.Admin.Project.Secrets.HandleListProjectManagedSecretUses)
	s.registerV1Operation(r, operationBeginProjectManagedSecretReveal, s.Admin.Project.Secrets.HandleBeginProjectManagedSecretReveal)
	s.registerV1Operation(r, operationCompleteProjectManagedSecretReveal, s.Admin.Project.Secrets.HandleCompleteProjectManagedSecretReveal)
	s.registerV1Operation(r, operationRevokeProjectManagedSecret, s.Admin.Project.Secrets.HandleRevokeProjectManagedSecret)
	s.registerV1Operation(r, operationPromoteProject, s.Admin.Project.Promotion.HandlePromoteProject)
	s.registerV1Operation(r, operationCancelProjectPromotion, s.Admin.Project.Promotion.HandleCancelProjectPromotion)
	s.registerV1Operation(r, operationAttachProjectRoot, s.Admin.Project.Roots.HandleAttachProjectRoot)
	s.registerV1Operation(r, operationDetachProjectRoot, s.Admin.Project.Roots.HandleDetachProjectRoot)
	s.registerV1Operation(r, operationUpdateProjectRoot, s.Admin.Project.Roots.HandleUpdateProjectRoot)
	s.registerV1Operation(r, operationGetProjectSource, s.Sources.Workspace.HandleGetProjectSource)
	s.registerV1Operation(r, operationGetSourceWorkspace, s.Sources.Workspace.HandleGetSourceWorkspace)
	s.registerV1Operation(r, operationOpenEditorDocument, s.Sources.Editor.HandleOpenEditorDocument)
	s.registerV1Operation(r, operationReplaceEditorDocumentRetention, s.Sources.Editor.HandleReplaceEditorDocumentRetention)
	s.registerV1Operation(r, operationReadEditorDocumentStatuses, s.Sources.Editor.HandleReadEditorDocumentStatuses)
	s.registerV1Operation(r, operationReplaceEditorDocument, s.Sources.Editor.HandleReplaceEditorDocument)
	s.registerV1Operation(r, operationSyncEditorDocument, s.Sources.Editor.HandleSyncEditorDocument)
	s.registerV1Operation(r, operationResolveEditorDocumentConflict, s.Sources.Editor.HandleResolveEditorDocumentConflict)
	s.registerV1Operation(r, operationCreateEditorDocumentSnapshot, s.Sources.Editor.HandleCreateEditorDocumentSnapshot)
	s.registerV1Operation(r, operationListEditorDocumentChanges, s.Sources.Editor.HandleListEditorDocumentChanges)
	s.registerV1Operation(r, operationRevertEditorDocumentChange, s.Sources.Editor.HandleRevertEditorDocumentChange)
	s.registerV1Operation(r, operationSubmitEditorDocumentUpdate, s.Sources.Editor.HandleSubmitEditorDocumentUpdate)
	s.registerV1Operation(r, operationPublishEditorDocumentPresence, s.Sources.Editor.HandlePublishEditorDocumentPresence)
	s.registerV1Operation(r, operationLeaveEditorDocument, s.Sources.Editor.HandleLeaveEditorDocument)
	s.registerV1Operation(r, operationDiscardEditorDocument, s.Sources.Editor.HandleDiscardEditorDocument)
	s.registerV1Operation(r, operationReloadEditorDocument, s.Sources.Editor.HandleReloadEditorDocument)
	s.registerV1Operation(r, operationObserveEditorDocument, s.Sources.Editor.HandleObserveEditorDocument)
	s.registerV1Operation(r, operationSaveEditorDocument, s.Sources.Editor.HandleSaveEditorDocument)
	s.registerV1Operation(r, operationPreviewEditorSecretMark, s.Sources.Editor.HandlePreviewEditorSecretMark)
	s.registerV1Operation(r, operationMarkEditorSecret, s.Sources.Editor.HandleMarkEditorSecret)
	s.registerV1Operation(r, operationCreateProjectSourceEntry, s.Sources.Mutations.SourceRequestHandler(toSourceOperation(operationCreateProjectSourceEntry), s.Sources.Mutations.HandleCreateProjectSourceEntry))
	s.registerV1Operation(r, operationReplaceProjectSource, s.Sources.Mutations.HandleReplaceProjectSource)
	s.registerV1Operation(r, operationMakeProjectSourceEditable, s.Sources.Mutations.HandleMakeProjectSourceEditable)
	s.registerV1Operation(r, operationDeleteProjectSource, s.Sources.Mutations.SourceRequestHandler(toSourceOperation(operationDeleteProjectSource), s.Sources.Mutations.HandleDeleteProjectSource))
	s.registerV1Operation(r, operationGetProjectSourceRaw, s.Sources.Workspace.HandleGetProjectSourceRaw)
	s.registerV1Operation(r, operationGetProjectSourceEditorConfig, s.Sources.Workspace.HandleGetProjectSourceEditorConfig)
	s.registerV1Operation(r, operationBrowseProjectSource, s.Sources.Workspace.HandleBrowseProjectSource)
	s.registerV1Operation(r, operationGetProjectSourceHistory, s.Sources.Mutations.HandleGetProjectSourceHistory)
	s.registerV1Operation(r, operationUndoProjectSourceHistory, s.Sources.Mutations.SourceRequestHandler(toSourceOperation(operationUndoProjectSourceHistory), s.Sources.Mutations.HandleUndoProjectSourceHistory))
	s.registerV1Operation(r, operationRedoProjectSourceHistory, s.Sources.Mutations.SourceRequestHandler(toSourceOperation(operationRedoProjectSourceHistory), s.Sources.Mutations.HandleRedoProjectSourceHistory))
	s.registerV1Operation(r, operationRenameProjectSource, s.Sources.Mutations.SourceRequestHandler(toSourceOperation(operationRenameProjectSource), s.Sources.Mutations.HandleRenameProjectSource))
	s.registerV1Operation(r, operationCopyProjectSource, s.Sources.Mutations.SourceRequestHandler(toSourceOperation(operationCopyProjectSource), s.Sources.Mutations.HandleCopyProjectSource))
	s.registerV1Operation(r, operationGetProjectSourceIndex, s.Sources.Analysis.HandleProjectSourceIndex)
	s.registerV1Operation(r, operationSearchProjectSource, s.Sources.Analysis.HandleSearchProjectSource)
	s.registerV1Operation(r, operationResolveProjectSourceDefinition, s.Sources.Analysis.HandleResolveProjectSourceDefinition)
	s.registerV1Operation(r, operationListProjectSourceSymbols, s.Sources.Analysis.HandleListProjectSourceSymbols)
	s.registerV1Operation(r, operationListProjectSourceWalk, s.Sources.History.HandleListProjectSourceWalk)
	s.registerV1Operation(r, operationGetProjectSourceGitReview, s.Sources.Review.HandleGetProjectSourceGitReview)
	s.registerV1Operation(r, operationResolveProjectSourceRevisions, s.Sources.Review.HandleResolveProjectSourceRevisions)
	s.registerV1Operation(r, operationGetProjectSourceRevisionReview, s.Sources.Review.HandleGetProjectSourceRevisionReview)
	s.registerV1Operation(r, operationGetProjectSourceWalkSummary, s.Sources.History.HandleGetProjectSourceWalkSummary)
	s.registerV1Operation(r, operationListProjectSourceVersions, s.Sources.History.HandleListProjectSourceVersions)
	s.registerV1Operation(r, operationRestoreProjectSourceVersion, s.Sources.Mutations.HandleRestoreProjectSourceVersion)
	s.registerV1Operation(r, operationRestoreProjectSourceCommitState, s.Sources.Mutations.HandleRestoreProjectSourceCommitState)
	s.registerV1Operation(r, operationGetFileBriefing, s.Sources.Briefings.HandleGetFileBriefing)
	s.registerV1Operation(r, operationRequestFileBriefing, s.Sources.Briefings.HandleRequestFileBriefing)
	s.registerV1Operation(r, operationCompleteProjectSourcePresentation, s.Sources.History.HandleCompleteProjectSourcePresentation)
	s.registerV1Operation(r, operationWithdrawProjectSourcePresentation, s.Sources.History.HandleWithdrawProjectSourcePresentation)
	s.registerV1Operation(r, operationListProjectSourceSeen, s.Sources.History.HandleListProjectSourceSeen)
	s.registerV1Operation(r, operationGetProjectSourceStorage, s.Sources.History.HandleGetProjectSourceStorage)
	s.registerV1Operation(r, operationGetProjectSecurity, s.Admin.Scan.HandleGetProjectSecurity)
	s.registerV1Operation(r, operationQueryProjectFindings, s.Routes.Findings.handleQueryProjectFindings)
	s.registerV1Operation(r, operationListProjectFindingIgnores, s.Routes.Findings.handleListProjectFindingIgnores)
	s.registerV1Operation(r, operationCreateProjectFindingIgnore, s.Routes.Findings.handleCreateProjectFindingIgnore)
	s.registerV1Operation(r, operationDeleteProjectFindingIgnore, s.Routes.Findings.handleDeleteProjectFindingIgnore)
	s.registerV1Operation(r, operationExportProjectFindings, s.Routes.Findings.handleExportProjectFindings)
	s.registerV1Operation(r, operationListProjectSourcePins, s.Sources.History.HandleListProjectSourcePins)
	s.registerV1Operation(r, operationCreateProjectSourcePin, s.Sources.History.HandleCreateProjectSourcePin)
	s.registerV1Operation(r, operationUpdateProjectSourcePin, s.Sources.History.HandleUpdateProjectSourcePin)
	s.registerV1Operation(r, operationDeleteProjectSourcePin, s.Sources.History.HandleDeleteProjectSourcePin)
	s.registerV1Operation(r, operationGetProjectSourceComparison, s.Sources.Comparisons.HandleGetProjectSourceComparison)
	s.registerV1Operation(r, operationCreateSourceView, s.Sources.Views.HandleCreateSourceView)
	s.registerV1Operation(r, operationDigestSourceComparisons, s.Sources.Comparisons.HandleDigestSourceComparisons)
	s.registerV1Operation(r, operationGetSourceView, s.Sources.Views.HandleGetSourceView)
	s.registerV1Operation(r, operationApplySourceViewIntent, s.Sources.Trees.HandleApplySourceViewIntent)
	s.registerV1Operation(r, operationReleaseSourceView, s.Sources.Views.HandleReleaseSourceView)
	s.registerV1Operation(r, operationReplaceSourceViewportInterest, s.Sources.Presentation.HandleReplaceSourceViewportInterest)
	s.registerV1Operation(r, operationReleaseSourceViewportInterest, s.Sources.Presentation.HandleReleaseSourceViewportInterest)
	s.registerV1Operation(r, operationCreateSourcePresentation, s.Sources.Presentation.HandleCreateSourcePresentation)
	s.registerV1Operation(r, operationReleaseSourcePresentation, s.Sources.Presentation.HandleReleaseSourcePresentation)
	s.registerV1Operation(r, operationGetSourceViewRows, s.Sources.Presentation.HandleGetSourceViewRows)
	s.registerV1Operation(r, operationLocateSourceView, s.Sources.Presentation.HandleLocateSourceView)
	s.registerV1Operation(r, operationSearchSourceView, s.Sources.Presentation.HandleSearchSourceView)
	s.registerV1Operation(r, operationGetProjectSourceAttribution, s.Sources.History.HandleGetProjectSourceAttribution)
}

func (s *Server) registerScanRoutes(r chi.Router) {
	s.registerV1Operation(r, operationListCodeScans, s.Admin.Scan.HandleListCodeScans)
	s.registerV1Operation(r, operationStartFullScan, s.Admin.Scan.HandleStartFullScan)
	s.registerV1Operation(r, operationGetCodeScan, s.Admin.Scan.HandleGetCodeScan)
	s.registerV1Operation(r, operationExportCodeScanSARIF, s.Admin.Scan.HandleExportCodeScanSARIF)
	s.registerV1Operation(r, operationQueryCodeScan, s.Admin.Scan.HandleQueryCodeScan)
	s.registerV1Operation(r, operationListScanners, s.Admin.Scan.HandleListScanners)
	s.registerV1Operation(r, operationListProjectScanners, s.Admin.Scan.HandleListProjectScanners)
	s.registerV1Operation(r, operationCreateScanner, s.Admin.Scan.HandleCreateScanner)
	s.registerV1Operation(r, operationListScannerCatalog, s.Admin.Scan.HandleListScannerCatalog)
	s.registerV1Operation(r, operationCheckScanners, s.Admin.Scan.HandleScannerCheck)
	s.registerV1Operation(r, operationReplaceScannerSlot, s.Admin.Scan.HandleReplaceScannerSlot)
	s.registerV1Operation(r, operationUpdateScanner, s.Admin.Scan.HandleUpdateScanner)
	s.registerV1Operation(r, operationUpdateProjectScanner, s.Admin.Scan.HandleUpdateProjectScanner)
	s.registerV1Operation(r, operationDeleteScanner, s.Admin.Scan.HandleDeleteScanner)
}

func (s *Server) registerWebResearchRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetWebResearchProviders, s.Admin.researchAdmin.GetProviders)
	s.registerV1Operation(r, operationGetWebResearchSettings, s.Admin.researchAdmin.GetSettings)
	s.registerV1Operation(r, operationUpdateWebResearchSettings, s.Admin.researchAdmin.UpdateSettings)
	s.registerV1Operation(r, operationUpdateWebResearchProvider, s.Admin.researchAdmin.UpdateProvider)
	s.registerV1Operation(r, operationReplaceWebResearchCredential, s.Admin.researchAdmin.SetCredential)
	s.registerV1Operation(r, operationDeleteWebResearchCredential, s.Admin.researchAdmin.DeleteCredential)
	s.registerV1Operation(r, operationTestWebResearchProvider, s.Admin.researchAdmin.TestProvider)
	s.registerV1Operation(r, operationGetWebResearchIndex, s.Admin.researchAdmin.GetIndex)
}

func (s *Server) registerMCPRoutes(r chi.Router) {
	s.registerV1Operation(r, operationListMcpRecipes, s.Admin.mcpAdmin.ListRecipes)
	s.registerV1Operation(r, operationListMcpProviders, s.Admin.mcpAdmin.ListProviders)
	s.registerV1Operation(r, operationCreateMcpProvider, s.Admin.mcpAdmin.CreateProvider)
	s.registerV1Operation(r, operationUpdateMcpProvider, s.Admin.mcpAdmin.UpdateProvider)
	s.registerV1Operation(r, operationDeleteMcpProvider, s.Admin.mcpAdmin.DeleteProvider)
	s.registerV1Operation(r, operationListMcpProviderTools, s.Admin.mcpAdmin.ListProviderTools)
	s.registerV1Operation(r, operationRefreshMcpProvider, s.Admin.mcpAdmin.RefreshProvider)
	s.registerV1Operation(r, operationStartMcpOAuth, s.Admin.mcpAdmin.StartOAuth)
	s.registerV1Operation(r, operationCompleteMcpOAuth, s.Admin.mcpAdmin.CompleteOAuth)
	s.registerV1Operation(r, operationCancelMcpOAuth, s.Admin.mcpAdmin.CancelOAuth)
	s.registerV1Operation(r, operationRevokeMcpOAuth, s.Admin.mcpAdmin.RevokeOAuth)
	s.registerV1Operation(r, operationCheckMcpProviders, s.Admin.mcpAdmin.CheckProviders)
}

func (s *Server) registerGitRoutes(r chi.Router) {
	s.registerV1Operation(r, operationListGitRepos, s.Admin.Git.HandleGitRepos)
	s.registerV1Operation(r, operationGetGitStatus, s.Admin.Git.HandleGitStatus)
	s.registerV1Operation(r, operationListGitChanges, s.Admin.Git.HandleGitChanges)
	s.registerV1Operation(r, operationListGitBranches, s.Admin.Git.HandleGitBranches)
	s.registerV1Operation(r, operationCheckoutGit, s.Admin.Git.HandleGitCheckout)
	s.registerV1Operation(r, operationCreateGitRepo, s.Admin.Git.HandleCreateGitRepo)
	s.registerV1Operation(r, operationCommitGit, s.Admin.Git.HandleGitCommit)
	s.registerV1Operation(r, operationStashGit, s.Admin.Git.HandleGitStash)
	s.registerV1Operation(r, operationDiscardGit, s.Admin.Git.HandleGitDiscard)
	s.registerV1Operation(r, operationPushGit, s.Admin.Git.HandleGitPush)
	s.registerV1Operation(r, operationPullGit, s.Admin.Git.HandleGitPull)
	s.registerV1Operation(r, operationDraftGitCommitMessage, s.Admin.Git.HandleGitCommitMessage)
	s.registerV1Operation(r, operationGetGitWorktree, s.Admin.Git.HandleGitWorktreeView)
	s.registerV1Operation(r, operationBindGitWorktree, s.Admin.Git.HandleGitWorktreeBind)
	s.registerV1Operation(r, operationLandGitWorktree, s.Admin.Git.HandleGitWorktreeLand)
	s.registerV1Operation(r, operationDeleteGitWorktree, s.Admin.Git.HandleDeleteGitWorktree)
}

func (s *Server) registerExtensionsRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetExtensionsCatalog, s.Admin.Extensions.Catalog.HandleGetExtensionsCatalog)
	s.registerV1Operation(r, operationGetExtensionUnit, s.Admin.Extensions.Mutations.HandleGetExtensionUnit)
	s.registerV1Operation(r, operationUpdateExtensionUnit, s.Admin.Extensions.Mutations.HandleUpdateExtensionUnit)
	s.registerV1Operation(r, operationInstallExtensionPack, s.Admin.Extensions.Mutations.HandleInstallExtensionPack)
	s.registerV1Operation(r, operationUpdateExtensionPack, s.Admin.Extensions.Mutations.HandleUpdateExtensionPack)
	s.registerV1Operation(r, operationDeleteExtensionPack, s.Admin.Extensions.Mutations.HandleDeleteExtensionPack)
	s.registerV1Operation(r, operationUpdateExtensionConfiguration, s.Admin.Extensions.Mutations.HandleUpdateExtensionConfiguration)
	s.registerV1Operation(r, operationGetExtensionPackUpdate, s.Admin.Extensions.Mutations.HandleGetExtensionPackUpdate)
	s.registerV1Operation(r, operationApplyExtensionPackUpdate, s.Admin.Extensions.Mutations.HandleApplyExtensionPackUpdate)
	s.registerV1Operation(r, operationReloadExtensionPack, s.Admin.Extensions.Mutations.HandleReloadExtensionPack)
	s.registerV1Operation(r, operationApplyExtensionPackProfile, s.Admin.Extensions.Mutations.HandleApplyExtensionPackProfile)
	s.registerV1Operation(r, operationInstallExtensionMetaPack, s.Admin.Extensions.Catalog.HandleInstallExtensionMetaPack)
	s.registerV1Operation(r, operationUpdateExtensionMetaPack, s.Admin.Extensions.Catalog.HandleUpdateExtensionMetaPack)
	s.registerV1Operation(r, operationDeleteExtensionMetaPack, s.Admin.Extensions.Catalog.HandleDeleteExtensionMetaPack)
	s.registerV1Operation(r, operationApplyExtensionMetaPack, s.Admin.Extensions.Catalog.HandleApplyExtensionMetaPack)
	s.registerV1Operation(r, operationGetExtensionSuggestions, s.Admin.Extensions.Suggestions.HandleGetExtensionSuggestions)
	s.registerV1Operation(r, operationAcceptExtensionSuggestions, s.Admin.Extensions.Suggestions.HandleAcceptExtensionSuggestions)
}

func (s *Server) registerHostResourceRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetHostResources, s.Routes.Activity.handleGetHostResources)
	s.registerV1Operation(r, operationRefreshHostResources, s.Routes.Activity.handleRefreshHostResources)
	s.registerV1Operation(r, operationUpdateHostResource, s.Routes.Activity.handleUpdateHostResource)
}

func (s *Server) registerSettingsRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetApprovalsSettings, s.Admin.Settings.HandleGetApprovals)
	s.registerV1Operation(r, operationUpdateApprovalsSettings, s.Admin.Settings.HandleUpdateApprovals)
	s.registerV1Operation(r, operationListApprovalGrants, s.Admin.Capabilities.Inventory.HandleListApprovalGrants)
	s.registerV1Operation(r, operationCreateApprovalGrant, s.Admin.Capabilities.Grants.HandleCreateApprovalGrant)
	s.registerV1Operation(r, operationListApprovalAsks, s.Admin.Capabilities.Inventory.HandleListApprovalAsks)
	s.registerV1Operation(r, operationResolveSocketGrant, s.Admin.Capabilities.Grants.HandleResolveSocketGrant)
	s.registerV1Operation(r, operationRevokeApprovalGrants, s.Admin.Capabilities.Grants.HandleRevokeApprovalGrants)
	s.registerV1Operation(r, operationGetElevatedAccess, s.Admin.Capabilities.Access.HandleGetElevatedAccess)
	s.registerV1Operation(r, operationRevokeElevatedAccess, s.Admin.Capabilities.Access.HandleRevokeElevatedAccess)
	s.registerV1Operation(r, operationListDetectionPacks, s.Admin.Scan.HandleListDetectionPacks)
	s.registerV1Operation(r, operationUpdateDetectionPack, s.Admin.Scan.HandleUpdateDetectionPack)
	s.registerV1Operation(r, operationImportDetectionPack, s.Admin.Scan.HandleImportDetectionPack)
	s.registerV1Operation(r, operationDeleteDetectionPack, s.Admin.Scan.HandleDeleteDetectionPack)
	s.registerV1Operation(r, operationGetLimitsSettings, s.Admin.Settings.HandleGetLimits)
	s.registerV1Operation(r, operationUpdateLimitsSettings, s.Admin.Settings.HandleUpdateLimits)
	s.registerV1Operation(r, operationGetReviewSettings, s.Admin.Settings.HandleGetReview)
	s.registerV1Operation(r, operationUpdateReviewSettings, s.Admin.Settings.HandleUpdateReview)
	s.registerV1Operation(r, operationGetFileSummariesSettings, s.Admin.Settings.HandleGetFileSummariesSettings)
	s.registerV1Operation(r, operationUpdateFileSummariesSettings, s.Admin.Settings.HandleUpdateFileSummariesSettings)
	s.registerV1Operation(r, operationGetPowerSettings, s.Admin.Settings.HandleGetPowerSettings)
	s.registerV1Operation(r, operationUpdatePowerSettings, s.Admin.Settings.HandleUpdatePowerSettings)
	s.registerV1Operation(r, operationGetVerifySettings, s.Admin.Settings.HandleGetVerify)
	s.registerV1Operation(r, operationUpdateVerifySettings, s.Admin.Settings.HandleUpdateVerify)
	s.registerV1Operation(r, operationDismissVerifySettings, s.Admin.Settings.HandleDismissVerify)
	s.registerV1Operation(r, operationGetSecurityScannersSettings, s.Admin.Settings.HandleGetSecurityScannersSettings)
	s.registerV1Operation(r, operationUpdateSecurityScannersSettings, s.Admin.Settings.HandleUpdateSecurityScannersSettings)
	s.registerV1Operation(r, operationGetPricingSettings, s.Admin.Settings.HandleGetPricingSettings)
	s.registerV1Operation(r, operationUpdatePricingSettings, s.Admin.Settings.HandleUpdatePricingSettings)
	s.registerV1Operation(r, operationRefreshPricingSource, s.Admin.Settings.HandleRefreshPricingSource)
	s.registerV1Operation(r, operationGetTrustSettings, s.Admin.Project.Trust.HandleGetTrustSettings)
	s.registerV1Operation(r, operationUpdateTrustSettings, s.Admin.Project.Trust.HandleUpdateTrustSettings)
}
