package api

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/lycaon/lycaon/internal/api/sourceapi"
)

func toSourceOperation(op generatedOperation) sourceapi.Operation {
	return sourceapi.Operation{ID: op.ID, Method: op.Method, Path: op.Path}
}

func (s *Server) registerContributionRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetContributions, s.Extensions.HandleGetContributions)
	s.registerV1Operation(r, operationInvokeProjectCommand, s.Extensions.HandleInvokeProjectCommand)
	s.registerV1Operation(r, operationInvokeSessionCommand, s.Extensions.HandleInvokeSessionCommand)
	s.registerV1Operation(r, operationResolveContributionChoices, s.Extensions.HandleContributionChoices)
	s.registerV1Operation(r, operationSearchContributionSource, s.Extensions.HandleContributionSearch)
}

func registerRootOperation(r chi.Router, operation generatedOperation, handler http.HandlerFunc) {
	r.Method(operation.Method, operation.Path, handler)
}

func (s *Server) registerV1Operation(r chi.Router, operation generatedOperation, handler http.HandlerFunc) {
	if !strings.HasPrefix(operation.Path, "/v1/") {
		panic("v1 operation path must start with /v1/")
	}
	r.Method(operation.Method, strings.TrimPrefix(operation.Path, "/v1"),
		s.authorizeOperation(operation, s.rateLimitOperation(operation, s.recordPersonAction(operation, handler)).ServeHTTP))
}

func (s *Server) registerProjectRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetSourceOperation, s.Sources.HandleGetSourceOperation)
	s.registerV1Operation(r, operationListSourceOperations, s.Sources.HandleListSourceOperations)
	s.registerV1Operation(r, operationCancelSourceOperation, s.Sources.HandleCancelSourceOperation)
	s.registerV1Operation(r, operationRetrySourceOperation, s.Sources.HandleRetrySourceOperation)
	s.registerV1Operation(r, operationListProjects, s.Project.HandleListProjects)
	s.registerV1Operation(r, operationCreateProject, s.Project.HandleCreateProject)
	s.registerV1Operation(r, operationCloneProject, s.Project.HandleCloneProject)
	s.registerV1Operation(r, operationDetectFolder, s.Extensions.HandleDetectFolder)
	s.registerV1Operation(r, operationGetProject, s.Project.HandleGetProject)
	s.registerV1Operation(r, operationListProjectSessions, s.SessionAdmin.HandleListProjectSessions)
	s.registerV1Operation(r, operationGetAgentPresence, s.handleGetAgentPresence)
	s.registerV1Operation(r, operationUpdateProject, s.Project.HandleUpdateProject)
	s.registerV1Operation(r, operationGetProjectTrust, s.Project.HandleGetProjectTrust)
	s.registerV1Operation(r, operationOpenProjectTrustReview, s.Project.HandleOpenProjectTrustReview)
	s.registerV1Operation(r, operationUpdateProjectTrust, s.Project.HandleUpdateProjectTrust)
	s.registerV1Operation(r, operationGetProjectAgentContext, s.Project.HandleGetProjectAgentContext)
	s.registerV1Operation(r, operationAssessProjectRemoval, s.Project.HandleAssessProjectRemoval)
	s.registerV1Operation(r, operationCreateProjectRemoval, s.Project.HandleCreateProjectRemoval)
	s.registerV1Operation(r, operationGetProjectRemoval, s.Project.HandleGetProjectRemoval)
	s.registerV1Operation(r, operationListProjectArtifacts, s.handleListProjectArtifacts)
	s.registerV1Operation(r, operationDeleteProjectArtifact, s.handleDeleteProjectArtifact)
	s.registerV1Operation(r, operationListProjectSecretIgnores, s.Project.HandleListSecretIgnores)
	s.registerV1Operation(r, operationCreateProjectSecretIgnore, s.Project.HandleCreateProjectSecretIgnore)
	s.registerV1Operation(r, operationDeleteProjectSecretIgnore, s.Project.HandleDeleteProjectSecretIgnore)
	s.registerV1Operation(r, operationGetSecretIgnoreCandidate, s.Project.HandleSecretIgnoreCandidate)
	s.registerV1Operation(r, operationListProjectManagedSecrets, s.Project.HandleListProjectManagedSecrets)
	s.registerV1Operation(r, operationCreateProjectManagedSecret, s.Project.HandleCreateProjectManagedSecret)
	s.registerV1Operation(r, operationUpdateProjectManagedSecret, s.Project.HandleUpdateProjectManagedSecret)
	s.registerV1Operation(r, operationReplaceProjectManagedSecretValue, s.Project.HandleReplaceProjectManagedSecretValue)
	s.registerV1Operation(r, operationHoldProjectManagedSecret, s.Project.HandleHoldProjectManagedSecret)
	s.registerV1Operation(r, operationListProjectManagedSecretUses, s.Project.HandleListProjectManagedSecretUses)
	s.registerV1Operation(r, operationBeginProjectManagedSecretReveal, s.Project.HandleBeginProjectManagedSecretReveal)
	s.registerV1Operation(r, operationCompleteProjectManagedSecretReveal, s.Project.HandleCompleteProjectManagedSecretReveal)
	s.registerV1Operation(r, operationRevokeProjectManagedSecret, s.Project.HandleRevokeProjectManagedSecret)
	s.registerV1Operation(r, operationPromoteProject, s.Project.HandlePromoteProject)
	s.registerV1Operation(r, operationCancelProjectPromotion, s.Project.HandleCancelProjectPromotion)
	s.registerV1Operation(r, operationAttachProjectRoot, s.Project.HandleAttachProjectRoot)
	s.registerV1Operation(r, operationDetachProjectRoot, s.Project.HandleDetachProjectRoot)
	s.registerV1Operation(r, operationUpdateProjectRoot, s.Project.HandleUpdateProjectRoot)
	s.registerV1Operation(r, operationGetProjectSource, s.Sources.HandleGetProjectSource)
	s.registerV1Operation(r, operationGetSourceWorkspace, s.Sources.HandleGetSourceWorkspace)
	s.registerV1Operation(r, operationOpenEditorDocument, s.Sources.HandleOpenEditorDocument)
	s.registerV1Operation(r, operationReplaceEditorDocumentRetention, s.Sources.HandleReplaceEditorDocumentRetention)
	s.registerV1Operation(r, operationReadEditorDocumentStatuses, s.Sources.HandleReadEditorDocumentStatuses)
	s.registerV1Operation(r, operationReplaceEditorDocument, s.Sources.HandleReplaceEditorDocument)
	s.registerV1Operation(r, operationSyncEditorDocument, s.Sources.HandleSyncEditorDocument)
	s.registerV1Operation(r, operationResolveEditorDocumentConflict, s.Sources.HandleResolveEditorDocumentConflict)
	s.registerV1Operation(r, operationCreateEditorDocumentSnapshot, s.Sources.HandleCreateEditorDocumentSnapshot)
	s.registerV1Operation(r, operationListEditorDocumentChanges, s.Sources.HandleListEditorDocumentChanges)
	s.registerV1Operation(r, operationRevertEditorDocumentChange, s.Sources.HandleRevertEditorDocumentChange)
	s.registerV1Operation(r, operationSubmitEditorDocumentUpdate, s.Sources.HandleSubmitEditorDocumentUpdate)
	s.registerV1Operation(r, operationPublishEditorDocumentPresence, s.Sources.HandlePublishEditorDocumentPresence)
	s.registerV1Operation(r, operationLeaveEditorDocument, s.Sources.HandleLeaveEditorDocument)
	s.registerV1Operation(r, operationDiscardEditorDocument, s.Sources.HandleDiscardEditorDocument)
	s.registerV1Operation(r, operationReloadEditorDocument, s.Sources.HandleReloadEditorDocument)
	s.registerV1Operation(r, operationObserveEditorDocument, s.Sources.HandleObserveEditorDocument)
	s.registerV1Operation(r, operationSaveEditorDocument, s.Sources.HandleSaveEditorDocument)
	s.registerV1Operation(r, operationPreviewEditorSecretMark, s.Sources.HandlePreviewEditorSecretMark)
	s.registerV1Operation(r, operationMarkEditorSecret, s.Sources.HandleMarkEditorSecret)
	s.registerV1Operation(r, operationCreateProjectSourceEntry, s.Sources.SourceRequestHandler(toSourceOperation(operationCreateProjectSourceEntry), s.Sources.HandleCreateProjectSourceEntry))
	s.registerV1Operation(r, operationReplaceProjectSource, s.Sources.HandleReplaceProjectSource)
	s.registerV1Operation(r, operationMakeProjectSourceEditable, s.Sources.HandleMakeProjectSourceEditable)
	s.registerV1Operation(r, operationDeleteProjectSource, s.Sources.SourceRequestHandler(toSourceOperation(operationDeleteProjectSource), s.Sources.HandleDeleteProjectSource))
	s.registerV1Operation(r, operationGetProjectSourceRaw, s.Sources.HandleGetProjectSourceRaw)
	s.registerV1Operation(r, operationGetProjectSourceEditorConfig, s.Sources.HandleGetProjectSourceEditorConfig)
	s.registerV1Operation(r, operationBrowseProjectSource, s.Sources.HandleBrowseProjectSource)
	s.registerV1Operation(r, operationGetProjectSourceHistory, s.Sources.HandleGetProjectSourceHistory)
	s.registerV1Operation(r, operationUndoProjectSourceHistory, s.Sources.SourceRequestHandler(toSourceOperation(operationUndoProjectSourceHistory), s.Sources.HandleUndoProjectSourceHistory))
	s.registerV1Operation(r, operationRedoProjectSourceHistory, s.Sources.SourceRequestHandler(toSourceOperation(operationRedoProjectSourceHistory), s.Sources.HandleRedoProjectSourceHistory))
	s.registerV1Operation(r, operationRenameProjectSource, s.Sources.SourceRequestHandler(toSourceOperation(operationRenameProjectSource), s.Sources.HandleRenameProjectSource))
	s.registerV1Operation(r, operationCopyProjectSource, s.Sources.SourceRequestHandler(toSourceOperation(operationCopyProjectSource), s.Sources.HandleCopyProjectSource))
	s.registerV1Operation(r, operationGetProjectSourceIndex, s.Sources.HandleProjectSourceIndex)
	s.registerV1Operation(r, operationSearchProjectSource, s.Sources.HandleSearchProjectSource)
	s.registerV1Operation(r, operationResolveProjectSourceDefinition, s.Sources.HandleResolveProjectSourceDefinition)
	s.registerV1Operation(r, operationListProjectSourceSymbols, s.Sources.HandleListProjectSourceSymbols)
	s.registerV1Operation(r, operationListProjectSourceWalk, s.Sources.HandleListProjectSourceWalk)
	s.registerV1Operation(r, operationGetProjectSourceGitReview, s.Sources.HandleGetProjectSourceGitReview)
	s.registerV1Operation(r, operationResolveProjectSourceRevisions, s.Sources.HandleResolveProjectSourceRevisions)
	s.registerV1Operation(r, operationGetProjectSourceRevisionReview, s.Sources.HandleGetProjectSourceRevisionReview)
	s.registerV1Operation(r, operationGetProjectSourceWalkSummary, s.Sources.HandleGetProjectSourceWalkSummary)
	s.registerV1Operation(r, operationListProjectSourceVersions, s.Sources.HandleListProjectSourceVersions)
	s.registerV1Operation(r, operationRestoreProjectSourceVersion, s.Sources.HandleRestoreProjectSourceVersion)
	s.registerV1Operation(r, operationRestoreProjectSourceCommitState, s.Sources.HandleRestoreProjectSourceCommitState)
	s.registerV1Operation(r, operationGetFileBriefing, s.Sources.HandleGetFileBriefing)
	s.registerV1Operation(r, operationRequestFileBriefing, s.Sources.HandleRequestFileBriefing)
	s.registerV1Operation(r, operationCompleteProjectSourcePresentation, s.Sources.HandleCompleteProjectSourcePresentation)
	s.registerV1Operation(r, operationWithdrawProjectSourcePresentation, s.Sources.HandleWithdrawProjectSourcePresentation)
	s.registerV1Operation(r, operationListProjectSourceSeen, s.Sources.HandleListProjectSourceSeen)
	s.registerV1Operation(r, operationGetProjectSourceStorage, s.Sources.HandleGetProjectSourceStorage)
	s.registerV1Operation(r, operationGetProjectSecurity, s.Scan.HandleGetProjectSecurity)
	s.registerV1Operation(r, operationQueryProjectFindings, s.handleQueryProjectFindings)
	s.registerV1Operation(r, operationListProjectFindingIgnores, s.handleListProjectFindingIgnores)
	s.registerV1Operation(r, operationCreateProjectFindingIgnore, s.handleCreateProjectFindingIgnore)
	s.registerV1Operation(r, operationDeleteProjectFindingIgnore, s.handleDeleteProjectFindingIgnore)
	s.registerV1Operation(r, operationExportProjectFindings, s.handleExportProjectFindings)
	s.registerV1Operation(r, operationListProjectSourcePins, s.Sources.HandleListProjectSourcePins)
	s.registerV1Operation(r, operationCreateProjectSourcePin, s.Sources.HandleCreateProjectSourcePin)
	s.registerV1Operation(r, operationUpdateProjectSourcePin, s.Sources.HandleUpdateProjectSourcePin)
	s.registerV1Operation(r, operationDeleteProjectSourcePin, s.Sources.HandleDeleteProjectSourcePin)
	s.registerV1Operation(r, operationGetProjectSourceComparison, s.Sources.HandleGetProjectSourceComparison)
	s.registerV1Operation(r, operationCreateSourceView, s.Sources.HandleCreateSourceView)
	s.registerV1Operation(r, operationDigestSourceComparisons, s.Sources.HandleDigestSourceComparisons)
	s.registerV1Operation(r, operationGetSourceView, s.Sources.HandleGetSourceView)
	s.registerV1Operation(r, operationApplySourceViewIntent, s.Sources.HandleApplySourceViewIntent)
	s.registerV1Operation(r, operationReleaseSourceView, s.Sources.HandleReleaseSourceView)
	s.registerV1Operation(r, operationReplaceSourceViewportInterest, s.Sources.HandleReplaceSourceViewportInterest)
	s.registerV1Operation(r, operationReleaseSourceViewportInterest, s.Sources.HandleReleaseSourceViewportInterest)
	s.registerV1Operation(r, operationCreateSourcePresentation, s.Sources.HandleCreateSourcePresentation)
	s.registerV1Operation(r, operationReleaseSourcePresentation, s.Sources.HandleReleaseSourcePresentation)
	s.registerV1Operation(r, operationGetSourceViewRows, s.Sources.HandleGetSourceViewRows)
	s.registerV1Operation(r, operationLocateSourceView, s.Sources.HandleLocateSourceView)
	s.registerV1Operation(r, operationSearchSourceView, s.Sources.HandleSearchSourceView)
	s.registerV1Operation(r, operationGetProjectSourceAttribution, s.Sources.HandleGetProjectSourceAttribution)
}

func (s *Server) registerScanRoutes(r chi.Router) {
	s.registerV1Operation(r, operationListCodeScans, s.Scan.HandleListCodeScans)
	s.registerV1Operation(r, operationStartFullScan, s.Scan.HandleStartFullScan)
	s.registerV1Operation(r, operationGetCodeScan, s.Scan.HandleGetCodeScan)
	s.registerV1Operation(r, operationExportCodeScanSARIF, s.Scan.HandleExportCodeScanSARIF)
	s.registerV1Operation(r, operationQueryCodeScan, s.Scan.HandleQueryCodeScan)
	s.registerV1Operation(r, operationListScanners, s.Scan.HandleListScanners)
	s.registerV1Operation(r, operationListProjectScanners, s.Scan.HandleListProjectScanners)
	s.registerV1Operation(r, operationCreateScanner, s.Scan.HandleCreateScanner)
	s.registerV1Operation(r, operationListScannerCatalog, s.Scan.HandleListScannerCatalog)
	s.registerV1Operation(r, operationCheckScanners, s.Scan.HandleScannerCheck)
	s.registerV1Operation(r, operationReplaceScannerSlot, s.Scan.HandleReplaceScannerSlot)
	s.registerV1Operation(r, operationUpdateScanner, s.Scan.HandleUpdateScanner)
	s.registerV1Operation(r, operationUpdateProjectScanner, s.Scan.HandleUpdateProjectScanner)
	s.registerV1Operation(r, operationDeleteScanner, s.Scan.HandleDeleteScanner)
}

func (s *Server) registerWebResearchRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetWebResearchProviders, s.researchAdmin.GetProviders)
	s.registerV1Operation(r, operationGetWebResearchSettings, s.researchAdmin.GetSettings)
	s.registerV1Operation(r, operationUpdateWebResearchSettings, s.researchAdmin.UpdateSettings)
	s.registerV1Operation(r, operationUpdateWebResearchProvider, s.researchAdmin.UpdateProvider)
	s.registerV1Operation(r, operationReplaceWebResearchCredential, s.researchAdmin.SetCredential)
	s.registerV1Operation(r, operationDeleteWebResearchCredential, s.researchAdmin.DeleteCredential)
	s.registerV1Operation(r, operationTestWebResearchProvider, s.researchAdmin.TestProvider)
	s.registerV1Operation(r, operationGetWebResearchIndex, s.researchAdmin.GetIndex)
}

func (s *Server) registerMCPRoutes(r chi.Router) {
	s.registerV1Operation(r, operationListMcpRecipes, s.mcpAdmin.ListRecipes)
	s.registerV1Operation(r, operationListMcpProviders, s.mcpAdmin.ListProviders)
	s.registerV1Operation(r, operationCreateMcpProvider, s.mcpAdmin.CreateProvider)
	s.registerV1Operation(r, operationUpdateMcpProvider, s.mcpAdmin.UpdateProvider)
	s.registerV1Operation(r, operationDeleteMcpProvider, s.mcpAdmin.DeleteProvider)
	s.registerV1Operation(r, operationListMcpProviderTools, s.mcpAdmin.ListProviderTools)
	s.registerV1Operation(r, operationRefreshMcpProvider, s.mcpAdmin.RefreshProvider)
	s.registerV1Operation(r, operationStartMcpOAuth, s.mcpAdmin.StartOAuth)
	s.registerV1Operation(r, operationCompleteMcpOAuth, s.mcpAdmin.CompleteOAuth)
	s.registerV1Operation(r, operationCancelMcpOAuth, s.mcpAdmin.CancelOAuth)
	s.registerV1Operation(r, operationRevokeMcpOAuth, s.mcpAdmin.RevokeOAuth)
	s.registerV1Operation(r, operationCheckMcpProviders, s.mcpAdmin.CheckProviders)
}

func (s *Server) registerGitRoutes(r chi.Router) {
	s.registerV1Operation(r, operationListGitRepos, s.Git.HandleGitRepos)
	s.registerV1Operation(r, operationGetGitStatus, s.Git.HandleGitStatus)
	s.registerV1Operation(r, operationListGitChanges, s.Git.HandleGitChanges)
	s.registerV1Operation(r, operationListGitBranches, s.Git.HandleGitBranches)
	s.registerV1Operation(r, operationCheckoutGit, s.Git.HandleGitCheckout)
	s.registerV1Operation(r, operationCreateGitRepo, s.Git.HandleCreateGitRepo)
	s.registerV1Operation(r, operationCommitGit, s.Git.HandleGitCommit)
	s.registerV1Operation(r, operationStashGit, s.Git.HandleGitStash)
	s.registerV1Operation(r, operationDiscardGit, s.Git.HandleGitDiscard)
	s.registerV1Operation(r, operationPushGit, s.Git.HandleGitPush)
	s.registerV1Operation(r, operationPullGit, s.Git.HandleGitPull)
	s.registerV1Operation(r, operationDraftGitCommitMessage, s.Git.HandleGitCommitMessage)
	s.registerV1Operation(r, operationGetGitWorktree, s.Git.HandleGitWorktreeView)
	s.registerV1Operation(r, operationBindGitWorktree, s.Git.HandleGitWorktreeBind)
	s.registerV1Operation(r, operationLandGitWorktree, s.Git.HandleGitWorktreeLand)
	s.registerV1Operation(r, operationDeleteGitWorktree, s.Git.HandleDeleteGitWorktree)
}

func (s *Server) registerExtensionsRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetExtensionsCatalog, s.Extensions.HandleGetExtensionsCatalog)
	s.registerV1Operation(r, operationGetExtensionUnit, s.Extensions.HandleGetExtensionUnit)
	s.registerV1Operation(r, operationUpdateExtensionUnit, s.Extensions.HandleUpdateExtensionUnit)
	s.registerV1Operation(r, operationInstallExtensionPack, s.Extensions.HandleInstallExtensionPack)
	s.registerV1Operation(r, operationUpdateExtensionPack, s.Extensions.HandleUpdateExtensionPack)
	s.registerV1Operation(r, operationDeleteExtensionPack, s.Extensions.HandleDeleteExtensionPack)
	s.registerV1Operation(r, operationUpdateExtensionConfiguration, s.Extensions.HandleUpdateExtensionConfiguration)
	s.registerV1Operation(r, operationGetExtensionPackUpdate, s.Extensions.HandleGetExtensionPackUpdate)
	s.registerV1Operation(r, operationApplyExtensionPackUpdate, s.Extensions.HandleApplyExtensionPackUpdate)
	s.registerV1Operation(r, operationReloadExtensionPack, s.Extensions.HandleReloadExtensionPack)
	s.registerV1Operation(r, operationApplyExtensionPackProfile, s.Extensions.HandleApplyExtensionPackProfile)
	s.registerV1Operation(r, operationInstallExtensionMetaPack, s.Extensions.HandleInstallExtensionMetaPack)
	s.registerV1Operation(r, operationUpdateExtensionMetaPack, s.Extensions.HandleUpdateExtensionMetaPack)
	s.registerV1Operation(r, operationDeleteExtensionMetaPack, s.Extensions.HandleDeleteExtensionMetaPack)
	s.registerV1Operation(r, operationApplyExtensionMetaPack, s.Extensions.HandleApplyExtensionMetaPack)
	s.registerV1Operation(r, operationGetExtensionSuggestions, s.Extensions.HandleGetExtensionSuggestions)
	s.registerV1Operation(r, operationAcceptExtensionSuggestions, s.Extensions.HandleAcceptExtensionSuggestions)
}

func (s *Server) registerHostResourceRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetHostResources, s.handleGetHostResources)
	s.registerV1Operation(r, operationRefreshHostResources, s.handleRefreshHostResources)
	s.registerV1Operation(r, operationUpdateHostResource, s.handleUpdateHostResource)
}

func (s *Server) registerSettingsRoutes(r chi.Router) {
	s.registerV1Operation(r, operationGetApprovalsSettings, s.Settings.HandleGetApprovals)
	s.registerV1Operation(r, operationUpdateApprovalsSettings, s.Settings.HandleUpdateApprovals)
	s.registerV1Operation(r, operationListApprovalGrants, s.Capabilities.HandleListApprovalGrants)
	s.registerV1Operation(r, operationCreateApprovalGrant, s.Capabilities.HandleCreateApprovalGrant)
	s.registerV1Operation(r, operationListApprovalAsks, s.Capabilities.HandleListApprovalAsks)
	s.registerV1Operation(r, operationResolveSocketGrant, s.Capabilities.HandleResolveSocketGrant)
	s.registerV1Operation(r, operationRevokeApprovalGrants, s.Capabilities.HandleRevokeApprovalGrants)
	s.registerV1Operation(r, operationGetElevatedAccess, s.Capabilities.HandleGetElevatedAccess)
	s.registerV1Operation(r, operationRevokeElevatedAccess, s.Capabilities.HandleRevokeElevatedAccess)
	s.registerV1Operation(r, operationListDetectionPacks, s.Scan.HandleListDetectionPacks)
	s.registerV1Operation(r, operationUpdateDetectionPack, s.Scan.HandleUpdateDetectionPack)
	s.registerV1Operation(r, operationImportDetectionPack, s.Scan.HandleImportDetectionPack)
	s.registerV1Operation(r, operationDeleteDetectionPack, s.Scan.HandleDeleteDetectionPack)
	s.registerV1Operation(r, operationGetLimitsSettings, s.Settings.HandleGetLimits)
	s.registerV1Operation(r, operationUpdateLimitsSettings, s.Settings.HandleUpdateLimits)
	s.registerV1Operation(r, operationGetReviewSettings, s.Settings.HandleGetReview)
	s.registerV1Operation(r, operationUpdateReviewSettings, s.Settings.HandleUpdateReview)
	s.registerV1Operation(r, operationGetFileSummariesSettings, s.Settings.HandleGetFileSummariesSettings)
	s.registerV1Operation(r, operationUpdateFileSummariesSettings, s.Settings.HandleUpdateFileSummariesSettings)
	s.registerV1Operation(r, operationGetPowerSettings, s.Settings.HandleGetPowerSettings)
	s.registerV1Operation(r, operationUpdatePowerSettings, s.Settings.HandleUpdatePowerSettings)
	s.registerV1Operation(r, operationGetVerifySettings, s.Settings.HandleGetVerify)
	s.registerV1Operation(r, operationUpdateVerifySettings, s.Settings.HandleUpdateVerify)
	s.registerV1Operation(r, operationDismissVerifySettings, s.Settings.HandleDismissVerify)
	s.registerV1Operation(r, operationGetSecurityScannersSettings, s.Settings.HandleGetSecurityScannersSettings)
	s.registerV1Operation(r, operationUpdateSecurityScannersSettings, s.Settings.HandleUpdateSecurityScannersSettings)
	s.registerV1Operation(r, operationGetPricingSettings, s.Settings.HandleGetPricingSettings)
	s.registerV1Operation(r, operationUpdatePricingSettings, s.Settings.HandleUpdatePricingSettings)
	s.registerV1Operation(r, operationRefreshPricingSource, s.Settings.HandleRefreshPricingSource)
	s.registerV1Operation(r, operationGetTrustSettings, s.Project.HandleGetTrustSettings)
	s.registerV1Operation(r, operationUpdateTrustSettings, s.Project.HandleUpdateTrustSettings)
}
