// Generated by codegen-contribution-facts from the Go contribution
// vocabulary. Do not edit; run ./task codegen:contribution-facts.

/** Chords each platform consumes before an app window sees them; "+*" covers every chord holding the listed modifiers. */
export const OS_INTERCEPTED_CHORDS: Readonly<Record<"linux" | "macos" | "windows", readonly string[]>> = {
  linux: [
    "Super+*",
    "Alt+Tab",
    "Mod+Alt+Delete",
  ],
  macos: [
    "Mod+Space",
    "Mod+Alt+Space",
    "Mod+Ctrl+Space",
    "Ctrl+Space",
    "Mod+Tab",
    "Mod+Alt+Escape",
    "Mod+Shift+Q",
    "Mod+Ctrl+Q",
    "Mod+Alt+D",
    "Mod+Shift+3",
    "Mod+Shift+4",
    "Mod+Shift+5",
    "Ctrl+ArrowUp",
    "Ctrl+ArrowDown",
    "Ctrl+ArrowLeft",
    "Ctrl+ArrowRight",
  ],
  windows: [
    "Alt+Tab",
    "Mod+Shift+Escape",
    "Mod+Alt+Delete",
    "Super+*",
  ],
};

/** Keys reserved for assistive navigation on every platform. */
export const ASSISTIVE_RESERVED_KEYS: readonly string[] = [
  "CapsLock",
  "Insert",
  "ScrollLock",
];
