/** Built-in context action identity and presentation. Domain helpers own target binding and order. */
export const CONTEXT_ACTIONS = {
  addToChat: { label: "Add to chat" },
  archiveChat: { label: "Archive chat" },
  askAboutSelection: { label: "Ask about selection" },
  close: { label: "Close" },
  closeAll: { label: "Close all" },
  closeCurrent: { label: "Close current" },
  closeOthers: { label: "Close others" },
  closeSaved: { label: "Close saved" },
  closeToTheRight: { label: "Close to the right" },
  closeWindow: { label: "Close window" },
  collapseAll: { label: "Collapse all" },
  convertIndentationToSpaces: { label: "Convert indentation to spaces" },
  convertIndentationToTabs: { label: "Convert indentation to tabs" },
  copy: { label: "Copy" },
  copyContents: { label: "Copy contents" },
  copyFileName: { label: "Copy file name" },
  copyJobID: { label: "Copy job ID" },
  copyLink: { label: "Copy link" },
  copyPath: { label: "Copy path" },
  copyPathLine: { label: "Copy path:line" },
  copyRelativePath: { label: "Copy relative path" },
  copyRelativePathLine: { label: "Copy relative path:line" },
  copySessionID: { label: "Copy session ID" },
  copyTitle: { label: "Copy title" },
  currentVersion: { label: "Current" },
  cut: { label: "Cut" },
  delete: { label: "Delete", danger: true },
  deleteArtifact: { label: "Delete artifact…", danger: true },
  deleteChat: { label: "Delete chat…", danger: true },
  duplicate: { label: "Duplicate" },
  eolCrlf: { label: "CRLF" },
  eolLf: { label: "LF" },
  expandAll: { label: "Expand all" },
  explainInReview: { label: "Explain in review" },
  export: { label: "Export" },
  exportAsJSON: { label: "Export as JSON" },
  exportAsMarkdown: { label: "Export as Markdown" },
  findEverywhere: { label: "Find everywhere", handler: "find.everywhere" },
  findInFile: { label: "Find in file", handler: "find.inView" },
  findNext: { label: "Find next", handler: "find.next" },
  findPrevious: { label: "Find previous", handler: "find.prev" },
  focusWindow: { label: "Focus window" },
  goToDefinition: { label: "Go to definition", handler: "files.goToDefinition" },
  goToLine: { label: "Go to line", handler: "editor.goToLine" },
  goToNextFinding: { label: "Go to next finding", handler: "editor.nextFinding" },
  goToPreviousFinding: { label: "Go to previous finding", handler: "editor.previousFinding" },
  inlineEdit: { label: "Inline edit", handler: "editor.inlineEdit" },
  keepOpen: { label: "Keep open" },
  markAsSecret: { label: "Mark as secret" },
  moveDown: { label: "Move down" },
  moveTo: { label: "Move to…" },
  moveToTrash: { label: "Move to trash", danger: true },
  moveUp: { label: "Move up" },
  newFile: { label: "New file" },
  newFolder: { label: "New folder" },
  open: { label: "Open" },
  openAnotherWindow: { label: "Open another window" },
  openAsUTF16BE: { label: "Open as UTF-16 BE" },
  openAsUTF16LE: { label: "Open as UTF-16 LE" },
  openEvidence: { label: "Open evidence" },
  openFiles: { label: "Open files…" },
  openIn: { label: "Open in" },
  openInNewWindow: { label: "Open in new window" },
  openWorker: { label: "Open worker" },
  paste: { label: "Paste" },
  pin: { label: "Pin" },
  previousVersion: { label: "Before this version" },
  removeFolderFromProject: { label: "Remove folder from project", danger: true },
  rename: { label: "Rename" },
  replaceInFile: { label: "Replace in file", handler: "find.replace" },
  restoreComparisonBaseline: { label: "Restore comparison baseline", danger: true },
  revealInTree: { label: "Reveal in tree" },
  selectAll: { label: "Select all" },
  selectAllFindMatches: { label: "Select all find matches", handler: "find.selectAllMatches" },
  showInReview: { label: "Show in review" },
  showSecretScreen: { label: "Show secret screen", handler: "files.showSecretScreen" },
  unarchiveChat: { label: "Unarchive chat" },
  unpin: { label: "Unpin" },
  exportSarif: { label: "Export SARIF" },
  exportOpenVex: { label: "Export OpenVEX" },
  exportCsvPage: { label: "Export CSV (this page)" },
  ignoreRules: { label: "Ignore rules…" },
  scanRuns: { label: "Scan runs…" },
  backToFindings: { label: "Back to findings" },
  exportJsonl: { label: "Export JSONL" },
  exportCsv: { label: "Export CSV" },
  exportFilteredCsv: { label: "Export CSV (filtered)" },
} as const;

export type ContextActionId = keyof typeof CONTEXT_ACTIONS;
