// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: artifacts.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countArtifactsWithContentHash = `-- name: CountArtifactsWithContentHash :one
SELECT COUNT(*) FROM artifacts
WHERE project_id = ? AND content_hash = ? AND deleted_at IS NULL AND id != ?
`

type CountArtifactsWithContentHashParams struct {
	ProjectID   string `json:"project_id"`
	ContentHash string `json:"content_hash"`
	ID          string `json:"id"`
}

func (q *Queries) CountArtifactsWithContentHash(ctx context.Context, arg CountArtifactsWithContentHashParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtifactsWithContentHash, arg.ProjectID, arg.ContentHash, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessageArtifactRefs = `-- name: DeleteMessageArtifactRefs :exec
DELETE FROM artifact_refs WHERE message_id = ?
`

func (q *Queries) DeleteMessageArtifactRefs(ctx context.Context, messageID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteMessageArtifactRefs, messageID)
	return err
}

const deleteProjectArtifactRefsOfKind = `-- name: DeleteProjectArtifactRefsOfKind :exec
DELETE FROM artifact_refs WHERE project_id = ? AND kind = ?
`

type DeleteProjectArtifactRefsOfKindParams struct {
	ProjectID string `json:"project_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) DeleteProjectArtifactRefsOfKind(ctx context.Context, arg DeleteProjectArtifactRefsOfKindParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectArtifactRefsOfKind, arg.ProjectID, arg.Kind)
	return err
}

const deleteUnreferencedArtifact = `-- name: DeleteUnreferencedArtifact :execrows
DELETE FROM artifacts
WHERE project_id = ? AND id = ?
  AND NOT EXISTS (SELECT 1 FROM artifact_refs WHERE artifact_id = artifacts.id)
`

type DeleteUnreferencedArtifactParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) DeleteUnreferencedArtifact(ctx context.Context, arg DeleteUnreferencedArtifactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedArtifact, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findTreeArtifactByEvidenceHandle = `-- name: FindTreeArtifactByEvidenceHandle :one
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE root_session_id = ? AND evidence_handle = ? AND deleted_at IS NULL
ORDER BY created_at DESC, rowid DESC
LIMIT 1
`

type FindTreeArtifactByEvidenceHandleParams struct {
	RootSessionID  sql.NullString `json:"root_session_id"`
	EvidenceHandle string         `json:"evidence_handle"`
}

func (q *Queries) FindTreeArtifactByEvidenceHandle(ctx context.Context, arg FindTreeArtifactByEvidenceHandleParams) (Artifacts, error) {
	row := q.db.QueryRowContext(ctx, findTreeArtifactByEvidenceHandle, arg.RootSessionID, arg.EvidenceHandle)
	var i Artifacts
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.SessionID,
		&i.WorkflowRunID,
		&i.ToolCallID,
		&i.OriginMessageID,
		&i.OperationID,
		&i.NaturalKey,
		&i.ContentHash,
		&i.RetentionClass,
		&i.ByteSize,
		&i.StoredSize,
		&i.Mime,
		&i.Source,
		&i.Caption,
		&i.EvidenceHandle,
		&i.PageID,
		&i.Perceive,
		&i.DurationMs,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifacts, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifacts
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.SessionID,
		&i.WorkflowRunID,
		&i.ToolCallID,
		&i.OriginMessageID,
		&i.OperationID,
		&i.NaturalKey,
		&i.ContentHash,
		&i.RetentionClass,
		&i.ByteSize,
		&i.StoredSize,
		&i.Mime,
		&i.Source,
		&i.Caption,
		&i.EvidenceHandle,
		&i.PageID,
		&i.Perceive,
		&i.DurationMs,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const getArtifactByNaturalKey = `-- name: GetArtifactByNaturalKey :one
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE project_id = ? AND natural_key = ? AND deleted_at IS NULL
`

type GetArtifactByNaturalKeyParams struct {
	ProjectID  string         `json:"project_id"`
	NaturalKey sql.NullString `json:"natural_key"`
}

func (q *Queries) GetArtifactByNaturalKey(ctx context.Context, arg GetArtifactByNaturalKeyParams) (Artifacts, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByNaturalKey, arg.ProjectID, arg.NaturalKey)
	var i Artifacts
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.SessionID,
		&i.WorkflowRunID,
		&i.ToolCallID,
		&i.OriginMessageID,
		&i.OperationID,
		&i.NaturalKey,
		&i.ContentHash,
		&i.RetentionClass,
		&i.ByteSize,
		&i.StoredSize,
		&i.Mime,
		&i.Source,
		&i.Caption,
		&i.EvidenceHandle,
		&i.PageID,
		&i.Perceive,
		&i.DurationMs,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const getArtifactByOperation = `-- name: GetArtifactByOperation :one
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE project_id = ? AND operation_id = ? AND deleted_at IS NULL
`

type GetArtifactByOperationParams struct {
	ProjectID   string         `json:"project_id"`
	OperationID sql.NullString `json:"operation_id"`
}

// Identity lookups claim only live rows.
func (q *Queries) GetArtifactByOperation(ctx context.Context, arg GetArtifactByOperationParams) (Artifacts, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByOperation, arg.ProjectID, arg.OperationID)
	var i Artifacts
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.SessionID,
		&i.WorkflowRunID,
		&i.ToolCallID,
		&i.OriginMessageID,
		&i.OperationID,
		&i.NaturalKey,
		&i.ContentHash,
		&i.RetentionClass,
		&i.ByteSize,
		&i.StoredSize,
		&i.Mime,
		&i.Source,
		&i.Caption,
		&i.EvidenceHandle,
		&i.PageID,
		&i.Perceive,
		&i.DurationMs,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const getArtifactInProject = `-- name: GetArtifactInProject :one
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE project_id = ? AND id = ?
`

type GetArtifactInProjectParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetArtifactInProject(ctx context.Context, arg GetArtifactInProjectParams) (Artifacts, error) {
	row := q.db.QueryRowContext(ctx, getArtifactInProject, arg.ProjectID, arg.ID)
	var i Artifacts
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.SessionID,
		&i.WorkflowRunID,
		&i.ToolCallID,
		&i.OriginMessageID,
		&i.OperationID,
		&i.NaturalKey,
		&i.ContentHash,
		&i.RetentionClass,
		&i.ByteSize,
		&i.StoredSize,
		&i.Mime,
		&i.Source,
		&i.Caption,
		&i.EvidenceHandle,
		&i.PageID,
		&i.Perceive,
		&i.DurationMs,
		&i.RecordedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const listArtifactRefs = `-- name: ListArtifactRefs :many
SELECT id, artifact_id, project_id, kind, message_id, session_id, tool_call_id, created_at
FROM artifact_refs
WHERE artifact_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListArtifactRefs(ctx context.Context, artifactID string) ([]ArtifactRefs, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactRefs, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactRefs
	for rows.Next() {
		var i ArtifactRefs
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.ProjectID,
			&i.Kind,
			&i.MessageID,
			&i.SessionID,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectArtifactOriginsFor = `-- name: ListProjectArtifactOriginsFor :many
SELECT r.artifact_id, r.message_id, r.tool_call_id
FROM artifact_refs r
JOIN artifacts a ON a.id = r.artifact_id
WHERE a.project_id = ?1
  AND r.artifact_id IN (/*SLICE:artifact_ids*/?)
  AND (r.message_id IS NOT NULL OR r.tool_call_id <> '')
ORDER BY r.created_at ASC, r.id ASC
`

type ListProjectArtifactOriginsForParams struct {
	ProjectID   string   `json:"project_id"`
	ArtifactIds []string `json:"artifact_ids"`
}

type ListProjectArtifactOriginsForRow struct {
	ArtifactID string         `json:"artifact_id"`
	MessageID  sql.NullString `json:"message_id"`
	ToolCallID string         `json:"tool_call_id"`
}

func (q *Queries) ListProjectArtifactOriginsFor(ctx context.Context, arg ListProjectArtifactOriginsForParams) ([]ListProjectArtifactOriginsForRow, error) {
	query := listProjectArtifactOriginsFor
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.ArtifactIds) > 0 {
		for _, v := range arg.ArtifactIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:artifact_ids*/?", strings.Repeat(",?", len(arg.ArtifactIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:artifact_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectArtifactOriginsForRow
	for rows.Next() {
		var i ListProjectArtifactOriginsForRow
		if err := rows.Scan(&i.ArtifactID, &i.MessageID, &i.ToolCallID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectArtifactRefCountsFor = `-- name: ListProjectArtifactRefCountsFor :many
SELECT r.artifact_id, r.kind, COUNT(*) AS ref_count
FROM artifact_refs r
JOIN artifacts a ON a.id = r.artifact_id
WHERE a.project_id = ?1
  AND r.artifact_id IN (/*SLICE:artifact_ids*/?)
GROUP BY r.artifact_id, r.kind
ORDER BY r.artifact_id ASC, r.kind ASC
`

type ListProjectArtifactRefCountsForParams struct {
	ProjectID   string   `json:"project_id"`
	ArtifactIds []string `json:"artifact_ids"`
}

type ListProjectArtifactRefCountsForRow struct {
	ArtifactID string `json:"artifact_id"`
	Kind       string `json:"kind"`
	RefCount   int64  `json:"ref_count"`
}

func (q *Queries) ListProjectArtifactRefCountsFor(ctx context.Context, arg ListProjectArtifactRefCountsForParams) ([]ListProjectArtifactRefCountsForRow, error) {
	query := listProjectArtifactRefCountsFor
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.ArtifactIds) > 0 {
		for _, v := range arg.ArtifactIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:artifact_ids*/?", strings.Repeat(",?", len(arg.ArtifactIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:artifact_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectArtifactRefCountsForRow
	for rows.Next() {
		var i ListProjectArtifactRefCountsForRow
		if err := rows.Scan(&i.ArtifactID, &i.Kind, &i.RefCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreeArtifactOrigins = `-- name: ListTreeArtifactOrigins :many
SELECT r.artifact_id, r.message_id, r.tool_call_id FROM artifact_refs r
JOIN artifacts a ON a.id = r.artifact_id
WHERE a.root_session_id = ? AND (r.message_id IS NOT NULL OR r.tool_call_id <> '')
ORDER BY r.created_at ASC, r.id ASC
`

type ListTreeArtifactOriginsRow struct {
	ArtifactID string         `json:"artifact_id"`
	MessageID  sql.NullString `json:"message_id"`
	ToolCallID string         `json:"tool_call_id"`
}

func (q *Queries) ListTreeArtifactOrigins(ctx context.Context, rootSessionID sql.NullString) ([]ListTreeArtifactOriginsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTreeArtifactOrigins, rootSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTreeArtifactOriginsRow
	for rows.Next() {
		var i ListTreeArtifactOriginsRow
		if err := rows.Scan(&i.ArtifactID, &i.MessageID, &i.ToolCallID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreeArtifacts = `-- name: ListTreeArtifacts :many
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE project_id = ? AND root_session_id = ? AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

type ListTreeArtifactsParams struct {
	ProjectID     string         `json:"project_id"`
	RootSessionID sql.NullString `json:"root_session_id"`
}

func (q *Queries) ListTreeArtifacts(ctx context.Context, arg ListTreeArtifactsParams) ([]Artifacts, error) {
	rows, err := q.db.QueryContext(ctx, listTreeArtifacts, arg.ProjectID, arg.RootSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifacts
	for rows.Next() {
		var i Artifacts
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RootSessionID,
			&i.SessionID,
			&i.WorkflowRunID,
			&i.ToolCallID,
			&i.OriginMessageID,
			&i.OperationID,
			&i.NaturalKey,
			&i.ContentHash,
			&i.RetentionClass,
			&i.ByteSize,
			&i.StoredSize,
			&i.Mime,
			&i.Source,
			&i.Caption,
			&i.EvidenceHandle,
			&i.PageID,
			&i.Perceive,
			&i.DurationMs,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedReason,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageProjectArtifacts = `-- name: PageProjectArtifacts :many
SELECT id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, deleted_at, deleted_reason, width, height
FROM artifacts
WHERE project_id = ?1 AND deleted_at IS NULL
  AND (
    created_at > ?2
    OR (created_at = ?2 AND id > ?3)
  )
ORDER BY created_at ASC, id ASC
LIMIT ?4
`

type PageProjectArtifactsParams struct {
	ProjectID      string `json:"project_id"`
	AfterCreatedAt string `json:"after_created_at"`
	AfterID        string `json:"after_id"`
	PageLimit      int64  `json:"page_limit"`
}

func (q *Queries) PageProjectArtifacts(ctx context.Context, arg PageProjectArtifactsParams) ([]Artifacts, error) {
	rows, err := q.db.QueryContext(ctx, pageProjectArtifacts,
		arg.ProjectID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifacts
	for rows.Next() {
		var i Artifacts
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RootSessionID,
			&i.SessionID,
			&i.WorkflowRunID,
			&i.ToolCallID,
			&i.OriginMessageID,
			&i.OperationID,
			&i.NaturalKey,
			&i.ContentHash,
			&i.RetentionClass,
			&i.ByteSize,
			&i.StoredSize,
			&i.Mime,
			&i.Source,
			&i.Caption,
			&i.EvidenceHandle,
			&i.PageID,
			&i.Perceive,
			&i.DurationMs,
			&i.RecordedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedReason,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArtifact = `-- name: SoftDeleteArtifact :execrows
UPDATE artifacts SET deleted_at = ?, deleted_reason = ?, updated_at = ?
WHERE project_id = ? AND id = ? AND deleted_at IS NULL
`

type SoftDeleteArtifactParams struct {
	DeletedAt     sql.NullString `json:"deleted_at"`
	DeletedReason sql.NullString `json:"deleted_reason"`
	UpdatedAt     string         `json:"updated_at"`
	ProjectID     string         `json:"project_id"`
	ID            string         `json:"id"`
}

func (q *Queries) SoftDeleteArtifact(ctx context.Context, arg SoftDeleteArtifactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteArtifact,
		arg.DeletedAt,
		arg.DeletedReason,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumProjectArtifactBytes = `-- name: SumProjectArtifactBytes :one
SELECT CAST(COALESCE(SUM(stored_size), 0) AS INTEGER) AS total_bytes
FROM (
    SELECT MAX(live.stored_size) AS stored_size
    FROM artifacts live
    WHERE live.project_id = ?1 AND live.deleted_at IS NULL
    GROUP BY live.content_hash
    UNION ALL
    SELECT q.stored_size FROM artifact_gc_queue q
    WHERE q.project_id = ?1
      AND NOT EXISTS(SELECT 1 FROM artifacts a WHERE a.project_id=q.project_id AND a.content_hash=q.content_hash AND a.deleted_at IS NULL)
) AS unique_content
`

func (q *Queries) SumProjectArtifactBytes(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumProjectArtifactBytes, projectID)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const upsertArtifact = `-- name: UpsertArtifact :execrows

INSERT INTO artifacts (
    id, project_id, root_session_id, session_id, workflow_run_id, tool_call_id,
    origin_message_id, operation_id, natural_key, content_hash, retention_class, byte_size, stored_size, mime, source, caption,
    evidence_handle, page_id, perceive, duration_ms, recorded_at,
    created_at, updated_at, width, height
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    root_session_id = excluded.root_session_id,
    session_id = excluded.session_id,
    workflow_run_id = excluded.workflow_run_id,
    tool_call_id = excluded.tool_call_id,
    origin_message_id = excluded.origin_message_id,
    operation_id = excluded.operation_id,
    natural_key = excluded.natural_key,
    content_hash = excluded.content_hash,
    byte_size = excluded.byte_size,
    stored_size = excluded.stored_size,
    mime = excluded.mime,
    source = excluded.source,
    retention_class = excluded.retention_class,
    caption = excluded.caption,
    evidence_handle = excluded.evidence_handle,
    page_id = excluded.page_id,
    perceive = excluded.perceive,
    duration_ms = excluded.duration_ms,
    recorded_at = excluded.recorded_at,
    updated_at = excluded.updated_at,
    width = excluded.width,
    height = excluded.height
WHERE artifacts.deleted_at IS NULL
`

type UpsertArtifactParams struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	RootSessionID   sql.NullString `json:"root_session_id"`
	SessionID       sql.NullString `json:"session_id"`
	WorkflowRunID   sql.NullString `json:"workflow_run_id"`
	ToolCallID      string         `json:"tool_call_id"`
	OriginMessageID string         `json:"origin_message_id"`
	OperationID     sql.NullString `json:"operation_id"`
	NaturalKey      sql.NullString `json:"natural_key"`
	ContentHash     string         `json:"content_hash"`
	RetentionClass  string         `json:"retention_class"`
	ByteSize        int64          `json:"byte_size"`
	StoredSize      int64          `json:"stored_size"`
	Mime            string         `json:"mime"`
	Source          string         `json:"source"`
	Caption         string         `json:"caption"`
	EvidenceHandle  string         `json:"evidence_handle"`
	PageID          string         `json:"page_id"`
	Perceive        int64          `json:"perceive"`
	DurationMs      int64          `json:"duration_ms"`
	RecordedAt      sql.NullString `json:"recorded_at"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	Width           int64          `json:"width"`
	Height          int64          `json:"height"`
}

// Durable visual artifact records and the reference rows that pin them.
// Tombstones reserve their IDs.
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertArtifact,
		arg.ID,
		arg.ProjectID,
		arg.RootSessionID,
		arg.SessionID,
		arg.WorkflowRunID,
		arg.ToolCallID,
		arg.OriginMessageID,
		arg.OperationID,
		arg.NaturalKey,
		arg.ContentHash,
		arg.RetentionClass,
		arg.ByteSize,
		arg.StoredSize,
		arg.Mime,
		arg.Source,
		arg.Caption,
		arg.EvidenceHandle,
		arg.PageID,
		arg.Perceive,
		arg.DurationMs,
		arg.RecordedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Width,
		arg.Height,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertArtifactRef = `-- name: UpsertArtifactRef :exec
INSERT INTO artifact_refs (id, artifact_id, project_id, kind, message_id, session_id, tool_call_id, created_at)
SELECT ?, a.id, a.project_id, ?, ?, ?, ?, ?
FROM artifacts a
WHERE a.id = ? AND a.project_id = ?
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    message_id = excluded.message_id,
    session_id = excluded.session_id,
    tool_call_id = excluded.tool_call_id
`

type UpsertArtifactRefParams struct {
	ID         string         `json:"id"`
	Kind       string         `json:"kind"`
	MessageID  sql.NullString `json:"message_id"`
	SessionID  sql.NullString `json:"session_id"`
	ToolCallID string         `json:"tool_call_id"`
	CreatedAt  string         `json:"created_at"`
	ID_2       string         `json:"id_2"`
	ProjectID  string         `json:"project_id"`
}

func (q *Queries) UpsertArtifactRef(ctx context.Context, arg UpsertArtifactRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtifactRef,
		arg.ID,
		arg.Kind,
		arg.MessageID,
		arg.SessionID,
		arg.ToolCallID,
		arg.CreatedAt,
		arg.ID_2,
		arg.ProjectID,
	)
	return err
}
