// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cookie_jars.sql

package db

import (
	"context"
	"database/sql"
)

const createCookieJarSave = `-- name: CreateCookieJarSave :exec
INSERT INTO managed_cookie_jar_saves (project_id, chat_session_id, session_id, operation_id, name, secret_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCookieJarSaveParams struct {
	ProjectID     string         `json:"project_id"`
	ChatSessionID string         `json:"chat_session_id"`
	SessionID     string         `json:"session_id"`
	OperationID   string         `json:"operation_id"`
	Name          string         `json:"name"`
	SecretID      sql.NullString `json:"secret_id"`
}

func (q *Queries) CreateCookieJarSave(ctx context.Context, arg CreateCookieJarSaveParams) error {
	_, err := q.db.ExecContext(ctx, createCookieJarSave,
		arg.ProjectID,
		arg.ChatSessionID,
		arg.SessionID,
		arg.OperationID,
		arg.Name,
		arg.SecretID,
	)
	return err
}

const getCookieJarSave = `-- name: GetCookieJarSave :one
SELECT project_id, chat_session_id, session_id, operation_id, name, secret_id
FROM managed_cookie_jar_saves
WHERE project_id = ? AND session_id = ? AND operation_id = ?
`

type GetCookieJarSaveParams struct {
	ProjectID   string `json:"project_id"`
	SessionID   string `json:"session_id"`
	OperationID string `json:"operation_id"`
}

func (q *Queries) GetCookieJarSave(ctx context.Context, arg GetCookieJarSaveParams) (ManagedCookieJarSaves, error) {
	row := q.db.QueryRowContext(ctx, getCookieJarSave, arg.ProjectID, arg.SessionID, arg.OperationID)
	var i ManagedCookieJarSaves
	err := row.Scan(
		&i.ProjectID,
		&i.ChatSessionID,
		&i.SessionID,
		&i.OperationID,
		&i.Name,
		&i.SecretID,
	)
	return i, err
}
