// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: draft_versions.sql

package db

import (
	"context"
)

const countDraftVersions = `-- name: CountDraftVersions :one
SELECT COUNT(*) FROM draft_versions WHERE session_id = ? AND slot_id = ?
`

type CountDraftVersionsParams struct {
	SessionID string `json:"session_id"`
	SlotID    string `json:"slot_id"`
}

func (q *Queries) CountDraftVersions(ctx context.Context, arg CountDraftVersionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDraftVersions, arg.SessionID, arg.SlotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertDraftVersion = `-- name: InsertDraftVersion :exec
INSERT INTO draft_versions (session_id, slot_id, version_index, body, outcome_code, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDraftVersionParams struct {
	SessionID    string `json:"session_id"`
	SlotID       string `json:"slot_id"`
	VersionIndex int64  `json:"version_index"`
	Body         string `json:"body"`
	OutcomeCode  string `json:"outcome_code"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) InsertDraftVersion(ctx context.Context, arg InsertDraftVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertDraftVersion,
		arg.SessionID,
		arg.SlotID,
		arg.VersionIndex,
		arg.Body,
		arg.OutcomeCode,
		arg.CreatedAt,
	)
	return err
}

const listDraftVersions = `-- name: ListDraftVersions :many
SELECT version_index, body, outcome_code, created_at
FROM draft_versions
WHERE session_id = ? AND slot_id = ?
ORDER BY version_index
`

type ListDraftVersionsParams struct {
	SessionID string `json:"session_id"`
	SlotID    string `json:"slot_id"`
}

type ListDraftVersionsRow struct {
	VersionIndex int64  `json:"version_index"`
	Body         string `json:"body"`
	OutcomeCode  string `json:"outcome_code"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) ListDraftVersions(ctx context.Context, arg ListDraftVersionsParams) ([]ListDraftVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftVersions, arg.SessionID, arg.SlotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftVersionsRow
	for rows.Next() {
		var i ListDraftVersionsRow
		if err := rows.Scan(
			&i.VersionIndex,
			&i.Body,
			&i.OutcomeCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDraftVersionIndex = `-- name: NextDraftVersionIndex :one

SELECT COALESCE(MAX(version_index), -1) + 1 AS next_index
FROM draft_versions
WHERE session_id = ? AND slot_id = ?
`

type NextDraftVersionIndexParams struct {
	SessionID string `json:"session_id"`
	SlotID    string `json:"slot_id"`
}

// Superseded coordinator draft snapshots, one row per attempt.
func (q *Queries) NextDraftVersionIndex(ctx context.Context, arg NextDraftVersionIndexParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextDraftVersionIndex, arg.SessionID, arg.SlotID)
	var next_index int64
	err := row.Scan(&next_index)
	return next_index, err
}
