// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type ApprovalOperations struct {
	CheckpointID string         `json:"checkpoint_id"`
	SessionID    string         `json:"session_id"`
	OptionID     string         `json:"option_id"`
	OptionJson   string         `json:"option_json"`
	Status       string         `json:"status"`
	CreatedAt    string         `json:"created_at"`
	CommittedAt  sql.NullString `json:"committed_at"`
	RolledBackAt sql.NullString `json:"rolled_back_at"`
}

type ArtifactGcQueue struct {
	ProjectID   string `json:"project_id"`
	ContentHash string `json:"content_hash"`
	StoredSize  int64  `json:"stored_size"`
}

type ArtifactRefs struct {
	ID         string         `json:"id"`
	ArtifactID string         `json:"artifact_id"`
	ProjectID  string         `json:"project_id"`
	Kind       string         `json:"kind"`
	MessageID  sql.NullString `json:"message_id"`
	SessionID  sql.NullString `json:"session_id"`
	ToolCallID string         `json:"tool_call_id"`
	CreatedAt  string         `json:"created_at"`
}

type Artifacts struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	RootSessionID   sql.NullString `json:"root_session_id"`
	SessionID       sql.NullString `json:"session_id"`
	WorkflowRunID   sql.NullString `json:"workflow_run_id"`
	ToolCallID      string         `json:"tool_call_id"`
	OriginMessageID string         `json:"origin_message_id"`
	OperationID     sql.NullString `json:"operation_id"`
	NaturalKey      sql.NullString `json:"natural_key"`
	ContentHash     string         `json:"content_hash"`
	RetentionClass  string         `json:"retention_class"`
	ByteSize        int64          `json:"byte_size"`
	StoredSize      int64          `json:"stored_size"`
	Mime            string         `json:"mime"`
	Source          string         `json:"source"`
	Caption         string         `json:"caption"`
	EvidenceHandle  string         `json:"evidence_handle"`
	PageID          string         `json:"page_id"`
	Perceive        int64          `json:"perceive"`
	DurationMs      int64          `json:"duration_ms"`
	RecordedAt      sql.NullString `json:"recorded_at"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	DeletedAt       sql.NullString `json:"deleted_at"`
	DeletedReason   sql.NullString `json:"deleted_reason"`
	Width           int64          `json:"width"`
	Height          int64          `json:"height"`
}

type AssessmentFindingRollups struct {
	AssessmentID    string `json:"assessment_id"`
	MemberSignature string `json:"member_signature"`
	RollupJson      string `json:"rollup_json"`
}

type AssessmentScanBindings struct {
	AssessmentID string `json:"assessment_id"`
	ScanID       string `json:"scan_id"`
	CreatedAt    string `json:"created_at"`
}

type AuthorizationContexts struct {
	ID                   string `json:"id"`
	SessionID            string `json:"session_id"`
	ContextSeq           int64  `json:"context_seq"`
	PrevHash             string `json:"prev_hash"`
	RowHash              string `json:"row_hash"`
	HashVersion          int64  `json:"hash_version"`
	Ts                   string `json:"ts"`
	WorkerJobID          string `json:"worker_job_id"`
	ParentSessionID      string `json:"parent_session_id"`
	ProjectID            string `json:"project_id"`
	AgentType            string `json:"agent_type"`
	ToolProfile          string `json:"tool_profile"`
	Posture              string `json:"posture"`
	ApprovalPosture      string `json:"approval_posture"`
	AllowedToolsJson     string `json:"allowed_tools_json"`
	DenyToolsJson        string `json:"deny_tools_json"`
	McpDenyJson          string `json:"mcp_deny_json"`
	ReadGlobsJson        string `json:"read_globs_json"`
	WriteGlobsJson       string `json:"write_globs_json"`
	AskRulesJson         string `json:"ask_rules_json"`
	GrantsJson           string `json:"grants_json"`
	ChatGrantsJson       string `json:"chat_grants_json"`
	NeverAsk             int64  `json:"never_ask"`
	MaxToolLoops         int64  `json:"max_tool_loops"`
	McpInventoryJson     string `json:"mcp_inventory_json"`
	SpawnAllowlistJson   string `json:"spawn_allowlist_json"`
	WorkerToolBudgetJson string `json:"worker_tool_budget_json"`
	ConfigHash           string `json:"config_hash"`
}

type AuthzEvents struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	EventSeq         int64          `json:"event_seq"`
	PrevHash         string         `json:"prev_hash"`
	RowHash          string         `json:"row_hash"`
	HashVersion      int64          `json:"hash_version"`
	Ts               string         `json:"ts"`
	ContextSeq       int64          `json:"context_seq"`
	Action           string         `json:"action"`
	Outcome          string         `json:"outcome"`
	ResolvedBy       string         `json:"resolved_by"`
	ResolverPersonID sql.NullString `json:"resolver_person_id"`
	ToolName         string         `json:"tool_name"`
	RejectCode       string         `json:"reject_code"`
	DetailJson       string         `json:"detail_json"`
	ConfigHash       string         `json:"config_hash"`
}

type BlueprintApprovals struct {
	ProjectID          string         `json:"project_id"`
	Path               string         `json:"path"`
	ContentDigest      string         `json:"content_digest"`
	WorkflowRunID      sql.NullString `json:"workflow_run_id"`
	WorkflowRevision   int64          `json:"workflow_revision"`
	Status             string         `json:"status"`
	ApprovedAt         string         `json:"approved_at"`
	ApprovedVia        string         `json:"approved_via"`
	ApprovedByPersonID string         `json:"approved_by_person_id"`
	RevokedAt          sql.NullString `json:"revoked_at"`
	SessionID          string         `json:"session_id"`
	RevokedCause       string         `json:"revoked_cause"`
}

type CallReservations struct {
	Path      string         `json:"path"`
	Agent     string         `json:"agent"`
	SessionID sql.NullString `json:"session_id"`
	CreatedAt string         `json:"created_at"`
}

type ChatGrants struct {
	ChatSessionID string         `json:"chat_session_id"`
	ID            string         `json:"id"`
	CheckpointID  string         `json:"checkpoint_id"`
	DeltaJson     string         `json:"delta_json"`
	CreatedAt     string         `json:"created_at"`
	ExpiresAt     sql.NullString `json:"expires_at"`
}

type CheckpointAnchors struct {
	SessionID    string `json:"session_id"`
	AnchorID     string `json:"anchor_id"`
	ProjectID    string `json:"project_id"`
	RootKey      string `json:"root_key"`
	SealedAt     string `json:"sealed_at"`
	ManifestJson string `json:"manifest_json"`
	PrunedAt     string `json:"pruned_at"`
	PruneReason  string `json:"prune_reason"`
}

type CheckpointDecisionStamps struct {
	SessionID    string `json:"session_id"`
	ToolCallID   string `json:"tool_call_id"`
	DecisionJson string `json:"decision_json"`
	CreatedAt    string `json:"created_at"`
}

type CheckpointObjectRefs struct {
	SessionID    string `json:"session_id"`
	AnchorID     string `json:"anchor_id"`
	Path         string `json:"path"`
	Sha256       string `json:"sha256"`
	OriginalSize int64  `json:"original_size"`
	Mode         int64  `json:"mode"`
}

type CheckpointResolutionOrdinals struct {
	Ordinal      int64  `json:"ordinal"`
	CheckpointID string `json:"checkpoint_id"`
}

type Checkpoints struct {
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
	ProjectDir         string         `json:"project_dir"`
	Kind               string         `json:"kind"`
	Status             string         `json:"status"`
	Type               string         `json:"type"`
	Title              string         `json:"title"`
	Description        string         `json:"description"`
	ToolName           string         `json:"tool_name"`
	Path               string         `json:"path"`
	ArgsJson           sql.NullString `json:"args_json"`
	FilesJson          sql.NullString `json:"files_json"`
	PayloadJson        sql.NullString `json:"payload_json"`
	ResultJson         sql.NullString `json:"result_json"`
	CreatedAt          string         `json:"created_at"`
	ResolvedAt         sql.NullString `json:"resolved_at"`
	ResolvedBy         sql.NullString `json:"resolved_by"`
	ResolvedByPersonID sql.NullString `json:"resolved_by_person_id"`
	ProjectID          string         `json:"project_id"`
}

type ChunkProjections struct {
	SessionID      string `json:"session_id"`
	MessageID      string `json:"message_id"`
	ProjectionJson string `json:"projection_json"`
}

type CodeScanPageOrdinals struct {
	Ordinal int64  `json:"ordinal"`
	ScanID  string `json:"scan_id"`
}

type CodeScans struct {
	ID                string         `json:"id"`
	CanonicalPath     string         `json:"canonical_path"`
	CategoriesJson    string         `json:"categories_json"`
	ScannerID         sql.NullString `json:"scanner_id"`
	ClaimedBy         sql.NullString `json:"claimed_by"`
	ClaimToken        sql.NullString `json:"claim_token"`
	Attempt           int64          `json:"attempt"`
	HeartbeatAt       sql.NullString `json:"heartbeat_at"`
	LeaseExpiresAt    sql.NullString `json:"lease_expires_at"`
	Status            string         `json:"status"`
	ResultJson        sql.NullString `json:"result_json"`
	CreatedAt         string         `json:"created_at"`
	DelegationID      string         `json:"delegation_id"`
	HeadSha           string         `json:"head_sha"`
	SourceSnapshotID  string         `json:"source_snapshot_id"`
	ReplacementScanID string         `json:"replacement_scan_id"`
	Trigger           string         `json:"trigger"`
	CompletedAt       sql.NullString `json:"completed_at"`
	PathsJson         string         `json:"paths_json"`
	ReuseKey          string         `json:"reuse_key"`
	Error             sql.NullString `json:"error"`
	GuidanceJson      sql.NullString `json:"guidance_json"`
	IngestJson        sql.NullString `json:"ingest_json"`
	RuntimeJson       string         `json:"runtime_json"`
	ProgressJson      string         `json:"progress_json"`
	DeltaJson         string         `json:"delta_json"`
	StartedAt         sql.NullString `json:"started_at"`
	LongRunningAt     sql.NullString `json:"long_running_at"`
}

type CommandInvocations struct {
	OperationID  string `json:"operation_id"`
	InputDigest  string `json:"input_digest"`
	ResponseJson string `json:"response_json"`
	CreatedAt    string `json:"created_at"`
}

type CompactionAttempts struct {
	SessionID string `json:"session_id"`
	Revision  string `json:"revision"`
	Reason    string `json:"reason"`
}

type CompactionSpillRefs struct {
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
	RelPath   string `json:"rel_path"`
}

type CompactionViews struct {
	SessionID               string         `json:"session_id"`
	Generation              int64          `json:"generation"`
	ViewJson                string         `json:"view_json"`
	CoveredThroughOrd       int64          `json:"covered_through_ord"`
	CoveredThroughMessageID sql.NullString `json:"covered_through_message_id"`
	SourceSeq               int64          `json:"source_seq"`
	TokensBefore            int64          `json:"tokens_before"`
	TokensAfter             int64          `json:"tokens_after"`
	CreatedAt               string         `json:"created_at"`
}

type ContentBlobObjects struct {
	ProjectID  string `json:"project_id"`
	Sha256     string `json:"sha256"`
	ByteSize   int64  `json:"byte_size"`
	StoredSize int64  `json:"stored_size"`
	Tier       string `json:"tier"`
	CreatedAt  string `json:"created_at"`
}

type ContentBlobReclaimQueue struct {
	ProjectID string `json:"project_id"`
	Sha256    string `json:"sha256"`
}

type CredentialAuthoredValues struct {
	ProjectID        string `json:"project_id"`
	RootID           string `json:"root_id"`
	Path             string `json:"path"`
	ValueFingerprint string `json:"value_fingerprint"`
	SessionID        string `json:"session_id"`
	ToolCallID       string `json:"tool_call_id"`
	CreatedAt        string `json:"created_at"`
}

type DelegationLegs struct {
	ID                     string         `json:"id"`
	DelegationID           string         `json:"delegation_id"`
	Title                  string         `json:"title"`
	Status                 string         `json:"status"`
	ParentID               sql.NullString `json:"parent_id"`
	DependsOnJson          sql.NullString `json:"depends_on_json"`
	FilesJson              sql.NullString `json:"files_json"`
	CompletionCriteriaJson sql.NullString `json:"completion_criteria_json"`
	WorkspaceRoot          sql.NullString `json:"workspace_root"`
	WorkspaceID            sql.NullString `json:"workspace_id"`
	Prompt                 sql.NullString `json:"prompt"`
	AgentType              sql.NullString `json:"agent_type"`
	WorkerID               sql.NullString `json:"worker_id"`
	ResultJson             sql.NullString `json:"result_json"`
	CreatedAt              string         `json:"created_at"`
	StartedAt              sql.NullString `json:"started_at"`
	CompletedAt            sql.NullString `json:"completed_at"`
}

type Delegations struct {
	ID                   string         `json:"id"`
	ProjectID            string         `json:"project_id"`
	WorkspaceRootID      sql.NullString `json:"workspace_root_id"`
	WorkspacePath        string         `json:"workspace_path"`
	CoordinatorSessionID sql.NullString `json:"coordinator_session_id"`
	Task                 string         `json:"task"`
	Strategy             string         `json:"strategy"`
	InspectMode          sql.NullString `json:"inspect_mode"`
	Status               string         `json:"status"`
	Reason               sql.NullString `json:"reason"`
	Phase                sql.NullString `json:"phase"`
	WorkflowID           sql.NullString `json:"workflow_id"`
	WorkflowVersion      sql.NullString `json:"workflow_version"`
	WorkflowRunID        sql.NullString `json:"workflow_run_id"`
	BlueprintPath        sql.NullString `json:"blueprint_path"`
	BaseHeadSha          sql.NullString `json:"base_head_sha"`
	OperationID          sql.NullString `json:"operation_id"`
	InputDigest          sql.NullString `json:"input_digest"`
	CreatedAt            string         `json:"created_at"`
}

type DraftVersions struct {
	SessionID    string `json:"session_id"`
	SlotID       string `json:"slot_id"`
	VersionIndex int64  `json:"version_index"`
	Body         string `json:"body"`
	OutcomeCode  string `json:"outcome_code"`
	CreatedAt    string `json:"created_at"`
}

type EditorAgentReceipts struct {
	DocumentID           string `json:"document_id"`
	OperationID          string `json:"operation_id"`
	InputDigest          string `json:"input_digest"`
	HeldVersionID        string `json:"held_version_id"`
	PublicationError     string `json:"publication_error"`
	PublicationRequested int64  `json:"publication_requested"`
}

type EditorDocumentChanges struct {
	DocumentID  string         `json:"document_id"`
	Revision    int64          `json:"revision"`
	Epoch       int64          `json:"epoch"`
	OperationID string         `json:"operation_id"`
	ActorKind   string         `json:"actor_kind"`
	PersonID    sql.NullString `json:"person_id"`
	ClientID    string         `json:"client_id"`
	UndoBytes   []byte         `json:"undo_bytes"`
	UndoUnits   int64          `json:"undo_units"`
	RevertedBy  sql.NullString `json:"reverted_by"`
	CreatedAt   string         `json:"created_at"`
}

type EditorDocumentRetention struct {
	DocumentID string `json:"document_id"`
	ClientID   string `json:"client_id"`
	PersonID   string `json:"person_id"`
}

type EditorDocumentSnapshots struct {
	DocumentID   string `json:"document_id"`
	Revision     int64  `json:"revision"`
	Payload      []byte `json:"payload"`
	LogicalBytes int64  `json:"logical_bytes"`
	CreatedAt    string `json:"created_at"`
}

type EditorDocuments struct {
	BranchID           string `json:"branch_id"`
	ID                 string `json:"id"`
	ProjectID          string `json:"project_id"`
	FileID             string `json:"file_id"`
	RootID             string `json:"root_id"`
	Path               string `json:"path"`
	Draft              string `json:"draft"`
	BaseContent        string `json:"base_content"`
	BaseSha256         string `json:"base_sha256"`
	Encoding           string `json:"encoding"`
	SizeBytes          int64  `json:"size_bytes"`
	Eol                string `json:"eol"`
	BaseEol            string `json:"base_eol"`
	MixedEol           int64  `json:"mixed_eol"`
	BaseMixedEol       int64  `json:"base_mixed_eol"`
	Revision           int64  `json:"revision"`
	Dirty              int64  `json:"dirty"`
	Diverged           int64  `json:"diverged"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
	OpenedAt           string `json:"opened_at"`
	HeldAgentVersionID string `json:"held_agent_version_id"`
	Absent             int64  `json:"absent"`
}

type EditorMutations struct {
	BranchID         string         `json:"branch_id"`
	ID               string         `json:"id"`
	InputDigest      string         `json:"input_digest"`
	ClientID         string         `json:"client_id"`
	DocumentID       string         `json:"document_id"`
	ProjectID        string         `json:"project_id"`
	FileID           string         `json:"file_id"`
	RootID           string         `json:"root_id"`
	Path             string         `json:"path"`
	ExpectedSha256   string         `json:"expected_sha256"`
	AfterSha256      string         `json:"after_sha256"`
	Encoding         string         `json:"encoding"`
	Content          string         `json:"content"`
	DraftRevision    int64          `json:"draft_revision"`
	Checkpoint       []byte         `json:"checkpoint"`
	BeforeCheckpoint []byte         `json:"before_checkpoint"`
	Eol              string         `json:"eol"`
	BeforeBytes      []byte         `json:"before_bytes"`
	AfterBytes       []byte         `json:"after_bytes"`
	Status           string         `json:"status"`
	SessionID        string         `json:"session_id"`
	Turn             int64          `json:"turn"`
	Error            string         `json:"error"`
	ReplayCompacted  int64          `json:"replay_compacted"`
	ResponseJson     sql.NullString `json:"response_json"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	Origin           string         `json:"origin"`
	PersonID         sql.NullString `json:"person_id"`
	ToolCallID       string         `json:"tool_call_id"`
	ToolName         string         `json:"tool_name"`
}

type EditorReplicaHeads struct {
	DocumentID          string `json:"document_id"`
	Epoch               int64  `json:"epoch"`
	HostClient          int64  `json:"host_client"`
	FilesystemClient    int64  `json:"filesystem_client"`
	PublishedCheckpoint []byte `json:"published_checkpoint"`
	Checkpoint          []byte `json:"checkpoint"`
	CheckpointRevision  int64  `json:"checkpoint_revision"`
	Vector              []byte `json:"vector"`
	PublishedRevision   int64  `json:"published_revision"`
}

type EditorReplicaReceipts struct {
	DocumentID       string `json:"document_id"`
	OperationID      string `json:"operation_id"`
	InputDigest      string `json:"input_digest"`
	AcceptedRevision int64  `json:"accepted_revision"`
	Epoch            int64  `json:"epoch"`
	CommandHistory   []byte `json:"command_history"`
	CreatedAt        string `json:"created_at"`
}

type EditorReplicaUpdates struct {
	DocumentID  string         `json:"document_id"`
	Revision    int64          `json:"revision"`
	Epoch       int64          `json:"epoch"`
	OperationID string         `json:"operation_id"`
	ActorKind   string         `json:"actor_kind"`
	PersonID    sql.NullString `json:"person_id"`
	ClientID    string         `json:"client_id"`
	UpdateBytes []byte         `json:"update_bytes"`
	Vector      []byte         `json:"vector"`
	CreatedAt   string         `json:"created_at"`
}

type EditorReplicas struct {
	Role        string         `json:"role"`
	DocumentID  string         `json:"document_id"`
	ClientID    string         `json:"client_id"`
	PersonID    sql.NullString `json:"person_id"`
	Incarnation string         `json:"incarnation"`
	ReplicaID   int64          `json:"replica_id"`
	CreatedAt   string         `json:"created_at"`
}

type EditorRetargets struct {
	BranchID          string `json:"branch_id"`
	ID                string `json:"id"`
	ProjectID         string `json:"project_id"`
	RootID            string `json:"root_id"`
	SourceOperationID string `json:"source_operation_id"`
	FromPath          string `json:"from_path"`
	ToPath            string `json:"to_path"`
	CreatedAt         string `json:"created_at"`
}

type EditorSavePins struct {
	OperationID string `json:"operation_id"`
	DocumentID  string `json:"document_id"`
	Revision    int64  `json:"revision"`
	ClientID    string `json:"client_id"`
	CreatedAt   string `json:"created_at"`
}

type EventOutbox struct {
	ID             int64          `json:"id"`
	EventID        string         `json:"event_id"`
	Topic          string         `json:"topic"`
	ProjectID      string         `json:"project_id"`
	SessionID      sql.NullString `json:"session_id"`
	Facet          sql.NullString `json:"facet"`
	EntityRevision int64          `json:"entity_revision"`
	DataJson       string         `json:"data_json"`
	Attempts       int64          `json:"attempts"`
	LastError      string         `json:"last_error"`
	CreatedAt      string         `json:"created_at"`
}

type EvidenceFts struct {
	Snippet string `json:"snippet"`
	Path    string `json:"path"`
	Url     string `json:"url"`
}

type EvidenceIndex struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	Source        string         `json:"source"`
	HitKind       string         `json:"hit_kind"`
	SessionID     sql.NullString `json:"session_id"`
	RootSessionID sql.NullString `json:"root_session_id"`
	MessageID     sql.NullString `json:"message_id"`
	SourceRef     sql.NullString `json:"source_ref"`
	LegID         sql.NullString `json:"leg_id"`
	Handle        sql.NullString `json:"handle"`
	Tool          sql.NullString `json:"tool"`
	Kind          sql.NullString `json:"kind"`
	Shape         sql.NullString `json:"shape"`
	Role          sql.NullString `json:"role"`
	Path          sql.NullString `json:"path"`
	Line          sql.NullInt64  `json:"line"`
	Url           sql.NullString `json:"url"`
	Snippet       sql.NullString `json:"snippet"`
	Verified      sql.NullInt64  `json:"verified"`
	HintCode      sql.NullString `json:"hint_code"`
	CheckID       sql.NullString `json:"check_id"`
	Trust         sql.NullString `json:"trust"`
	Truncated     sql.NullInt64  `json:"truncated"`
	Ts            sql.NullString `json:"ts"`
	WorkflowRunID sql.NullString `json:"workflow_run_id"`
	Verdict       sql.NullString `json:"verdict"`
	Untrusted     sql.NullInt64  `json:"untrusted"`
	Tombstoned    int64          `json:"tombstoned"`
}

type EvidenceRecords struct {
	SessionID         string         `json:"session_id"`
	ProjectID         string         `json:"project_id"`
	Handle            string         `json:"handle"`
	Ordinal           int64          `json:"ordinal"`
	Kind              string         `json:"kind"`
	Shape             string         `json:"shape"`
	Fidelity          string         `json:"fidelity"`
	SourceTool        string         `json:"source_tool"`
	MarksUntrusted    int64          `json:"marks_untrusted"`
	Path              string         `json:"path"`
	Url               string         `json:"url"`
	LineRanges        string         `json:"line_ranges"`
	ContentBlobSha256 string         `json:"content_blob_sha256"`
	Truncated         int64          `json:"truncated"`
	Survey            int64          `json:"survey"`
	SupersededBy      sql.NullString `json:"superseded_by"`
}

type ExtensionOperations struct {
	ID         string         `json:"id"`
	Scope      string         `json:"scope"`
	ProjectDir sql.NullString `json:"project_dir"`
	ProjectID  sql.NullString `json:"project_id"`
	Status     string         `json:"status"`
	PlanJson   string         `json:"plan_json"`
	CreatedAt  string         `json:"created_at"`
}

type FileBriefings struct {
	ProjectID        string        `json:"project_id"`
	RootID           string        `json:"root_id"`
	Path             string        `json:"path"`
	TargetKey        string        `json:"target_key"`
	AttemptID        string        `json:"attempt_id"`
	Presentation     string        `json:"presentation"`
	SourceSha256     string        `json:"source_sha256"`
	Trigger          string        `json:"trigger"`
	Status           string        `json:"status"`
	PreviewJson      string        `json:"preview_json"`
	LocationsJson    string        `json:"locations_json"`
	SectionsJson     string        `json:"sections_json"`
	Truncated        int64         `json:"truncated"`
	Error            string        `json:"error"`
	FallbackText     string        `json:"fallback_text"`
	UpdatedAt        string        `json:"updated_at"`
	LastAccessedAtMs int64         `json:"last_accessed_at_ms"`
	StorageBytes     sql.NullInt64 `json:"storage_bytes"`
}

type Findings struct {
	ID        int64  `json:"id"`
	SessionID string `json:"session_id"`
	Agent     string `json:"agent"`
	Summary   string `json:"summary"`
	Ref       string `json:"ref"`
	Body      string `json:"body"`
	CreatedAt string `json:"created_at"`
}

type FtsMaintenance struct {
	Name            string `json:"name"`
	LastOptimizedAt string `json:"last_optimized_at"`
}

type FullPassSessionBindings struct {
	PassID    string `json:"pass_id"`
	SessionID string `json:"session_id"`
	CreatedAt string `json:"created_at"`
}

type FullPassWorkflowBindings struct {
	PassID        string `json:"pass_id"`
	WorkflowRunID string `json:"workflow_run_id"`
	CreatedAt     string `json:"created_at"`
}

type HistoryBusyProjects struct {
	ProjectID string `json:"project_id"`
}

type HistoryProtections struct {
	ProjectID string         `json:"project_id"`
	SessionID sql.NullString `json:"session_id"`
	OwnerID   string         `json:"owner_id"`
	Protected int64          `json:"protected"`
}

type HistoryPrunedBodies struct {
	Class     string `json:"class"`
	OwnerID   string `json:"owner_id"`
	ProjectID string `json:"project_id"`
	PrunedAt  string `json:"pruned_at"`
	Reason    string `json:"reason"`
}

type HistoryStorageClock struct {
	ID         int64 `json:"id"`
	Generation int64 `json:"generation"`
}

type InvocationReceipts struct {
	ID                   string         `json:"id"`
	ProjectID            string         `json:"project_id"`
	SessionID            string         `json:"session_id"`
	AssistantMessageID   sql.NullString `json:"assistant_message_id"`
	ToolCallID           string         `json:"tool_call_id"`
	ToolName             string         `json:"tool_name"`
	ContractDigest       string         `json:"contract_digest"`
	ArgsDigest           string         `json:"args_digest"`
	Owner                string         `json:"owner"`
	Lifecycle            string         `json:"lifecycle"`
	Reversibility        string         `json:"reversibility"`
	EvidencePolicy       string         `json:"evidence_policy"`
	RecoveryPolicy       string         `json:"recovery_policy"`
	Status               string         `json:"status"`
	Invoked              int64          `json:"invoked"`
	EvidenceKind         string         `json:"evidence_kind"`
	EvidenceRef          string         `json:"evidence_ref"`
	OwnerRef             string         `json:"owner_ref"`
	SourceRevision       string         `json:"source_revision"`
	SourceRootDigest     string         `json:"source_root_digest"`
	SourceVerdict        string         `json:"source_verdict"`
	IsolationCode        string         `json:"isolation_code"`
	IsolationDisposition string         `json:"isolation_disposition"`
	FailureCode          string         `json:"failure_code"`
	FailureClass         string         `json:"failure_class"`
	FailureRetryable     int64          `json:"failure_retryable"`
	FailureOwnerRef      string         `json:"failure_owner_ref"`
	StartedAt            string         `json:"started_at"`
	SettledAt            sql.NullString `json:"settled_at"`
}

type LandedChanges struct {
	ID               string         `json:"id"`
	WorkerJobID      string         `json:"worker_job_id"`
	CanonicalPath    string         `json:"canonical_path"`
	DelegationID     string         `json:"delegation_id"`
	WorkflowRunID    string         `json:"workflow_run_id"`
	ChangedPathsJson string         `json:"changed_paths_json"`
	DeletedPathsJson string         `json:"deleted_paths_json"`
	ScanRequired     int64          `json:"scan_required"`
	ScanID           sql.NullString `json:"scan_id"`
	CreatedAt        string         `json:"created_at"`
}

type LiveModelOutputs struct {
	ID            string         `json:"id"`
	TurnAttemptID string         `json:"turn_attempt_id"`
	SessionID     string         `json:"session_id"`
	Iteration     int64          `json:"iteration"`
	MessageID     string         `json:"message_id"`
	Content       string         `json:"content"`
	ToolCallsJson sql.NullString `json:"tool_calls_json"`
	ReasoningJson sql.NullString `json:"reasoning_json"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type LlmCallRollups struct {
	ProjectID           string `json:"project_id"`
	SessionID           string `json:"session_id"`
	ParentSessionID     string `json:"parent_session_id"`
	ProviderID          string `json:"provider_id"`
	Model               string `json:"model"`
	Caller              string `json:"caller"`
	Day                 string `json:"day"`
	CallCount           int64  `json:"call_count"`
	PromptTokens        int64  `json:"prompt_tokens"`
	CompletionTokens    int64  `json:"completion_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheWriteTokens    int64  `json:"cache_write_tokens"`
	CacheWrite1hTokens  int64  `json:"cache_write_1h_tokens"`
	UnpricedTokens      int64  `json:"unpriced_tokens"`
	RateSnapshot        string `json:"rate_snapshot"`
	CacheSavingsNanoUsd int64  `json:"cache_savings_nano_usd"`
	UnpricedCacheTokens int64  `json:"unpriced_cache_tokens"`
	EstimatedNanoUsd    int64  `json:"estimated_nano_usd"`
	UnpricedCount       int64  `json:"unpriced_count"`
	PricedCount         int64  `json:"priced_count"`
	PricingSource       string `json:"pricing_source"`
	PricedAsOf          string `json:"priced_as_of"`
	UsageSource         string `json:"usage_source"`
	NoCharge            int64  `json:"no_charge"`
}

type LlmCalls struct {
	ID                  string         `json:"id"`
	SessionID           string         `json:"session_id"`
	ParentSessionID     string         `json:"parent_session_id"`
	ProjectID           string         `json:"project_id"`
	ProviderID          string         `json:"provider_id"`
	Model               string         `json:"model"`
	Caller              string         `json:"caller"`
	Status              string         `json:"status"`
	PromptTokens        int64          `json:"prompt_tokens"`
	CompletionTokens    int64          `json:"completion_tokens"`
	CacheReadTokens     int64          `json:"cache_read_tokens"`
	CacheWriteTokens    int64          `json:"cache_write_tokens"`
	CacheWrite1hTokens  int64          `json:"cache_write_1h_tokens"`
	UnpricedTokens      int64          `json:"unpriced_tokens"`
	RateSnapshot        string         `json:"rate_snapshot"`
	CacheSavingsNanoUsd int64          `json:"cache_savings_nano_usd"`
	UnpricedCacheTokens int64          `json:"unpriced_cache_tokens"`
	EstimatedNanoUsd    sql.NullInt64  `json:"estimated_nano_usd"`
	Unpriced            int64          `json:"unpriced"`
	PricingSource       string         `json:"pricing_source"`
	PricedAsOf          sql.NullString `json:"priced_as_of"`
	StartedAt           string         `json:"started_at"`
	CompletedAt         sql.NullString `json:"completed_at"`
	NoCharge            int64          `json:"no_charge"`
	UsageSource         string         `json:"usage_source"`
}

type LlmCostTotals struct {
	ProjectID           string `json:"project_id"`
	SessionID           string `json:"session_id"`
	ParentSessionID     string `json:"parent_session_id"`
	Caller              string `json:"caller"`
	Status              string `json:"status"`
	PricingSource       string `json:"pricing_source"`
	PricedAsOf          string `json:"priced_as_of"`
	UsageSource         string `json:"usage_source"`
	NoCharge            int64  `json:"no_charge"`
	Priced              int64  `json:"priced"`
	CallCount           int64  `json:"call_count"`
	PromptTokens        int64  `json:"prompt_tokens"`
	CompletionTokens    int64  `json:"completion_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheWriteTokens    int64  `json:"cache_write_tokens"`
	UnpricedTokens      int64  `json:"unpriced_tokens"`
	CacheSavingsNanoUsd int64  `json:"cache_savings_nano_usd"`
	UnpricedCacheTokens int64  `json:"unpriced_cache_tokens"`
	EstimatedNanoUsd    int64  `json:"estimated_nano_usd"`
}

type ManagedCookieJarSaves struct {
	ProjectID     string         `json:"project_id"`
	ChatSessionID string         `json:"chat_session_id"`
	SessionID     string         `json:"session_id"`
	OperationID   string         `json:"operation_id"`
	Name          string         `json:"name"`
	SecretID      sql.NullString `json:"secret_id"`
}

type ManagedSecretReveals struct {
	ID            string `json:"id"`
	SecretID      string `json:"secret_id"`
	Version       int64  `json:"version"`
	Authenticator string `json:"authenticator"`
	WindowLabel   string `json:"window_label"`
	PersonID      string `json:"person_id"`
	RevealedAt    string `json:"revealed_at"`
}

type ManagedSecretUses struct {
	ID             string         `json:"id"`
	SecretID       string         `json:"secret_id"`
	Version        sql.NullInt64  `json:"version"`
	ToolName       string         `json:"tool_name"`
	SessionID      sql.NullString `json:"session_id"`
	ChatSessionID  sql.NullString `json:"chat_session_id"`
	Outcome        string         `json:"outcome"`
	ToolCallID     sql.NullString `json:"tool_call_id"`
	Delivery       string         `json:"delivery"`
	RecipientsJson string         `json:"recipients_json"`
	UnlockID       sql.NullString `json:"unlock_id"`
	UsedAt         string         `json:"used_at"`
}

type ManagedSecretVersions struct {
	ID        string         `json:"id"`
	SecretID  string         `json:"secret_id"`
	Version   int64          `json:"version"`
	CreatedAt string         `json:"created_at"`
	RetiredAt sql.NullString `json:"retired_at"`
}

type ManagedSecrets struct {
	ID                 string         `json:"id"`
	ProjectID          string         `json:"project_id"`
	ChatSessionID      sql.NullString `json:"chat_session_id"`
	CreatedBySessionID sql.NullString `json:"created_by_session_id"`
	CreatedByPersonID  sql.NullString `json:"created_by_person_id"`
	Scope              string         `json:"scope"`
	Name               string         `json:"name"`
	Purpose            string         `json:"purpose"`
	Origin             string         `json:"origin"`
	Format             sql.NullString `json:"format"`
	EntropyBits        sql.NullInt64  `json:"entropy_bits"`
	OperationID        string         `json:"operation_id"`
	CreatedAt          string         `json:"created_at"`
	AgentUseEndsAt     sql.NullString `json:"agent_use_ends_at"`
	RevokedAt          sql.NullString `json:"revoked_at"`
	RevokedBy          sql.NullString `json:"revoked_by"`
	RevokedByPersonID  sql.NullString `json:"revoked_by_person_id"`
}

type ManagedTokenJarSaves struct {
	ProjectID     string         `json:"project_id"`
	ChatSessionID string         `json:"chat_session_id"`
	SessionID     string         `json:"session_id"`
	OperationID   string         `json:"operation_id"`
	Name          string         `json:"name"`
	SecretID      sql.NullString `json:"secret_id"`
}

type MessageAttachmentRefs struct {
	MessageID string `json:"message_id"`
	ProjectID string `json:"project_id"`
	BlobID    string `json:"blob_id"`
}

type MessageSpillRefs struct {
	MessageID string `json:"message_id"`
	ProjectID string `json:"project_id"`
	RelPath   string `json:"rel_path"`
}

type Messages struct {
	ID                      string         `json:"id"`
	EntryID                 string         `json:"entry_id"`
	SessionID               string         `json:"session_id"`
	Role                    string         `json:"role"`
	Content                 string         `json:"content"`
	Origin                  string         `json:"origin"`
	Authority               string         `json:"authority"`
	TrustTier               string         `json:"trust_tier"`
	AuthorPersonID          sql.NullString `json:"author_person_id"`
	ContentPartsJson        sql.NullString `json:"content_parts_json"`
	HostSecretRedactionJson sql.NullString `json:"host_secret_redaction_json"`
	Kind                    string         `json:"kind"`
	HostSignalID            string         `json:"host_signal_id"`
	WorkflowRunID           sql.NullString `json:"workflow_run_id"`
	WorkerJobID             sql.NullString `json:"worker_job_id"`
	WorkflowBoundaryJson    sql.NullString `json:"workflow_boundary_json"`
	ProgressCompleteJson    sql.NullString `json:"progress_complete_json"`
	ProgressUpdateJson      sql.NullString `json:"progress_update_json"`
	WorkflowFeedbackJson    sql.NullString `json:"workflow_feedback_json"`
	WorkflowExplainJson     sql.NullString `json:"workflow_explain_json"`
	IndexWarmingJson        sql.NullString `json:"index_warming_json"`
	BlueprintJson           sql.NullString `json:"blueprint_json"`
	ArtifactIdsJson         sql.NullString `json:"artifact_ids_json"`
	EvidenceHandlesJson     sql.NullString `json:"evidence_handles_json"`
	ToolCallsJson           sql.NullString `json:"tool_calls_json"`
	ToolResultJson          sql.NullString `json:"tool_result_json"`
	ToolResultCallID        sql.NullString `json:"tool_result_call_id"`
	WorkerSummaryJson       sql.NullString `json:"worker_summary_json"`
	GroundingJson           sql.NullString `json:"grounding_json"`
	NavigationRefsJson      sql.NullString `json:"navigation_refs_json"`
	CompactedChunkJson      sql.NullString `json:"compacted_chunk_json"`
	CompactionCheckpoint    int64          `json:"compaction_checkpoint"`
	Visibility              string         `json:"visibility"`
	DraftVersionCount       int64          `json:"draft_version_count"`
	DraftStatus             string         `json:"draft_status"`
	Seq                     int64          `json:"seq"`
	Ord                     int64          `json:"ord"`
	Ts                      string         `json:"ts"`
	ReasoningJson           sql.NullString `json:"reasoning_json"`
	CompletionReportJson    sql.NullString `json:"completion_report_json"`
	SecretScreenGeneration  int64          `json:"secret_screen_generation"`
}

type MessagesFts struct {
	Content string `json:"content"`
	Kind    string `json:"kind"`
}

type ModelOutputProjections struct {
	ModelOutputID string `json:"model_output_id"`
	MessageSeq    int64  `json:"message_seq"`
	ProjectedAt   string `json:"projected_at"`
}

type ModelOutputs struct {
	ID                string `json:"id"`
	TurnAttemptID     string `json:"turn_attempt_id"`
	SessionID         string `json:"session_id"`
	ProjectID         string `json:"project_id"`
	Iteration         int64  `json:"iteration"`
	Scripted          int64  `json:"scripted"`
	MessageID         string `json:"message_id"`
	ProviderID        string `json:"provider_id"`
	Model             string `json:"model"`
	ContentBlobSha256 string `json:"content_blob_sha256"`
	FinishReason      string `json:"finish_reason"`
	CreatedAt         string `json:"created_at"`
	SettledAt         string `json:"settled_at"`
}

type PendingCheckpointScopes struct {
	CheckpointID string `json:"checkpoint_id"`
	SessionID    string `json:"session_id"`
	CreatedAt    string `json:"created_at"`
}

type People struct {
	ID        string `json:"id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}

type PersonActions struct {
	ID             string `json:"id"`
	PersonID       string `json:"person_id"`
	OperationID    string `json:"operation_id"`
	PathParamsJson string `json:"path_params_json"`
	SubjectJson    string `json:"subject_json"`
	Status         int64  `json:"status"`
	RecordedAt     string `json:"recorded_at"`
}

type ProjectPromotions struct {
	ProjectID       string `json:"project_id"`
	RootID          string `json:"root_id"`
	SourcePath      string `json:"source_path"`
	DestinationPath string `json:"destination_path"`
	StagePath       string `json:"stage_path"`
	ReservationPath string `json:"reservation_path"`
	InitGit         int64  `json:"init_git"`
	Phase           string `json:"phase"`
	SourceSha256    string `json:"source_sha256"`
	ManifestSha256  string `json:"manifest_sha256"`
	LastError       string `json:"last_error"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type ProjectRemovals struct {
	OperationID string `json:"operation_id"`
	ProjectID   string `json:"project_id"`
	RequestJson string `json:"request_json"`
	ResultJson  string `json:"result_json"`
	Settled     int64  `json:"settled"`
	CreatedAt   string `json:"created_at"`
}

type ProjectRoots struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	Path          string         `json:"path"`
	Label         string         `json:"label"`
	IsPrimary     int64          `json:"is_primary"`
	GitRemoteHash sql.NullString `json:"git_remote_hash"`
	AddedAt       string         `json:"added_at"`
	Kind          string         `json:"kind"`
}

type ProjectTrustBaselines struct {
	ProjectID   string `json:"project_id"`
	ReviewState string `json:"review_state"`
}

type Projects struct {
	ID                    string         `json:"id"`
	Name                  sql.NullString `json:"name"`
	LastOpenedAt          string         `json:"last_opened_at"`
	CreatedAt             string         `json:"created_at"`
	RootsGeneration       int64          `json:"roots_generation"`
	SourceHistoryOrdinal  int64          `json:"source_history_ordinal"`
	SessionCount          int64          `json:"session_count"`
	LastSessionActivityAt sql.NullString `json:"last_session_activity_at"`
	Starred               int64          `json:"starred"`
	CoverArtifactID       sql.NullString `json:"cover_artifact_id"`
	CoverRootSessionID    sql.NullString `json:"cover_root_session_id"`
	CoverSource           sql.NullString `json:"cover_source"`
	CoverUpdatedAt        sql.NullString `json:"cover_updated_at"`
	TrustEnabled          string         `json:"trust_enabled"`
	TrustReadBaseline     string         `json:"trust_read_baseline"`
	StorageTier           string         `json:"storage_tier"`
}

type PromptAttachmentAdmissions struct {
	SubmissionID string `json:"submission_id"`
	ProjectID    string `json:"project_id"`
	BlobID       string `json:"blob_id"`
}

type PromptAttachmentBlobs struct {
	ProjectID string `json:"project_id"`
	BlobID    string `json:"blob_id"`
	ByteSize  int64  `json:"byte_size"`
	CreatedAt string `json:"created_at"`
}

type PromptSubmissions struct {
	ID           string         `json:"id"`
	SessionID    string         `json:"session_id"`
	AdmissionSeq int64          `json:"admission_seq"`
	ProjectID    string         `json:"project_id"`
	InputDigest  string         `json:"input_digest"`
	InputJson    string         `json:"input_json"`
	Status       string         `json:"status"`
	ClaimToken   sql.NullString `json:"claim_token"`
	ResultJson   sql.NullString `json:"result_json"`
	Error        string         `json:"error"`
	CreatedAt    string         `json:"created_at"`
	StartedAt    sql.NullString `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	Origin       string         `json:"origin"`
	ErrorCode    string         `json:"error_code"`
	SubmittedBy  sql.NullString `json:"submitted_by"`
}

type RewindOperations struct {
	ID                      string         `json:"id"`
	SessionID               string         `json:"session_id"`
	AnchorMessageID         string         `json:"anchor_message_id"`
	InputDigest             string         `json:"input_digest"`
	ProjectDir              string         `json:"project_dir"`
	JournalPath             string         `json:"journal_path"`
	Status                  string         `json:"status"`
	Error                   string         `json:"error"`
	ResponseJson            sql.NullString `json:"response_json"`
	CheckpointAnchorIdsJson string         `json:"checkpoint_anchor_ids_json"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

type ScanBlobFindings struct {
	ExecutionFingerprint string `json:"execution_fingerprint"`
	ContentID            string `json:"content_id"`
	TargetPath           string `json:"target_path"`
	FindingsJson         string `json:"findings_json"`
	CreatedAt            string `json:"created_at"`
}

type ScanComparisons struct {
	OldSetID     string `json:"old_set_id"`
	NewSetID     string `json:"new_set_id"`
	ResponseJson string `json:"response_json"`
	BoardJson    string `json:"board_json"`
}

type ScanFindingEntries struct {
	FindingSetID string `json:"finding_set_id"`
	Ordinal      int64  `json:"ordinal"`
	FindingJson  string `json:"finding_json"`
}

type ScanFindingEvents struct {
	CanonicalPath string `json:"canonical_path"`
	ScannerID     string `json:"scanner_id"`
	Fingerprint   string `json:"fingerprint"`
	Event         string `json:"event"`
	SnapshotID    string `json:"snapshot_id"`
	ScanID        string `json:"scan_id"`
	ObservedAt    string `json:"observed_at"`
	FindingJson   string `json:"finding_json"`
}

type ScanFindingLedger struct {
	CanonicalPath       string `json:"canonical_path"`
	ScannerID           string `json:"scanner_id"`
	Fingerprint         string `json:"fingerprint"`
	State               string `json:"state"`
	Level               string `json:"level"`
	LevelRank           int64  `json:"level_rank"`
	Kind                string `json:"kind"`
	RuleID              string `json:"rule_id"`
	Message             string `json:"message"`
	Uri                 string `json:"uri"`
	StartLine           int64  `json:"start_line"`
	AdvisoryIds         string `json:"advisory_ids"`
	HintCode            string `json:"hint_code"`
	FirstSeenAt         string `json:"first_seen_at"`
	FirstScanID         string `json:"first_scan_id"`
	FirstSnapshotID     string `json:"first_snapshot_id"`
	LastEventAt         string `json:"last_event_at"`
	LastScanID          string `json:"last_scan_id"`
	Observations        int64  `json:"observations"`
	LeftTargetKind      string `json:"left_target_kind"`
	LeftCoverage        string `json:"left_coverage"`
	LeftExecution       string `json:"left_execution"`
	IgnoreEntryID       string `json:"ignore_entry_id"`
	IgnoreReason        string `json:"ignore_reason"`
	IgnoreMatchedOn     string `json:"ignore_matched_on"`
	IgnoreJustification string `json:"ignore_justification"`
	IgnoreExpires       string `json:"ignore_expires"`
	FindingJson         string `json:"finding_json"`
}

type ScanFindingLedgerView struct {
	CanonicalPath       string `json:"canonical_path"`
	ScannerID           string `json:"scanner_id"`
	Fingerprint         string `json:"fingerprint"`
	Level               string `json:"level"`
	LevelRank           int64  `json:"level_rank"`
	Kind                string `json:"kind"`
	RuleID              string `json:"rule_id"`
	Message             string `json:"message"`
	Uri                 string `json:"uri"`
	StartLine           int64  `json:"start_line"`
	AdvisoryIds         string `json:"advisory_ids"`
	HintCode            string `json:"hint_code"`
	FirstSeenAt         string `json:"first_seen_at"`
	FirstScanID         string `json:"first_scan_id"`
	FirstSnapshotID     string `json:"first_snapshot_id"`
	LastEventAt         string `json:"last_event_at"`
	LastScanID          string `json:"last_scan_id"`
	Observations        int64  `json:"observations"`
	LeftCoverage        string `json:"left_coverage"`
	LeftExecution       string `json:"left_execution"`
	FindingJson         string `json:"finding_json"`
	IgnoreEntryID       string `json:"ignore_entry_id"`
	IgnoreReason        string `json:"ignore_reason"`
	IgnoreMatchedOn     string `json:"ignore_matched_on"`
	IgnoreJustification string `json:"ignore_justification"`
	IgnoreExpires       string `json:"ignore_expires"`
	SeriesCompletedAt   string `json:"series_completed_at"`
	SeriesExecution     string `json:"series_execution"`
	LedgerState         string `json:"ledger_state"`
}

type ScanFindingRollups struct {
	FindingSetID string `json:"finding_set_id"`
	RollupJson   string `json:"rollup_json"`
}

type ScanFindingSets struct {
	ID                   string         `json:"id"`
	ScanID               string         `json:"scan_id"`
	BaseSetID            sql.NullString `json:"base_set_id"`
	CanonicalPath        string         `json:"canonical_path"`
	ScannerID            string         `json:"scanner_id"`
	SourceSnapshotID     string         `json:"source_snapshot_id"`
	ExecutionFingerprint string         `json:"execution_fingerprint"`
	FingerprintScheme    string         `json:"fingerprint_scheme"`
	CoverageStatus       string         `json:"coverage_status"`
	WarningsJson         string         `json:"warnings_json"`
	CreatedAt            string         `json:"created_at"`
}

type ScanIgnoreState struct {
	CanonicalPath string `json:"canonical_path"`
	Digest        string `json:"digest"`
	AppliedAt     string `json:"applied_at"`
}

type ScanRunFacts struct {
	ScanID                string `json:"scan_id"`
	BaseSnapshotID        string `json:"base_snapshot_id"`
	AssessmentID          string `json:"assessment_id"`
	TargetKind            string `json:"target_kind"`
	TargetPathsJson       string `json:"target_paths_json"`
	DeletedPathsJson      string `json:"deleted_paths_json"`
	ExecutionManifestJson string `json:"execution_manifest_json"`
	ExecutionFingerprint  string `json:"execution_fingerprint"`
	FingerprintScheme     string `json:"fingerprint_scheme"`
	SourceCaptureQuality  string `json:"source_capture_quality"`
	SourceAdmissionMode   string `json:"source_admission_mode"`
	CoverageStatus        string `json:"coverage_status"`
	FailureCode           string `json:"failure_code"`
	FindingSetID          string `json:"finding_set_id"`
}

type ScanSecretIdentities struct {
	ScanID             string `json:"scan_id"`
	FindingFingerprint string `json:"finding_fingerprint"`
	ValueFingerprint   string `json:"value_fingerprint"`
}

type ScanSeries struct {
	CanonicalPath                   string `json:"canonical_path"`
	ScannerID                       string `json:"scanner_id"`
	CategoriesJson                  string `json:"categories_json"`
	DesiredPassID                   string `json:"desired_pass_id"`
	DesiredPathsJson                string `json:"desired_paths_json"`
	DesiredTrigger                  string `json:"desired_trigger"`
	DirtySinceAt                    string `json:"dirty_since_at"`
	DueAt                           string `json:"due_at"`
	MaxDueAt                        string `json:"max_due_at"`
	DispatchToken                   string `json:"dispatch_token"`
	ClaimHeartbeatAt                string `json:"claim_heartbeat_at"`
	DispatchPassID                  string `json:"dispatch_pass_id"`
	DispatchPathsJson               string `json:"dispatch_paths_json"`
	DispatchTrigger                 string `json:"dispatch_trigger"`
	ActiveScanID                    string `json:"active_scan_id"`
	LastFileCount                   int64  `json:"last_file_count"`
	LastStartedAt                   string `json:"last_started_at"`
	LastCompletedAt                 string `json:"last_completed_at"`
	LastSuccessfulScanID            string `json:"last_successful_scan_id"`
	LastCoveredSnapshotID           string `json:"last_covered_snapshot_id"`
	LastCoveredExecutionFingerprint string `json:"last_covered_execution_fingerprint"`
	UpdatedAt                       string `json:"updated_at"`
}

type ScanSummaries struct {
	ScanID      string `json:"scan_id"`
	ListJson    string `json:"list_json"`
	SummaryJson string `json:"summary_json"`
}

type SchemaMigrations struct {
	ID           string `json:"id"`
	Checksum     string `json:"checksum"`
	FromRevision int64  `json:"from_revision"`
	ToRevision   int64  `json:"to_revision"`
	AppliedAt    string `json:"applied_at"`
}

type SecurityAssessments struct {
	ID                   string `json:"id"`
	CanonicalPath        string `json:"canonical_path"`
	SourceSnapshotID     string `json:"source_snapshot_id"`
	RequiredScannersJson string `json:"required_scanners_json"`
	IsComplete           int64  `json:"is_complete"`
	TargetKind           string `json:"target_kind"`
	TargetPathsJson      string `json:"target_paths_json"`
	DeletedPathsJson     string `json:"deleted_paths_json"`
	Trigger              string `json:"trigger"`
	CreatedAt            string `json:"created_at"`
}

type SecurityFullPasses struct {
	ID            string `json:"id"`
	CanonicalPath string `json:"canonical_path"`
	ScannersJson  string `json:"scanners_json"`
	Trigger       string `json:"trigger"`
	RequestedAt   string `json:"requested_at"`
	StartedAt     string `json:"started_at"`
}

type SessionEntries struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	Ord          int64  `json:"ord"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	CreatedAt    string `json:"created_at"`
}

type SessionModelLimits struct {
	SessionID          string         `json:"session_id"`
	ResponseLimit      int64          `json:"response_limit"`
	ExhaustedAttemptID sql.NullString `json:"exhausted_attempt_id"`
}

type SessionProgress struct {
	SessionID     string `json:"session_id"`
	WorkflowRunID string `json:"workflow_run_id"`
	Content       string `json:"content"`
	UpdatedAt     string `json:"updated_at"`
}

type SessionScanBindings struct {
	SessionID string `json:"session_id"`
	ScanID    string `json:"scan_id"`
	CreatedAt string `json:"created_at"`
}

type SessionSourceTurns struct {
	SessionID         string         `json:"session_id"`
	OpeningMessageID  string         `json:"opening_message_id"`
	Turn              int64          `json:"turn"`
	SourceChangeBrief sql.NullString `json:"source_change_brief"`
}

type SessionSpendWarnings struct {
	SessionID      string `json:"session_id"`
	CeilingNanoUsd int64  `json:"ceiling_nano_usd"`
	FiredAt        string `json:"fired_at"`
}

type SessionTurnHeads struct {
	SessionID         string         `json:"session_id"`
	TurnID            string         `json:"turn_id"`
	CloseoutAttemptID sql.NullString `json:"closeout_attempt_id"`
}

type SessionWorkflowScaffold struct {
	SessionID string `json:"session_id"`
	VarsJson  string `json:"vars_json"`
	UpdatedAt string `json:"updated_at"`
}

type SessionWorkflows struct {
	SessionID            string         `json:"session_id"`
	WorkflowID           string         `json:"workflow_id"`
	Version              string         `json:"version"`
	ManifestYaml         string         `json:"manifest_yaml"`
	EffectiveSummaryJson string         `json:"effective_summary_json"`
	CreatedAt            string         `json:"created_at"`
	CreatedBy            string         `json:"created_by"`
	CreatedByPersonID    sql.NullString `json:"created_by_person_id"`
}

type SessionWorktrees struct {
	SessionID  string `json:"session_id"`
	ProjectID  string `json:"project_id"`
	WorktreeID string `json:"worktree_id"`
	CreatedAt  string `json:"created_at"`
}

type Sessions struct {
	ID                   string         `json:"id"`
	ProjectID            string         `json:"project_id"`
	OwnerPersonID        string         `json:"owner_person_id"`
	WorkspaceRootID      sql.NullString `json:"workspace_root_id"`
	Posture              string         `json:"posture"`
	WorkflowID           sql.NullString `json:"workflow_id"`
	WorkflowVersion      sql.NullString `json:"workflow_version"`
	AgentType            sql.NullString `json:"agent_type"`
	ProviderID           sql.NullString `json:"provider_id"`
	Model                sql.NullString `json:"model"`
	ParentSessionID      sql.NullString `json:"parent_session_id"`
	MaxToolLoops         sql.NullInt64  `json:"max_tool_loops"`
	CompactionGeneration int64          `json:"compaction_generation"`
	TranscriptSeq        int64          `json:"transcript_seq"`
	TranscriptOrd        int64          `json:"transcript_ord"`
	Title                sql.NullString `json:"title"`
	Status               string         `json:"status"`
	DoomLoopJson         sql.NullString `json:"doom_loop_json"`
	ScaffoldPhase        sql.NullString `json:"scaffold_phase"`
	CreatedAt            string         `json:"created_at"`
	ActivityAt           string         `json:"activity_at"`
	UpdatedAt            string         `json:"updated_at"`
	StatusChangedAt      sql.NullString `json:"status_changed_at"`
	ArchivedAt           sql.NullString `json:"archived_at"`
	PinRank              sql.NullInt64  `json:"pin_rank"`
	SeenAt               sql.NullString `json:"seen_at"`
}

type SourceAgentPresentations struct {
	EffectID  string `json:"effect_id"`
	ProjectID string `json:"project_id"`
	FileID    string `json:"file_id"`
	Ordinal   int64  `json:"ordinal"`
}

type SourceBlobObjects struct {
	Sha256         string `json:"sha256"`
	Size           int64  `json:"size"`
	StoredSize     int64  `json:"stored_size"`
	StorageRelpath string `json:"storage_relpath"`
	GitOidSha1     string `json:"git_oid_sha1"`
	GitOidSha256   string `json:"git_oid_sha256"`
}

type SourceBlobReclaimQueue struct {
	Sha256 string `json:"sha256"`
}

type SourceBranchHeads struct {
	ProjectID     string `json:"project_id"`
	BranchID      string `json:"branch_id"`
	FileID        string `json:"file_id"`
	VersionID     string `json:"version_id"`
	RootID        string `json:"root_id"`
	Path          string `json:"path"`
	State         string `json:"state"`
	ContentSha256 string `json:"content_sha256"`
	Ordinal       int64  `json:"ordinal"`
	ObservedTs    string `json:"observed_ts"`
}

type SourceCheckpointEntries struct {
	CheckpointID string `json:"checkpoint_id"`
	FileID       string `json:"file_id"`
	VersionID    string `json:"version_id"`
	Ordinal      int64  `json:"ordinal"`
}

type SourceCheckpointGitStates struct {
	CheckpointID string `json:"checkpoint_id"`
	RootID       string `json:"root_id"`
	RepoState    string `json:"repo_state"`
	HeadCommit   string `json:"head_commit"`
	HeadRef      string `json:"head_ref"`
}

type SourceCheckpoints struct {
	ID             string `json:"id"`
	ProjectID      string `json:"project_id"`
	Kind           string `json:"kind"`
	Label          string `json:"label"`
	ParentID       string `json:"parent_id"`
	SessionID      string `json:"session_id"`
	Turn           int64  `json:"turn"`
	CreatedOrdinal int64  `json:"created_ordinal"`
	CreatedTs      string `json:"created_ts"`
}

type SourceCommandWindowObjects struct {
	WindowID string `json:"window_id"`
	Sha256   string `json:"sha256"`
}

type SourceCommandWindows struct {
	ID            string `json:"id"`
	ProjectID     string `json:"project_id"`
	SessionID     string `json:"session_id"`
	Turn          int64  `json:"turn"`
	ToolCallID    string `json:"tool_call_id"`
	ToolName      string `json:"tool_name"`
	CommandLine   string `json:"command_line"`
	State         string `json:"state"`
	AdmissionMode string `json:"admission_mode"`
	Ordinal       int64  `json:"ordinal"`
	StartedTs     string `json:"started_ts"`
	EndedTs       string `json:"ended_ts"`
}

type SourceEffectAuthors struct {
	EffectID       string `json:"effect_id"`
	ProjectID      string `json:"project_id"`
	ContributionID string `json:"contribution_id"`
	Origin         string `json:"origin"`
	SessionID      string `json:"session_id"`
	Turn           int64  `json:"turn"`
	PersonID       string `json:"person_id"`
	ToolCallID     string `json:"tool_call_id"`
	ToolName       string `json:"tool_name"`
	JobID          string `json:"job_id"`
	ActorLabel     string `json:"actor_label"`
	CreatedTs      string `json:"created_ts"`
}

type SourceEffectContributions struct {
	EffectID       string `json:"effect_id"`
	ContributionID string `json:"contribution_id"`
}

type SourceEffects struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	OperationID     string         `json:"operation_id"`
	FileID          string         `json:"file_id"`
	BeforeVersionID sql.NullString `json:"before_version_id"`
	AfterVersionID  string         `json:"after_version_id"`
	RootID          string         `json:"root_id"`
	Path            string         `json:"path"`
	FromRootID      string         `json:"from_root_id"`
	FromPath        string         `json:"from_path"`
	Op              string         `json:"op"`
	EntryKind       string         `json:"entry_kind"`
	Ordinal         int64          `json:"ordinal"`
	WalkVisible     int64          `json:"walk_visible"`
	CreatedTs       string         `json:"created_ts"`
}

type SourceFileRequests struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	PersonID         string         `json:"person_id"`
	Operation        string         `json:"operation"`
	Method           string         `json:"method"`
	Uri              string         `json:"uri"`
	SessionID        string         `json:"session_id"`
	Turn             int64          `json:"turn"`
	Body             []byte         `json:"body"`
	InputDigest      string         `json:"input_digest"`
	RootScope        string         `json:"root_scope"`
	State            string         `json:"state"`
	Phase            string         `json:"phase"`
	EntriesProcessed int64          `json:"entries_processed"`
	BytesProcessed   int64          `json:"bytes_processed"`
	Cancelable       int64          `json:"cancelable"`
	ResponseStatus   int64          `json:"response_status"`
	ResponseBody     string         `json:"response_body"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	CompletedAt      sql.NullString `json:"completed_at"`
}

type SourceFiles struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	EntryKind string `json:"entry_kind"`
	CreatedTs string `json:"created_ts"`
}

type SourceGitHeads struct {
	BranchID   string `json:"branch_id"`
	ProjectID  string `json:"project_id"`
	RootID     string `json:"root_id"`
	RepoState  string `json:"repo_state"`
	HeadCommit string `json:"head_commit"`
	HeadRef    string `json:"head_ref"`
	ObservedTs string `json:"observed_ts"`
}

type SourceGitTransitions struct {
	ID              string         `json:"id"`
	BranchID        string         `json:"branch_id"`
	ProjectID       string         `json:"project_id"`
	RootID          string         `json:"root_id"`
	Kind            string         `json:"kind"`
	FromCommit      string         `json:"from_commit"`
	ToCommit        string         `json:"to_commit"`
	FromRef         string         `json:"from_ref"`
	ToRef           string         `json:"to_ref"`
	Detail          string         `json:"detail"`
	SessionID       string         `json:"session_id"`
	Turn            int64          `json:"turn"`
	ToolCallID      string         `json:"tool_call_id"`
	ToolName        string         `json:"tool_name"`
	CommandWindowID sql.NullString `json:"command_window_id"`
	Ordinal         int64          `json:"ordinal"`
	ObservedTs      string         `json:"observed_ts"`
}

type SourceHistoryEntries struct {
	Seq          int64  `json:"seq"`
	ID           string `json:"id"`
	ProjectID    string `json:"project_id"`
	Kind         string `json:"kind"`
	State        string `json:"state"`
	UndoLabel    string `json:"undo_label"`
	RedoLabel    string `json:"redo_label"`
	UndoPlanJson string `json:"undo_plan_json"`
	RedoPlanJson string `json:"redo_plan_json"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type SourceInventoryState struct {
	BranchID            string `json:"branch_id"`
	ProjectID           string `json:"project_id"`
	RequestedGeneration int64  `json:"requested_generation"`
	CompletedGeneration int64  `json:"completed_generation"`
	Phase               string `json:"phase"`
	FileCount           int64  `json:"file_count"`
	RequestedTs         string `json:"requested_ts"`
	StartedTs           string `json:"started_ts"`
	CompletedTs         string `json:"completed_ts"`
	LastError           string `json:"last_error"`
	RequestedEpoch      string `json:"requested_epoch"`
	CompletedEpoch      string `json:"completed_epoch"`
	SnapshotID          string `json:"snapshot_id"`
}

type SourceLineAttr struct {
	ProjectID string `json:"project_id"`
	BranchID  string `json:"branch_id"`
	FileID    string `json:"file_id"`
	StartLine int64  `json:"start_line"`
	EndLine   int64  `json:"end_line"`
	EffectID  string `json:"effect_id"`
}

type SourceManifestChunks struct {
	ID         string `json:"id"`
	EntryCount int64  `json:"entry_count"`
	TotalBytes int64  `json:"total_bytes"`
}

type SourceManifestEntries struct {
	ChunkID    string `json:"chunk_id"`
	Ordinal    int64  `json:"ordinal"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

type SourceManifestStaging struct {
	BuildID    string `json:"build_id"`
	Bucket     int64  `json:"bucket"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

type SourceMutations struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	Kind         string         `json:"kind"`
	InputDigest  string         `json:"input_digest"`
	PlanJson     string         `json:"plan_json"`
	Status       string         `json:"status"`
	ResponseJson sql.NullString `json:"response_json"`
	Error        string         `json:"error"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type SourceOperations struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	BranchID        string         `json:"branch_id"`
	Origin          string         `json:"origin"`
	PersonID        sql.NullString `json:"person_id"`
	Cause           string         `json:"cause"`
	ActorLabel      string         `json:"actor_label"`
	SessionID       string         `json:"session_id"`
	JobID           string         `json:"job_id"`
	Turn            int64          `json:"turn"`
	ToolCallID      string         `json:"tool_call_id"`
	ToolName        string         `json:"tool_name"`
	BatchID         string         `json:"batch_id"`
	OperationKey    string         `json:"operation_key"`
	CaptureQuality  string         `json:"capture_quality"`
	StartedTs       string         `json:"started_ts"`
	CommittedTs     string         `json:"committed_ts"`
	GitTransitionID sql.NullString `json:"git_transition_id"`
	CommandWindowID sql.NullString `json:"command_window_id"`
}

type SourcePresentationWatermarks struct {
	ProjectID         string `json:"project_id"`
	FileID            string `json:"file_id"`
	SeenAfterOrdinal  int64  `json:"seen_after_ordinal"`
	ThroughOrdinal    int64  `json:"through_ordinal"`
	DisplayedEffectID string `json:"displayed_effect_id"`
	SeenTs            string `json:"seen_ts"`
}

type SourceRecoveryEntries struct {
	ProjectID  string `json:"project_id"`
	RecoveryID string `json:"recovery_id"`
	Ordinal    int64  `json:"ordinal"`
	Path       string `json:"path"`
	Mode       int64  `json:"mode"`
	Sha256     string `json:"sha256"`
	Link       string `json:"link"`
}

type SourceRecoveryObjects struct {
	ProjectID  string `json:"project_id"`
	RecoveryID string `json:"recovery_id"`
	Sha256     string `json:"sha256"`
}

type SourceSnapshotBoundaries struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	Entries    int64  `json:"entries"`
}

type SourceSnapshotChunks struct {
	SnapshotID string `json:"snapshot_id"`
	Bucket     int64  `json:"bucket"`
	ChunkID    string `json:"chunk_id"`
}

type SourceSnapshotHeads struct {
	RootsKey    string `json:"roots_key"`
	SnapshotID  string `json:"snapshot_id"`
	PublishedTs string `json:"published_ts"`
}

type SourceSnapshotRoots struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Ordinal    int64  `json:"ordinal"`
}

type SourceSnapshots struct {
	ID             string `json:"id"`
	RootsKey       string `json:"roots_key"`
	MerkleSha256   string `json:"merkle_sha256"`
	FileCount      int64  `json:"file_count"`
	TotalBytes     int64  `json:"total_bytes"`
	CaptureQuality string `json:"capture_quality"`
	CreatedTs      string `json:"created_ts"`
}

type SourceTextContributions struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	FileID       string         `json:"file_id"`
	DocumentID   string         `json:"document_id"`
	Epoch        int64          `json:"epoch"`
	Revision     int64          `json:"revision"`
	OperationID  string         `json:"operation_id"`
	Origin       string         `json:"origin"`
	PersonID     sql.NullString `json:"person_id"`
	ClientID     string         `json:"client_id"`
	SessionID    string         `json:"session_id"`
	Turn         int64          `json:"turn"`
	ToolCallID   string         `json:"tool_call_id"`
	ToolName     string         `json:"tool_name"`
	JobID        string         `json:"job_id"`
	InsertedJson string         `json:"inserted_json"`
	DeletedJson  string         `json:"deleted_json"`
	CreatedAt    string         `json:"created_at"`
}

type SourceTextIdentityRanges struct {
	ContributionID string `json:"contribution_id"`
	DocumentID     string `json:"document_id"`
	Epoch          int64  `json:"epoch"`
	Kind           string `json:"kind"`
	Client         int64  `json:"client"`
	ClockStart     int64  `json:"clock_start"`
	ClockEnd       int64  `json:"clock_end"`
}

type SourceVersionTextStates struct {
	Revision   int64  `json:"revision"`
	VersionID  string `json:"version_id"`
	DocumentID string `json:"document_id"`
	Epoch      int64  `json:"epoch"`
	SpansJson  string `json:"spans_json"`
}

type SourceVersions struct {
	ID                   string         `json:"id"`
	FileID               string         `json:"file_id"`
	ProjectID            string         `json:"project_id"`
	BranchID             string         `json:"branch_id"`
	ParentVersionID      sql.NullString `json:"parent_version_id"`
	DerivedFromVersionID sql.NullString `json:"derived_from_version_id"`
	OperationID          sql.NullString `json:"operation_id"`
	RootID               string         `json:"root_id"`
	Path                 string         `json:"path"`
	State                string         `json:"state"`
	ContentSha256        string         `json:"content_sha256"`
	ByteSize             int64          `json:"byte_size"`
	CaptureState         string         `json:"capture_state"`
	CaptureReason        string         `json:"capture_reason"`
	CaptureQuality       string         `json:"capture_quality"`
	CreatedTs            string         `json:"created_ts"`
	Seq                  int64          `json:"seq"`
	Landing              string         `json:"landing"`
}

type SourceWorktrees struct {
	ID           string `json:"id"`
	ProjectID    string `json:"project_id"`
	RepoID       string `json:"repo_id"`
	Toplevel     string `json:"toplevel"`
	WorktreePath string `json:"worktree_path"`
	Branch       string `json:"branch"`
	BaseBranch   string `json:"base_branch"`
	CreatedAt    string `json:"created_at"`
}

type StoreMeta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TurnAttemptCloseouts struct {
	TurnAttemptID string `json:"turn_attempt_id"`
	CloseoutJson  string `json:"closeout_json"`
}

type TurnAttempts struct {
	ID             string         `json:"id"`
	TurnID         string         `json:"turn_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	Phase          string         `json:"phase"`
	CheckpointJson string         `json:"checkpoint_json"`
	Error          string         `json:"error"`
	StartedAt      string         `json:"started_at"`
	UpdatedAt      string         `json:"updated_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}

type TurnClocks struct {
	OpeningMessageID string         `json:"opening_message_id"`
	SessionID        string         `json:"session_id"`
	ActiveMs         int64          `json:"active_ms"`
	WorkMs           int64          `json:"work_ms"`
	RunningAt        sql.NullString `json:"running_at"`
	SettledAt        sql.NullString `json:"settled_at"`
}

type TurnLoadReceipts struct {
	ID               int64          `json:"id"`
	SessionID        string         `json:"session_id"`
	OpeningMessageID sql.NullString `json:"opening_message_id"`
	ToolCallID       string         `json:"tool_call_id"`
	Trigger          string         `json:"trigger"`
	SurfaceID        string         `json:"surface_id"`
	Engine           string         `json:"engine"`
	CatalogRevision  string         `json:"catalog_revision"`
	StateJson        string         `json:"state_json"`
	DecisionsJson    string         `json:"decisions_json"`
	StandingJson     string         `json:"standing_json"`
	ElapsedMs        int64          `json:"elapsed_ms"`
	Abstained        int64          `json:"abstained"`
	Reason           string         `json:"reason"`
	CreatedAt        string         `json:"created_at"`
}

type TurnSubmissions struct {
	TurnID       string `json:"turn_id"`
	SubmissionID string `json:"submission_id"`
	Position     int64  `json:"position"`
}

type Turns struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	ProjectID       string         `json:"project_id"`
	Origin          string         `json:"origin"`
	InputJson       string         `json:"input_json"`
	Status          string         `json:"status"`
	Revision        int64          `json:"revision"`
	ActiveAttemptID sql.NullString `json:"active_attempt_id"`
	FinalOutputID   sql.NullString `json:"final_output_id"`
	ResultJson      sql.NullString `json:"result_json"`
	Error           string         `json:"error"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	ProgressedAt    string         `json:"progressed_at"`
}

type VaultUnlocks struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	ChatSessionID string         `json:"chat_session_id"`
	PersonID      string         `json:"person_id"`
	Authenticator string         `json:"authenticator"`
	WindowLabel   string         `json:"window_label"`
	UnlockedAt    string         `json:"unlocked_at"`
	EndedAt       sql.NullString `json:"ended_at"`
	EndReason     sql.NullString `json:"end_reason"`
}

type WaitLeases struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	ProjectID         string         `json:"project_id"`
	WorkerJobID       sql.NullString `json:"worker_job_id"`
	RootSessionID     string         `json:"root_session_id"`
	ToolCallID        string         `json:"tool_call_id"`
	ProjectDir        string         `json:"project_dir"`
	ProfileID         string         `json:"profile_id"`
	Status            string         `json:"status"`
	DeadlineAt        sql.NullString `json:"deadline_at"`
	UntilComplete     int64          `json:"until_complete"`
	ConditionsJson    string         `json:"conditions_json"`
	LoopbackPortsJson string         `json:"loopback_ports_json"`
	WinnerJson        sql.NullString `json:"winner_json"`
	Reason            string         `json:"reason"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	ResolvedAt        sql.NullString `json:"resolved_at"`
	ResumeDeliveredAt sql.NullString `json:"resume_delivered_at"`
}

type WorkerAttempts struct {
	ID          string         `json:"id"`
	WorkerJobID string         `json:"worker_job_id"`
	Attempt     int64          `json:"attempt"`
	ClaimToken  string         `json:"claim_token"`
	ClaimedBy   string         `json:"claimed_by"`
	Status      string         `json:"status"`
	Error       string         `json:"error"`
	FailureJson sql.NullString `json:"failure_json"`
	StartedAt   string         `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

type WorkerBaselineObjects struct {
	BaselineID string `json:"baseline_id"`
	Sha256     string `json:"sha256"`
}

type WorkerBaselines struct {
	ID             string `json:"id"`
	ManifestSha256 string `json:"manifest_sha256"`
	FormatVersion  int64  `json:"format_version"`
	JobID          string `json:"job_id"`
	CreatedAt      string `json:"created_at"`
}

type WorkerDecisions struct {
	ChildSessionID string `json:"child_session_id"`
	JobID          string `json:"job_id"`
	DecisionJson   string `json:"decision_json"`
	CreatedAt      string `json:"created_at"`
}

type WorkerFindingDelivery struct {
	WorkerJobID string `json:"worker_job_id"`
	ResponseID  string `json:"response_id"`
	Cursor      int64  `json:"cursor"`
	NotesJson   string `json:"notes_json"`
}

type WorkerJobs struct {
	ID                  string         `json:"id"`
	ProjectID           string         `json:"project_id"`
	WorkspaceRootID     sql.NullString `json:"workspace_root_id"`
	WorkspacePath       string         `json:"workspace_path"`
	WorkspaceKey        string         `json:"workspace_key"`
	DelegationID        sql.NullString `json:"delegation_id"`
	LegID               sql.NullString `json:"leg_id"`
	ParentSessionID     sql.NullString `json:"parent_session_id"`
	SourceToolCallID    string         `json:"source_tool_call_id"`
	SourceArgsDigest    string         `json:"source_args_digest"`
	ChildSessionID      sql.NullString `json:"child_session_id"`
	WorkflowRunID       sql.NullString `json:"workflow_run_id"`
	WorkflowPhase       string         `json:"workflow_phase"`
	WorkflowWorkID      string         `json:"workflow_work_id"`
	ExecutionTarget     string         `json:"execution_target"`
	RunnerID            sql.NullString `json:"runner_id"`
	ClaimedBy           sql.NullString `json:"claimed_by"`
	ClaimToken          sql.NullString `json:"claim_token"`
	Attempt             int64          `json:"attempt"`
	HeartbeatAt         sql.NullString `json:"heartbeat_at"`
	LeaseExpiresAt      sql.NullString `json:"lease_expires_at"`
	AgentType           string         `json:"agent_type"`
	Status              string         `json:"status"`
	SpawnReason         sql.NullString `json:"spawn_reason"`
	Prompt              string         `json:"prompt"`
	Brief               string         `json:"brief"`
	FilesJson           sql.NullString `json:"files_json"`
	ScopeJson           sql.NullString `json:"scope_json"`
	ResultJson          sql.NullString `json:"result_json"`
	Error               sql.NullString `json:"error"`
	FailureJson         sql.NullString `json:"failure_json"`
	CreatedAt           string         `json:"created_at"`
	StartedAt           sql.NullString `json:"started_at"`
	CompletedAt         sql.NullString `json:"completed_at"`
	WorkspaceBaselineID sql.NullString `json:"workspace_baseline_id"`
	WorkspaceOverlayID  sql.NullString `json:"workspace_overlay_id"`
	WorkspaceRelpath    sql.NullString `json:"workspace_relpath"`
	MergeStatus         sql.NullString `json:"merge_status"`
	OverlayID           sql.NullString `json:"overlay_id"`
	MaxToolLoops        sql.NullInt64  `json:"max_tool_loops"`
	BudgetRequestJson   string         `json:"budget_request_json"`
	ToolLoopsUsed       sql.NullInt64  `json:"tool_loops_used"`
	ToolCallsUsed       sql.NullInt64  `json:"tool_calls_used"`
	CancelRequestedAt   sql.NullString `json:"cancel_requested_at"`
	MergeClaimToken     sql.NullString `json:"merge_claim_token"`
	MergeHeartbeatAt    sql.NullString `json:"merge_heartbeat_at"`
	MergeLeaseExpiresAt sql.NullString `json:"merge_lease_expires_at"`
}

type WorkerOutcomeDeliveries struct {
	WorkerJobID string `json:"worker_job_id"`
	DeliveredAt string `json:"delivered_at"`
}

type WorkerPrerequisites struct {
	WorkerJobID    string `json:"worker_job_id"`
	PrerequisiteID string `json:"prerequisite_id"`
}

type WorkerResults struct {
	ID              string         `json:"id"`
	WorkerJobID     string         `json:"worker_job_id"`
	WorkerAttemptID sql.NullString `json:"worker_attempt_id"`
	Status          string         `json:"status"`
	ResultJson      sql.NullString `json:"result_json"`
	Error           string         `json:"error"`
	FailureJson     sql.NullString `json:"failure_json"`
	CreatedAt       string         `json:"created_at"`
}

type WorkerTurns struct {
	TurnID      string `json:"turn_id"`
	WorkerJobID string `json:"worker_job_id"`
}

type WorkflowCommands struct {
	OperationID    string `json:"operation_id"`
	RunID          string `json:"run_id"`
	SourceRevision int64  `json:"source_revision"`
	Kind           string `json:"kind"`
	InputDigest    string `json:"input_digest"`
	ResultRevision int64  `json:"result_revision"`
	ResponseJson   string `json:"response_json"`
	RejectionJson  string `json:"rejection_json"`
	CommittedAt    string `json:"committed_at"`
}

type WorkflowReviewAssignments struct {
	ID          string `json:"id"`
	RunID       string `json:"run_id"`
	SubjectID   string `json:"subject_id"`
	Phase       string `json:"phase"`
	WorkID      string `json:"work_id"`
	Agent       string `json:"agent"`
	BindingJson string `json:"binding_json"`
}

type WorkflowReviewSubjects struct {
	ID          string `json:"id"`
	RunID       string `json:"run_id"`
	Phase       string `json:"phase"`
	Revision    string `json:"revision"`
	SubjectJson string `json:"subject_json"`
}

type WorkflowRunPageOrdinals struct {
	Ordinal int64  `json:"ordinal"`
	RunID   string `json:"run_id"`
}

type WorkflowRuns struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	ProjectID       string         `json:"project_id"`
	WorkflowID      string         `json:"workflow_id"`
	WorkflowVersion string         `json:"workflow_version"`
	AttachPolicy    string         `json:"attach_policy"`
	Status          string         `json:"status"`
	ParentRunID     sql.NullString `json:"parent_run_id"`
	Revision        int64          `json:"revision"`
	CurrentPhase    string         `json:"current_phase"`
	ProjectDir      string         `json:"project_dir"`
	VarsJson        string         `json:"vars_json"`
	BlueprintPath   sql.NullString `json:"blueprint_path"`
	PauseReason     sql.NullString `json:"pause_reason"`
	FailureJson     sql.NullString `json:"failure_json"`
	StartMessageID  sql.NullString `json:"start_message_id"`
	EndMessageID    sql.NullString `json:"end_message_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	PausedAt        sql.NullString `json:"paused_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	ReviewRevision  int64          `json:"review_revision"`
}

type WorkflowScanBindings struct {
	WorkflowRunID      string         `json:"workflow_run_id"`
	ScanID             string         `json:"scan_id"`
	CreatedAt          string         `json:"created_at"`
	TerminalNotifiedAt sql.NullString `json:"terminal_notified_at"`
}

type WorkflowStartOperations struct {
	ID            string `json:"id"`
	SessionID     string `json:"session_id"`
	InputDigest   string `json:"input_digest"`
	WorkflowRunID string `json:"workflow_run_id"`
	ResponseJson  string `json:"response_json"`
	CommittedAt   string `json:"committed_at"`
}

type WorkflowTeardownOperations struct {
	ID              string `json:"id"`
	RunID           string `json:"run_id"`
	SourceRevision  int64  `json:"source_revision"`
	CancelScope     string `json:"cancel_scope"`
	AbortDelegation int64  `json:"abort_delegation"`
	Reason          string `json:"reason"`
	Status          string `json:"status"`
	Attempts        int64  `json:"attempts"`
	LastError       string `json:"last_error"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type WorkflowVerdictOperations struct {
	ToolCallID        string         `json:"tool_call_id"`
	RunID             string         `json:"run_id"`
	SourceRevision    int64          `json:"source_revision"`
	Phase             string         `json:"phase"`
	InputDigest       string         `json:"input_digest"`
	EvidenceRecordID  string         `json:"evidence_record_id"`
	EvidenceJson      string         `json:"evidence_json"`
	Status            string         `json:"status"`
	ResponseJson      sql.NullString `json:"response_json"`
	Error             string         `json:"error"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	EvidencePublished int64          `json:"evidence_published"`
}
