// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: source_snapshots.sql

package db

import (
	"context"
)

const deleteExpiredSourceSnapshotHeads = `-- name: DeleteExpiredSourceSnapshotHeads :execrows
DELETE FROM source_snapshot_heads
WHERE roots_key IN (
    SELECT source_snapshot_heads.roots_key FROM source_snapshot_heads
    WHERE source_snapshot_heads.published_ts < ?1
    ORDER BY source_snapshot_heads.published_ts, source_snapshot_heads.roots_key
    LIMIT ?2
)
`

type DeleteExpiredSourceSnapshotHeadsParams struct {
	CreatedBefore string `json:"created_before"`
	BatchLimit    int64  `json:"batch_limit"`
}

func (q *Queries) DeleteExpiredSourceSnapshotHeads(ctx context.Context, arg DeleteExpiredSourceSnapshotHeadsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSourceSnapshotHeads, arg.CreatedBefore, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSourceManifestStagingBelow = `-- name: DeleteSourceManifestStagingBelow :exec
DELETE FROM source_manifest_staging
WHERE build_id = ?1 AND root_path = ?2
  AND path > ?3 AND path < ?4
`

type DeleteSourceManifestStagingBelowParams struct {
	BuildID  string `json:"build_id"`
	RootPath string `json:"root_path"`
	Low      string `json:"low"`
	High     string `json:"high"`
}

func (q *Queries) DeleteSourceManifestStagingBelow(ctx context.Context, arg DeleteSourceManifestStagingBelowParams) error {
	_, err := q.db.ExecContext(ctx, deleteSourceManifestStagingBelow,
		arg.BuildID,
		arg.RootPath,
		arg.Low,
		arg.High,
	)
	return err
}

const deleteSourceManifestStagingBucket = `-- name: DeleteSourceManifestStagingBucket :exec
DELETE FROM source_manifest_staging WHERE build_id = ? AND bucket = ?
`

type DeleteSourceManifestStagingBucketParams struct {
	BuildID string `json:"build_id"`
	Bucket  int64  `json:"bucket"`
}

// A build is released one bucket at a time so no single delete holds the
// writer for a whole manifest.
func (q *Queries) DeleteSourceManifestStagingBucket(ctx context.Context, arg DeleteSourceManifestStagingBucketParams) error {
	_, err := q.db.ExecContext(ctx, deleteSourceManifestStagingBucket, arg.BuildID, arg.Bucket)
	return err
}

const deleteSourceManifestStagingPath = `-- name: DeleteSourceManifestStagingPath :exec
DELETE FROM source_manifest_staging WHERE build_id = ? AND root_path = ? AND path = ?
`

type DeleteSourceManifestStagingPathParams struct {
	BuildID  string `json:"build_id"`
	RootPath string `json:"root_path"`
	Path     string `json:"path"`
}

func (q *Queries) DeleteSourceManifestStagingPath(ctx context.Context, arg DeleteSourceManifestStagingPathParams) error {
	_, err := q.db.ExecContext(ctx, deleteSourceManifestStagingPath, arg.BuildID, arg.RootPath, arg.Path)
	return err
}

const deleteSourceSnapshotHeadForRootsKey = `-- name: DeleteSourceSnapshotHeadForRootsKey :execrows
DELETE FROM source_snapshot_heads WHERE roots_key = ?
`

// Releases the snapshots of a roots key nothing attaches any more, without
// waiting out the age-based sweep.
func (q *Queries) DeleteSourceSnapshotHeadForRootsKey(ctx context.Context, rootsKey string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSourceSnapshotHeadForRootsKey, rootsKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStaleSourceManifestStaging = `-- name: DeleteStaleSourceManifestStaging :execrows
DELETE FROM source_manifest_staging
WHERE substr(build_id, 1, length(?1)) != ?1
`

// Builds of an earlier process never complete; the prefix names this one.
func (q *Queries) DeleteStaleSourceManifestStaging(ctx context.Context, prefix interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaleSourceManifestStaging, prefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnreferencedSourceManifestChunks = `-- name: DeleteUnreferencedSourceManifestChunks :execrows
DELETE FROM source_manifest_chunks
WHERE id IN (
    SELECT manifest.id FROM source_manifest_chunks manifest
    WHERE NOT EXISTS (
        SELECT 1 FROM source_snapshot_chunks snapshot
        WHERE snapshot.chunk_id = manifest.id
    )
    ORDER BY manifest.id
    LIMIT ?
)
`

func (q *Queries) DeleteUnreferencedSourceManifestChunks(ctx context.Context, limit int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedSourceManifestChunks, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnreferencedSourceSnapshots = `-- name: DeleteUnreferencedSourceSnapshots :execrows
DELETE FROM source_snapshots
WHERE id IN (
    SELECT snapshot.id FROM source_snapshots snapshot
    WHERE NOT EXISTS (
        SELECT 1 FROM source_snapshot_heads head
        WHERE head.snapshot_id = snapshot.id
    )
      AND NOT EXISTS (
        SELECT 1 FROM source_inventory_state inventory
        WHERE inventory.snapshot_id = snapshot.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM code_scans scan
        WHERE scan.source_snapshot_id = snapshot.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM scan_series series
        WHERE series.last_covered_snapshot_id = snapshot.id
      )
      AND snapshot.created_ts < ?1
    ORDER BY snapshot.created_ts, snapshot.id
    LIMIT ?2
)
`

type DeleteUnreferencedSourceSnapshotsParams struct {
	CreatedBefore string `json:"created_before"`
	BatchLimit    int64  `json:"batch_limit"`
}

func (q *Queries) DeleteUnreferencedSourceSnapshots(ctx context.Context, arg DeleteUnreferencedSourceSnapshotsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedSourceSnapshots, arg.CreatedBefore, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnreferencedSourceSnapshotsForRootsKey = `-- name: DeleteUnreferencedSourceSnapshotsForRootsKey :execrows
DELETE FROM source_snapshots
WHERE id IN (
    SELECT snapshot.id FROM source_snapshots snapshot
    WHERE snapshot.roots_key = ?1
      AND NOT EXISTS (
        SELECT 1 FROM source_snapshot_heads head
        WHERE head.snapshot_id = snapshot.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM source_inventory_state inventory
        WHERE inventory.snapshot_id = snapshot.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM code_scans scan
        WHERE scan.source_snapshot_id = snapshot.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM scan_series series
        WHERE series.last_covered_snapshot_id = snapshot.id
      )
    ORDER BY snapshot.created_ts, snapshot.id
    LIMIT ?2
)
`

type DeleteUnreferencedSourceSnapshotsForRootsKeyParams struct {
	RootsKey   string `json:"roots_key"`
	BatchLimit int64  `json:"batch_limit"`
}

func (q *Queries) DeleteUnreferencedSourceSnapshotsForRootsKey(ctx context.Context, arg DeleteUnreferencedSourceSnapshotsForRootsKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedSourceSnapshotsForRootsKey, arg.RootsKey, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSourceManifestChunk = `-- name: GetSourceManifestChunk :one
SELECT id, entry_count, total_bytes FROM source_manifest_chunks WHERE id = ?
`

func (q *Queries) GetSourceManifestChunk(ctx context.Context, id string) (SourceManifestChunks, error) {
	row := q.db.QueryRowContext(ctx, getSourceManifestChunk, id)
	var i SourceManifestChunks
	err := row.Scan(&i.ID, &i.EntryCount, &i.TotalBytes)
	return i, err
}

const getSourceSnapshot = `-- name: GetSourceSnapshot :one
SELECT id, roots_key, merkle_sha256, file_count, total_bytes, capture_quality, created_ts
FROM source_snapshots
WHERE id = ?
`

func (q *Queries) GetSourceSnapshot(ctx context.Context, id string) (SourceSnapshots, error) {
	row := q.db.QueryRowContext(ctx, getSourceSnapshot, id)
	var i SourceSnapshots
	err := row.Scan(
		&i.ID,
		&i.RootsKey,
		&i.MerkleSha256,
		&i.FileCount,
		&i.TotalBytes,
		&i.CaptureQuality,
		&i.CreatedTs,
	)
	return i, err
}

const getSourceSnapshotEntry = `-- name: GetSourceSnapshotEntry :one
SELECT e.root_path, e.path, e.sha256, e.git_oid, e.identity, e.size, e.mode, e.modified_ns
FROM source_snapshot_chunks c
JOIN source_manifest_entries e ON e.chunk_id = c.chunk_id
WHERE c.snapshot_id = ? AND e.root_path = ? AND e.path = ?
`

type GetSourceSnapshotEntryParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
}

type GetSourceSnapshotEntryRow struct {
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

func (q *Queries) GetSourceSnapshotEntry(ctx context.Context, arg GetSourceSnapshotEntryParams) (GetSourceSnapshotEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getSourceSnapshotEntry, arg.SnapshotID, arg.RootPath, arg.Path)
	var i GetSourceSnapshotEntryRow
	err := row.Scan(
		&i.RootPath,
		&i.Path,
		&i.Sha256,
		&i.GitOid,
		&i.Identity,
		&i.Size,
		&i.Mode,
		&i.ModifiedNs,
	)
	return i, err
}

const getSourceSnapshotHeadID = `-- name: GetSourceSnapshotHeadID :one
SELECT snapshot_id FROM source_snapshot_heads WHERE roots_key = ?
`

func (q *Queries) GetSourceSnapshotHeadID(ctx context.Context, rootsKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSourceSnapshotHeadID, rootsKey)
	var snapshot_id string
	err := row.Scan(&snapshot_id)
	return snapshot_id, err
}

const insertSourceManifestChunk = `-- name: InsertSourceManifestChunk :exec
INSERT INTO source_manifest_chunks (id, entry_count, total_bytes)
VALUES (?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type InsertSourceManifestChunkParams struct {
	ID         string `json:"id"`
	EntryCount int64  `json:"entry_count"`
	TotalBytes int64  `json:"total_bytes"`
}

func (q *Queries) InsertSourceManifestChunk(ctx context.Context, arg InsertSourceManifestChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceManifestChunk, arg.ID, arg.EntryCount, arg.TotalBytes)
	return err
}

const insertSourceManifestEntry = `-- name: InsertSourceManifestEntry :exec
INSERT INTO source_manifest_entries (
    chunk_id, ordinal, root_path, path, sha256, git_oid, identity, size, mode, modified_ns
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(chunk_id, ordinal) DO NOTHING
`

type InsertSourceManifestEntryParams struct {
	ChunkID    string `json:"chunk_id"`
	Ordinal    int64  `json:"ordinal"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

func (q *Queries) InsertSourceManifestEntry(ctx context.Context, arg InsertSourceManifestEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceManifestEntry,
		arg.ChunkID,
		arg.Ordinal,
		arg.RootPath,
		arg.Path,
		arg.Sha256,
		arg.GitOid,
		arg.Identity,
		arg.Size,
		arg.Mode,
		arg.ModifiedNs,
	)
	return err
}

const insertSourceManifestStaging = `-- name: InsertSourceManifestStaging :exec
INSERT INTO source_manifest_staging (
    build_id, bucket, root_path, path, sha256, git_oid, identity, size, mode, modified_ns
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(build_id, bucket, root_path, path) DO UPDATE SET
    sha256 = excluded.sha256, git_oid = excluded.git_oid, identity = excluded.identity,
    size = excluded.size, mode = excluded.mode, modified_ns = excluded.modified_ns
`

type InsertSourceManifestStagingParams struct {
	BuildID    string `json:"build_id"`
	Bucket     int64  `json:"bucket"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

func (q *Queries) InsertSourceManifestStaging(ctx context.Context, arg InsertSourceManifestStagingParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceManifestStaging,
		arg.BuildID,
		arg.Bucket,
		arg.RootPath,
		arg.Path,
		arg.Sha256,
		arg.GitOid,
		arg.Identity,
		arg.Size,
		arg.Mode,
		arg.ModifiedNs,
	)
	return err
}

const insertSourceSnapshotBoundary = `-- name: InsertSourceSnapshotBoundary :exec
INSERT INTO source_snapshot_boundaries (snapshot_id, root_path, path, reason, detail, entries)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(snapshot_id, root_path, path) DO NOTHING
`

type InsertSourceSnapshotBoundaryParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	Entries    int64  `json:"entries"`
}

func (q *Queries) InsertSourceSnapshotBoundary(ctx context.Context, arg InsertSourceSnapshotBoundaryParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceSnapshotBoundary,
		arg.SnapshotID,
		arg.RootPath,
		arg.Path,
		arg.Reason,
		arg.Detail,
		arg.Entries,
	)
	return err
}

const insertSourceSnapshotChunk = `-- name: InsertSourceSnapshotChunk :exec
INSERT INTO source_snapshot_chunks (snapshot_id, bucket, chunk_id)
VALUES (?, ?, ?)
ON CONFLICT(snapshot_id, bucket) DO NOTHING
`

type InsertSourceSnapshotChunkParams struct {
	SnapshotID string `json:"snapshot_id"`
	Bucket     int64  `json:"bucket"`
	ChunkID    string `json:"chunk_id"`
}

func (q *Queries) InsertSourceSnapshotChunk(ctx context.Context, arg InsertSourceSnapshotChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceSnapshotChunk, arg.SnapshotID, arg.Bucket, arg.ChunkID)
	return err
}

const insertSourceSnapshotRoot = `-- name: InsertSourceSnapshotRoot :exec
INSERT INTO source_snapshot_roots (snapshot_id, root_path, ordinal)
VALUES (?, ?, ?)
ON CONFLICT(snapshot_id, root_path) DO NOTHING
`

type InsertSourceSnapshotRootParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Ordinal    int64  `json:"ordinal"`
}

func (q *Queries) InsertSourceSnapshotRoot(ctx context.Context, arg InsertSourceSnapshotRootParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceSnapshotRoot, arg.SnapshotID, arg.RootPath, arg.Ordinal)
	return err
}

const listSourceManifestChunkEntries = `-- name: ListSourceManifestChunkEntries :many
SELECT root_path, path, sha256, git_oid, identity, size, mode, modified_ns
FROM source_manifest_entries
WHERE chunk_id = ?
ORDER BY ordinal
`

type ListSourceManifestChunkEntriesRow struct {
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

// One chunk's entries in manifest order.
func (q *Queries) ListSourceManifestChunkEntries(ctx context.Context, chunkID string) ([]ListSourceManifestChunkEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceManifestChunkEntries, chunkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceManifestChunkEntriesRow
	for rows.Next() {
		var i ListSourceManifestChunkEntriesRow
		if err := rows.Scan(
			&i.RootPath,
			&i.Path,
			&i.Sha256,
			&i.GitOid,
			&i.Identity,
			&i.Size,
			&i.Mode,
			&i.ModifiedNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceManifestStagingBucket = `-- name: ListSourceManifestStagingBucket :many
SELECT root_path, path, sha256, git_oid, identity, size, mode, modified_ns
FROM source_manifest_staging
WHERE build_id = ? AND bucket = ?
ORDER BY root_path, path
`

type ListSourceManifestStagingBucketParams struct {
	BuildID string `json:"build_id"`
	Bucket  int64  `json:"bucket"`
}

type ListSourceManifestStagingBucketRow struct {
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

func (q *Queries) ListSourceManifestStagingBucket(ctx context.Context, arg ListSourceManifestStagingBucketParams) ([]ListSourceManifestStagingBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceManifestStagingBucket, arg.BuildID, arg.Bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceManifestStagingBucketRow
	for rows.Next() {
		var i ListSourceManifestStagingBucketRow
		if err := rows.Scan(
			&i.RootPath,
			&i.Path,
			&i.Sha256,
			&i.GitOid,
			&i.Identity,
			&i.Size,
			&i.Mode,
			&i.ModifiedNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceManifestStagingPathsBelow = `-- name: ListSourceManifestStagingPathsBelow :many
SELECT path FROM source_manifest_staging
WHERE build_id = ?1 AND root_path = ?2
  AND path > ?3 AND path < ?4
ORDER BY path
`

type ListSourceManifestStagingPathsBelowParams struct {
	BuildID  string `json:"build_id"`
	RootPath string `json:"root_path"`
	Low      string `json:"low"`
	High     string `json:"high"`
}

func (q *Queries) ListSourceManifestStagingPathsBelow(ctx context.Context, arg ListSourceManifestStagingPathsBelowParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSourceManifestStagingPathsBelow,
		arg.BuildID,
		arg.RootPath,
		arg.Low,
		arg.High,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSnapshotBoundaries = `-- name: ListSourceSnapshotBoundaries :many
SELECT root_path, path, reason, detail, entries
FROM source_snapshot_boundaries
WHERE snapshot_id = ?
ORDER BY root_path, path
`

type ListSourceSnapshotBoundariesRow struct {
	RootPath string `json:"root_path"`
	Path     string `json:"path"`
	Reason   string `json:"reason"`
	Detail   string `json:"detail"`
	Entries  int64  `json:"entries"`
}

func (q *Queries) ListSourceSnapshotBoundaries(ctx context.Context, snapshotID string) ([]ListSourceSnapshotBoundariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceSnapshotBoundaries, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceSnapshotBoundariesRow
	for rows.Next() {
		var i ListSourceSnapshotBoundariesRow
		if err := rows.Scan(
			&i.RootPath,
			&i.Path,
			&i.Reason,
			&i.Detail,
			&i.Entries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSnapshotChunks = `-- name: ListSourceSnapshotChunks :many
SELECT bucket, chunk_id
FROM source_snapshot_chunks
WHERE snapshot_id = ?
ORDER BY bucket
`

type ListSourceSnapshotChunksRow struct {
	Bucket  int64  `json:"bucket"`
	ChunkID string `json:"chunk_id"`
}

func (q *Queries) ListSourceSnapshotChunks(ctx context.Context, snapshotID string) ([]ListSourceSnapshotChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceSnapshotChunks, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceSnapshotChunksRow
	for rows.Next() {
		var i ListSourceSnapshotChunksRow
		if err := rows.Scan(&i.Bucket, &i.ChunkID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSnapshotEntriesBelow = `-- name: ListSourceSnapshotEntriesBelow :many
SELECT e.root_path, e.path, e.sha256, e.git_oid, e.identity, e.size, e.mode, e.modified_ns
FROM source_snapshot_chunks c
JOIN source_manifest_entries e ON e.chunk_id = c.chunk_id
WHERE c.snapshot_id = ?1 AND e.root_path = ?2
  AND e.path > ?3 AND e.path < ?4
ORDER BY e.root_path, e.path
`

type ListSourceSnapshotEntriesBelowParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Low        string `json:"low"`
	High       string `json:"high"`
}

type ListSourceSnapshotEntriesBelowRow struct {
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

// Entries strictly below one directory: the caller passes the bounds
// dir/ and dir0 so the path index answers the range.
func (q *Queries) ListSourceSnapshotEntriesBelow(ctx context.Context, arg ListSourceSnapshotEntriesBelowParams) ([]ListSourceSnapshotEntriesBelowRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceSnapshotEntriesBelow,
		arg.SnapshotID,
		arg.RootPath,
		arg.Low,
		arg.High,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceSnapshotEntriesBelowRow
	for rows.Next() {
		var i ListSourceSnapshotEntriesBelowRow
		if err := rows.Scan(
			&i.RootPath,
			&i.Path,
			&i.Sha256,
			&i.GitOid,
			&i.Identity,
			&i.Size,
			&i.Mode,
			&i.ModifiedNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSnapshotHashedEntries = `-- name: ListSourceSnapshotHashedEntries :many
SELECT e.root_path, e.path, e.sha256, e.git_oid, e.identity, e.size, e.mode, e.modified_ns
FROM source_snapshot_chunks c
JOIN source_manifest_entries e INDEXED BY idx_source_manifest_entries_hashed ON e.chunk_id = c.chunk_id
WHERE c.snapshot_id = ?1 AND e.identity = 'hashed' AND e.size <= ?2
ORDER BY e.root_path, e.path
LIMIT ?3
`

type ListSourceSnapshotHashedEntriesParams struct {
	SnapshotID string `json:"snapshot_id"`
	MaxSize    int64  `json:"max_size"`
	RowLimit   int64  `json:"row_limit"`
}

type ListSourceSnapshotHashedEntriesRow struct {
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

// Files the host read to identify, up to a size, in path order: the ones
// git's object store cannot answer for. The partial index keeps this
// proportional to those files rather than to the manifest.
func (q *Queries) ListSourceSnapshotHashedEntries(ctx context.Context, arg ListSourceSnapshotHashedEntriesParams) ([]ListSourceSnapshotHashedEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceSnapshotHashedEntries, arg.SnapshotID, arg.MaxSize, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceSnapshotHashedEntriesRow
	for rows.Next() {
		var i ListSourceSnapshotHashedEntriesRow
		if err := rows.Scan(
			&i.RootPath,
			&i.Path,
			&i.Sha256,
			&i.GitOid,
			&i.Identity,
			&i.Size,
			&i.Mode,
			&i.ModifiedNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSnapshotRootEntries = `-- name: ListSourceSnapshotRootEntries :many
SELECT e.root_path, e.path, e.sha256, e.git_oid, e.identity, e.size, e.mode, e.modified_ns
FROM source_snapshot_chunks c
JOIN source_manifest_entries e ON e.chunk_id = c.chunk_id
WHERE c.snapshot_id = ? AND e.root_path = ?
ORDER BY e.root_path, e.path
`

type ListSourceSnapshotRootEntriesParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
}

type ListSourceSnapshotRootEntriesRow struct {
	RootPath   string `json:"root_path"`
	Path       string `json:"path"`
	Sha256     string `json:"sha256"`
	GitOid     string `json:"git_oid"`
	Identity   string `json:"identity"`
	Size       int64  `json:"size"`
	Mode       int64  `json:"mode"`
	ModifiedNs int64  `json:"modified_ns"`
}

func (q *Queries) ListSourceSnapshotRootEntries(ctx context.Context, arg ListSourceSnapshotRootEntriesParams) ([]ListSourceSnapshotRootEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceSnapshotRootEntries, arg.SnapshotID, arg.RootPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceSnapshotRootEntriesRow
	for rows.Next() {
		var i ListSourceSnapshotRootEntriesRow
		if err := rows.Scan(
			&i.RootPath,
			&i.Path,
			&i.Sha256,
			&i.GitOid,
			&i.Identity,
			&i.Size,
			&i.Mode,
			&i.ModifiedNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSnapshotRoots = `-- name: ListSourceSnapshotRoots :many
SELECT snapshot_id, root_path, ordinal
FROM source_snapshot_roots
WHERE snapshot_id = ?
ORDER BY ordinal
`

func (q *Queries) ListSourceSnapshotRoots(ctx context.Context, snapshotID string) ([]SourceSnapshotRoots, error) {
	rows, err := q.db.QueryContext(ctx, listSourceSnapshotRoots, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceSnapshotRoots
	for rows.Next() {
		var i SourceSnapshotRoots
		if err := rows.Scan(&i.SnapshotID, &i.RootPath, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceManifestChunkExists = `-- name: SourceManifestChunkExists :one
SELECT EXISTS(SELECT 1 FROM source_manifest_chunks WHERE id = ?)
`

func (q *Queries) SourceManifestChunkExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceManifestChunkExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sourceManifestStagingHoldsPath = `-- name: SourceManifestStagingHoldsPath :one
SELECT EXISTS(SELECT 1 FROM source_manifest_staging WHERE build_id = ? AND root_path = ? AND path = ?)
`

type SourceManifestStagingHoldsPathParams struct {
	BuildID  string `json:"build_id"`
	RootPath string `json:"root_path"`
	Path     string `json:"path"`
}

func (q *Queries) SourceManifestStagingHoldsPath(ctx context.Context, arg SourceManifestStagingHoldsPathParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceManifestStagingHoldsPath, arg.BuildID, arg.RootPath, arg.Path)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sourceSnapshotHoldsBelow = `-- name: SourceSnapshotHoldsBelow :one
SELECT EXISTS(
    SELECT 1 FROM source_snapshot_chunks c
    JOIN source_manifest_entries e ON e.chunk_id = c.chunk_id
    WHERE c.snapshot_id = ?1 AND e.root_path = ?2
      AND e.path > ?3 AND e.path < ?4
)
`

type SourceSnapshotHoldsBelowParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
	Low        string `json:"low"`
	High       string `json:"high"`
}

func (q *Queries) SourceSnapshotHoldsBelow(ctx context.Context, arg SourceSnapshotHoldsBelowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceSnapshotHoldsBelow,
		arg.SnapshotID,
		arg.RootPath,
		arg.Low,
		arg.High,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sourceSnapshotHoldsRoot = `-- name: SourceSnapshotHoldsRoot :one
SELECT EXISTS(
    SELECT 1 FROM source_snapshot_chunks c
    JOIN source_manifest_entries e ON e.chunk_id = c.chunk_id
    WHERE c.snapshot_id = ? AND e.root_path = ?
)
`

type SourceSnapshotHoldsRootParams struct {
	SnapshotID string `json:"snapshot_id"`
	RootPath   string `json:"root_path"`
}

func (q *Queries) SourceSnapshotHoldsRoot(ctx context.Context, arg SourceSnapshotHoldsRootParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceSnapshotHoldsRoot, arg.SnapshotID, arg.RootPath)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertSourceSnapshot = `-- name: UpsertSourceSnapshot :exec
INSERT INTO source_snapshots (
    id, roots_key, merkle_sha256, file_count, total_bytes, capture_quality, created_ts
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET capture_quality = excluded.capture_quality
WHERE source_snapshots.capture_quality = 'observed'
  AND excluded.capture_quality = 'exact'
`

type UpsertSourceSnapshotParams struct {
	ID             string `json:"id"`
	RootsKey       string `json:"roots_key"`
	MerkleSha256   string `json:"merkle_sha256"`
	FileCount      int64  `json:"file_count"`
	TotalBytes     int64  `json:"total_bytes"`
	CaptureQuality string `json:"capture_quality"`
	CreatedTs      string `json:"created_ts"`
}

func (q *Queries) UpsertSourceSnapshot(ctx context.Context, arg UpsertSourceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceSnapshot,
		arg.ID,
		arg.RootsKey,
		arg.MerkleSha256,
		arg.FileCount,
		arg.TotalBytes,
		arg.CaptureQuality,
		arg.CreatedTs,
	)
	return err
}

const upsertSourceSnapshotHead = `-- name: UpsertSourceSnapshotHead :exec
INSERT INTO source_snapshot_heads (roots_key, snapshot_id, published_ts)
VALUES (?, ?, ?)
ON CONFLICT(roots_key) DO UPDATE SET
    snapshot_id = excluded.snapshot_id,
    published_ts = excluded.published_ts
`

type UpsertSourceSnapshotHeadParams struct {
	RootsKey    string `json:"roots_key"`
	SnapshotID  string `json:"snapshot_id"`
	PublishedTs string `json:"published_ts"`
}

func (q *Queries) UpsertSourceSnapshotHead(ctx context.Context, arg UpsertSourceSnapshotHeadParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceSnapshotHead, arg.RootsKey, arg.SnapshotID, arg.PublishedTs)
	return err
}
