// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: store_meta.sql

package db

import (
	"context"
)

const deleteStoreMeta = `-- name: DeleteStoreMeta :exec
DELETE FROM store_meta WHERE key = ?
`

func (q *Queries) DeleteStoreMeta(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteStoreMeta, key)
	return err
}

const getStoreMetaValue = `-- name: GetStoreMetaValue :one

SELECT value FROM store_meta WHERE key = ?
`

// store_meta sidecar boot counter and other key/value meta.
func (q *Queries) GetStoreMetaValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getStoreMetaValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertStoreMeta = `-- name: UpsertStoreMeta :exec
INSERT INTO store_meta (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertStoreMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertStoreMeta(ctx context.Context, arg UpsertStoreMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertStoreMeta, arg.Key, arg.Value)
	return err
}
