// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: turns.sql

package db

import (
	"context"
	"database/sql"
)

const checkpointTurnAttempt = `-- name: CheckpointTurnAttempt :execrows
UPDATE turn_attempts SET phase = ?, checkpoint_json = ?, updated_at = ?
WHERE id = ? AND turn_id = ? AND status = 'running'
`

type CheckpointTurnAttemptParams struct {
	Phase          string `json:"phase"`
	CheckpointJson string `json:"checkpoint_json"`
	UpdatedAt      string `json:"updated_at"`
	ID             string `json:"id"`
	TurnID         string `json:"turn_id"`
}

func (q *Queries) CheckpointTurnAttempt(ctx context.Context, arg CheckpointTurnAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, checkpointTurnAttempt,
		arg.Phase,
		arg.CheckpointJson,
		arg.UpdatedAt,
		arg.ID,
		arg.TurnID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeFinalizingTurnAttempts = `-- name: CompleteFinalizingTurnAttempts :exec
UPDATE turn_attempts
SET status = 'complete', phase = 'complete', error = '', updated_at = ?, completed_at = ?
WHERE status = 'running' AND phase = 'finalizing'
  AND EXISTS (
      SELECT 1 FROM turns
      WHERE turns.active_attempt_id = turn_attempts.id AND turns.status = 'complete'
  )
`

type CompleteFinalizingTurnAttemptsParams struct {
	UpdatedAt   string         `json:"updated_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

func (q *Queries) CompleteFinalizingTurnAttempts(ctx context.Context, arg CompleteFinalizingTurnAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, completeFinalizingTurnAttempts, arg.UpdatedAt, arg.CompletedAt)
	return err
}

const completeFinalizingTurns = `-- name: CompleteFinalizingTurns :exec
UPDATE turns
SET status = 'complete', revision = revision + 1,
    final_output_id = NULLIF(json_extract((
        SELECT checkpoint_json FROM turn_attempts
        WHERE turn_attempts.id = turns.active_attempt_id
    ), '$.final_output_id'), ''),
    result_json = json_extract((
        SELECT checkpoint_json FROM turn_attempts
        WHERE turn_attempts.id = turns.active_attempt_id
    ), '$.result'),
    error = '', updated_at = ?, completed_at = ?
WHERE status = 'running' AND EXISTS (
    SELECT 1 FROM turn_attempts
    WHERE turn_attempts.id = turns.active_attempt_id
      AND turn_attempts.status = 'running' AND turn_attempts.phase = 'finalizing'
)
`

type CompleteFinalizingTurnsParams struct {
	UpdatedAt   string         `json:"updated_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

func (q *Queries) CompleteFinalizingTurns(ctx context.Context, arg CompleteFinalizingTurnsParams) error {
	_, err := q.db.ExecContext(ctx, completeFinalizingTurns, arg.UpdatedAt, arg.CompletedAt)
	return err
}

const completeSubmissionsForRecoveredTurns = `-- name: CompleteSubmissionsForRecoveredTurns :exec
UPDATE prompt_submissions
SET status = 'complete',
    result_json = (
        SELECT turns.result_json
        FROM turn_submissions
        JOIN turns ON turns.id = turn_submissions.turn_id
        WHERE turn_submissions.submission_id = prompt_submissions.id
          AND turns.status = 'complete'
    ),
    error = '', completed_at = ?
WHERE status = 'running' AND EXISTS (
    SELECT 1
    FROM turn_submissions
    JOIN turns ON turns.id = turn_submissions.turn_id
    WHERE turn_submissions.submission_id = prompt_submissions.id
      AND turns.status = 'complete'
)
`

func (q *Queries) CompleteSubmissionsForRecoveredTurns(ctx context.Context, completedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, completeSubmissionsForRecoveredTurns, completedAt)
	return err
}

const deleteLiveModelOutput = `-- name: DeleteLiveModelOutput :exec
DELETE FROM live_model_outputs WHERE id = ?
`

func (q *Queries) DeleteLiveModelOutput(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLiveModelOutput, id)
	return err
}

const deleteLiveModelOutputs = `-- name: DeleteLiveModelOutputs :exec
DELETE FROM live_model_outputs WHERE 1 = 1
`

func (q *Queries) DeleteLiveModelOutputs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLiveModelOutputs)
	return err
}

const deleteTurnsFromSessionOrd = `-- name: DeleteTurnsFromSessionOrd :exec
DELETE FROM turns
WHERE turns.session_id = ?1 AND turns.id IN (
    SELECT submission.turn_id
    FROM turn_submissions submission
    JOIN messages message ON message.id = submission.submission_id
    WHERE message.session_id = ?1 AND message.ord >= ?2
    UNION
    SELECT attempt.turn_id
    FROM session_entries entry
    JOIN model_outputs output
      ON entry.resource_kind = 'model_output' AND output.id = entry.resource_id
    JOIN turn_attempts attempt ON attempt.id = output.turn_attempt_id
    WHERE entry.session_id = ?1 AND entry.ord >= ?2
)
`

type DeleteTurnsFromSessionOrdParams struct {
	TargetSessionID string `json:"target_session_id"`
	Ord             int64  `json:"ord"`
}

func (q *Queries) DeleteTurnsFromSessionOrd(ctx context.Context, arg DeleteTurnsFromSessionOrdParams) error {
	_, err := q.db.ExecContext(ctx, deleteTurnsFromSessionOrd, arg.TargetSessionID, arg.Ord)
	return err
}

const findRecoverableTurnByWorkerJob = `-- name: FindRecoverableTurnByWorkerJob :one

SELECT turns.id
FROM turns
JOIN worker_turns ON worker_turns.turn_id = turns.id
WHERE worker_turns.worker_job_id = ?
  AND turns.origin = ?
  AND turns.status IN ('recovering', 'failed', 'interrupted')
ORDER BY turns.created_at DESC, turns.id DESC
LIMIT 1
`

type FindRecoverableTurnByWorkerJobParams struct {
	WorkerJobID string `json:"worker_job_id"`
	Origin      string `json:"origin"`
}

// Durable turn execution and model-output projection.
func (q *Queries) FindRecoverableTurnByWorkerJob(ctx context.Context, arg FindRecoverableTurnByWorkerJobParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findRecoverableTurnByWorkerJob, arg.WorkerJobID, arg.Origin)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findRecoveringTurnBySubmission = `-- name: FindRecoveringTurnBySubmission :one
SELECT turns.id
FROM turns
JOIN turn_submissions ON turn_submissions.turn_id = turns.id
WHERE turn_submissions.submission_id = ? AND turns.status = 'recovering'
`

func (q *Queries) FindRecoveringTurnBySubmission(ctx context.Context, submissionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, findRecoveringTurnBySubmission, submissionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const finishTurnAttempt = `-- name: FinishTurnAttempt :execrows
UPDATE turn_attempts
SET status = ?1,
    phase = CASE WHEN ?1 = 'complete' THEN 'complete' ELSE phase END,
    error = ?2, updated_at = ?3, completed_at = ?4
WHERE id = ?5 AND turn_id = ?6 AND status = 'running'
`

type FinishTurnAttemptParams struct {
	Status      string         `json:"status"`
	Error       string         `json:"error"`
	UpdatedAt   string         `json:"updated_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	ID          string         `json:"id"`
	TurnID      string         `json:"turn_id"`
}

func (q *Queries) FinishTurnAttempt(ctx context.Context, arg FinishTurnAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishTurnAttempt,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ID,
		arg.TurnID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishTurnHead = `-- name: FinishTurnHead :execrows
UPDATE turns
SET status = ?1, revision = revision + 1,
    final_output_id = NULLIF(?2, ''),
    result_json = NULLIF(?3, ''), error = ?4,
    updated_at = ?5, completed_at = ?6,
    progressed_at = ?5
WHERE id = ?7 AND active_attempt_id = ?8 AND status = 'running'
`

type FinishTurnHeadParams struct {
	Status          string         `json:"status"`
	FinalOutputID   interface{}    `json:"final_output_id"`
	ResultJson      interface{}    `json:"result_json"`
	Error           string         `json:"error"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	ID              string         `json:"id"`
	ActiveAttemptID sql.NullString `json:"active_attempt_id"`
}

func (q *Queries) FinishTurnHead(ctx context.Context, arg FinishTurnHeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishTurnHead,
		arg.Status,
		arg.FinalOutputID,
		arg.ResultJson,
		arg.Error,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ID,
		arg.ActiveAttemptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestTurnStatus = `-- name: GetLatestTurnStatus :one
SELECT turn.status FROM session_turn_heads head
JOIN turns turn ON turn.id = head.turn_id
WHERE head.session_id = ?
`

func (q *Queries) GetLatestTurnStatus(ctx context.Context, sessionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestTurnStatus, sessionID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getModelOutput = `-- name: GetModelOutput :one
SELECT id, turn_attempt_id, session_id, project_id, iteration, scripted, message_id, provider_id, model, content_blob_sha256, finish_reason, created_at, settled_at FROM model_outputs
WHERE id = ?
`

func (q *Queries) GetModelOutput(ctx context.Context, id string) (ModelOutputs, error) {
	row := q.db.QueryRowContext(ctx, getModelOutput, id)
	var i ModelOutputs
	err := row.Scan(
		&i.ID,
		&i.TurnAttemptID,
		&i.SessionID,
		&i.ProjectID,
		&i.Iteration,
		&i.Scripted,
		&i.MessageID,
		&i.ProviderID,
		&i.Model,
		&i.ContentBlobSha256,
		&i.FinishReason,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, session_id, project_id, origin, input_json, status, revision,
       active_attempt_id, final_output_id, result_json, error,
       created_at, updated_at, completed_at, progressed_at
FROM turns
WHERE id = ?
`

func (q *Queries) GetTurn(ctx context.Context, id string) (Turns, error) {
	row := q.db.QueryRowContext(ctx, getTurn, id)
	var i Turns
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.Origin,
		&i.InputJson,
		&i.Status,
		&i.Revision,
		&i.ActiveAttemptID,
		&i.FinalOutputID,
		&i.ResultJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ProgressedAt,
	)
	return i, err
}

const getWorkerJobForTurnAttempt = `-- name: GetWorkerJobForTurnAttempt :one
SELECT worker_turn.worker_job_id
FROM turn_attempts attempt
JOIN worker_turns worker_turn ON worker_turn.turn_id = attempt.turn_id
WHERE attempt.id = ?
`

func (q *Queries) GetWorkerJobForTurnAttempt(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkerJobForTurnAttempt, id)
	var worker_job_id string
	err := row.Scan(&worker_job_id)
	return worker_job_id, err
}

const insertModelOutput = `-- name: InsertModelOutput :exec
INSERT INTO model_outputs (
    id, turn_attempt_id, session_id, project_id, iteration, message_id, provider_id,
    model, content_blob_sha256, finish_reason, created_at, settled_at, scripted
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type InsertModelOutputParams struct {
	ID                string `json:"id"`
	TurnAttemptID     string `json:"turn_attempt_id"`
	SessionID         string `json:"session_id"`
	ProjectID         string `json:"project_id"`
	Iteration         int64  `json:"iteration"`
	MessageID         string `json:"message_id"`
	ProviderID        string `json:"provider_id"`
	Model             string `json:"model"`
	ContentBlobSha256 string `json:"content_blob_sha256"`
	FinishReason      string `json:"finish_reason"`
	CreatedAt         string `json:"created_at"`
	SettledAt         string `json:"settled_at"`
	Scripted          int64  `json:"scripted"`
}

func (q *Queries) InsertModelOutput(ctx context.Context, arg InsertModelOutputParams) error {
	_, err := q.db.ExecContext(ctx, insertModelOutput,
		arg.ID,
		arg.TurnAttemptID,
		arg.SessionID,
		arg.ProjectID,
		arg.Iteration,
		arg.MessageID,
		arg.ProviderID,
		arg.Model,
		arg.ContentBlobSha256,
		arg.FinishReason,
		arg.CreatedAt,
		arg.SettledAt,
		arg.Scripted,
	)
	return err
}

const insertTurn = `-- name: InsertTurn :exec
INSERT INTO turns (
    id, session_id, project_id, origin, input_json, status, revision,
    active_attempt_id, created_at, updated_at, progressed_at
) VALUES (?, ?, ?, ?, ?, 'running', 1, ?, ?, ?, ?)
`

type InsertTurnParams struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	ProjectID       string         `json:"project_id"`
	Origin          string         `json:"origin"`
	InputJson       string         `json:"input_json"`
	ActiveAttemptID sql.NullString `json:"active_attempt_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	ProgressedAt    string         `json:"progressed_at"`
}

func (q *Queries) InsertTurn(ctx context.Context, arg InsertTurnParams) error {
	_, err := q.db.ExecContext(ctx, insertTurn,
		arg.ID,
		arg.SessionID,
		arg.ProjectID,
		arg.Origin,
		arg.InputJson,
		arg.ActiveAttemptID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ProgressedAt,
	)
	return err
}

const insertTurnAttempt = `-- name: InsertTurnAttempt :exec
INSERT INTO turn_attempts (
    id, turn_id, attempt, status, phase, checkpoint_json, started_at, updated_at
) VALUES (?, ?, ?, 'running', 'preparing', '{}', ?, ?)
`

type InsertTurnAttemptParams struct {
	ID        string `json:"id"`
	TurnID    string `json:"turn_id"`
	Attempt   int64  `json:"attempt"`
	StartedAt string `json:"started_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertTurnAttempt(ctx context.Context, arg InsertTurnAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertTurnAttempt,
		arg.ID,
		arg.TurnID,
		arg.Attempt,
		arg.StartedAt,
		arg.UpdatedAt,
	)
	return err
}

const interruptRunningTurnAttempts = `-- name: InterruptRunningTurnAttempts :exec
UPDATE turn_attempts
SET status = 'interrupted', error = 'host stopped during turn execution',
    updated_at = ?, completed_at = ?
WHERE status = 'running'
`

type InterruptRunningTurnAttemptsParams struct {
	UpdatedAt   string         `json:"updated_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

func (q *Queries) InterruptRunningTurnAttempts(ctx context.Context, arg InterruptRunningTurnAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, interruptRunningTurnAttempts, arg.UpdatedAt, arg.CompletedAt)
	return err
}

const linkTurnSubmission = `-- name: LinkTurnSubmission :exec
INSERT INTO turn_submissions (turn_id, submission_id, position)
VALUES (?, ?, ?)
`

type LinkTurnSubmissionParams struct {
	TurnID       string `json:"turn_id"`
	SubmissionID string `json:"submission_id"`
	Position     int64  `json:"position"`
}

func (q *Queries) LinkTurnSubmission(ctx context.Context, arg LinkTurnSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, linkTurnSubmission, arg.TurnID, arg.SubmissionID, arg.Position)
	return err
}

const linkWorkerTurn = `-- name: LinkWorkerTurn :exec
INSERT INTO worker_turns (worker_job_id, turn_id) VALUES (?, ?)
`

type LinkWorkerTurnParams struct {
	WorkerJobID string `json:"worker_job_id"`
	TurnID      string `json:"turn_id"`
}

func (q *Queries) LinkWorkerTurn(ctx context.Context, arg LinkWorkerTurnParams) error {
	_, err := q.db.ExecContext(ctx, linkWorkerTurn, arg.WorkerJobID, arg.TurnID)
	return err
}

const listPendingModelOutputs = `-- name: ListPendingModelOutputs :many
SELECT output.id, output.turn_attempt_id, output.session_id, output.project_id, output.iteration, output.scripted, output.message_id, output.provider_id, output.model, output.content_blob_sha256, output.finish_reason, output.created_at, output.settled_at
FROM model_outputs output
LEFT JOIN model_output_projections projection ON projection.model_output_id = output.id
WHERE projection.model_output_id IS NULL
ORDER BY output.settled_at, output.id
LIMIT 256
`

func (q *Queries) ListPendingModelOutputs(ctx context.Context) ([]ModelOutputs, error) {
	rows, err := q.db.QueryContext(ctx, listPendingModelOutputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelOutputs
	for rows.Next() {
		var i ModelOutputs
		if err := rows.Scan(
			&i.ID,
			&i.TurnAttemptID,
			&i.SessionID,
			&i.ProjectID,
			&i.Iteration,
			&i.Scripted,
			&i.MessageID,
			&i.ProviderID,
			&i.Model,
			&i.ContentBlobSha256,
			&i.FinishReason,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveringTurns = `-- name: ListRecoveringTurns :many
SELECT id, session_id, project_id, origin, input_json, status, revision,
       active_attempt_id, final_output_id, result_json, error,
       created_at, updated_at, completed_at, progressed_at
FROM turns
WHERE status = 'recovering'
ORDER BY created_at, id
LIMIT 256
`

func (q *Queries) ListRecoveringTurns(ctx context.Context) ([]Turns, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveringTurns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turns
	for rows.Next() {
		var i Turns
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.Origin,
			&i.InputJson,
			&i.Status,
			&i.Revision,
			&i.ActiveAttemptID,
			&i.FinalOutputID,
			&i.ResultJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ProgressedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelOutputProjected = `-- name: MarkModelOutputProjected :execrows
INSERT INTO model_output_projections (model_output_id, message_seq, projected_at)
SELECT output.id, message.seq, ?
FROM model_outputs output
JOIN messages message ON message.id = output.message_id
WHERE output.id = ? AND message.seq > 0
ON CONFLICT(model_output_id) DO UPDATE SET
    message_seq = excluded.message_seq,
    projected_at = excluded.projected_at
`

type MarkModelOutputProjectedParams struct {
	ProjectedAt string `json:"projected_at"`
	ID          string `json:"id"`
}

func (q *Queries) MarkModelOutputProjected(ctx context.Context, arg MarkModelOutputProjectedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markModelOutputProjected, arg.ProjectedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextTurnAttempt = `-- name: NextTurnAttempt :one
SELECT COALESCE(MAX(attempt), 0) + 1 FROM turn_attempts WHERE turn_id = ?
`

func (q *Queries) NextTurnAttempt(ctx context.Context, turnID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTurnAttempt, turnID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const recoverRunningTurns = `-- name: RecoverRunningTurns :exec
UPDATE turns
SET status = CASE WHEN origin IN ('user', 'worker') THEN 'recovering' ELSE 'interrupted' END,
    revision = revision + 1, updated_at = ?,
    completed_at = CASE WHEN origin IN ('user', 'worker') THEN NULL ELSE ? END,
    error = 'host stopped during turn execution'
WHERE status = 'running'
`

type RecoverRunningTurnsParams struct {
	UpdatedAt   string         `json:"updated_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

func (q *Queries) RecoverRunningTurns(ctx context.Context, arg RecoverRunningTurnsParams) error {
	_, err := q.db.ExecContext(ctx, recoverRunningTurns, arg.UpdatedAt, arg.CompletedAt)
	return err
}

const resumeTurn = `-- name: ResumeTurn :execrows
UPDATE turns
SET status = 'running', revision = revision + 1, active_attempt_id = ?,
    error = '', updated_at = ?, completed_at = NULL
WHERE id = ? AND status IN ('recovering', 'failed', 'interrupted')
`

type ResumeTurnParams struct {
	ActiveAttemptID sql.NullString `json:"active_attempt_id"`
	UpdatedAt       string         `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) ResumeTurn(ctx context.Context, arg ResumeTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resumeTurn, arg.ActiveAttemptID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchCheckpointedTurn = `-- name: TouchCheckpointedTurn :execrows
UPDATE turns SET revision = revision + 1, updated_at = ?, progressed_at = ?
WHERE id = ? AND active_attempt_id = ? AND status = 'running'
`

type TouchCheckpointedTurnParams struct {
	UpdatedAt       string         `json:"updated_at"`
	ProgressedAt    string         `json:"progressed_at"`
	ID              string         `json:"id"`
	ActiveAttemptID sql.NullString `json:"active_attempt_id"`
}

func (q *Queries) TouchCheckpointedTurn(ctx context.Context, arg TouchCheckpointedTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchCheckpointedTurn,
		arg.UpdatedAt,
		arg.ProgressedAt,
		arg.ID,
		arg.ActiveAttemptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertLiveModelOutput = `-- name: UpsertLiveModelOutput :exec
INSERT INTO live_model_outputs (
    id, turn_attempt_id, session_id, iteration, message_id, content,
    tool_calls_json, reasoning_json, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    content = excluded.content,
    tool_calls_json = excluded.tool_calls_json,
    reasoning_json = excluded.reasoning_json,
    updated_at = excluded.updated_at
`

type UpsertLiveModelOutputParams struct {
	ID            string         `json:"id"`
	TurnAttemptID string         `json:"turn_attempt_id"`
	SessionID     string         `json:"session_id"`
	Iteration     int64          `json:"iteration"`
	MessageID     string         `json:"message_id"`
	Content       string         `json:"content"`
	ToolCallsJson sql.NullString `json:"tool_calls_json"`
	ReasoningJson sql.NullString `json:"reasoning_json"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) UpsertLiveModelOutput(ctx context.Context, arg UpsertLiveModelOutputParams) error {
	_, err := q.db.ExecContext(ctx, upsertLiveModelOutput,
		arg.ID,
		arg.TurnAttemptID,
		arg.SessionID,
		arg.Iteration,
		arg.MessageID,
		arg.Content,
		arg.ToolCallsJson,
		arg.ReasoningJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
