// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: worker_baselines.sql

package db

import (
	"context"
)

const discardUnpublishedWorkerBaseline = `-- name: DiscardUnpublishedWorkerBaseline :execrows
DELETE FROM worker_baselines
WHERE id=?1 AND NOT EXISTS
 (SELECT 1 FROM worker_jobs WHERE workspace_baseline_id=worker_baselines.id OR workspace_overlay_id=worker_baselines.id)
`

// A manifest is published once a worker row names it as its baseline or its
// overlay; both references keep it and its pinned objects alive.
func (q *Queries) DiscardUnpublishedWorkerBaseline(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, discardUnpublishedWorkerBaseline, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertWorkerBaseline = `-- name: InsertWorkerBaseline :exec
INSERT INTO worker_baselines(id,job_id,created_at) VALUES(?,?,?)
`

type InsertWorkerBaselineParams struct {
	ID        string `json:"id"`
	JobID     string `json:"job_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertWorkerBaseline(ctx context.Context, arg InsertWorkerBaselineParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkerBaseline, arg.ID, arg.JobID, arg.CreatedAt)
	return err
}

const pinWorkerBaselineObject = `-- name: PinWorkerBaselineObject :exec
INSERT OR IGNORE INTO worker_baseline_objects(baseline_id,sha256) VALUES(?,?)
`

type PinWorkerBaselineObjectParams struct {
	BaselineID string `json:"baseline_id"`
	Sha256     string `json:"sha256"`
}

func (q *Queries) PinWorkerBaselineObject(ctx context.Context, arg PinWorkerBaselineObjectParams) error {
	_, err := q.db.ExecContext(ctx, pinWorkerBaselineObject, arg.BaselineID, arg.Sha256)
	return err
}

const pruneAbandonedWorkerBaselines = `-- name: PruneAbandonedWorkerBaselines :execrows
DELETE FROM worker_baselines WHERE id IN (
 SELECT b.id FROM worker_baselines b
 WHERE b.created_at < ?1 AND NOT EXISTS
 (SELECT 1 FROM worker_jobs j WHERE j.workspace_baseline_id=b.id OR j.workspace_overlay_id=b.id)
 ORDER BY b.created_at LIMIT ?2
)
`

type PruneAbandonedWorkerBaselinesParams struct {
	CreatedBefore string `json:"created_before"`
	BatchLimit    int64  `json:"batch_limit"`
}

func (q *Queries) PruneAbandonedWorkerBaselines(ctx context.Context, arg PruneAbandonedWorkerBaselinesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAbandonedWorkerBaselines, arg.CreatedBefore, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sealWorkerBaseline = `-- name: SealWorkerBaseline :exec
UPDATE worker_baselines SET manifest_sha256 = ?, format_version = ? WHERE id = ?
`

type SealWorkerBaselineParams struct {
	ManifestSha256 string `json:"manifest_sha256"`
	FormatVersion  int64  `json:"format_version"`
	ID             string `json:"id"`
}

func (q *Queries) SealWorkerBaseline(ctx context.Context, arg SealWorkerBaselineParams) error {
	_, err := q.db.ExecContext(ctx, sealWorkerBaseline, arg.ManifestSha256, arg.FormatVersion, arg.ID)
	return err
}

const workerBaselineExists = `-- name: WorkerBaselineExists :one
SELECT CAST(EXISTS(SELECT 1 FROM worker_baselines WHERE id=?) AS INTEGER)
`

func (q *Queries) WorkerBaselineExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, workerBaselineExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
