// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workflow_runs.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const activeWorkflowRunByProjectAndBlueprintPath = `-- name: ActiveWorkflowRunByProjectAndBlueprintPath :one
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE project_id = ? AND blueprint_path = ?
  AND status IN ('running','paused','paused_on_child')
ORDER BY CASE WHEN parent_run_id IS NOT NULL AND TRIM(parent_run_id) != '' THEN 0 ELSE 1 END,
    created_at DESC, rowid DESC
LIMIT 1
`

type ActiveWorkflowRunByProjectAndBlueprintPathParams struct {
	ProjectID     string         `json:"project_id"`
	BlueprintPath sql.NullString `json:"blueprint_path"`
}

func (q *Queries) ActiveWorkflowRunByProjectAndBlueprintPath(ctx context.Context, arg ActiveWorkflowRunByProjectAndBlueprintPathParams) (WorkflowRuns, error) {
	row := q.db.QueryRowContext(ctx, activeWorkflowRunByProjectAndBlueprintPath, arg.ProjectID, arg.BlueprintPath)
	var i WorkflowRuns
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.AttachPolicy,
		&i.Status,
		&i.ParentRunID,
		&i.Revision,
		&i.CurrentPhase,
		&i.ProjectDir,
		&i.VarsJson,
		&i.BlueprintPath,
		&i.PauseReason,
		&i.FailureJson,
		&i.StartMessageID,
		&i.EndMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ReviewRevision,
	)
	return i, err
}

const activeWorkflowRunBySession = `-- name: ActiveWorkflowRunBySession :one
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE session_id = ? AND status IN ('running','paused','paused_on_child')
ORDER BY CASE WHEN parent_run_id IS NOT NULL AND TRIM(parent_run_id) != '' THEN 0 ELSE 1 END,
    created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) ActiveWorkflowRunBySession(ctx context.Context, sessionID string) (WorkflowRuns, error) {
	row := q.db.QueryRowContext(ctx, activeWorkflowRunBySession, sessionID)
	var i WorkflowRuns
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.AttachPolicy,
		&i.Status,
		&i.ParentRunID,
		&i.Revision,
		&i.CurrentPhase,
		&i.ProjectDir,
		&i.VarsJson,
		&i.BlueprintPath,
		&i.PauseReason,
		&i.FailureJson,
		&i.StartMessageID,
		&i.EndMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ReviewRevision,
	)
	return i, err
}

const cancelActiveRootWorkflowLineage = `-- name: CancelActiveRootWorkflowLineage :execrows
UPDATE workflow_runs
SET status = 'canceled', pause_reason = ?1, completed_at = ?2,
    updated_at = ?3, revision = revision + 1
WHERE workflow_runs.session_id = ?4
  AND workflow_runs.status IN ('running', 'paused', 'paused_on_child')
  AND EXISTS (
      SELECT 1 FROM workflow_runs expected
      WHERE expected.id = ?5
        AND expected.session_id = ?4
        AND expected.revision = ?6
        AND expected.parent_run_id IS NULL
        AND expected.status IN ('running', 'paused', 'paused_on_child')
  )
`

type CancelActiveRootWorkflowLineageParams struct {
	Reason           sql.NullString `json:"reason"`
	CompletedAt      sql.NullString `json:"completed_at"`
	UpdatedAt        string         `json:"updated_at"`
	TargetSessionID  string         `json:"target_session_id"`
	ExpectedID       string         `json:"expected_id"`
	ExpectedRevision int64          `json:"expected_revision"`
}

func (q *Queries) CancelActiveRootWorkflowLineage(ctx context.Context, arg CancelActiveRootWorkflowLineageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelActiveRootWorkflowLineage,
		arg.Reason,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.TargetSessionID,
		arg.ExpectedID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelActiveWorkflowLineage = `-- name: CancelActiveWorkflowLineage :execrows
UPDATE workflow_runs
SET status = 'canceled', pause_reason = ?1, completed_at = ?2,
    updated_at = ?3, revision = revision + 1
WHERE workflow_runs.session_id = ?4
  AND workflow_runs.status IN ('running', 'paused', 'paused_on_child')
  AND EXISTS (
      SELECT 1 FROM workflow_runs expected
      WHERE expected.id = ?5
        AND expected.session_id = ?4
        AND expected.revision = ?6
        AND expected.status IN ('running', 'paused', 'paused_on_child')
  )
`

type CancelActiveWorkflowLineageParams struct {
	Reason           sql.NullString `json:"reason"`
	CompletedAt      sql.NullString `json:"completed_at"`
	UpdatedAt        string         `json:"updated_at"`
	TargetSessionID  string         `json:"target_session_id"`
	ExpectedID       string         `json:"expected_id"`
	ExpectedRevision int64          `json:"expected_revision"`
}

func (q *Queries) CancelActiveWorkflowLineage(ctx context.Context, arg CancelActiveWorkflowLineageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelActiveWorkflowLineage,
		arg.Reason,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.TargetSessionID,
		arg.ExpectedID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const commitWorkflowRunState = `-- name: CommitWorkflowRunState :execrows
UPDATE workflow_runs
SET status = ?, current_phase = ?, project_dir = ?, vars_json = ?, pause_reason = ?, failure_json = ?,
    updated_at = ?, paused_at = ?, completed_at = ?, revision = revision + 1
WHERE id = ? AND revision = ?
`

type CommitWorkflowRunStateParams struct {
	Status       string         `json:"status"`
	CurrentPhase string         `json:"current_phase"`
	ProjectDir   string         `json:"project_dir"`
	VarsJson     string         `json:"vars_json"`
	PauseReason  sql.NullString `json:"pause_reason"`
	FailureJson  sql.NullString `json:"failure_json"`
	UpdatedAt    string         `json:"updated_at"`
	PausedAt     sql.NullString `json:"paused_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	ID           string         `json:"id"`
	Revision     int64          `json:"revision"`
}

func (q *Queries) CommitWorkflowRunState(ctx context.Context, arg CommitWorkflowRunStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitWorkflowRunState,
		arg.Status,
		arg.CurrentPhase,
		arg.ProjectDir,
		arg.VarsJson,
		arg.PauseReason,
		arg.FailureJson,
		arg.UpdatedAt,
		arg.PausedAt,
		arg.CompletedAt,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const commitWorkflowVerdictOperation = `-- name: CommitWorkflowVerdictOperation :execrows
UPDATE workflow_verdict_operations
SET status = 'committed', response_json = ?, updated_at = ?
WHERE tool_call_id = ? AND status IN ('prepared', 'evidence_applied')
`

type CommitWorkflowVerdictOperationParams struct {
	ResponseJson sql.NullString `json:"response_json"`
	UpdatedAt    string         `json:"updated_at"`
	ToolCallID   string         `json:"tool_call_id"`
}

func (q *Queries) CommitWorkflowVerdictOperation(ctx context.Context, arg CommitWorkflowVerdictOperationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitWorkflowVerdictOperation, arg.ResponseJson, arg.UpdatedAt, arg.ToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeWorkflowTeardownOperation = `-- name: CompleteWorkflowTeardownOperation :exec
UPDATE workflow_teardown_operations
SET status = 'complete', attempts = attempts + 1, last_error = '', updated_at = ?
WHERE id = ? AND status = 'pending'
`

type CompleteWorkflowTeardownOperationParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteWorkflowTeardownOperation(ctx context.Context, arg CompleteWorkflowTeardownOperationParams) error {
	_, err := q.db.ExecContext(ctx, completeWorkflowTeardownOperation, arg.UpdatedAt, arg.ID)
	return err
}

const countMatchingBlueprintApproval = `-- name: CountMatchingBlueprintApproval :one
SELECT COUNT(*) FROM blueprint_approvals
WHERE project_id = ? AND path = ? AND workflow_run_id = ? AND workflow_revision = ?
  AND content_digest = ? AND status = 'approved'
`

type CountMatchingBlueprintApprovalParams struct {
	ProjectID        string         `json:"project_id"`
	Path             string         `json:"path"`
	WorkflowRunID    sql.NullString `json:"workflow_run_id"`
	WorkflowRevision int64          `json:"workflow_revision"`
	ContentDigest    string         `json:"content_digest"`
}

func (q *Queries) CountMatchingBlueprintApproval(ctx context.Context, arg CountMatchingBlueprintApprovalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMatchingBlueprintApproval,
		arg.ProjectID,
		arg.Path,
		arg.WorkflowRunID,
		arg.WorkflowRevision,
		arg.ContentDigest,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failWorkflowTeardownOperation = `-- name: FailWorkflowTeardownOperation :exec
UPDATE workflow_teardown_operations
SET attempts = attempts + 1, last_error = ?, updated_at = ?
WHERE id = ? AND status = 'pending'
`

type FailWorkflowTeardownOperationParams struct {
	LastError string `json:"last_error"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) FailWorkflowTeardownOperation(ctx context.Context, arg FailWorkflowTeardownOperationParams) error {
	_, err := q.db.ExecContext(ctx, failWorkflowTeardownOperation, arg.LastError, arg.UpdatedAt, arg.ID)
	return err
}

const getScaffoldVars = `-- name: GetScaffoldVars :one
SELECT vars_json FROM workflow_runs WHERE id = ?
`

func (q *Queries) GetScaffoldVars(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getScaffoldVars, id)
	var vars_json string
	err := row.Scan(&vars_json)
	return vars_json, err
}

const getWorkflowCommandByOperation = `-- name: GetWorkflowCommandByOperation :one
SELECT kind, input_digest, response_json, rejection_json
FROM workflow_commands
WHERE operation_id = ?
`

type GetWorkflowCommandByOperationRow struct {
	Kind          string `json:"kind"`
	InputDigest   string `json:"input_digest"`
	ResponseJson  string `json:"response_json"`
	RejectionJson string `json:"rejection_json"`
}

func (q *Queries) GetWorkflowCommandByOperation(ctx context.Context, operationID string) (GetWorkflowCommandByOperationRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowCommandByOperation, operationID)
	var i GetWorkflowCommandByOperationRow
	err := row.Scan(
		&i.Kind,
		&i.InputDigest,
		&i.ResponseJson,
		&i.RejectionJson,
	)
	return i, err
}

const getWorkflowCommandByRevision = `-- name: GetWorkflowCommandByRevision :one
SELECT kind, input_digest, response_json, rejection_json
FROM workflow_commands
WHERE run_id = ? AND source_revision = ?
`

type GetWorkflowCommandByRevisionParams struct {
	RunID          string `json:"run_id"`
	SourceRevision int64  `json:"source_revision"`
}

type GetWorkflowCommandByRevisionRow struct {
	Kind          string `json:"kind"`
	InputDigest   string `json:"input_digest"`
	ResponseJson  string `json:"response_json"`
	RejectionJson string `json:"rejection_json"`
}

func (q *Queries) GetWorkflowCommandByRevision(ctx context.Context, arg GetWorkflowCommandByRevisionParams) (GetWorkflowCommandByRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowCommandByRevision, arg.RunID, arg.SourceRevision)
	var i GetWorkflowCommandByRevisionRow
	err := row.Scan(
		&i.Kind,
		&i.InputDigest,
		&i.ResponseJson,
		&i.RejectionJson,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE id = ?
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id string) (WorkflowRuns, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRun, id)
	var i WorkflowRuns
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.AttachPolicy,
		&i.Status,
		&i.ParentRunID,
		&i.Revision,
		&i.CurrentPhase,
		&i.ProjectDir,
		&i.VarsJson,
		&i.BlueprintPath,
		&i.PauseReason,
		&i.FailureJson,
		&i.StartMessageID,
		&i.EndMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ReviewRevision,
	)
	return i, err
}

const getWorkflowStartOperation = `-- name: GetWorkflowStartOperation :one
SELECT session_id, input_digest, workflow_run_id, response_json
FROM workflow_start_operations
WHERE id = ?
`

type GetWorkflowStartOperationRow struct {
	SessionID     string `json:"session_id"`
	InputDigest   string `json:"input_digest"`
	WorkflowRunID string `json:"workflow_run_id"`
	ResponseJson  string `json:"response_json"`
}

func (q *Queries) GetWorkflowStartOperation(ctx context.Context, id string) (GetWorkflowStartOperationRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowStartOperation, id)
	var i GetWorkflowStartOperationRow
	err := row.Scan(
		&i.SessionID,
		&i.InputDigest,
		&i.WorkflowRunID,
		&i.ResponseJson,
	)
	return i, err
}

const getWorkflowVerdictOperation = `-- name: GetWorkflowVerdictOperation :one
SELECT tool_call_id, run_id, source_revision, phase, input_digest, evidence_record_id,
       evidence_json, status, response_json, error, created_at, updated_at
FROM workflow_verdict_operations
WHERE tool_call_id = ?
`

func (q *Queries) GetWorkflowVerdictOperation(ctx context.Context, toolCallID string) (WorkflowVerdictOperations, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowVerdictOperation, toolCallID)
	var i WorkflowVerdictOperations
	err := row.Scan(
		&i.ToolCallID,
		&i.RunID,
		&i.SourceRevision,
		&i.Phase,
		&i.InputDigest,
		&i.EvidenceRecordID,
		&i.EvidenceJson,
		&i.Status,
		&i.ResponseJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const holdWorkflowWorkers = `-- name: HoldWorkflowWorkers :exec
UPDATE worker_jobs SET status = 'held'
WHERE workflow_run_id = ? AND status = 'pending' AND cancel_requested_at IS NULL
`

func (q *Queries) HoldWorkflowWorkers(ctx context.Context, workflowRunID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, holdWorkflowWorkers, workflowRunID)
	return err
}

const insertWorkflowCommand = `-- name: InsertWorkflowCommand :exec
INSERT INTO workflow_commands(
    operation_id, run_id, source_revision, kind, input_digest,
    result_revision, response_json, rejection_json, committed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWorkflowCommandParams struct {
	OperationID    string `json:"operation_id"`
	RunID          string `json:"run_id"`
	SourceRevision int64  `json:"source_revision"`
	Kind           string `json:"kind"`
	InputDigest    string `json:"input_digest"`
	ResultRevision int64  `json:"result_revision"`
	ResponseJson   string `json:"response_json"`
	RejectionJson  string `json:"rejection_json"`
	CommittedAt    string `json:"committed_at"`
}

func (q *Queries) InsertWorkflowCommand(ctx context.Context, arg InsertWorkflowCommandParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkflowCommand,
		arg.OperationID,
		arg.RunID,
		arg.SourceRevision,
		arg.Kind,
		arg.InputDigest,
		arg.ResultRevision,
		arg.ResponseJson,
		arg.RejectionJson,
		arg.CommittedAt,
	)
	return err
}

const insertWorkflowRunPageOrdinal = `-- name: InsertWorkflowRunPageOrdinal :exec
INSERT INTO workflow_run_page_ordinals(run_id) VALUES (?)
`

func (q *Queries) InsertWorkflowRunPageOrdinal(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, insertWorkflowRunPageOrdinal, runID)
	return err
}

const insertWorkflowRunRow = `-- name: InsertWorkflowRunRow :exec

INSERT INTO workflow_runs (
    id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
    blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
    created_at, updated_at, paused_at, completed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWorkflowRunRowParams struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	ProjectID       string         `json:"project_id"`
	WorkflowID      string         `json:"workflow_id"`
	WorkflowVersion string         `json:"workflow_version"`
	AttachPolicy    string         `json:"attach_policy"`
	Status          string         `json:"status"`
	ParentRunID     sql.NullString `json:"parent_run_id"`
	Revision        int64          `json:"revision"`
	CurrentPhase    string         `json:"current_phase"`
	ProjectDir      string         `json:"project_dir"`
	VarsJson        string         `json:"vars_json"`
	BlueprintPath   sql.NullString `json:"blueprint_path"`
	PauseReason     sql.NullString `json:"pause_reason"`
	FailureJson     sql.NullString `json:"failure_json"`
	StartMessageID  sql.NullString `json:"start_message_id"`
	EndMessageID    sql.NullString `json:"end_message_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	PausedAt        sql.NullString `json:"paused_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
}

// Matching column order keeps reads on one generated row type.
func (q *Queries) InsertWorkflowRunRow(ctx context.Context, arg InsertWorkflowRunRowParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkflowRunRow,
		arg.ID,
		arg.SessionID,
		arg.ProjectID,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.AttachPolicy,
		arg.Status,
		arg.ParentRunID,
		arg.Revision,
		arg.CurrentPhase,
		arg.ProjectDir,
		arg.VarsJson,
		arg.BlueprintPath,
		arg.PauseReason,
		arg.FailureJson,
		arg.StartMessageID,
		arg.EndMessageID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PausedAt,
		arg.CompletedAt,
	)
	return err
}

const insertWorkflowStartOperation = `-- name: InsertWorkflowStartOperation :exec
INSERT INTO workflow_start_operations(
    id, session_id, input_digest, workflow_run_id, response_json, committed_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertWorkflowStartOperationParams struct {
	ID            string `json:"id"`
	SessionID     string `json:"session_id"`
	InputDigest   string `json:"input_digest"`
	WorkflowRunID string `json:"workflow_run_id"`
	ResponseJson  string `json:"response_json"`
	CommittedAt   string `json:"committed_at"`
}

func (q *Queries) InsertWorkflowStartOperation(ctx context.Context, arg InsertWorkflowStartOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkflowStartOperation,
		arg.ID,
		arg.SessionID,
		arg.InputDigest,
		arg.WorkflowRunID,
		arg.ResponseJson,
		arg.CommittedAt,
	)
	return err
}

const insertWorkflowTeardownOperation = `-- name: InsertWorkflowTeardownOperation :exec
INSERT INTO workflow_teardown_operations(
    id, run_id, source_revision, cancel_scope, abort_delegation, reason,
    status, attempts, last_error, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 'pending', 0, '', ?, ?)
ON CONFLICT(run_id, source_revision) DO NOTHING
`

type InsertWorkflowTeardownOperationParams struct {
	ID              string `json:"id"`
	RunID           string `json:"run_id"`
	SourceRevision  int64  `json:"source_revision"`
	CancelScope     string `json:"cancel_scope"`
	AbortDelegation int64  `json:"abort_delegation"`
	Reason          string `json:"reason"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) InsertWorkflowTeardownOperation(ctx context.Context, arg InsertWorkflowTeardownOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkflowTeardownOperation,
		arg.ID,
		arg.RunID,
		arg.SourceRevision,
		arg.CancelScope,
		arg.AbortDelegation,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const latestChildWorkflowRun = `-- name: LatestChildWorkflowRun :one
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE parent_run_id = ?
ORDER BY created_at DESC, rowid DESC
LIMIT 1
`

func (q *Queries) LatestChildWorkflowRun(ctx context.Context, parentRunID sql.NullString) (WorkflowRuns, error) {
	row := q.db.QueryRowContext(ctx, latestChildWorkflowRun, parentRunID)
	var i WorkflowRuns
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.AttachPolicy,
		&i.Status,
		&i.ParentRunID,
		&i.Revision,
		&i.CurrentPhase,
		&i.ProjectDir,
		&i.VarsJson,
		&i.BlueprintPath,
		&i.PauseReason,
		&i.FailureJson,
		&i.StartMessageID,
		&i.EndMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ReviewRevision,
	)
	return i, err
}

const listPausedOnChildWorkflowRuns = `-- name: ListPausedOnChildWorkflowRuns :many
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE status = 'paused_on_child'
ORDER BY created_at, id
`

func (q *Queries) ListPausedOnChildWorkflowRuns(ctx context.Context) ([]WorkflowRuns, error) {
	rows, err := q.db.QueryContext(ctx, listPausedOnChildWorkflowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRuns
	for rows.Next() {
		var i WorkflowRuns
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.AttachPolicy,
			&i.Status,
			&i.ParentRunID,
			&i.Revision,
			&i.CurrentPhase,
			&i.ProjectDir,
			&i.VarsJson,
			&i.BlueprintPath,
			&i.PauseReason,
			&i.FailureJson,
			&i.StartMessageID,
			&i.EndMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ReviewRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWorkflowTeardownOperations = `-- name: ListPendingWorkflowTeardownOperations :many
SELECT id, run_id, source_revision, cancel_scope, abort_delegation, reason,
       status, attempts, last_error, created_at, updated_at
FROM workflow_teardown_operations
WHERE status = 'pending'
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListPendingWorkflowTeardownOperations(ctx context.Context) ([]WorkflowTeardownOperations, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWorkflowTeardownOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowTeardownOperations
	for rows.Next() {
		var i WorkflowTeardownOperations
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.SourceRevision,
			&i.CancelScope,
			&i.AbortDelegation,
			&i.Reason,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWorkflowVerdictOperations = `-- name: ListPendingWorkflowVerdictOperations :many
SELECT tool_call_id, run_id, source_revision, phase, input_digest, evidence_record_id,
       evidence_json, status, response_json, error, created_at, updated_at
FROM workflow_verdict_operations
WHERE status IN ('prepared', 'evidence_applied')
ORDER BY created_at, tool_call_id
`

func (q *Queries) ListPendingWorkflowVerdictOperations(ctx context.Context) ([]WorkflowVerdictOperations, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWorkflowVerdictOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVerdictOperations
	for rows.Next() {
		var i WorkflowVerdictOperations
		if err := rows.Scan(
			&i.ToolCallID,
			&i.RunID,
			&i.SourceRevision,
			&i.Phase,
			&i.InputDigest,
			&i.EvidenceRecordID,
			&i.EvidenceJson,
			&i.Status,
			&i.ResponseJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningWorkflowRuns = `-- name: ListRunningWorkflowRuns :many
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE status = 'running'
ORDER BY created_at, id
`

func (q *Queries) ListRunningWorkflowRuns(ctx context.Context) ([]WorkflowRuns, error) {
	rows, err := q.db.QueryContext(ctx, listRunningWorkflowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRuns
	for rows.Next() {
		var i WorkflowRuns
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.AttachPolicy,
			&i.Status,
			&i.ParentRunID,
			&i.Revision,
			&i.CurrentPhase,
			&i.ProjectDir,
			&i.VarsJson,
			&i.BlueprintPath,
			&i.PauseReason,
			&i.FailureJson,
			&i.StartMessageID,
			&i.EndMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ReviewRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsBySession = `-- name: ListWorkflowRunsBySession :many

SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE session_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListWorkflowRunsBySessionParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

// Empty slice expansion shifts later placeholders, so filtered queries stay separate.
func (q *Queries) ListWorkflowRunsBySession(ctx context.Context, arg ListWorkflowRunsBySessionParams) ([]WorkflowRuns, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRunsBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRuns
	for rows.Next() {
		var i WorkflowRuns
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.AttachPolicy,
			&i.Status,
			&i.ParentRunID,
			&i.Revision,
			&i.CurrentPhase,
			&i.ProjectDir,
			&i.VarsJson,
			&i.BlueprintPath,
			&i.PauseReason,
			&i.FailureJson,
			&i.StartMessageID,
			&i.EndMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ReviewRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsBySessionWithStatus = `-- name: ListWorkflowRunsBySessionWithStatus :many
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
WHERE session_id = ? AND status IN (/*SLICE:statuses*/?)
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListWorkflowRunsBySessionWithStatusParams struct {
	SessionID string   `json:"session_id"`
	Statuses  []string `json:"statuses"`
	Limit     int64    `json:"limit"`
}

func (q *Queries) ListWorkflowRunsBySessionWithStatus(ctx context.Context, arg ListWorkflowRunsBySessionWithStatusParams) ([]WorkflowRuns, error) {
	query := listWorkflowRunsBySessionWithStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SessionID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRuns
	for rows.Next() {
		var i WorkflowRuns
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.AttachPolicy,
			&i.Status,
			&i.ParentRunID,
			&i.Revision,
			&i.CurrentPhase,
			&i.ProjectDir,
			&i.VarsJson,
			&i.BlueprintPath,
			&i.PauseReason,
			&i.FailureJson,
			&i.StartMessageID,
			&i.EndMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ReviewRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVerdictReceipts = `-- name: ListWorkflowVerdictReceipts :many
SELECT tool_call_id, run_id, source_revision, phase, evidence_json, status,
       COALESCE(response_json, '') AS response_json
FROM workflow_verdict_operations
WHERE run_id = ?
ORDER BY source_revision, tool_call_id
`

type ListWorkflowVerdictReceiptsRow struct {
	ToolCallID     string `json:"tool_call_id"`
	RunID          string `json:"run_id"`
	SourceRevision int64  `json:"source_revision"`
	Phase          string `json:"phase"`
	EvidenceJson   string `json:"evidence_json"`
	Status         string `json:"status"`
	ResponseJson   string `json:"response_json"`
}

func (q *Queries) ListWorkflowVerdictReceipts(ctx context.Context, runID string) ([]ListWorkflowVerdictReceiptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowVerdictReceipts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowVerdictReceiptsRow
	for rows.Next() {
		var i ListWorkflowVerdictReceiptsRow
		if err := rows.Scan(
			&i.ToolCallID,
			&i.RunID,
			&i.SourceRevision,
			&i.Phase,
			&i.EvidenceJson,
			&i.Status,
			&i.ResponseJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowVerdictEvidenceApplied = `-- name: MarkWorkflowVerdictEvidenceApplied :exec
UPDATE workflow_verdict_operations
SET status = 'evidence_applied', updated_at = ?
WHERE tool_call_id = ? AND status = 'prepared'
`

type MarkWorkflowVerdictEvidenceAppliedParams struct {
	UpdatedAt  string `json:"updated_at"`
	ToolCallID string `json:"tool_call_id"`
}

func (q *Queries) MarkWorkflowVerdictEvidenceApplied(ctx context.Context, arg MarkWorkflowVerdictEvidenceAppliedParams) error {
	_, err := q.db.ExecContext(ctx, markWorkflowVerdictEvidenceApplied, arg.UpdatedAt, arg.ToolCallID)
	return err
}

const pageWorkflowRunsBySession = `-- name: PageWorkflowRunsBySession :many
WITH page AS (
  SELECT CAST(?2 AS TEXT) AS statuses_json,
         CAST(?3 AS INTEGER) AS watermark_ordinal,
         CAST(?4 AS TEXT) AS before_created_at,
         CAST(?5 AS TEXT) AS before_id,
         CAST(?6 AS INTEGER) AS page_limit
)
SELECT id, session_id, project_id, workflow_id, workflow_version, attach_policy, status, parent_run_id, revision, current_phase, project_dir, vars_json,
       blueprint_path, pause_reason, failure_json, start_message_id, end_message_id,
       created_at, updated_at, paused_at, completed_at, review_revision
FROM workflow_runs
JOIN workflow_run_page_ordinals AS page_ordinal ON page_ordinal.run_id = workflow_runs.id
CROSS JOIN page
WHERE session_id = ?1
  AND (page.statuses_json = '[]' OR status IN (SELECT value FROM json_each(page.statuses_json)))
  AND page_ordinal.ordinal <= page.watermark_ordinal
  AND (page.before_created_at = '' OR created_at < page.before_created_at OR (created_at = page.before_created_at AND id < page.before_id))
ORDER BY created_at DESC, id DESC
LIMIT (SELECT page_limit FROM page)
`

type PageWorkflowRunsBySessionParams struct {
	SessionID        string `json:"session_id"`
	StatusesJson     string `json:"statuses_json"`
	WatermarkOrdinal int64  `json:"watermark_ordinal"`
	BeforeCreatedAt  string `json:"before_created_at"`
	BeforeID         string `json:"before_id"`
	PageLimit        int64  `json:"page_limit"`
}

func (q *Queries) PageWorkflowRunsBySession(ctx context.Context, arg PageWorkflowRunsBySessionParams) ([]WorkflowRuns, error) {
	rows, err := q.db.QueryContext(ctx, pageWorkflowRunsBySession,
		arg.SessionID,
		arg.StatusesJson,
		arg.WatermarkOrdinal,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRuns
	for rows.Next() {
		var i WorkflowRuns
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.AttachPolicy,
			&i.Status,
			&i.ParentRunID,
			&i.Revision,
			&i.CurrentPhase,
			&i.ProjectDir,
			&i.VarsJson,
			&i.BlueprintPath,
			&i.PauseReason,
			&i.FailureJson,
			&i.StartMessageID,
			&i.EndMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ReviewRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prepareWorkflowVerdictOperation = `-- name: PrepareWorkflowVerdictOperation :execrows
INSERT INTO workflow_verdict_operations(
    tool_call_id, run_id, source_revision, phase, input_digest, evidence_record_id,
    evidence_json, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 'prepared', ?, ?)
ON CONFLICT(tool_call_id) DO NOTHING
`

type PrepareWorkflowVerdictOperationParams struct {
	ToolCallID       string `json:"tool_call_id"`
	RunID            string `json:"run_id"`
	SourceRevision   int64  `json:"source_revision"`
	Phase            string `json:"phase"`
	InputDigest      string `json:"input_digest"`
	EvidenceRecordID string `json:"evidence_record_id"`
	EvidenceJson     string `json:"evidence_json"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

func (q *Queries) PrepareWorkflowVerdictOperation(ctx context.Context, arg PrepareWorkflowVerdictOperationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, prepareWorkflowVerdictOperation,
		arg.ToolCallID,
		arg.RunID,
		arg.SourceRevision,
		arg.Phase,
		arg.InputDigest,
		arg.EvidenceRecordID,
		arg.EvidenceJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rebaseWorkflowVerdictOperation = `-- name: RebaseWorkflowVerdictOperation :execrows
UPDATE workflow_verdict_operations
SET source_revision = ?, updated_at = ?
WHERE tool_call_id = ? AND status IN ('prepared', 'evidence_applied')
`

type RebaseWorkflowVerdictOperationParams struct {
	SourceRevision int64  `json:"source_revision"`
	UpdatedAt      string `json:"updated_at"`
	ToolCallID     string `json:"tool_call_id"`
}

func (q *Queries) RebaseWorkflowVerdictOperation(ctx context.Context, arg RebaseWorkflowVerdictOperationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rebaseWorkflowVerdictOperation, arg.SourceRevision, arg.UpdatedAt, arg.ToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseWorkflowWorkers = `-- name: ReleaseWorkflowWorkers :exec
UPDATE worker_jobs SET status = 'pending'
WHERE workflow_run_id = ? AND status = 'held' AND cancel_requested_at IS NULL
`

func (q *Queries) ReleaseWorkflowWorkers(ctx context.Context, workflowRunID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, releaseWorkflowWorkers, workflowRunID)
	return err
}

const relocateWorkflowRunBlueprintPaths = `-- name: RelocateWorkflowRunBlueprintPaths :many
UPDATE workflow_runs
SET blueprint_path = ?1, updated_at = ?2, revision = revision + 1
WHERE project_id = ?3 AND blueprint_path = ?4
RETURNING session_id
`

type RelocateWorkflowRunBlueprintPathsParams struct {
	ToPath    sql.NullString `json:"to_path"`
	UpdatedAt string         `json:"updated_at"`
	ProjectID string         `json:"project_id"`
	FromPath  sql.NullString `json:"from_path"`
}

func (q *Queries) RelocateWorkflowRunBlueprintPaths(ctx context.Context, arg RelocateWorkflowRunBlueprintPathsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, relocateWorkflowRunBlueprintPaths,
		arg.ToPath,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.FromPath,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestRunningWorkflowWorkerCancellation = `-- name: RequestRunningWorkflowWorkerCancellation :exec
UPDATE worker_jobs
SET cancel_requested_at = COALESCE(cancel_requested_at, ?1)
WHERE workflow_run_id = ?2 AND status IN ('running', 'waiting')
`

type RequestRunningWorkflowWorkerCancellationParams struct {
	RequestedAt   sql.NullString `json:"requested_at"`
	WorkflowRunID sql.NullString `json:"workflow_run_id"`
}

func (q *Queries) RequestRunningWorkflowWorkerCancellation(ctx context.Context, arg RequestRunningWorkflowWorkerCancellationParams) error {
	_, err := q.db.ExecContext(ctx, requestRunningWorkflowWorkerCancellation, arg.RequestedAt, arg.WorkflowRunID)
	return err
}

const requestWorkflowWorkerCancellation = `-- name: RequestWorkflowWorkerCancellation :exec
UPDATE worker_jobs
SET cancel_requested_at = COALESCE(cancel_requested_at, ?1)
WHERE workflow_run_id = ?2 AND status IN ('pending', 'running', 'waiting', 'held')
`

type RequestWorkflowWorkerCancellationParams struct {
	RequestedAt   sql.NullString `json:"requested_at"`
	WorkflowRunID sql.NullString `json:"workflow_run_id"`
}

func (q *Queries) RequestWorkflowWorkerCancellation(ctx context.Context, arg RequestWorkflowWorkerCancellationParams) error {
	_, err := q.db.ExecContext(ctx, requestWorkflowWorkerCancellation, arg.RequestedAt, arg.WorkflowRunID)
	return err
}

const resolveWorkflowVerdictOperationDiverged = `-- name: ResolveWorkflowVerdictOperationDiverged :execrows
UPDATE workflow_verdict_operations
SET status = 'diverged', error = ?, updated_at = ?
WHERE tool_call_id = ? AND status IN ('prepared', 'evidence_applied')
`

type ResolveWorkflowVerdictOperationDivergedParams struct {
	Error      string `json:"error"`
	UpdatedAt  string `json:"updated_at"`
	ToolCallID string `json:"tool_call_id"`
}

func (q *Queries) ResolveWorkflowVerdictOperationDiverged(ctx context.Context, arg ResolveWorkflowVerdictOperationDivergedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveWorkflowVerdictOperationDiverged, arg.Error, arg.UpdatedAt, arg.ToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkflowRunEndMessageID = `-- name: SetWorkflowRunEndMessageID :exec
UPDATE workflow_runs SET end_message_id = ? WHERE id = ?
`

type SetWorkflowRunEndMessageIDParams struct {
	EndMessageID sql.NullString `json:"end_message_id"`
	ID           string         `json:"id"`
}

func (q *Queries) SetWorkflowRunEndMessageID(ctx context.Context, arg SetWorkflowRunEndMessageIDParams) error {
	_, err := q.db.ExecContext(ctx, setWorkflowRunEndMessageID, arg.EndMessageID, arg.ID)
	return err
}

const setWorkflowRunVarsProjection = `-- name: SetWorkflowRunVarsProjection :exec
UPDATE workflow_runs
SET vars_json = ?1
WHERE id = ?2
`

type SetWorkflowRunVarsProjectionParams struct {
	VarsJson string `json:"vars_json"`
	ID       string `json:"id"`
}

func (q *Queries) SetWorkflowRunVarsProjection(ctx context.Context, arg SetWorkflowRunVarsProjectionParams) error {
	_, err := q.db.ExecContext(ctx, setWorkflowRunVarsProjection, arg.VarsJson, arg.ID)
	return err
}

const updateWorkflowRun = `-- name: UpdateWorkflowRun :execrows
UPDATE workflow_runs
SET status = ?, current_phase = ?, pause_reason = ?, failure_json = ?, updated_at = ?, paused_at = ?, completed_at = ?, revision = revision + 1
WHERE id = ? AND revision = ?
`

type UpdateWorkflowRunParams struct {
	Status       string         `json:"status"`
	CurrentPhase string         `json:"current_phase"`
	PauseReason  sql.NullString `json:"pause_reason"`
	FailureJson  sql.NullString `json:"failure_json"`
	UpdatedAt    string         `json:"updated_at"`
	PausedAt     sql.NullString `json:"paused_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	ID           string         `json:"id"`
	Revision     int64          `json:"revision"`
}

func (q *Queries) UpdateWorkflowRun(ctx context.Context, arg UpdateWorkflowRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkflowRun,
		arg.Status,
		arg.CurrentPhase,
		arg.PauseReason,
		arg.FailureJson,
		arg.UpdatedAt,
		arg.PausedAt,
		arg.CompletedAt,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkflowRunVars = `-- name: UpdateWorkflowRunVars :execrows
UPDATE workflow_runs
SET project_dir = ?, vars_json = ?, updated_at = ?, revision = revision + 1
WHERE id = ? AND revision = ?
`

type UpdateWorkflowRunVarsParams struct {
	ProjectDir string `json:"project_dir"`
	VarsJson   string `json:"vars_json"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
	Revision   int64  `json:"revision"`
}

func (q *Queries) UpdateWorkflowRunVars(ctx context.Context, arg UpdateWorkflowRunVarsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkflowRunVars,
		arg.ProjectDir,
		arg.VarsJson,
		arg.UpdatedAt,
		arg.ID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertBlueprintApproval = `-- name: UpsertBlueprintApproval :exec
INSERT INTO blueprint_approvals(
    project_id, path, content_digest, workflow_run_id, workflow_revision,
    status, approved_at, approved_via, approved_by_person_id, session_id
) VALUES (?, ?, ?, ?, ?, 'approved', ?, ?, ?, ?)
ON CONFLICT(project_id, path) DO UPDATE SET
    content_digest = excluded.content_digest,
    workflow_run_id = excluded.workflow_run_id,
    workflow_revision = excluded.workflow_revision,
    status = 'approved',
    approved_at = excluded.approved_at,
    approved_via = excluded.approved_via,
    approved_by_person_id = excluded.approved_by_person_id,
    revoked_at = NULL,
    session_id = excluded.session_id,
    revoked_cause = ''
`

type UpsertBlueprintApprovalParams struct {
	ProjectID          string         `json:"project_id"`
	Path               string         `json:"path"`
	ContentDigest      string         `json:"content_digest"`
	WorkflowRunID      sql.NullString `json:"workflow_run_id"`
	WorkflowRevision   int64          `json:"workflow_revision"`
	ApprovedAt         string         `json:"approved_at"`
	ApprovedVia        string         `json:"approved_via"`
	ApprovedByPersonID string         `json:"approved_by_person_id"`
	SessionID          string         `json:"session_id"`
}

// Re-approval clears the grant's revocation fields.
func (q *Queries) UpsertBlueprintApproval(ctx context.Context, arg UpsertBlueprintApprovalParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlueprintApproval,
		arg.ProjectID,
		arg.Path,
		arg.ContentDigest,
		arg.WorkflowRunID,
		arg.WorkflowRevision,
		arg.ApprovedAt,
		arg.ApprovedVia,
		arg.ApprovedByPersonID,
		arg.SessionID,
	)
	return err
}

const workflowRunPageWatermark = `-- name: WorkflowRunPageWatermark :one
SELECT CAST(COALESCE(MAX(ordinal), 0) AS INTEGER) AS watermark_ordinal
FROM workflow_run_page_ordinals
`

func (q *Queries) WorkflowRunPageWatermark(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, workflowRunPageWatermark)
	var watermark_ordinal int64
	err := row.Scan(&watermark_ordinal)
	return watermark_ordinal, err
}
