import { SECURITY_SCANNERS_SECTION_LABEL } from "../settings-nav-model.ts";
import { overlayRel } from "../../platform/files/overlay-dir.ts";

export const EXTENSIONS_SETTINGS_COPY = {
  title: "Extensions",
  settingsBanner:
    "Install packs and set defaults here. Turn units off for a project under Context → Extensions.",
  projectBanner:
    "Units available to this project. Device-controlled items are managed in Settings.",
  tabPacks: "Installed",
  tabUnits: "Active",
  tabDesired: "Config",
  tabSettings: "Settings",
  tabModel: "How it works",
  configurationEmptyTitle: "No pack settings",
  configurationEmptyHint:
    "Packs that declare settings show them here, with the value in force.",
  configurationSaved: "Pack settings saved.",
  configurationSave: "Save settings",
  configurationDiscard: "Discard",
  configurationListPlaceholder: "Comma-separated",
  packsBack: "Installed",
  unitsBack: "Active",
  addFromGit: "Install from Git…",
  addFromFolder: "Install from folder…",
  applyProfile: "Apply profile…",
  suiteOtherPacks: "Other packs",
  suiteEnable: "Enable suite",
  suiteDisable: "Disable suite",
  suiteDisableStock: "The built-in suite contains the platform required to run extensions",
  suiteRemove: "Remove suite",
  suiteRemoveConfirm: "Remove this suite grouping? Installed member packs stay installed.",
  suiteInstall: "Install suite…",
  suiteInstallTitle: "Install suite",
  suiteInstallBody:
    "Resolves one compatible suite release and installs every member in one exact dependency graph. Suite actions only flip pack enables.",
  suiteInstallUrlLabel: "Suite source (URL or path:…)",
  suiteInstallVersionLabel: "Version range (optional)",
  suiteInstallRefLabel: "Ref (exact pin, optional)",
  suiteInstallSubmit: "Install suite",
  suiteInstallUrlRequired: "Suite source is required.",
  chipSuiteConflict: "Suite conflict",
  chipPartialSuite: "Partial suite",
  chipMissingMember: "Missing member",
  statusComplete: "Complete",
  statusPartial: "Partial",
  statusInactive: "Inactive",
  modelMetaPacksTitle: "Suites",
  modelMetaPacks:
    "Suites group packs that belong together. The effective catalog is still provide(enabled) − disabled ⊕ own — suite actions only flip pack enables, and never change load order.",
  loading: "Loading extensions…",
  emptyPacks: "No extensions installed yet.",
  emptyUnits: "No active items match.",
  emptyProvides: "This pack doesn’t contribute any items.",
  loadError: "Could not load extensions.",
  projectRequired: "Choose a project to load its extensions.",
  actionError: "Could not update extensions.",
  actionErrorReload: "Reload extensions",
  deviceBanner: "Changes are saved on this device.",
  projectDesiredPath: overlayRel("extensions.yaml"),
  deviceDesiredPath: "extensions.yaml (device)",
  sourceOfTruth: "Source of truth",
  desiredHint:
    "This file is what the app actually reads. Disabling a pack or item removes it. Selecting a winning pack resolves conflicts. Profiles write to this file, and applying the same profile twice changes nothing.",
  projectDesiredHint:
    "Packs this project suggests, and units it has turned off. Installing happens on the device.",
  updatePack: "Update",
  confirmUpdate: "Confirm update",
  upToDate: "Up to date",
  reloadFromDisk: "Reload from disk",
  version: "Version",
  installationState: "Install mode",
  extensionApi: "Extension API",
  revision: "Revision",
  integrity: "Integrity",
  dependencies: "Dependencies",
  diagnosticsHeading: "Diagnostics",
  chipLinkedFolder: "Linked folder",
  chipGit: "Git",
  remove: "Remove",
  removeDisabledStock: "Built-in and transitive packages are removed with their direct parent",
  providesHeading: "Provides",
  needsScannerTitle: "Needs scanners",
  needsScannerHint: `Enable these scanners in Settings → ${SECURITY_SCANNERS_SECTION_LABEL} before this pack can run.`,
  scannerSettingsLink: `Open ${SECURITY_SCANNERS_SECTION_LABEL}`,
  packNeedsReloadTitle: "Disk changed",
  packNeedsReloadHint:
    "This folder changed since it was last locked. Reload from disk to record the new files.",
  packInvalidTitle: "This pack has an error",
  packInvalidHint: "It is not in effect. Other packs are unchanged.",
  packIntegrityTitle: "Files no longer match",
  packIntegrityHint:
    "Installed files no longer match the lock. Remove the pack and install it again.",
  disable: "Disable",
  deviceControlledUnit: "Manage this item in Settings → Extensions on this device.",
  reEnable: "Re-enable",
  clearSelection: "Clear choice",
  selectionPrefix: "Use",
  resolution: "How it resolves",
  contributionsPane: "From packs",
  effectivePane: "In effect",
  conflictEffective:
    "Two packs provide this item. Choose one, or it stays inactive.",
  disabledEffective: "Disabled — not in the active set.",
  addDialogTitle: "Install pack from Git",
  addDialogBody:
    "Installs the newest release matching a version range, or an exact ref pin. Dependencies are resolved and integrity-locked with it.",
  addUrlLabel: "Repository URL",
  addVersionLabel: "Version range (optional)",
  addRefLabel: "Ref (exact pin, optional)",
  versionOrRef: "Choose a version range or an exact ref, not both.",
  addCancel: "Cancel",
  addInstall: "Install",
  addUrlRequired: "Repository URL is required.",
  folderDialogTitle: "Install pack from folder",
  folderDialogBody:
    "Links a local folder that contains extension.yaml. Edits on disk apply after Reload from disk — no special app build required.",
  folderPathLabel: "Folder",
  folderBrowse: "Choose folder…",
  folderInstall: "Install",
  folderPathRequired: "Choose a folder that contains extension.yaml.",
  authorLoopBlurb:
    "Authors can link a local folder and reload after edits — no special app build required.",
  profileDialogTitle: "Apply profile",
  profileDialogBody:
    "Applies the profile’s preferences. Other packs stay as they are.",
  profilePackLabel: "Pack",
  profileNameLabel: "Profile",
  profileApplyDevice: "Apply on this device",
  profileCancel: "Cancel",
  profileNameRequired: "Enter a profile name.",
  profilePackRequired: "Choose a pack that has a profile.",
  kindAll: "All",
  kindGuidance: "Guidance",
  kindPolicy: "Policy",
  kindWorkflows: "Workflows",
  kindAgents: "Agents",
  kindSkill: "Skill",
  searchPlaceholder: "Search…",
  winnerLabel: "Winner",
  contributionLabel: "Contribution",
  effectiveBlocked: "Blocked",
  effectiveDisabled: "Disabled",
  effectiveDisabledDetail: "disabled in config",
  effectiveConflictDetail: "Choose a pack to continue.",

  modelIntroTitle: "What are Extensions?",
  modelIntro:
    "Extensions are packs of workflows, guidance, and policy. The app ships built-in stock packs. You can install more from Git and tune what’s active per project.",
  modelWhereTitle: "Where you manage them",
  modelWhereBullets: [
    "Settings → Extensions — install packs and set device defaults.",
    "Context → Extensions — inspect active units and turn them off for the project.",
  ],
  modelActiveTitle: "What’s “active”?",
  modelActive:
    "Active items are the workflows, guidance, and rules currently in effect. If two packs offer the same item, pick which one wins — or the item stays inactive until you choose.",
  platformDisableWarn:
    "Disabling Platform removes host primitives. Continue only if you know what you are doing.",
  securityDisableWarn:
    "Disabling Security removes security policy packs. Continue only if you know what you are doing.",

  notAppliedFromProject: "Not applied from this project",
} as const;
