[package]
name = "document-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "document_core"
path = "src/lib.rs"

[[bin]]
name = "pw-document-core"
path = "src/main.rs"

[dependencies]
yrs = "=0.27.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.23"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
overflow-checks = true
debug-assertions = true
strip = true
