// Command codegen-client-notices emits notice bindings from the notice catalogs.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/lycaon/lycaon/internal/clientnotice"
	"github.com/lycaon/lycaon/internal/usernotice"
)

func main() {
	outTS := flag.String("out-ts", "", "output path for client-notices.generated.ts")
	outGo := flag.String("out-go", "", "output path for notice_codes.generated.go")
	outOpenAPI := flag.String("out-openapi", "", "output path for notice-code.generated.yaml")
	userNoticesDir := flag.String("user-notices-dir", "", "host user-notices directory")
	check := flag.Bool("check", false, "exit 1 if the output is stale")
	flag.Parse()

	if *outTS == "" || *outGo == "" || *outOpenAPI == "" || *userNoticesDir == "" {
		fatal(fmt.Errorf("--out-ts, --out-go, --out-openapi, and --user-notices-dir are required"))
	}
	cat, err := clientnotice.Load()
	if err != nil {
		fatal(err)
	}

	body := renderTypeScript(cat)
	userNotices, err := usernotice.LoadNoticeDir(*userNoticesDir)
	if err != nil {
		fatal(err)
	}
	codes := usernotice.HostErrorCodes(userNotices)
	goBody, err := renderNoticeGo(codes)
	if err != nil {
		fatal(err)
	}
	if *check {
		for path, expected := range map[string]string{*outTS: body, *outGo: string(goBody), *outOpenAPI: renderNoticeOpenAPI(codes)} {
			// #nosec G304 -- output paths are explicit command inputs.
			current, err := os.ReadFile(path)
			if err != nil || string(current) != expected {
				fatal(fmt.Errorf("%s is stale — run ./task codegen:client-notices", path))
			}
		}
		return
	}
	if err := os.WriteFile(*outTS, []byte(body), 0o600); err != nil {
		fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(*outGo), 0o750); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outGo, goBody, 0o600); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outOpenAPI, []byte(renderNoticeOpenAPI(codes)), 0o600); err != nil {
		fatal(err)
	}
}

func renderNoticeOpenAPI(codes []string) string {
	var b strings.Builder
	b.WriteString("# Code generated by codegen-client-notices. DO NOT EDIT.\ncomponents:\n  schemas:\n    NoticeCode:\n      type: string\n      enum:\n")
	for _, code := range codes {
		fmt.Fprintf(&b, "        - %s\n", code)
	}
	return b.String()
}

func renderNoticeGo(codes []string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by codegen-client-notices. DO NOT EDIT.\n\npackage api\n\nconst (\n")
	for _, code := range codes {
		fmt.Fprintf(&b, "\tNoticeCode%s NoticeCode = %q\n", goNoticeName(code), code)
	}
	b.WriteString(")\n\n// NewSessionHostError constructs a typed host notice.\n")
	b.WriteString("func NewSessionHostError(code NoticeCode) SessionHostError { return SessionHostError{Code: code} }\n")
	return format.Source([]byte(b.String()))
}

func goNoticeName(code string) string {
	var out strings.Builder
	for _, part := range strings.FieldsFunc(strings.ToLower(code), func(r rune) bool { return r < 'a' || r > 'z' }) {
		if part != "" {
			out.WriteString(strings.ToUpper(part[:1]))
			out.WriteString(part[1:])
		}
	}
	return out.String()
}

func renderTypeScript(cat *clientnotice.Catalog) string {
	var b strings.Builder
	b.WriteString(`// Code generated by codegen-client-notices. DO NOT EDIT.
//
// Source: config/packs/painted-wolf/platform/host/client-notices/
// Regenerate: ./task codegen:client-notices

export type ClientNoticeScope = "app" | "project" | "session";

export type ClientNoticeCopy = {
  readonly title: string;
  readonly message: string;
  readonly suggestedAction?: string;
  /** Structured in-app destination, when the remedy has one. */
  readonly action?: ClientNoticeAction;
  readonly scope: ClientNoticeScope;
};

export type ClientNoticeAction = "retry_contribution_frame";

`)
	b.WriteString("export type ClientNoticeKind =\n")
	for index, n := range cat.Notices {
		suffix := ""
		if index == len(cat.Notices)-1 {
			suffix = ";"
		}
		b.WriteString("  | " + tsString(n.Kind) + suffix + "\n")
	}
	b.WriteString("\nexport const CLIENT_NOTICES: Readonly<Record<ClientNoticeKind, ClientNoticeCopy>> = {\n")
	for _, n := range cat.Notices {
		b.WriteString("  " + n.Kind + ": {\n")
		b.WriteString("    title: " + tsString(n.Title) + ",\n")
		b.WriteString("    message: " + tsString(n.Message) + ",\n")
		if strings.TrimSpace(n.SuggestedAction) != "" {
			b.WriteString("    suggestedAction: " + tsString(n.SuggestedAction) + ",\n")
		}
		if strings.TrimSpace(n.Action) != "" {
			b.WriteString("    action: " + tsString(n.Action) + ",\n")
		}
		b.WriteString("    scope: " + tsString(string(n.Scope)) + ",\n")
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")
	return b.String()
}

func tsString(s string) string {
	flat := strings.Join(strings.Fields(strings.TrimSpace(s)), " ")
	esc := strings.ReplaceAll(flat, `\`, `\\`)
	esc = strings.ReplaceAll(esc, `"`, `\"`)
	return `"` + esc + `"`
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "codegen-client-notices: %v\n", err)
	os.Exit(1)
}
