// Command codegen-contribution-facts emits the Den fact vocabulary and the
// reserved-chord tables from the contribution schema, so the host compiler and
// Den close over one fact set and one reservation set.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/lycaon/lycaon/internal/contribution"
)

func main() {
	outTS := flag.String("out-ts", "", "output path for contribution-facts.generated.ts")
	outReservedTS := flag.String("out-reserved-ts", "", "output path for reserved-chords.generated.ts")
	check := flag.Bool("check", false, "exit 1 if an output is stale")
	flag.Parse()

	if *outTS == "" || *outReservedTS == "" {
		fatal(fmt.Errorf("--out-ts and --out-reserved-ts are required"))
	}
	outputs := []struct {
		path string
		body []byte
	}{
		{*outTS, renderTypeScript(contribution.Facts())},
		{*outReservedTS, renderReservedChords(contribution.OSInterceptedChords(), contribution.AssistiveReservedKeys())},
	}
	for _, output := range outputs {
		if *check {
			existing, err := os.ReadFile(output.path) // #nosec G304 -- path from Taskfile
			if err != nil || !bytes.Equal(existing, output.body) {
				fatal(fmt.Errorf("stale %s — run ./task codegen:contribution-facts", output.path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(output.path), 0o750); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(output.path, output.body, 0o600); err != nil {
			fatal(err)
		}
	}
}

func renderTypeScript(facts map[string]contribution.FactSpec) []byte {
	ids := make([]string, 0, len(facts))
	for id := range facts {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var b bytes.Buffer
	b.WriteString("// Generated by codegen-contribution-facts from the Go contribution\n")
	b.WriteString("// condition schema. Do not edit; run ./task codegen:contribution-facts.\n\n")
	b.WriteString("export type FactPlane = \"host\" | \"shell\";\n\n")
	b.WriteString("export type ContributionFactId =\n")
	for i, id := range ids {
		terminator := "\n"
		if i == len(ids)-1 {
			terminator = ";\n"
		}
		fmt.Fprintf(&b, "  | %q%s", id, terminator)
	}
	b.WriteString("\nexport type ContributionFactSpec = {\n")
	b.WriteString("  plane: FactPlane;\n")
	b.WriteString("  operand: string | null;\n")
	b.WriteString("};\n\n")
	b.WriteString("export const CONTRIBUTION_FACTS: Record<ContributionFactId, ContributionFactSpec> = {\n")
	for _, id := range ids {
		spec := facts[id]
		operand := "null"
		if spec.Operand != contribution.OperandNone {
			operand = fmt.Sprintf("%q", string(spec.Operand))
		}
		fmt.Fprintf(&b, "  %q: { plane: %q, operand: %s },\n", id, string(spec.Plane), operand)
	}
	b.WriteString("};\n")
	return b.Bytes()
}

func renderReservedChords(osIntercepted map[string][]string, assistive []string) []byte {
	platforms := make([]string, 0, len(osIntercepted))
	for platform := range osIntercepted {
		platforms = append(platforms, platform)
	}
	sort.Strings(platforms)

	var b bytes.Buffer
	b.WriteString("// Generated by codegen-contribution-facts from the Go contribution\n")
	b.WriteString("// vocabulary. Do not edit; run ./task codegen:contribution-facts.\n\n")
	b.WriteString("/** Chords each platform consumes before an app window sees them; \"+*\" covers every chord holding the listed modifiers. */\n")
	b.WriteString("export const OS_INTERCEPTED_CHORDS: Readonly<Record<")
	for i, platform := range platforms {
		if i > 0 {
			b.WriteString(" | ")
		}
		fmt.Fprintf(&b, "%q", platform)
	}
	b.WriteString(", readonly string[]>> = {\n")
	for _, platform := range platforms {
		fmt.Fprintf(&b, "  %s: [\n", platform)
		for _, spec := range osIntercepted[platform] {
			fmt.Fprintf(&b, "    %q,\n", spec)
		}
		b.WriteString("  ],\n")
	}
	b.WriteString("};\n\n")
	b.WriteString("/** Keys reserved for assistive navigation on every platform. */\n")
	b.WriteString("export const ASSISTIVE_RESERVED_KEYS: readonly string[] = [\n")
	for _, key := range assistive {
		fmt.Fprintf(&b, "  %q,\n", key)
	}
	b.WriteString("];\n")
	return b.Bytes()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "codegen-contribution-facts:", err)
	os.Exit(1)
}
