#!/usr/bin/env bash
# Vendor a verified OAR source bundle; --check also works without its source checkout.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python3 - "$REPO_ROOT" "$@" <<'PYTHON'
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import sys

root = Path(sys.argv[1])
parser = argparse.ArgumentParser(description="Vendor verified OAR 1.0 schemas and conformance fixtures")
parser.add_argument("--source", type=Path)
parser.add_argument("--check", action="store_true")
args = parser.parse_args(sys.argv[2:])
source = args.source or Path(os.environ.get("OAR_SPEC_DIR") or
    str(Path(os.environ.get("OAR_STANDARD_DIR", root.parent / "open-agent-rules")) / "spec/oar/1.0"))
dest = root / "schemas/oar"
release_name = "release-manifest.json"
vendor_name = "vendor-manifest.json"


def sha(data):
    return hashlib.sha256(data).hexdigest()


def release(directory):
    raw = (directory / release_name).read_bytes()
    doc = json.loads(raw)
    if doc["oar_release_version"] != "1.0":
        raise ValueError("unsupported OAR source version")
    identity = sha(json.dumps(doc["files"], sort_keys=True, separators=(",", ":")).encode())
    if identity != doc["content_sha256"]:
        raise ValueError("OAR release content identity does not match its file manifest")
    for name, digest in doc["files"].items():
        path = Path(name)
        if path.is_absolute() or ".." in path.parts or len(digest) != 64:
            raise ValueError("invalid OAR release source entry")
    return raw, doc


def selected_files(doc):
    files = {}
    for name, digest in doc["files"].items():
        if name.startswith("schemas/") or name == "vocabulary.yaml" or name == "LICENSE" or name.startswith("conformance/"):
            target = name if name.startswith("conformance/") else Path(name).name
            if target in files:
                raise ValueError("OAR source paths collide after vendoring")
            files[target] = {"sha256": digest, "source": name}
    return files


def expected_vendor(raw, doc):
    files = selected_files(doc)
    files[release_name] = {"sha256": sha(raw), "source": release_name}
    return {
        "_": "Generated by scripts/vendor-oar-spec.sh from a verified versioned OAR source bundle.",
        "oar_version": "1.0",
        "upstream": "https://openagentrules.org/spec/1.0/",
        "source": "https://openagentrules.org/spec/1.0/release-manifest.json",
        "oar_content_sha256": doc["content_sha256"],
        "corpus_fixtures": len([name for name in files if name.startswith("conformance/") and Path(name).name not in ("manifest.json", "exempt.json")]),
        "files": dict(sorted(files.items())),
    }


def verify_sources(directory, doc):
    actual = {}
    for path in directory.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"source symlink: {path}")
        if path.is_file() and path.name != ".DS_Store" and path != directory / release_name:
            actual[path.relative_to(directory).as_posix()] = sha(path.read_bytes())
    if actual != doc["files"]:
        raise ValueError("OAR source bundle differs from its release manifest; refresh the draft manifest in the standard repository")


try:
    if not args.check:
        raw, doc = release(source)
        verify_sources(source, doc)
        expected = expected_vendor(raw, doc)
        previous = json.loads((dest / vendor_name).read_text()) if (dest / vendor_name).exists() else {"files": {}}
        for name in previous["files"]:
            path = Path(name)
            if path.is_absolute() or ".." in path.parts:
                raise ValueError("invalid existing vendor manifest path")
        for name, entry in expected["files"].items():
            path = dest / name
            path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source / entry["source"], path)
        for name in set(previous["files"]) - set(expected["files"]):
            (dest / name).unlink(missing_ok=True)
        (dest / vendor_name).write_text(json.dumps(expected, indent=2) + "\n")
    raw, doc = release(dest)
    expected = expected_vendor(raw, doc)
    if json.loads((dest / vendor_name).read_text()) != expected:
        raise ValueError("vendor manifest differs from the pinned OAR source release")
    actual_names = set()
    for path in dest.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"vendored symlink: {path}")
        if path.is_file() and path.name not in (".DS_Store", "VENDORED.md") and path != dest / vendor_name:
            actual_names.add(path.relative_to(dest).as_posix())
    if actual_names != set(expected["files"]):
        raise ValueError("vendored file membership differs from the OAR release pin")
    for name, entry in expected["files"].items():
        if sha((dest / name).read_bytes()) != entry["sha256"]:
            raise ValueError(f"vendored OAR artifact changed: {name}")
    if source.is_dir():
        source_raw, source_doc = release(source)
        verify_sources(source, source_doc)
        if source_raw != raw:
            raise ValueError("vendored OAR release is behind the source; run ./task oar:vendor")
    print(f"ok: {expected['corpus_fixtures']} fixtures and supporting artifacts match OAR 1.0 content {doc['content_sha256']}")
except (ValueError, OSError, KeyError) as error:
    raise SystemExit(f"vendor-oar-spec: {error}") from error
PYTHON
