id: bittrex-api-secret
title: Bittrex API secret
regex: '(?i)\bbittrex_(?:api_)?secret(?:_key)?\b[''" ]*[:=][ ''"]*([a-z0-9]{32})\b'
keywords:
  - bittrex_secret
  - bittrex_api_secret
severity: critical
secret_group: 1
entropy: 3.5
