id: mixpanel-api-secret
title: Mixpanel API secret
regex: '(?i)\bmixpanel_(?:api_)?secret\b[''" ]*[:=][ ''"]*([a-f0-9]{32})\b'
keywords:
  - mixpanel_secret
  - mixpanel_api_secret
severity: critical
secret_group: 1
entropy: 3.5
