package sourceview

import (
	"strings"
	"testing"

	"github.com/lycaon/lycaon/internal/testutil"
)

func TestCompactProjectionMapsMultipleScripts(t *testing.T) {
	source := []byte("<p>狼</p>\r\n<script>let value = location.hash;</script>\r\n<div>unrelated</div>\r\n<script>eval(value);</script>")
	projected, _, err := Scripts(t.Context(), source, false)
	testutil.FailErr(t, "project document scopes", err)
	if len(projected) != 1 {
		t.Fatalf("scopes=%d", len(projected))
	}
	for _, tc := range []struct{ start, end, wantStart, wantEnd Position }{
		{Position{1, 1}, Position{1, 26}, Position{2, 9}, Position{2, 34}},
		{Position{3, 1}, Position{3, 13}, Position{4, 9}, Position{4, 21}},
	} {
		start, end, ok := projected[0].Map.MapSpan(tc.start, tc.end)
		if !ok || start != tc.wantStart || end != tc.wantEnd {
			t.Fatalf("mapped=%+v..%+v valid=%v want=%+v..%+v", start, end, ok, tc.wantStart, tc.wantEnd)
		}
	}
	for _, point := range []Position{{0, 1}, {1, 0}, {1, 999}, {2, 1}, {4, 1}} {
		if _, _, ok := projected[0].Map.MapSpan(point, point); ok {
			t.Fatalf("invented source for invalid or synthetic point %+v", point)
		}
	}
}

func TestCompactProjectionKeepsUTF8AndCRLFByteCoordinates(t *testing.T) {
	projected, _, err := Scripts(t.Context(), []byte("<script>const x = '狼';\r\neval(x);</script>"), false)
	testutil.FailErr(t, "project UTF-8", err)
	start, end, ok := projected[0].Map.MapSpan(Position{1, 12}, Position{2, 9})
	if !ok || start != (Position{1, 20}) || end != (Position{2, 9}) {
		t.Fatalf("UTF-8 mapping %+v..%+v valid=%v", start, end, ok)
	}
	eof, ok := projected[0].Map.MapPosition(Position{2, 9})
	if !ok || eof != (Position{2, 9}) {
		t.Fatalf("EOF mapping=%+v valid=%v", eof, ok)
	}
}

func TestManyModulesProduceLinearSourceOutput(t *testing.T) {
	const count = 1000
	projected, _, err := Scripts(t.Context(), []byte(strings.Repeat("<script type=module>const value = 1;</script>\n", count)), false)
	testutil.FailErr(t, "project many modules", err)
	total := 0
	for _, projection := range projected {
		total += len(projection.Source)
	}
	if len(projected) != count || total != count*len("const value = 1;") {
		t.Fatalf("module count=%d generated bytes=%d", len(projected), total)
	}
}
