// Command codegen-theme-tokens generates theme artifacts from stock units.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/lycaon/lycaon/internal/contribution"
	"github.com/lycaon/lycaon/internal/theme"
)

const stockPackID = "painted-wolf/platform"

const themesRel = "config/packs/painted-wolf/platform/contributions/themes"

// packThemesRel contains reference themes excluded from the startup stylesheet.
const packThemesRel = "config/packs/painted-wolf/themes/contributions/themes"

// stockAppearanceThemes names each scheme's cold-start theme.
var stockAppearanceThemes = map[theme.Appearance]string{
	theme.AppearanceLight: stockPackID + ":daylight",
	theme.AppearanceDark:  stockPackID + ":charcoal",
}

// #nosec G101 -- these are generated output paths.
var generatedRel = map[string]string{
	"tokens":     "../lycaon-den/src/tokens.generated.css",
	"highlight":  "../lycaon-den/src/components/source/editor/codemirror-highlight.generated.ts",
	"schema":     "../docs/schemas/theme-unit.schema.json",
	"vocabulary": "../lycaon-den/src/contributions/theme-vocabulary.generated.ts",
	"reference":  "../docs/theme-tokens.md",
}

func main() {
	root := flag.String("root", ".", "repo-relative Go module root")
	check := flag.Bool("check", false, "fail when generated output is stale")
	flag.Parse()

	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, "codegen-theme-tokens:", err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	compiled, err := loadThemes(filepath.Join(root, themesRel))
	if err != nil {
		return err
	}
	for appearance, id := range stockAppearanceThemes {
		if _, ok := compiled[id]; !ok {
			return fmt.Errorf("stock %s theme %s is missing", appearance, id)
		}
	}
	packThemes, err := loadThemes(filepath.Join(root, packThemesRel))
	if err != nil {
		return err
	}

	schema, err := authorSchema()
	if err != nil {
		return err
	}
	outputs := map[string][]byte{
		"tokens":     tokensStylesheet(compiled),
		"highlight":  highlightStyle(),
		"schema":     schema,
		"vocabulary": vocabularyModule(),
		"reference":  tokenReference(compiled, packThemes),
	}
	for key, body := range outputs {
		path := filepath.Join(root, generatedRel[key])
		if check {
			current, err := os.ReadFile(path) // #nosec G304 -- generated path from the Taskfile
			if err != nil {
				return fmt.Errorf("read %s: %w", path, err)
			}
			if !bytes.Equal(current, body) {
				return fmt.Errorf("%s is stale; run ./task codegen:theme-tokens", path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, body, 0o600); err != nil { // #nosec G306 -- generated artifact
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func loadThemes(dir string) (map[string]theme.Compiled, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}
	out := map[string]theme.Compiled{}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		body, err := os.ReadFile(path) // #nosec G304 -- bundled pack path from the Taskfile
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		decl, err := contribution.DecodeTheme(body)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		c, err := decl.Compiled()
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		out[c.ID] = c
	}
	return out, nil
}

// tokensStylesheet generates the cold-start base plane.
func tokensStylesheet(compiled map[string]theme.Compiled) []byte {
	var b bytes.Buffer
	b.WriteString("/* Generated by cmd/codegen-theme-tokens. Do not edit by hand.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Stock base tokens paint before theme hydration.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Edit the stock theme units under\n")
	b.WriteString(" * config/packs/painted-wolf/platform/contributions/themes/ instead.\n")
	b.WriteString(" */\n\n")

	light := compiled[stockAppearanceThemes[theme.AppearanceLight]]
	dark := compiled[stockAppearanceThemes[theme.AppearanceDark]]

	b.WriteString(":root {\n")
	b.WriteString("  color-scheme: light dark;\n")
	writeTokenBlock(&b, light, "  ")
	b.WriteString("}\n\n")

	b.WriteString("/* System scheme before the shell stamps an explicit appearance. */\n")
	b.WriteString("@media (prefers-color-scheme: dark) {\n")
	b.WriteString("  :root:not([data-den-appearance]) {\n")
	writeTokenBlock(&b, dark, "    ")
	b.WriteString("  }\n}\n\n")

	b.WriteString(":root[data-den-appearance=\"light\"] {\n  color-scheme: light;\n")
	writeTokenBlock(&b, light, "  ")
	b.WriteString("}\n\n")

	b.WriteString("/* Explicit mode overrides the system media query. */\n")
	b.WriteString(":root[data-den-appearance=\"dark\"] {\n  color-scheme: dark;\n")
	writeTokenBlock(&b, dark, "  ")
	b.WriteString("}\n")
	return b.Bytes()
}

func writeTokenBlock(b *bytes.Buffer, c theme.Compiled, indent string) {
	anchors := make([]string, 0, len(c.WindowColors.Anchors))
	for _, anchor := range c.WindowColors.Anchors {
		anchors = append(anchors, anchor.String())
	}
	fmt.Fprintf(b, "%s--den-window-color-main: %s;\n%s--den-window-color-anchors: %s;\n%s--den-window-color-hue-spread: %g;\n%s--den-window-color-chroma-min: %g;\n%s--den-window-color-chroma-max: %g;\n", indent, c.WindowColors.Main.String(), indent, strings.Join(anchors, " "), indent, c.WindowColors.HueSpread, indent, c.WindowColors.ChromaMin, indent, c.WindowColors.ChromaMax)
	fmt.Fprintf(b, "%s--den-agent-color-main: %s;\n%s--den-agent-color-lightness-step: %g;\n%s--den-agent-color-chroma: %g;\n", indent, c.AgentColors.Main.String(), indent, c.AgentColors.LightnessStep, indent, c.AgentColors.Chroma)

	for _, tok := range theme.BaseTokens() {
		fmt.Fprintf(b, "%s%s: %s;\n", indent, tok.CSSVar, c.Tokens[tok.ID].String())
	}
	for _, scope := range theme.SyntaxScopes() {
		if scope.StyleOnly {
			continue
		}
		fmt.Fprintf(b, "%s%s: %s;\n", indent, scope.CSSVar, c.Syntax[scope.ID].Color.String())
	}
}

// highlightStyle generates the editor style from the scope vocabulary.
func highlightStyle() []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by cmd/codegen-theme-tokens. Do not edit by hand.\n//\n")
	b.WriteString("// Child scopes follow parents because later entries win.\n")
	b.WriteString("// Paint and style flags resolve through theme properties.\n\n")
	b.WriteString(`import { HighlightStyle } from "@codemirror/language";` + "\n")
	b.WriteString(`import { tags as t } from "@lezer/highlight";` + "\n\n")
	b.WriteString("export const denHighlightStyle = HighlightStyle.define([\n")

	// Later entries win, so specific child scopes follow their parents.
	scopes := theme.SyntaxScopes()
	sort.SliceStable(scopes, func(i, j int) bool {
		return strings.Count(scopes[i].ID, ".") < strings.Count(scopes[j].ID, ".")
	})
	for _, scope := range scopes {
		tags := make([]string, 0, len(scope.Tags))
		for _, tag := range scope.Tags {
			tags = append(tags, qualifyTag(tag))
		}
		fmt.Fprintf(&b, "  {\n    tag: [%s],\n", strings.Join(tags, ", "))
		// Style-only scopes preserve the wrapped color.
		if !scope.StyleOnly {
			fmt.Fprintf(&b, "    color: \"var(%s)\",\n", scope.CSSVar)
		}
		fmt.Fprintf(&b, "    fontStyle: \"var(%s-style, normal)\",\n", scope.CSSVar)
		fmt.Fprintf(&b, "    fontWeight: \"var(%s-weight, inherit)\",\n", scope.CSSVar)
		fmt.Fprintf(&b, "    textDecoration: \"var(%s-decoration, none)\",\n", scope.CSSVar)
		b.WriteString("  },\n")
	}
	b.WriteString("]);\n")
	return b.Bytes()
}

// tokenSchema returns base-token properties and required ids.
func tokenSchema() (map[string]any, []string) {
	props := map[string]any{}
	var required []string
	for _, tok := range theme.BaseTokens() {
		if tok.Fill == theme.FillBevel || tok.Fill == theme.FillChange {
			continue
		}
		desc := tok.Description
		if tok.Opaque {
			desc += " Must be opaque."
		}
		if tok.Fill == theme.FillDerived {
			desc += " Optional: derived from other tokens when unset."
		} else {
			required = append(required, tok.ID)
		}
		props[tok.ID] = map[string]any{
			"type":        "string",
			"description": desc,
			"pattern":     colorPattern,
		}
	}
	sort.Strings(required)
	return props, required
}

// syntaxSchema returns the per-scope author schema.
func syntaxSchema() map[string]any {
	styleEntry := map[string]any{
		"oneOf": []any{
			map[string]any{
				"type":    "string",
				"pattern": colorPattern,
			},
			map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"required":             []string{"color"},
				"properties": map[string]any{
					"color": map[string]any{
						"type":    "string",
						"pattern": colorPattern,
					},
					"italic":    map[string]any{"type": "boolean"},
					"bold":      map[string]any{"type": "boolean"},
					"underline": map[string]any{"type": "boolean"},
				},
			},
		},
	}
	props := map[string]any{}
	for _, scope := range theme.SyntaxScopes() {
		desc := scope.Description
		if scope.Parent != "" {
			desc += fmt.Sprintf(" Folds to %s when unset.", scope.Parent)
		}
		entry := map[string]any{"description": desc}
		for k, v := range styleEntry {
			entry[k] = v
		}
		props[scope.ID] = entry
	}
	return props
}

// iconSchema returns stroke treatment and per-slot geometry.
func iconSchema() map[string]any {
	geometryProps := map[string]any{}
	for _, slot := range theme.IconSlots() {
		geometryProps[slot.ID] = map[string]any{
			"type": "string",
			"description": fmt.Sprintf("%s (%s group, %s). SVG child geometry on the %s grid, one color.",
				slot.Description, slot.Group, slot.Paint, theme.IconViewBox),
		}
	}
	return map[string]any{
		"stroke": map[string]any{
			"type":                 "object",
			"additionalProperties": false,
			"description": "The theme's handwriting, applied to every stroked " +
				"glyph — including the ones it never redraws. This is how a family " +
				"gets one hand across the whole product without authoring every slot.",
			"properties": map[string]any{
				"weight": map[string]any{
					"type": "number", "minimum": 0.5, "maximum": 2.0,
					"description": "Multiplier on each slot's host-defined width. 1 leaves the product's drawing alone.",
				},
				"cap":  map[string]any{"type": "string", "enum": theme.IconCaps()},
				"join": map[string]any{"type": "string", "enum": theme.IconJoins()},
			},
		},
		"geometry": map[string]any{
			"type":                 "object",
			"additionalProperties": false,
			"description":          "Per-slot glyph replacement. Partial: an unset slot keeps the host glyph.",
			"properties":           geometryProps,
		},
	}
}

// brandSchema limits themes to logomark visibility.
func brandSchema() map[string]any {
	visibilities := make([]string, 0)
	for _, v := range theme.LogomarkVisibilities() {
		visibilities = append(visibilities, string(v))
	}
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"description": "What a theme may say about product identity. One key, " +
			"and it carries a visibility rather than artwork: a theme may quiet " +
			"the product logomark and can never substitute one.",
		"properties": map[string]any{
			"logomark": map[string]any{
				"type": "string",
				"enum": visibilities,
				"description": "Whether the product logomark paints. Hiding " +
					"reserves its box, so a theme swap never relayouts the window.",
			},
		},
	}
}

// bevelSchema limits the bevel surface to one strength.
func bevelSchema() map[string]any {
	minimum, maximum := theme.BevelStrengthRange()
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"description": "How strongly raised and recessed controls show their " +
			"edges. The host derives every edge's color; a theme sets only " +
			"their strength.",
		"properties": map[string]any{
			"strength": map[string]any{
				"type": "number", "minimum": minimum, "maximum": maximum,
				"description": fmt.Sprintf("Multiplier on every edge's alpha. 1 keeps "+
					"the product's edges, %g flattens every control, %g doubles them.",
					minimum, maximum),
			},
		},
	}
}

// colorPattern admits literal six- or eight-digit hex colors.
const colorPattern = "^#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"

// authorSchema generates the theme unit schema.
func authorSchema() ([]byte, error) {
	tokenProps, required := tokenSchema()
	appearances := make([]string, 0)
	for _, a := range theme.Appearances() {
		appearances = append(appearances, string(a))
	}

	schema := map[string]any{
		"$schema":              "https://json-schema.org/draft/2020-12/schema",
		"title":                "Painted Wolf Code theme unit",
		"description":          "A theme assigns literal colors to host-defined token ids.",
		"type":                 "object",
		"additionalProperties": false,
		"required":             []string{"id", "name", "appearance", "tokens"},
		"properties": map[string]any{
			"id":   map[string]any{"type": "string", "description": "Contribution id: provider:name."},
			"name": map[string]any{"type": "string", "description": "Display name in Settings."},
			"appearance": map[string]any{
				"type":        "string",
				"enum":        appearances,
				"description": "Which scheme this theme implements.",
			},
			"tokens": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"required":             required,
				"properties":           tokenProps,
			},
			"syntax": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"properties":           syntaxSchema(),
			},
			"brand":         brandSchema(),
			"bevel":         bevelSchema(),
			"window_colors": windowColorsSchema(),
			"agent_colors":  agentColorsSchema(),
			"icons": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"description": "The glyph surface: a theme-wide stroke treatment " +
					"plus per-slot geometry. The frame — grid, size, paint, and " +
					"each slot's base weight — stays the host's.",
				"properties": iconSchema(),
			},
		},
	}
	body, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(body, '\n'), nil
}

// tokenReference generates the author reference.
func tokenReference(stock, pack map[string]theme.Compiled) []byte {
	var b bytes.Buffer
	b.WriteString("<!-- Generated by cmd/codegen-theme-tokens. Do not edit by hand. -->\n\n")
	b.WriteString("# Theme token reference\n\n")
	b.WriteString("The complete vocabulary. A theme assigns literal colors ")
	b.WriteString("(`#rrggbb` or `#rrggbbaa`) to the required and derived-by-default ids ")
	b.WriteString("and nothing else. The host draws every `bevel-edge` itself; a theme sets ")
	b.WriteString("only their strength — see [Bevel](#bevel). It fits every `change-fill` ")
	b.WriteString("too; a theme sets only the diff hues — see [Change fills](#change-fills).\n\n")
	b.WriteString("Authoring guide: [`extend.md`](extend.md#themes).\n\n")

	writeBundledThemes(&b, stock, pack)
	b.WriteString(windowColorsReference())
	b.WriteString(agentColorsReference())

	b.WriteString("## Base tokens\n\n")
	b.WriteString("Required tokens are the decisions no derivation can make for you. ")
	b.WriteString("Everything else has a host derivation, so a token added later never ")
	b.WriteString("invalidates an existing theme.\n\n")
	b.WriteString("| Token | Fill | Description |\n|-------|------|-------------|\n")
	for _, tok := range theme.BaseTokens() {
		desc := tok.Description
		if tok.Opaque {
			desc += " Must be opaque."
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", tok.ID, tok.Fill, desc)
	}

	b.WriteString("\n## Planes\n\n")
	b.WriteString("`background` and `surface-chrome` are the two *planes* — the opaque ")
	b.WriteString("surfaces everything else is painted on.\n\n")
	b.WriteString("Some marks carry no color of their own and take the plane instead, so ")
	b.WriteString("they disappear into it: the wash that fades rows out under the Settings ")
	b.WriteString("dock, the ring cutting the selection dot out of its pill, the ring ")
	b.WriteString("separating stacked folder tiles, a focus halo. The host tracks which ")
	b.WriteString("plane each region paints and resolves those marks against it. Set the ")
	b.WriteString("two planes and the marks follow.\n\n")

	minimum, maximum := theme.BevelStrengthRange()
	b.WriteString("## Bevel\n\n")
	b.WriteString("Raised and recessed controls show a lit edge and a shaded edge, drawn ")
	b.WriteString("in the `bevel-edge` inks above. A theme decides only how strongly they ")
	fmt.Fprintf(&b, "show: `bevel.strength` multiplies every edge's alpha — `1` keeps the "+
		"product's edges, `%g` flattens every control, and `%g` doubles them. An edge "+
		"already at full strength stays there.\n\n", minimum, maximum)
	b.WriteString("```yaml\nbevel:\n  strength: 0.7\n```\n\n")
	b.WriteString("A filled plate — a send button, a checked box — takes a white lit edge ")
	b.WriteString("rather than its label ink, so a pale accent carrying dark text still ")
	b.WriteString("catches light along its top.\n\n")

	b.WriteString(changeFillsReference())

	b.WriteString("## Syntax scopes\n\n")
	b.WriteString("Scopes are flat and apply to every language. An unset scope folds to its parent; ")
	b.WriteString("an unset root falls back to body text. Each entry is a color, or a color ")
	b.WriteString("plus `italic` / `bold` / `underline`.\n\n")
	b.WriteString("| Scope | Folds to | Description |\n|-------|----------|-------------|\n")
	for _, scope := range theme.SyntaxScopes() {
		parent := "body text"
		if scope.Parent != "" {
			parent = "`" + scope.Parent + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", scope.ID, parent, scope.Description)
	}

	b.WriteString("\n## Icon slots\n\n")
	b.WriteString("`icons.stroke` — `weight`, `cap`, `join` — restyles every stroked ")
	b.WriteString("slot at once, including slots with no geometry below. Weight ")
	b.WriteString("is a finite 0.5–2.0 multiplier on each slot's host-defined width; stroke never ")
	b.WriteString("contributes to layout.\n\n")
	b.WriteString("`icons.geometry` replaces one slot with the *children* of an `<svg>` ")
	b.WriteString("on the `")
	b.WriteString(theme.IconViewBox)
	b.WriteString("` grid, drawn in `currentColor` or `none`. Shapes are `path`, ")
	b.WriteString("`circle`, `rect`, `ellipse`, `line`, `polyline`, `polygon`, and `g`; ")
	b.WriteString("path commands, numeric attributes, point lists, and required dimensions are ")
	b.WriteString("parsed against their SVG grammars, and every shape must draw. Anything that ")
	b.WriteString("loads, scripts, styles, or references a resource outside the glyph fails to ")
	b.WriteString("compile. This plane stays partial — a glyph has no ")
	b.WriteString("derivation, so an unset slot keeps the host's.\n\n")
	b.WriteString("The frame is the host's either way: grid, rendered size, paint mode, ")
	b.WriteString("and each slot's base weight.\n\n")
	b.WriteString("| Slot | Description |\n|------|-------------|\n")
	for _, slot := range theme.IconSlots() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", slot.ID, slot.Description)
	}

	b.WriteString("\n## Legibility floor\n\n")
	b.WriteString("Security-critical chrome must not be paintable into invisibility. ")
	b.WriteString("These pairs are measured at compile time; a theme under any minimum ")
	b.WriteString("fails to compile with a typed diagnostic.\n\n")
	b.WriteString("| Foreground | Background | Minimum | Why |\n|------------|------------|---------|-----|\n")
	for _, pair := range theme.LegibilityFloor() {
		fmt.Fprintf(&b, "| `%s` | `%s` | %.1f:1 | %s |\n",
			pair.Foreground, pair.Background, pair.Min, pair.Why)
	}
	return b.Bytes()
}

func writeBundledThemes(b *bytes.Buffer, stock, pack map[string]theme.Compiled) {
	coldStart := map[string]theme.Appearance{}
	for appearance, id := range stockAppearanceThemes {
		coldStart[id] = appearance
	}

	b.WriteString("## Bundled themes\n\n")
	fmt.Fprintf(b, "%d themes ship with the app. The two stock units are the "+
		"cold-start planes — the app paints one of them before any saved choice "+
		"is restored, so neither can be uninstalled. The rest arrive as the "+
		"bundled **Themes** extension pack and sit in the picker beside anything "+
		"a user installs.\n\n", len(stock)+len(pack))
	b.WriteString("| Theme | Id | Appearance | Source |\n")
	b.WriteString("|-------|----|------------|--------|\n")

	writeThemeRows(b, stock, "Stock", coldStart)
	writeThemeRows(b, pack, "Themes pack", nil)
	b.WriteString("\n")
}

func writeThemeRows(b *bytes.Buffer, themes map[string]theme.Compiled, source string, coldStart map[string]theme.Appearance) {
	ids := make([]string, 0, len(themes))
	for id := range themes {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		c := themes[id]
		label := source
		if appearance, ok := coldStart[id]; ok {
			label = fmt.Sprintf("Stock — cold-start %s", appearance)
		}
		fmt.Fprintf(b, "| %s | `%s` | %s | %s |\n", c.Name, c.ID, c.Appearance, label)
	}
}

// vocabularyModule generates rendered token and icon metadata.
func vocabularyModule() []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by cmd/codegen-theme-tokens. Do not edit by hand.\n//\n")
	b.WriteString("// Theme token ids map to rendered custom properties.\n\n")

	b.WriteString("export const THEME_TOKEN_VARS: Readonly<Record<string, string>> = {\n")
	for _, tok := range theme.BaseTokens() {
		fmt.Fprintf(&b, "  %q: %q,\n", tok.ID, tok.CSSVar)
	}
	b.WriteString("};\n\n")

	b.WriteString("export const SYNTAX_SCOPE_VARS: Readonly<Record<string, string>> = {\n")
	for _, scope := range theme.SyntaxScopes() {
		fmt.Fprintf(&b, "  %q: %q,\n", scope.ID, scope.CSSVar)
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Host-defined frame for every glyph. */\n")
	fmt.Fprintf(&b, "export const ICON_VIEWBOX = %q;\n\n", theme.IconViewBox)

	b.WriteString("/** Host-defined paint and weight for every slot. */\n")
	b.WriteString("export const ICON_SLOTS = {\n")
	for _, slot := range theme.IconSlots() {
		fmt.Fprintf(&b, "  %q: { paint: %q, weight: %g },\n",
			slot.ID, slot.Paint, slot.Weight)
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type IconSlot = keyof typeof ICON_SLOTS;\n")
	return b.Bytes()
}

// tagIdentifier matches every bare name in a tag expression.
var tagIdentifier = regexp.MustCompile(`[A-Za-z_][A-Za-z0-9_]*`)

func qualifyTag(tag string) string {
	return tagIdentifier.ReplaceAllString(tag, "t.$0")
}

// changeFillsReference explains how the host fits diff fills to a palette.
func changeFillsReference() string {
	light := theme.ChangeFillShapeFor(theme.AppearanceLight)
	dark := theme.ChangeFillShapeFor(theme.AppearanceDark)
	var b strings.Builder
	b.WriteString("## Change fills\n\n")
	b.WriteString("A diff paints two layers in each hue: a fill behind every changed line, and ")
	b.WriteString("a deeper fill behind the words that changed within it. Code has to stay ")
	b.WriteString("readable on both, in every syntax color the theme sets, so the host fits ")
	b.WriteString("the fills to the palette instead of taking them from the theme.\n\n")
	fmt.Fprintf(&b, "Each ink keeps at least %.1f:1 on a changed word over its line. An ink the ", theme.CodeInkMin)
	fmt.Fprintf(&b, "theme already sets under that on the page keeps %.0f%% of its page ", theme.CodeInkRetention*100)
	b.WriteString("contrast instead. The host lays down as much of each hue as that allows, ")
	b.WriteString("up to a cap, and gives the line a fixed share of it so a changed word ")
	b.WriteString("always reads above its line:\n\n")
	b.WriteString("| Appearance | Cap | Line share |\n|------------|-----|------------|\n")
	fmt.Fprintf(&b, "| light | %.0f%% | %.0f%% |\n", light.Strength*100, light.LineShare*100)
	fmt.Fprintf(&b, "| dark | %.0f%% | %.0f%% |\n\n", dark.Strength*100, dark.LineShare*100)
	b.WriteString("A palette with dim syntax colors gets quieter fills rather than unreadable ")
	b.WriteString("code. To make diffs louder, raise the contrast of the dimmest syntax ")
	b.WriteString("colors; to recolor them, set `diff-add-hue` and `diff-delete-hue`.\n\n")
	return b.String()
}
