// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/ApiErrorCode.yaml

package api

// ApiErrorCode — Closed machine-readable error identity emitted by the private Den-sidecar API.
type ApiErrorCode string

const (
	// ApiErrorCodeSourceViewNotFound The host does not retain this source view,
	// presentation, or interest handle for the caller (never issued, expired,
	// released, evicted, or issued before a restart); reopen it with the same
	// intent.
	ApiErrorCodeSourceViewNotFound ApiErrorCode = "source_view_not_found"
	// ApiErrorCodeSourceViewRevisionChanged Numeric source coordinates or intent
	// refer to an outdated revision.
	ApiErrorCodeSourceViewRevisionChanged ApiErrorCode = "source_view_revision_changed"
	// ApiErrorCodeSourceViewCapacity Pinned source presentations exhausted the
	// bounded retention budget.
	ApiErrorCodeSourceViewCapacity ApiErrorCode = "source_view_capacity"
	// ApiErrorCodeSourceViewFrameTooLarge One source row and its required context
	// exceed the frame byte limit.
	ApiErrorCodeSourceViewFrameTooLarge ApiErrorCode = "source_view_frame_too_large"
	// ApiErrorCodeSourceViewPreparing The source view is still preparing its first
	// projection.
	ApiErrorCodeSourceViewPreparing ApiErrorCode = "source_view_preparing"
	// ApiErrorCodeTrustReviewChanged project roots or the read baseline changed
	// while a trust review was captured
	ApiErrorCodeTrustReviewChanged ApiErrorCode = "trust_review_changed"
	// ApiErrorCodeProjectInventoryUnavailable project contribution discovery could
	// not complete
	ApiErrorCodeProjectInventoryUnavailable ApiErrorCode = "project_inventory_unavailable"
	// ApiErrorCodeSourceAnalysisIncomplete structural analysis exceeded its parser
	// budget; the file remains readable
	ApiErrorCodeSourceAnalysisIncomplete ApiErrorCode = "source_analysis_incomplete"
	// ApiErrorCodeSourceAnalysisUnavailable structural analysis failed; the file
	// remains readable
	ApiErrorCodeSourceAnalysisUnavailable ApiErrorCode = "source_analysis_unavailable"
	// ApiErrorCodeInvalidPageCursor Opaque list cursor is malformed or belongs to
	// a different query scope.
	ApiErrorCodeInvalidPageCursor ApiErrorCode = "invalid_page_cursor"
	// ApiErrorCodeUnsupportedMediaType request body Content-Type is absent,
	// malformed, or unsupported by the endpoint
	ApiErrorCodeUnsupportedMediaType ApiErrorCode = "unsupported_media_type"
	// ApiErrorCodeMethodNotAllowed route exists but does not support the request
	// method
	ApiErrorCodeMethodNotAllowed ApiErrorCode = "method_not_allowed"
	// ApiErrorCodeBackgroundProcessNotFound background process handle not running
	// for this session
	ApiErrorCodeBackgroundProcessNotFound ApiErrorCode = "background_process_not_found"
	// ApiErrorCodeBodyTooLarge request body exceeded configured limit
	ApiErrorCodeBodyTooLarge ApiErrorCode = "body_too_large"
	// ApiErrorCodePromptTextTooLarge inline user prose exceeded the host composer
	// limit and must be attached
	ApiErrorCodePromptTextTooLarge ApiErrorCode = "prompt_text_too_large"
	// ApiErrorCodeDiagnosticsExportFailed diagnostics bundle could not be
	// assembled
	ApiErrorCodeDiagnosticsExportFailed ApiErrorCode = "diagnostics_export_failed"
	// ApiErrorCodePricingNoSource cost tracking was turned on with no pricing
	// source enabled
	ApiErrorCodePricingNoSource ApiErrorCode = "pricing_no_source"
	// ApiErrorCodeBackupInvalid uploaded backup archive failed structural
	// validation
	ApiErrorCodeBackupInvalid ApiErrorCode = "backup_invalid"
	// ApiErrorCodeBackupIncomplete retained data was missing, unreadable, or
	// changed during backup capture
	ApiErrorCodeBackupIncomplete ApiErrorCode = "backup_incomplete"
	// ApiErrorCodeBackupIncompatible backup archive schema does not match this
	// build
	ApiErrorCodeBackupIncompatible ApiErrorCode = "backup_incompatible"
	// ApiErrorCodeBackupUnavailable backup subsystem cannot serve this request on
	// this build
	ApiErrorCodeBackupUnavailable ApiErrorCode = "backup_unavailable"
	// ApiErrorCodeStoreIncompatible store cannot be served by this build; recovery
	// mode only
	ApiErrorCodeStoreIncompatible ApiErrorCode = "store_incompatible"
	// ApiErrorCodeExportFormatInvalid transcript export format query is not a
	// supported value
	ApiErrorCodeExportFormatInvalid ApiErrorCode = "export_format_invalid"
	// ApiErrorCodeCheckpointNotFound human checkpoint id not found
	ApiErrorCodeCheckpointNotFound ApiErrorCode = "checkpoint_not_found"
	// ApiErrorCodeApprovalGrantNotFound approval grant or ask quiet id is not held
	// on this device
	ApiErrorCodeApprovalGrantNotFound ApiErrorCode = "approval_grant_not_found"
	// ApiErrorCodeSessionNotIdle rewind refused while a turn or worker is still
	// running
	ApiErrorCodeSessionNotIdle ApiErrorCode = "session_not_idle"
	// ApiErrorCodePromptRecoveryStale a Keep going or Retry recovery no longer
	// matches the chat (turn running, newer messages, or nothing interrupted);
	// details.reason says which
	ApiErrorCodePromptRecoveryStale ApiErrorCode = "prompt_recovery_stale"
	// ApiErrorCodeRewindAnchorNotFound rewind anchor message id is not in the
	// transcript
	ApiErrorCodeRewindAnchorNotFound ApiErrorCode = "rewind_anchor_not_found"
	// ApiErrorCodeRewindAnchorIneligible rewind anchor is not a visible user ask
	ApiErrorCodeRewindAnchorIneligible ApiErrorCode = "rewind_anchor_ineligible"
	// ApiErrorCodeRewindBlocked selected source changes cannot be safely reversed
	// together
	ApiErrorCodeRewindBlocked ApiErrorCode = "rewind_blocked"
	// ApiErrorCodeRewindPlanChanged transcript, source, or document state changed
	// after preview
	ApiErrorCodeRewindPlanChanged ApiErrorCode = "rewind_plan_changed"
	// ApiErrorCodeRewindModeUnsupported rewind mode other than before_turn
	// requested
	ApiErrorCodeRewindModeUnsupported ApiErrorCode = "rewind_mode_unsupported"
	// ApiErrorCodeCloneFailed git clone of a remote returned a non-zero exit
	// (auth/url/network)
	ApiErrorCodeCloneFailed ApiErrorCode = "clone_failed"
	// ApiErrorCodeFolderExists clone destination folder already exists
	ApiErrorCodeFolderExists ApiErrorCode = "folder_exists"
	// ApiErrorCodeFolderNotEmpty promote target folder is not empty
	ApiErrorCodeFolderNotEmpty ApiErrorCode = "folder_not_empty"
	// ApiErrorCodeProjectMutationInProgress another lifecycle transition is active
	// on this project
	ApiErrorCodeProjectMutationInProgress ApiErrorCode = "project_mutation_in_progress"
	// ApiErrorCodePromotionConflict save-to-folder intent conflicts with the
	// durable transition
	ApiErrorCodePromotionConflict ApiErrorCode = "promotion_conflict"
	// ApiErrorCodePromotionNotFound project has no active save-to-folder
	// transition
	ApiErrorCodePromotionNotFound ApiErrorCode = "promotion_not_found"
	// ApiErrorCodeDraftRootImmutable draft roots change only through
	// save-to-folder
	ApiErrorCodeDraftRootImmutable ApiErrorCode = "draft_root_immutable"
	// ApiErrorCodeProjectBusy project acquired an in-flight dependent before
	// lifecycle commit
	ApiErrorCodeProjectBusy ApiErrorCode = "project_busy"
	// ApiErrorCodeCheckpointNotPending checkpoint resolve targeted a non-pending
	// record
	ApiErrorCodeCheckpointNotPending ApiErrorCode = "checkpoint_not_pending"
	// ApiErrorCodeDelegationNotFound delegation id not found
	ApiErrorCodeDelegationNotFound ApiErrorCode = "delegation_not_found"
	// ApiErrorCodeDelegationLegNotFound delegation leg id not found
	ApiErrorCodeDelegationLegNotFound ApiErrorCode = "delegation_leg_not_found"
	// ApiErrorCodeFeedbackNotPending feedback resolve targeted a non-pending phase
	ApiErrorCodeFeedbackNotPending ApiErrorCode = "feedback_not_pending"
	// ApiErrorCodeFeedbackResponseRequired feedback resolve had empty response
	ApiErrorCodeFeedbackResponseRequired ApiErrorCode = "feedback_response_required"
	// ApiErrorCodeFileBriefingDisabled file summaries are disabled
	ApiErrorCodeFileBriefingDisabled ApiErrorCode = "file_briefing_disabled"
	// ApiErrorCodeFileBriefingNotFound no briefing has been requested for the
	// source file
	ApiErrorCodeFileBriefingNotFound ApiErrorCode = "file_briefing_not_found"
	// ApiErrorCodeFileBriefingUnavailable the file briefing service is stopping
	// with the engine
	ApiErrorCodeFileBriefingUnavailable ApiErrorCode = "file_briefing_unavailable"
	// ApiErrorCodeSourceVersionUnavailable exact retained bytes or Git history
	// needed for the selected source version are unavailable
	ApiErrorCodeSourceVersionUnavailable ApiErrorCode = "source_version_unavailable"
	// ApiErrorCodeChoiceTransitionNotFound choice transition_id not on current
	// phase
	ApiErrorCodeChoiceTransitionNotFound ApiErrorCode = "choice_transition_not_found"
	// ApiErrorCodeChoiceTransitionActorDenied HTTP actor not listed on the choice
	// edge
	ApiErrorCodeChoiceTransitionActorDenied ApiErrorCode = "choice_transition_actor_denied"
	// ApiErrorCodeChoiceTransitionNotArmed choice transition when: readiness false
	ApiErrorCodeChoiceTransitionNotArmed ApiErrorCode = "choice_transition_not_armed"
	// ApiErrorCodeChoiceTransitionPendingInput choice transition blocked by
	// pending user input latch
	ApiErrorCodeChoiceTransitionPendingInput ApiErrorCode = "choice_transition_pending_input"
	// ApiErrorCodeDecisionChoiceInvalid choice resolve had an invalid choice or
	// selection count
	ApiErrorCodeDecisionChoiceInvalid ApiErrorCode = "decision_choice_invalid"
	// ApiErrorCodeNotChoicePhase choice resolve targeted a non-choice phase
	ApiErrorCodeNotChoicePhase ApiErrorCode = "not_choice_phase"
	// ApiErrorCodeGitCheckoutFailed git checkout/branch create returned a non-zero
	// exit
	ApiErrorCodeGitCheckoutFailed ApiErrorCode = "git_checkout_failed"
	// ApiErrorCodeGitCommitFailed git commit returned a non-zero exit
	ApiErrorCodeGitCommitFailed ApiErrorCode = "git_commit_failed"
	// ApiErrorCodeGitDiscardFailed git reset --hard / clean returned a non-zero
	// exit
	ApiErrorCodeGitDiscardFailed ApiErrorCode = "git_discard_failed"
	// ApiErrorCodeGitInitFailed git init returned a non-zero exit
	ApiErrorCodeGitInitFailed ApiErrorCode = "git_init_failed"
	// ApiErrorCodeGitPullFailed git pull --ff-only returned a non-zero exit
	// (diverged/auth/no upstream)
	ApiErrorCodeGitPullFailed ApiErrorCode = "git_pull_failed"
	// ApiErrorCodeGitPushFailed git push returned a non-zero exit (auth/no
	// upstream/rejected)
	ApiErrorCodeGitPushFailed ApiErrorCode = "git_push_failed"
	// ApiErrorCodeGitNoChanges git commit-message had no diff to summarize
	ApiErrorCodeGitNoChanges ApiErrorCode = "git_no_changes"
	// ApiErrorCodeGitDraftFailed git commit-message draftsman had no lite model or
	// the model call failed
	ApiErrorCodeGitDraftFailed ApiErrorCode = "git_draft_failed"
	// ApiErrorCodeGitRepoNotFound named repo_id is not in the project's repository
	// set
	ApiErrorCodeGitRepoNotFound ApiErrorCode = "git_repo_not_found"
	// ApiErrorCodeGitStashFailed git stash returned a non-zero exit
	ApiErrorCodeGitStashFailed ApiErrorCode = "git_stash_failed"
	// ApiErrorCodeWorktreeNotBound land/remove refused because the chat has no
	// worktree binding
	ApiErrorCodeWorktreeNotBound ApiErrorCode = "worktree_not_bound"
	// ApiErrorCodeWorktreeAlreadyBound bind refused because the chat already has a
	// worktree, or delete refused while bound
	ApiErrorCodeWorktreeAlreadyBound ApiErrorCode = "worktree_already_bound"
	// ApiErrorCodeWorktreeBranchExists bind refused because the requested branch
	// already exists
	ApiErrorCodeWorktreeBranchExists ApiErrorCode = "worktree_branch_exists"
	// ApiErrorCodeWorktreeDirty land/remove refused because the worktree has
	// uncommitted changes
	ApiErrorCodeWorktreeDirty ApiErrorCode = "worktree_dirty"
	// ApiErrorCodeWorktreeStale land or turn refused because the worktree
	// directory is missing
	ApiErrorCodeWorktreeStale ApiErrorCode = "worktree_stale"
	// ApiErrorCodeWorktreeLandBlocked bind/land refused for a machine-checked
	// base-checkout or merge reason
	ApiErrorCodeWorktreeLandBlocked ApiErrorCode = "worktree_land_blocked"
	// ApiErrorCodeInternalError unhandled server error fallthrough
	ApiErrorCodeInternalError ApiErrorCode = "internal_error"
	// ApiErrorCodeInvalidJson request body is not one well-formed JSON value of
	// the expected shape
	ApiErrorCodeInvalidJson ApiErrorCode = "invalid_json"
	// ApiErrorCodeInvalidPath path traversal or unsafe path argument
	ApiErrorCodeInvalidPath ApiErrorCode = "invalid_path"
	// ApiErrorCodeWriteRootIsFilesystemRoot project root or write_root grant is
	// filesystem root
	ApiErrorCodeWriteRootIsFilesystemRoot ApiErrorCode = "write_root_is_filesystem_root"
	// ApiErrorCodeWriteRootIsHome project root or write_root grant is bare $HOME
	ApiErrorCodeWriteRootIsHome ApiErrorCode = "write_root_is_home"
	// ApiErrorCodeWriteRootNotAbsolute project root or write_root grant is not an
	// absolute path
	ApiErrorCodeWriteRootNotAbsolute ApiErrorCode = "write_root_not_absolute"
	// ApiErrorCodeWriteRootUnderSecretStore project root or write_root grant
	// intersects a credential store
	ApiErrorCodeWriteRootUnderSecretStore ApiErrorCode = "write_root_under_secret_store"
	// ApiErrorCodeBlueprintContentConflict blueprint bytes changed before approval
	// committed
	ApiErrorCodeBlueprintContentConflict ApiErrorCode = "blueprint_content_conflict"
	// ApiErrorCodeIdempotencyConflict operation id was reused with different input
	// (every operation_id-bearing endpoint)
	ApiErrorCodeIdempotencyConflict ApiErrorCode = "idempotency_conflict"
	// ApiErrorCodeInvalidArguments contribution command arguments failed
	// validation
	ApiErrorCodeInvalidArguments ApiErrorCode = "invalid_arguments"
	// ApiErrorCodeInvalidQuery query parameter is malformed, missing, duplicated,
	// or outside its declared bounds; details.parameter names it
	ApiErrorCodeInvalidQuery ApiErrorCode = "invalid_query"
	// ApiErrorCodeCommandDisabled contribution command enablement is false
	ApiErrorCodeCommandDisabled ApiErrorCode = "command_disabled"
	// ApiErrorCodeChoiceSourceNotFound command interaction has no matching dynamic
	// choice source
	ApiErrorCodeChoiceSourceNotFound ApiErrorCode = "choice_source_not_found"
	// ApiErrorCodeChoiceSourceFailed dynamic choice provider call failed
	ApiErrorCodeChoiceSourceFailed ApiErrorCode = "choice_source_failed"
	// ApiErrorCodeChoiceSourceInvalid dynamic choice provider returned an invalid
	// projection
	ApiErrorCodeChoiceSourceInvalid ApiErrorCode = "choice_source_invalid"
	// ApiErrorCodeContributionSourceUnavailable contribution provider requirement
	// is not ready
	ApiErrorCodeContributionSourceUnavailable ApiErrorCode = "contribution_source_unavailable"
	// ApiErrorCodeSearchSourceNotFound contribution search source is absent from
	// the captured frame
	ApiErrorCodeSearchSourceNotFound ApiErrorCode = "search_source_not_found"
	// ApiErrorCodeContributionSearchFailed contribution search provider call
	// failed
	ApiErrorCodeContributionSearchFailed ApiErrorCode = "contribution_search_failed"
	// ApiErrorCodeContributionSearchInvalid contribution search provider returned
	// an invalid projection
	ApiErrorCodeContributionSearchInvalid ApiErrorCode = "contribution_search_invalid"
	// ApiErrorCodeOperationOutputInvalid typed operation output failed schema
	// validation
	ApiErrorCodeOperationOutputInvalid ApiErrorCode = "operation_output_invalid"
	// ApiErrorCodeSourceMutationDiverged source bytes diverged during operation
	// recovery
	ApiErrorCodeSourceMutationDiverged ApiErrorCode = "source_mutation_diverged"
	// ApiErrorCodeSourceHistoryChanged undo or redo targeted a lifecycle head that
	// is no longer current
	ApiErrorCodeSourceHistoryChanged ApiErrorCode = "source_history_changed"
	// ApiErrorCodeWorkflowRunNotActive blueprint approval targeted an inactive
	// workflow run
	ApiErrorCodeWorkflowRunNotActive ApiErrorCode = "workflow_run_not_active"
	// ApiErrorCodeCursorGenerationExpired pagination cursor belongs to an
	// unavailable snapshot generation
	ApiErrorCodeCursorGenerationExpired ApiErrorCode = "cursor_generation_expired"
	// ApiErrorCodeEventReplayUnavailable event replay cursor predates the retained
	// event window
	ApiErrorCodeEventReplayUnavailable ApiErrorCode = "event_replay_unavailable"
	// ApiErrorCodeInvalidRequest request body failed validation; details.field
	// names the field when one is at fault and details.reason carries the host's
	// explanation
	ApiErrorCodeInvalidRequest ApiErrorCode = "invalid_request"
	// ApiErrorCodeProviderCatalogUnavailable Model assignment could not be
	// established because provider discovery failed. No assignment was saved.
	ApiErrorCodeProviderCatalogUnavailable ApiErrorCode = "provider_catalog_unavailable"
	// ApiErrorCodeInvalidWorkflowTransition workflow run state transition rejected
	ApiErrorCodeInvalidWorkflowTransition ApiErrorCode = "invalid_workflow_transition"
	// ApiErrorCodeInvalidWorkflowTarget workflow command omitted its run id or
	// reviewed revision
	ApiErrorCodeInvalidWorkflowTarget ApiErrorCode = "invalid_workflow_target"
	// ApiErrorCodeInvalidWorkflowRevision workflow command supplied a non-positive
	// reviewed revision
	ApiErrorCodeInvalidWorkflowRevision ApiErrorCode = "invalid_workflow_revision"
	// ApiErrorCodeInvalidWorkflowReplacementTarget workflow replacement supplied
	// only one half of its target token
	ApiErrorCodeInvalidWorkflowReplacementTarget ApiErrorCode = "invalid_workflow_replacement_target"
	// ApiErrorCodeMessageNotFound session message id not found
	ApiErrorCodeMessageNotFound ApiErrorCode = "message_not_found"
	// ApiErrorCodeNotFound no route matches the request path; resources use
	// <resource>_not_found
	ApiErrorCodeNotFound ApiErrorCode = "not_found"
	// ApiErrorCodePathNotFound filesystem path does not exist
	ApiErrorCodePathNotFound ApiErrorCode = "path_not_found"
	// ApiErrorCodePersistNotConfirmed workflow_persist called without confirm
	// token
	ApiErrorCodePersistNotConfirmed ApiErrorCode = "persist_not_confirmed"
	// ApiErrorCodePhaseGateUnmet advance blocked by complete_when gate (see
	// workflow_handlers.go inline Code)
	ApiErrorCodePhaseGateUnmet ApiErrorCode = "phase_gate_unmet"
	// ApiErrorCodeBlueprintNotDraft blueprint must be draft for the requested
	// operation
	ApiErrorCodeBlueprintNotDraft ApiErrorCode = "blueprint_not_draft"
	// ApiErrorCodeBlueprintNotEditable blueprint in terminal state cannot be
	// edited
	ApiErrorCodeBlueprintNotEditable ApiErrorCode = "blueprint_not_editable"
	// ApiErrorCodeBlueprintNotFound blueprint id not found
	ApiErrorCodeBlueprintNotFound ApiErrorCode = "blueprint_not_found"
	// ApiErrorCodeBlueprintPathTaken a blueprint already exists at the minted
	// path; create never replaces
	ApiErrorCodeBlueprintPathTaken ApiErrorCode = "blueprint_path_taken"
	// ApiErrorCodeBlueprintRunActive blueprint delete refused while a workflow run
	// is bound to it
	ApiErrorCodeBlueprintRunActive ApiErrorCode = "blueprint_run_active"
	// ApiErrorCodeDetectionPackNotRemovable DELETE refused — only an imported
	// folder is removable here; a pack an extension provides is uninstalled with
	// it
	ApiErrorCodeDetectionPackNotRemovable ApiErrorCode = "detection_pack_not_removable"
	// ApiErrorCodeDetectionPackIdCollision import pack id is already provided by a
	// shipped pack, an extension pack, or an existing device pack
	ApiErrorCodeDetectionPackIdCollision ApiErrorCode = "detection_pack_id_collision"
	// ApiErrorCodeBlueprintLaunchIncompatible launch target fails
	// materialization-kind compatibility
	ApiErrorCodeBlueprintLaunchIncompatible ApiErrorCode = "blueprint_launch_incompatible"
	// ApiErrorCodeBlueprintLaunchUnsupported launch target lacks blueprint:
	// support
	ApiErrorCodeBlueprintLaunchUnsupported ApiErrorCode = "blueprint_launch_unsupported"
	// ApiErrorCodeHumanApprovalNotReady blueprint approve blocked —
	// human_approval readiness gate unmet; blueprint not marked approved
	ApiErrorCodeHumanApprovalNotReady ApiErrorCode = "human_approval_not_ready"
	// ApiErrorCodeProjectNotFound project id not found
	ApiErrorCodeProjectNotFound ApiErrorCode = "project_not_found"
	// ApiErrorCodeExtensionSuggestionChanged project extension proposal changed
	// after display and before installation
	ApiErrorCodeExtensionSuggestionChanged ApiErrorCode = "extension_suggestion_changed"
	// ApiErrorCodeExtensionSuggestionInvalid the project's extension suggestion
	// file does not decode or validate
	ApiErrorCodeExtensionSuggestionInvalid ApiErrorCode = "extension_suggestion_invalid"
	// ApiErrorCodeOverlayFormatUnsupported workspace .paintedwolf/overlay.yaml
	// overlay_format newer than binary
	ApiErrorCodeOverlayFormatUnsupported ApiErrorCode = "overlay_format_unsupported"
	// ApiErrorCodeOverlayFormatInvalid workspace .paintedwolf/overlay.yaml has a
	// missing or invalid overlay_format
	ApiErrorCodeOverlayFormatInvalid ApiErrorCode = "overlay_format_invalid"
	// ApiErrorCodeProjectApprovalsNeedRepair the project's
	// .paintedwolf/approvals.yaml has parts the host did not apply; saving would
	// replace them, so the file must be fixed first
	ApiErrorCodeProjectApprovalsNeedRepair ApiErrorCode = "project_approvals_need_repair"
	// ApiErrorCodeRootNotFound project root not found, or the named root_id is not
	// a project root
	ApiErrorCodeRootNotFound ApiErrorCode = "root_not_found"
	// ApiErrorCodeRootBusy folder has in-flight dependents; use ?force=true to
	// cancel
	ApiErrorCodeRootBusy ApiErrorCode = "root_busy"
	// ApiErrorCodeDuplicateRoot project root path already attached
	ApiErrorCodeDuplicateRoot ApiErrorCode = "duplicate_root"
	// ApiErrorCodeDuplicateRootLabel project root label already used
	// (case-insensitive)
	ApiErrorCodeDuplicateRootLabel ApiErrorCode = "duplicate_root_label"
	// ApiErrorCodeProjectRemovalAssessmentChanged Project removal references
	// changed after review; assess again.
	ApiErrorCodeProjectRemovalAssessmentChanged ApiErrorCode = "project_removal_assessment_changed"
	// ApiErrorCodeProjectRemovalOperationConflict A project removal operation id
	// was reused with different input.
	ApiErrorCodeProjectRemovalOperationConflict ApiErrorCode = "project_removal_operation_conflict"
	// ApiErrorCodeExtensionStateChanged Extension mutation expected_revision is
	// stale; reload and retry
	ApiErrorCodeExtensionStateChanged ApiErrorCode = "extension_state_changed"
	// ApiErrorCodeExtensionCandidateRejected the resolved pack candidate failed
	// validation; the reason names the specific pack, unit, or reference at fault
	ApiErrorCodeExtensionCandidateRejected ApiErrorCode = "extension_candidate_rejected"
	// ApiErrorCodeContributionsUnavailable the contribution frame source is not
	// available
	ApiErrorCodeContributionsUnavailable ApiErrorCode = "contributions_unavailable"
	// ApiErrorCodeCommandNotFound the invoked command is not in the current
	// contribution frame
	ApiErrorCodeCommandNotFound ApiErrorCode = "command_not_found"
	// ApiErrorCodeInvocationScopeMismatch the command's action kind does not
	// invoke on this route
	ApiErrorCodeInvocationScopeMismatch ApiErrorCode = "invocation_scope_mismatch"
	// ApiErrorCodeContributionFrameChanged the invoked command changed since the
	// caller's frame
	ApiErrorCodeContributionFrameChanged ApiErrorCode = "contribution_frame_changed"
	// ApiErrorCodeCommandUnavailable the command's condition or requirement does
	// not hold
	ApiErrorCodeCommandUnavailable ApiErrorCode = "command_unavailable"
	// ApiErrorCodeContributionNotAuthorized trust policy rejected the invocation
	ApiErrorCodeContributionNotAuthorized ApiErrorCode = "contribution_not_authorized"
	// ApiErrorCodeMcpCallFailed the MCP tool call failed
	ApiErrorCodeMcpCallFailed ApiErrorCode = "mcp_call_failed"
	// ApiErrorCodePathMissing Linked development pack source folder is missing or
	// unreadable
	ApiErrorCodePathMissing ApiErrorCode = "path_missing"
	// ApiErrorCodeTrustSurfaceOff the required project trust surface is off
	ApiErrorCodeTrustSurfaceOff ApiErrorCode = "trust_surface_off"
	// ApiErrorCodeArtifactEmpty live tool recording upload contained no bytes
	ApiErrorCodeArtifactEmpty ApiErrorCode = "artifact_empty"
	// ApiErrorCodeArtifactTooLarge live tool recording upload exceeded the video
	// artifact limit
	ApiErrorCodeArtifactTooLarge ApiErrorCode = "artifact_too_large"
	// ApiErrorCodeArtifactForeign visual artifact id belongs to a different
	// session tree
	ApiErrorCodeArtifactForeign ApiErrorCode = "artifact_foreign"
	// ApiErrorCodeArtifactUnavailable visual artifact bytes are no longer retained
	ApiErrorCodeArtifactUnavailable ApiErrorCode = "artifact_unavailable"
	// ApiErrorCodeArtifactDeleted visual artifact was deleted by a human; the
	// tombstone still resolves
	ApiErrorCodeArtifactDeleted ApiErrorCode = "artifact_deleted"
	// ApiErrorCodeArtifactNotFound no visual artifact by that id is known to this
	// session tree or project
	ApiErrorCodeArtifactNotFound ApiErrorCode = "artifact_not_found"
	// ApiErrorCodeBackupRestorePending backup restore is already pending
	ApiErrorCodeBackupRestorePending ApiErrorCode = "backup_restore_pending"
	// ApiErrorCodeRecordingDurationInvalid live tool recording duration_ms was not
	// a non-negative integer
	ApiErrorCodeRecordingDurationInvalid ApiErrorCode = "recording_duration_invalid"
	// ApiErrorCodeRecordingStartInvalid live tool recording recorded_at was not
	// RFC 3339
	ApiErrorCodeRecordingStartInvalid ApiErrorCode = "recording_start_invalid"
	// ApiErrorCodeUserImageNotVisible user attached images on a non-vision
	// coordinator model (SSE host notice)
	ApiErrorCodeUserImageNotVisible ApiErrorCode = "user_image_not_visible"
	// ApiErrorCodeUnsupportedAttachment prompt attachment rejected by
	// sniff/allowlist
	ApiErrorCodeUnsupportedAttachment ApiErrorCode = "unsupported_attachment"
	// ApiErrorCodeAttachmentTooLarge prompt attachment exceeded count/byte/turn
	// caps
	ApiErrorCodeAttachmentTooLarge ApiErrorCode = "attachment_too_large"
	// ApiErrorCodeAttachmentUndecodable prompt attachment is an admitted video
	// whose codec the managed browser cannot decode
	ApiErrorCodeAttachmentUndecodable ApiErrorCode = "attachment_undecodable"
	// ApiErrorCodeAttachmentNotFound prompt attachment blob id is not in the
	// project's upload store
	ApiErrorCodeAttachmentNotFound ApiErrorCode = "attachment_not_found"
	// ApiErrorCodeAttachmentUnavailable prompt attachment storage is unavailable
	ApiErrorCodeAttachmentUnavailable ApiErrorCode = "attachment_unavailable"
	// ApiErrorCodeReferenceOutOfJail prompt reference path/folder outside attached
	// project roots
	ApiErrorCodeReferenceOutOfJail ApiErrorCode = "reference_out_of_jail"
	// ApiErrorCodeAttachmentScannedNoText scanned document yielded no extractable
	// text
	ApiErrorCodeAttachmentScannedNoText ApiErrorCode = "attachment_scanned_no_text"
	// ApiErrorCodeNoProjectRoot project has no attached folder
	ApiErrorCodeNoProjectRoot ApiErrorCode = "no_project_root"
	// ApiErrorCodeSourcePathDenied path is outside the project sandbox
	ApiErrorCodeSourcePathDenied ApiErrorCode = "source_path_denied"
	// ApiErrorCodeSourcePathProtected mutation targets protected project metadata
	ApiErrorCodeSourcePathProtected ApiErrorCode = "source_path_protected"
	// ApiErrorCodeSourceMoveIncomplete cross-volume move retains its source
	// pending reconciliation
	ApiErrorCodeSourceMoveIncomplete ApiErrorCode = "source_move_incomplete"
	// ApiErrorCodeSourcePathBusy another file operation reserves this path
	ApiErrorCodeSourcePathBusy ApiErrorCode = "source_path_busy"
	// ApiErrorCodeSourceRecoveryFailed recovery content could not be preserved or
	// restored
	ApiErrorCodeSourceRecoveryFailed ApiErrorCode = "source_recovery_failed"
	// ApiErrorCodeSourceNotFound file not found under project roots
	ApiErrorCodeSourceNotFound ApiErrorCode = "source_not_found"
	// ApiErrorCodeSourceBinaryDenied binary content refused on PUT /source (reads
	// return metadata)
	ApiErrorCodeSourceBinaryDenied ApiErrorCode = "source_binary_denied"
	// ApiErrorCodeSourceReadOnly editor document admission requires a writable
	// source file
	ApiErrorCodeSourceReadOnly ApiErrorCode = "source_read_only"
	// ApiErrorCodeSourceBinary editor document requires editable text
	ApiErrorCodeSourceBinary ApiErrorCode = "source_binary"
	// ApiErrorCodeUnsupportedEncoding unsupported codepage text refused on GET
	// /source with a detected label
	ApiErrorCodeUnsupportedEncoding ApiErrorCode = "unsupported_encoding"
	// ApiErrorCodeSourceRawNotImage GET /source/raw refused a non-image payload
	ApiErrorCodeSourceRawNotImage ApiErrorCode = "source_raw_not_image"
	// ApiErrorCodeSourceRawTooLarge GET /source/raw refused an image over the 8
	// MiB cap
	ApiErrorCodeSourceRawTooLarge ApiErrorCode = "source_raw_too_large"
	// ApiErrorCodeSourceWorkspaceMismatch source request targeted a different
	// physical checkout
	ApiErrorCodeSourceWorkspaceMismatch ApiErrorCode = "source_workspace_mismatch"
	// ApiErrorCodeSourceWriteConflict in-app editor save refused because the file
	// changed on disk since it was loaded
	ApiErrorCodeSourceWriteConflict ApiErrorCode = "source_write_conflict"
	// ApiErrorCodeSourcePermissionChangeFailed host filesystem refused a human
	// request to make a project file owner-writable
	ApiErrorCodeSourcePermissionChangeFailed ApiErrorCode = "source_permission_change_failed"
	// ApiErrorCodeEditorRevisionConflict editor document command targeted a stale
	// document or file revision
	ApiErrorCodeEditorRevisionConflict ApiErrorCode = "editor_revision_conflict"
	// ApiErrorCodeEditorReplicaEpoch pending edits belong to an earlier external
	// import and require recovery
	ApiErrorCodeEditorReplicaEpoch ApiErrorCode = "editor_replica_epoch"
	// ApiErrorCodeEditorReplicaIdentity document update does not belong to the
	// invoking registered replica
	ApiErrorCodeEditorReplicaIdentity ApiErrorCode = "editor_replica_identity"
	// ApiErrorCodeEditorRootDetached editor document names a root the project no
	// longer has attached
	ApiErrorCodeEditorRootDetached ApiErrorCode = "editor_root_detached"
	// ApiErrorCodeSourcePresentationEffectChanged file presentation targeted a
	// different source effect
	ApiErrorCodeSourcePresentationEffectChanged ApiErrorCode = "source_presentation_effect_changed"
	// ApiErrorCodeSourceAlreadyExists in-app file create refused because a file or
	// folder already occupies that path
	ApiErrorCodeSourceAlreadyExists ApiErrorCode = "source_already_exists"
	// ApiErrorCodeSourceCrossRoot rename or copy refused because the path lives
	// under a different attached root
	ApiErrorCodeSourceCrossRoot ApiErrorCode = "source_cross_root"
	// ApiErrorCodeSourceNotEmpty delete refused because the folder still has
	// children and recursive was not set
	ApiErrorCodeSourceNotEmpty ApiErrorCode = "source_not_empty"
	// ApiErrorCodeSourceInventoryPending source inventory has not reached the
	// current root generation
	ApiErrorCodeSourceInventoryPending ApiErrorCode = "source_inventory_pending"
	// ApiErrorCodeSourceTrashFailed delete could not complete the operating system
	// trash move; recovery content is retained
	ApiErrorCodeSourceTrashFailed ApiErrorCode = "source_trash_failed"
	// ApiErrorCodeSourceUnavailable a source root cannot be read right now
	ApiErrorCodeSourceUnavailable ApiErrorCode = "source_unavailable"
	// ApiErrorCodeProjectPolicyDenied project open policy denied path
	ApiErrorCodeProjectPolicyDenied ApiErrorCode = "project_policy_denied"
	// ApiErrorCodeProviderNotFound LLM provider id not registered
	ApiErrorCodeProviderNotFound ApiErrorCode = "provider_not_found"
	// ApiErrorCodeProviderInUse provider is referenced by saved model policy
	ApiErrorCodeProviderInUse ApiErrorCode = "provider_in_use"
	// ApiErrorCodeProviderNotConfigured LLM provider has no API key or local
	// backend
	ApiErrorCodeProviderNotConfigured ApiErrorCode = "provider_not_configured"
	// ApiErrorCodeProviderEmptyCompletion LLM provider returned no text or tool
	// calls
	ApiErrorCodeProviderEmptyCompletion ApiErrorCode = "provider_empty_completion"
	// ApiErrorCodeProviderResponseInterrupted provider response stream ended
	// before completion
	ApiErrorCodeProviderResponseInterrupted ApiErrorCode = "provider_response_interrupted"
	// ApiErrorCodeProviderContextTooSmall prompt exceeds the model's context
	// window on the target host (SSE host_error)
	ApiErrorCodeProviderContextTooSmall ApiErrorCode = "provider_context_too_small"
	// ApiErrorCodeProviderToolCallsUnsupported model cannot make tool calls and a
	// detected attempt was unrecoverable (SSE host_error)
	ApiErrorCodeProviderToolCallsUnsupported ApiErrorCode = "provider_tool_calls_unsupported"
	// ApiErrorCodeProviderToolCallsInProse model emitted an unparseable tool call
	// as prose (SSE host_error)
	ApiErrorCodeProviderToolCallsInProse ApiErrorCode = "provider_tool_calls_in_prose"
	// ApiErrorCodeProviderRateLimited SSE host_error after provider HTTP 429 retry
	// exhaustion
	ApiErrorCodeProviderRateLimited ApiErrorCode = "provider_rate_limited"
	// ApiErrorCodeProviderOverloaded SSE host_error after provider HTTP 503/529
	// capacity exhaustion
	ApiErrorCodeProviderOverloaded ApiErrorCode = "provider_overloaded"
	// ApiErrorCodeProviderServerError SSE host_error after a provider-side HTTP
	// 5xx response exhausts retries
	ApiErrorCodeProviderServerError ApiErrorCode = "provider_server_error"
	// ApiErrorCodeThinkingOverrideUnavailable configured thinking override cannot
	// be applied to the model or request
	ApiErrorCodeThinkingOverrideUnavailable ApiErrorCode = "thinking_override_unavailable"
	// ApiErrorCodeProviderRequestRejected provider returned a terminal HTTP
	// request rejection (SSE host_error)
	ApiErrorCodeProviderRequestRejected ApiErrorCode = "provider_request_rejected"
	// ApiErrorCodeProviderUnreachable provider request never reached the
	// configured endpoint (SSE host_error)
	ApiErrorCodeProviderUnreachable ApiErrorCode = "provider_unreachable"
	// ApiErrorCodeProviderSilent provider accepted the request but sent no headers
	// before the deadline
	ApiErrorCodeProviderSilent ApiErrorCode = "provider_silent"
	// ApiErrorCodeModelRefused provider returned a structured refusal for the
	// assigned model
	ApiErrorCodeModelRefused ApiErrorCode = "model_refused"
	// ApiErrorCodeModelCatalogUnreachable model-list refresh could not reach the
	// configured provider
	ApiErrorCodeModelCatalogUnreachable ApiErrorCode = "model_catalog_unreachable"
	// ApiErrorCodeModelCatalogRefreshFailed model-list request was rejected or
	// returned an invalid response
	ApiErrorCodeModelCatalogRefreshFailed ApiErrorCode = "model_catalog_refresh_failed"
	// ApiErrorCodeMcpProviderUnreachable configured MCP provider did not answer
	ApiErrorCodeMcpProviderUnreachable ApiErrorCode = "mcp_provider_unreachable"
	// ApiErrorCodeMcpSyncFailed MCP provider answered but tools could not be
	// listed or registered
	ApiErrorCodeMcpSyncFailed ApiErrorCode = "mcp_sync_failed"
	// ApiErrorCodeMcpToolPinUnreadable device tool-definition pin state could not
	// be read; this provider's tools stayed at their last published generation
	ApiErrorCodeMcpToolPinUnreadable ApiErrorCode = "mcp_tool_pin_unreadable"
	// ApiErrorCodeMcpIdRequired create MCP provider omitted id
	ApiErrorCodeMcpIdRequired ApiErrorCode = "mcp_id_required"
	// ApiErrorCodeMcpTransportRequired create/update MCP provider omitted both url
	// and command
	ApiErrorCodeMcpTransportRequired ApiErrorCode = "mcp_transport_required"
	// ApiErrorCodeMcpTransportConflict create/update MCP provider named both url
	// and command
	ApiErrorCodeMcpTransportConflict ApiErrorCode = "mcp_transport_conflict"
	// ApiErrorCodeMcpProviderNotFound MCP admin targeted a provider id that is not
	// in the catalog
	ApiErrorCodeMcpProviderNotFound ApiErrorCode = "mcp_provider_not_found"
	// ApiErrorCodeMcpUpdateEmpty update MCP provider named neither inherit nor a
	// field
	ApiErrorCodeMcpUpdateEmpty ApiErrorCode = "mcp_update_empty"
	// ApiErrorCodeMcpOauthUnavailable MCP Authorization is not wired on this host
	ApiErrorCodeMcpOauthUnavailable ApiErrorCode = "mcp_oauth_unavailable"
	// ApiErrorCodeMcpOauthFailed MCP Authorization start, complete, or revoke
	// failed
	ApiErrorCodeMcpOauthFailed ApiErrorCode = "mcp_oauth_failed"
	// ApiErrorCodeMcpOauthNotSupported Sign in was requested for a recipe that
	// authenticates with a static token
	ApiErrorCodeMcpOauthNotSupported ApiErrorCode = "mcp_oauth_not_supported"
	// ApiErrorCodeMcpOauthRegistrationRequired Authorization server does not
	// accept dynamic client registration
	ApiErrorCodeMcpOauthRegistrationRequired ApiErrorCode = "mcp_oauth_registration_required"
	// ApiErrorCodeMcpRecipeNotFound add MCP recipe targeted an id that is not in
	// the bundled catalog
	ApiErrorCodeMcpRecipeNotFound ApiErrorCode = "mcp_recipe_not_found"
	// ApiErrorCodeMcpPersistFailed MCP overlay file could not be written
	ApiErrorCodeMcpPersistFailed ApiErrorCode = "mcp_persist_failed"
	// ApiErrorCodeRemoteRequiresHttps non-loopback MCP URL is not https
	ApiErrorCodeRemoteRequiresHttps ApiErrorCode = "remote_requires_https"
	// ApiErrorCodeInvalidUrl MCP HTTP URL could not be parsed
	ApiErrorCodeInvalidUrl ApiErrorCode = "invalid_url"
	// ApiErrorCodeProjectStdioForbidden project MCP overlay named command/args/env
	ApiErrorCodeProjectStdioForbidden ApiErrorCode = "project_stdio_forbidden"
	// ApiErrorCodeProjectHeadersForbidden project MCP overlay named token/headers
	ApiErrorCodeProjectHeadersForbidden ApiErrorCode = "project_headers_forbidden"
	// ApiErrorCodeProjectRemoteForbidden project MCP overlay named a non-loopback
	// URL
	ApiErrorCodeProjectRemoteForbidden ApiErrorCode = "project_remote_forbidden"
	// ApiErrorCodeProjectEnableForbidden project MCP overlay enabled a row it
	// could not have declared
	ApiErrorCodeProjectEnableForbidden ApiErrorCode = "project_enable_forbidden"
	// ApiErrorCodeOverlayUnknownField MCP overlay YAML named a field the catalog
	// does not accept
	ApiErrorCodeOverlayUnknownField ApiErrorCode = "overlay_unknown_field"
	// ApiErrorCodeUnreadableLayer MCP overlay YAML would not parse
	ApiErrorCodeUnreadableLayer ApiErrorCode = "unreadable_layer"
	// ApiErrorCodeRateLimited request rejected by rate limiter
	ApiErrorCodeRateLimited ApiErrorCode = "rate_limited"
	// ApiErrorCodeQueueRevisionConflict queue command targeted a stale revision
	ApiErrorCodeQueueRevisionConflict ApiErrorCode = "queue_revision_conflict"
	// ApiErrorCodeQueueEmpty queue command found no queued messages to act on
	ApiErrorCodeQueueEmpty ApiErrorCode = "queue_empty"
	// ApiErrorCodeQueueSendPending queue send refused because a reservation is
	// already in flight
	ApiErrorCodeQueueSendPending ApiErrorCode = "queue_send_pending"
	// ApiErrorCodeQueueSendReserved queue edit refused because the head group is
	// reserved for sending
	ApiErrorCodeQueueSendReserved ApiErrorCode = "queue_send_reserved"
	// ApiErrorCodeQueueNoSendToCancel queue cancel found no reservation
	// outstanding
	ApiErrorCodeQueueNoSendToCancel ApiErrorCode = "queue_no_send_to_cancel"
	// ApiErrorCodeScanNotComplete scan still running or pending
	ApiErrorCodeScanNotComplete ApiErrorCode = "scan_not_complete"
	// ApiErrorCodeScanNotFound scan id not found
	ApiErrorCodeScanNotFound ApiErrorCode = "scan_not_found"
	// ApiErrorCodeNoScannerAvailable no selected scanner can run a full pass for
	// the project
	ApiErrorCodeNoScannerAvailable ApiErrorCode = "no_scanner_available"
	// ApiErrorCodeInvalidEntry scanner catalog entry failed shape validation
	ApiErrorCodeInvalidEntry ApiErrorCode = "invalid_entry"
	// ApiErrorCodeCommunityDriverForbidden user/project scanner overlay used a
	// forbidden driver class
	ApiErrorCodeCommunityDriverForbidden ApiErrorCode = "community_driver_forbidden"
	// ApiErrorCodeCommunityParserForbidden user external scanner used a
	// non-allowlisted output_parser
	ApiErrorCodeCommunityParserForbidden ApiErrorCode = "community_parser_forbidden"
	// ApiErrorCodeMapperMissing map/json scanner missing device mapper
	ApiErrorCodeMapperMissing ApiErrorCode = "mapper_missing"
	// ApiErrorCodeProjectFieldsForbidden project scanners.yaml included non
	// enable-only fields
	ApiErrorCodeProjectFieldsForbidden ApiErrorCode = "project_fields_forbidden"
	// ApiErrorCodeArgvProjectPathForbidden external scanner argv referenced a
	// project path
	ApiErrorCodeArgvProjectPathForbidden ApiErrorCode = "argv_project_path_forbidden"
	// ApiErrorCodeArgvShellForbidden external scanner argv used shell
	// metacharacters
	ApiErrorCodeArgvShellForbidden ApiErrorCode = "argv_shell_forbidden"
	// ApiErrorCodeDuplicateId an id the caller chose already names another entry
	// of the same kind (scanner catalog row, MCP provider, model provider)
	ApiErrorCodeDuplicateId ApiErrorCode = "duplicate_id"
	// ApiErrorCodeSearchQueryInvalid search DSL parse/compile rejected the query
	ApiErrorCodeSearchQueryInvalid ApiErrorCode = "search_query_invalid"
	// ApiErrorCodeSearchPatternInvalid code search regex/pattern flags failed to
	// compile
	ApiErrorCodeSearchPatternInvalid ApiErrorCode = "search_pattern_invalid"
	// ApiErrorCodeSearchExportInvalidFormat search export format must be jsonl,
	// csv, or sarif
	ApiErrorCodeSearchExportInvalidFormat ApiErrorCode = "search_export_invalid_format"
	// ApiErrorCodeSearchExportSarifScope SARIF export requires a scan-scoped query
	// (kind:scan)
	ApiErrorCodeSearchExportSarifScope ApiErrorCode = "search_export_sarif_scope"
	// ApiErrorCodeSecurityDisabled Security product main is off
	ApiErrorCodeSecurityDisabled ApiErrorCode = "security_disabled"
	// ApiErrorCodeGroundingEscalated coordinator grounding guard escalated the
	// session (SSE host_error)
	ApiErrorCodeGroundingEscalated ApiErrorCode = "grounding_escalated"
	// ApiErrorCodeSessionSpendCeilingReached opt-in per-session USD spend ceiling
	// reached (SSE host_error)
	ApiErrorCodeSessionSpendCeilingReached ApiErrorCode = "session_spend_ceiling_reached"
	// ApiErrorCodePromptFailed generic async prompt turn failure (SSE host_error)
	ApiErrorCodePromptFailed ApiErrorCode = "prompt_failed"
	// ApiErrorCodeTurnCloseoutToolCall the model answered its final, tool-less
	// turn with a tool call, which the host did not run, so no summary was
	// recorded (SSE host_error)
	ApiErrorCodeTurnCloseoutToolCall ApiErrorCode = "turn_closeout_tool_call"
	// ApiErrorCodeHostFault the host could not record a tool call's outcome and
	// stopped the turn (SSE host_error)
	ApiErrorCodeHostFault ApiErrorCode = "host_fault"
	// ApiErrorCodeWorkerCloseoutExhausted worker hit LLM turn limit after
	// scheduled and recovery closeout (SSE worker.failure)
	ApiErrorCodeWorkerCloseoutExhausted ApiErrorCode = "worker_closeout_exhausted"
	// ApiErrorCodeWorkerExecuteFailed generic worker execute failure (SSE
	// worker.failure)
	ApiErrorCodeWorkerExecuteFailed ApiErrorCode = "worker_execute_failed"
	// ApiErrorCodeWorkerWorkspaceDiskFull central worker seed or branch storage
	// exhausted (SSE worker.failure)
	ApiErrorCodeWorkerWorkspaceDiskFull ApiErrorCode = "worker_workspace_disk_full"
	// ApiErrorCodeWorkerOwnerUnsettled worker child ended after a subsystem owner
	// was entered and could not commit (SSE worker.failure)
	ApiErrorCodeWorkerOwnerUnsettled ApiErrorCode = "worker_owner_unsettled"
	// ApiErrorCodeWorkerWorkspaceUnavailable isolated worker workspace could not
	// be prepared (SSE worker.failure)
	ApiErrorCodeWorkerWorkspaceUnavailable ApiErrorCode = "worker_workspace_unavailable"
	// ApiErrorCodeSessionArchived archived chats cannot be pinned; unarchive the
	// chat first
	ApiErrorCodeSessionArchived ApiErrorCode = "session_archived"
	// ApiErrorCodeSessionNotFound session id not found
	ApiErrorCodeSessionNotFound ApiErrorCode = "session_not_found"
	// ApiErrorCodeSessionNotPinned pin_position moves only a pinned chat
	ApiErrorCodeSessionNotPinned ApiErrorCode = "session_not_pinned"
	// ApiErrorCodeSessionPreparationFailed session workspace preparation failed
	ApiErrorCodeSessionPreparationFailed ApiErrorCode = "session_preparation_failed"
	// ApiErrorCodeSessionPreparing session workspace preparation is still running
	ApiErrorCodeSessionPreparing ApiErrorCode = "session_preparing"
	// ApiErrorCodeSessionStopping session-tree stop barrier rejected new work
	// admission
	ApiErrorCodeSessionStopping ApiErrorCode = "session_stopping"
	// ApiErrorCodeSessionWorkflowNotFound session-scoped workflow id not found
	ApiErrorCodeSessionWorkflowNotFound ApiErrorCode = "session_workflow_not_found"
	// ApiErrorCodeUnauthorized bearer token missing or invalid
	ApiErrorCodeUnauthorized ApiErrorCode = "unauthorized"
	// ApiErrorCodeForbidden the authenticated person does not hold the authority
	// the operation requires
	ApiErrorCodeForbidden ApiErrorCode = "forbidden"
	// ApiErrorCodeWorkerNotFound worker leg id not found
	ApiErrorCodeWorkerNotFound ApiErrorCode = "worker_not_found"
	// ApiErrorCodeWorkerNotCancelable worker cancel targeted a terminal job
	ApiErrorCodeWorkerNotCancelable ApiErrorCode = "worker_not_cancelable"
	// ApiErrorCodeLegNotPending delegation dispatch targeted a leg that already
	// left pending
	ApiErrorCodeLegNotPending ApiErrorCode = "leg_not_pending"
	// ApiErrorCodeDecisionNotPending no pending needs_decision for the worker job
	ApiErrorCodeDecisionNotPending ApiErrorCode = "decision_not_pending"
	// ApiErrorCodeWorkflowActive cannot start workflow while another is active
	ApiErrorCodeWorkflowActive ApiErrorCode = "workflow_active"
	// ApiErrorCodeWorkflowRevisionConflict workflow command targeted a stale run
	// revision
	ApiErrorCodeWorkflowRevisionConflict ApiErrorCode = "workflow_revision_conflict"
	// ApiErrorCodeWorkflowReplacementTargetRequired catalog replacement did not
	// identify the reviewed active lineage
	ApiErrorCodeWorkflowReplacementTargetRequired ApiErrorCode = "workflow_replacement_target_required"
	// ApiErrorCodeWorkflowStartRequiresHumanApproval coordinator state_start
	// recorded a proposal that requires a human start action
	ApiErrorCodeWorkflowStartRequiresHumanApproval ApiErrorCode = "workflow_start_requires_human_approval"
	// ApiErrorCodeBlueprintDraftRequired blueprint workflow start could not link a
	// draft blueprint row
	ApiErrorCodeBlueprintDraftRequired ApiErrorCode = "blueprint_draft_required"
	// ApiErrorCodeWorkflowNotFound workflow id not registered (unknown manifest)
	ApiErrorCodeWorkflowNotFound ApiErrorCode = "workflow_not_found"
	// ApiErrorCodeWorkflowNotRunnable workflow run is paused or terminal
	ApiErrorCodeWorkflowNotRunnable ApiErrorCode = "workflow_not_runnable"
	// ApiErrorCodeWorkflowVersionUnavailable the run's pinned workflow version is
	// no longer in the catalog, live or sealed
	ApiErrorCodeWorkflowVersionUnavailable ApiErrorCode = "workflow_version_unavailable"
	// ApiErrorCodeWorkflowRunNotFound workflow run id not found
	ApiErrorCodeWorkflowRunNotFound ApiErrorCode = "workflow_run_not_found"
	// ApiErrorCodeReportNotFound workflow run report PDF unavailable (not
	// report-enabled or no grounded closeout)
	ApiErrorCodeReportNotFound ApiErrorCode = "report_not_found"
	// ApiErrorCodeManagedSecretRevoked managed secret is permanently revoked
	ApiErrorCodeManagedSecretRevoked ApiErrorCode = "managed_secret_revoked"
	// ApiErrorCodeManagedSecretAgentUseExpired managed secret reference passed its
	// agent-use deadline
	ApiErrorCodeManagedSecretAgentUseExpired ApiErrorCode = "managed_secret_agent_use_expired"
	// ApiErrorCodePresenceUnavailable this app session has no trusted
	// user-presence verifier
	ApiErrorCodePresenceUnavailable ApiErrorCode = "presence_unavailable"
	// ApiErrorCodePresenceDenied a presence proof was refused
	ApiErrorCodePresenceDenied ApiErrorCode = "presence_denied"
	// ApiErrorCodePresenceRequired the chosen option releases values a person
	// holds and needs their verified presence
	ApiErrorCodePresenceRequired ApiErrorCode = "presence_required"
	// ApiErrorCodePresenceNotRequired the chosen option releases no value a person
	// holds, so it takes no presence challenge
	ApiErrorCodePresenceNotRequired ApiErrorCode = "presence_not_required"
	// ApiErrorCodePresenceChallengeNotFound a presence challenge was never issued,
	// expired, or was already used
	ApiErrorCodePresenceChallengeNotFound ApiErrorCode = "presence_challenge_not_found"
	// ApiErrorCodeManagedSecretValueChanged managed secret value changed after
	// presence verification began
	ApiErrorCodeManagedSecretValueChanged ApiErrorCode = "managed_secret_value_changed"
	// ApiErrorCodeManagedSecretValueUnavailable managed secret metadata stands but
	// its current value cannot be read
	ApiErrorCodeManagedSecretValueUnavailable ApiErrorCode = "managed_secret_value_unavailable"
	// ApiErrorCodeAuthUnavailable authenticated routes are unavailable because the
	// host has no API token or caller store
	ApiErrorCodeAuthUnavailable ApiErrorCode = "auth_unavailable"
	// ApiErrorCodeRecoverySnapshotInvalid the retained upgrade recovery snapshot
	// failed structural validation
	ApiErrorCodeRecoverySnapshotInvalid ApiErrorCode = "recovery_snapshot_invalid"
	// ApiErrorCodeSourceTextTooLarge source text exceeds the supported comparison
	// size
	ApiErrorCodeSourceTextTooLarge ApiErrorCode = "source_text_too_large"
	// ApiErrorCodeSourceContentTooLarge source content exceeds the editor's open
	// and save cap
	ApiErrorCodeSourceContentTooLarge ApiErrorCode = "source_content_too_large"
	// ApiErrorCodeSourceVersionChanged the file or retained edit changed after it
	// was opened; reload it
	ApiErrorCodeSourceVersionChanged ApiErrorCode = "source_version_changed"
	// ApiErrorCodeSourcePathAmbiguous a source path matches more than one attached
	// root
	ApiErrorCodeSourcePathAmbiguous ApiErrorCode = "source_path_ambiguous"
	// ApiErrorCodeFileOperationUnavailable the file operation's handler is no
	// longer available on this host
	ApiErrorCodeFileOperationUnavailable ApiErrorCode = "file_operation_unavailable"
	// ApiErrorCodeFileOperationCapacity the file operation queue is full;
	// Retry-After says when to retry
	ApiErrorCodeFileOperationCapacity ApiErrorCode = "file_operation_capacity"
	// ApiErrorCodeFileOperationNotCancelable the file operation has entered its
	// commit phase
	ApiErrorCodeFileOperationNotCancelable ApiErrorCode = "file_operation_not_cancelable"
	// ApiErrorCodeIgnoreFileChanged the project ignore file changed since it was
	// read; reload before saving
	ApiErrorCodeIgnoreFileChanged ApiErrorCode = "ignore_file_changed"
	// ApiErrorCodeStockPackImmutable stock extension packs and meta-packs cannot
	// be changed or removed
	ApiErrorCodeStockPackImmutable ApiErrorCode = "stock_pack_immutable"
	// ApiErrorCodeMessageReferencesChanged a message changed before its references
	// resolved
	ApiErrorCodeMessageReferencesChanged ApiErrorCode = "message_references_changed"
	// ApiErrorCodeChatContentChanged chat content changed since it was opened;
	// reopen it
	ApiErrorCodeChatContentChanged ApiErrorCode = "chat_content_changed"
	// ApiErrorCodeHistoryPreviewChanged history storage changed after the preview
	// was computed; preview again
	ApiErrorCodeHistoryPreviewChanged ApiErrorCode = "history_preview_changed"
	// ApiErrorCodePricingSourceInvalid a pricing source returned data that failed
	// validation
	ApiErrorCodePricingSourceInvalid ApiErrorCode = "pricing_source_invalid"
	// ApiErrorCodePricingSourceUnreachable a pricing source could not be reached
	ApiErrorCodePricingSourceUnreachable ApiErrorCode = "pricing_source_unreachable"
	// ApiErrorCodePricingSourceNotFound pricing source id is not configured
	ApiErrorCodePricingSourceNotFound ApiErrorCode = "pricing_source_not_found"
	// ApiErrorCodePricingSourceDisabled pricing source or cost tracking is
	// disabled
	ApiErrorCodePricingSourceDisabled ApiErrorCode = "pricing_source_disabled"
	// ApiErrorCodeSandboxSocketPathInvalid socket grant path is not an absolute,
	// clean path
	ApiErrorCodeSandboxSocketPathInvalid ApiErrorCode = "sandbox_socket_path_invalid"
	// ApiErrorCodeSandboxSocketPathNotFound socket grant path does not exist
	ApiErrorCodeSandboxSocketPathNotFound ApiErrorCode = "sandbox_socket_path_not_found"
	// ApiErrorCodeSandboxSocketPathNotSocket socket grant path is not a Unix
	// socket
	ApiErrorCodeSandboxSocketPathNotSocket ApiErrorCode = "sandbox_socket_path_not_socket"
	// ApiErrorCodeSandboxSocketPathRefused socket grant path could not be
	// inspected
	ApiErrorCodeSandboxSocketPathRefused ApiErrorCode = "sandbox_socket_path_refused"
	// ApiErrorCodeSandboxSocketPathLimit socket grant exceeded the socket path
	// limit
	ApiErrorCodeSandboxSocketPathLimit ApiErrorCode = "sandbox_socket_path_limit"
	// ApiErrorCodeSandboxSocketPathChanged socket grant path changed identity
	// while it was resolved
	ApiErrorCodeSandboxSocketPathChanged ApiErrorCode = "sandbox_socket_path_changed"
	// ApiErrorCodeAskUserRejected the ask was refused by the workflow;
	// details.reject_code names the tool rejection
	ApiErrorCodeAskUserRejected ApiErrorCode = "ask_user_rejected"
	// ApiErrorCodeWorkflowValidationFailed workflow manifest failed validation;
	// details.errors lists each diagnostic
	ApiErrorCodeWorkflowValidationFailed ApiErrorCode = "workflow_validation_failed"
	// ApiErrorCodeManagedSecretNotFound managed secret id not found
	ApiErrorCodeManagedSecretNotFound ApiErrorCode = "managed_secret_not_found"
	// ApiErrorCodeSourceHistoryNotFound source history, presentation, or baseline
	// pin not found
	ApiErrorCodeSourceHistoryNotFound ApiErrorCode = "source_history_not_found"
	// ApiErrorCodeSourcePresentationNotFound source presentation not found
	ApiErrorCodeSourcePresentationNotFound ApiErrorCode = "source_presentation_not_found"
	// ApiErrorCodeSourcePinNotFound source review or baseline pin not found
	ApiErrorCodeSourcePinNotFound ApiErrorCode = "source_pin_not_found"
	// ApiErrorCodeSourceEffectNotFound source effect (file edit) not found
	ApiErrorCodeSourceEffectNotFound ApiErrorCode = "source_effect_not_found"
	// ApiErrorCodeSourceVersionNotFound source version not found
	ApiErrorCodeSourceVersionNotFound ApiErrorCode = "source_version_not_found"
	// ApiErrorCodeSourceCommitNotFound commit not found in the repository serving
	// the addressed root
	ApiErrorCodeSourceCommitNotFound ApiErrorCode = "source_commit_not_found"
	// ApiErrorCodeSourceFileNotFound logical source file id not found
	ApiErrorCodeSourceFileNotFound ApiErrorCode = "source_file_not_found"
	// ApiErrorCodeGitMovementNotFound Git movement id not found
	ApiErrorCodeGitMovementNotFound ApiErrorCode = "git_movement_not_found"
	// ApiErrorCodeEditorDocumentNotFound editor document id not found
	ApiErrorCodeEditorDocumentNotFound ApiErrorCode = "editor_document_not_found"
	// ApiErrorCodeFileOperationNotFound file operation not found for this caller
	// and project
	ApiErrorCodeFileOperationNotFound ApiErrorCode = "file_operation_not_found"
	// ApiErrorCodeResearchProviderNotFound web research provider id not registered
	ApiErrorCodeResearchProviderNotFound ApiErrorCode = "research_provider_not_found"
	// ApiErrorCodeResearchCredentialNotFound web research credential not found
	ApiErrorCodeResearchCredentialNotFound ApiErrorCode = "research_credential_not_found"
	// ApiErrorCodeScannerNotFound scanner id not found in the catalog
	ApiErrorCodeScannerNotFound ApiErrorCode = "scanner_not_found"
	// ApiErrorCodeScannerCatalogEntryNotFound scanner catalog id not found
	ApiErrorCodeScannerCatalogEntryNotFound ApiErrorCode = "scanner_catalog_entry_not_found"
	// ApiErrorCodeDetectionPackNotFound detection pack id not found
	ApiErrorCodeDetectionPackNotFound ApiErrorCode = "detection_pack_not_found"
	// ApiErrorCodeHostResourceNotFound host resource id not found
	ApiErrorCodeHostResourceNotFound ApiErrorCode = "host_resource_not_found"
	// ApiErrorCodeIgnoreEntryNotFound ignore entry or declaration not found
	ApiErrorCodeIgnoreEntryNotFound ApiErrorCode = "ignore_entry_not_found"
	// ApiErrorCodeSecretReviewNotFound the secret review is no longer available
	ApiErrorCodeSecretReviewNotFound ApiErrorCode = "secret_review_not_found"
	// ApiErrorCodeExtensionPackNotFound extension pack not installed
	ApiErrorCodeExtensionPackNotFound ApiErrorCode = "extension_pack_not_found"
	// ApiErrorCodeExtensionUnitNotFound extension unit not found
	ApiErrorCodeExtensionUnitNotFound ApiErrorCode = "extension_unit_not_found"
	// ApiErrorCodeExtensionMetaPackNotFound extension meta-pack not found
	ApiErrorCodeExtensionMetaPackNotFound ApiErrorCode = "extension_meta_pack_not_found"
	// ApiErrorCodeExtensionProfileNotFound extension pack declares no profile with
	// this name
	ApiErrorCodeExtensionProfileNotFound ApiErrorCode = "extension_profile_not_found"
	// ApiErrorCodeExtensionSuggestionNotFound project extension suggestion not
	// found
	ApiErrorCodeExtensionSuggestionNotFound ApiErrorCode = "extension_suggestion_not_found"
	// ApiErrorCodeProjectRemovalNotFound project removal operation not found
	ApiErrorCodeProjectRemovalNotFound ApiErrorCode = "project_removal_not_found"
	// ApiErrorCodeChatContentNotFound chat content reference not found
	ApiErrorCodeChatContentNotFound ApiErrorCode = "chat_content_not_found"
	// ApiErrorCodeManualLlmRequestNotFound harness manual LLM request id is not
	// pending
	ApiErrorCodeManualLlmRequestNotFound ApiErrorCode = "manual_llm_request_not_found"
	// ApiErrorCodePreparationReceiptNotFound harness preparation has not reached
	// candidate entry
	ApiErrorCodePreparationReceiptNotFound ApiErrorCode = "preparation_receipt_not_found"
	// ApiErrorCodeHistoryProtectionNotFound history protection owner not found
	ApiErrorCodeHistoryProtectionNotFound ApiErrorCode = "history_protection_not_found"
)

var allApiErrorCodeValues = []ApiErrorCode{
	ApiErrorCodeSourceViewNotFound,
	ApiErrorCodeSourceViewRevisionChanged,
	ApiErrorCodeSourceViewCapacity,
	ApiErrorCodeSourceViewFrameTooLarge,
	ApiErrorCodeSourceViewPreparing,
	ApiErrorCodeTrustReviewChanged,
	ApiErrorCodeProjectInventoryUnavailable,
	ApiErrorCodeSourceAnalysisIncomplete,
	ApiErrorCodeSourceAnalysisUnavailable,
	ApiErrorCodeInvalidPageCursor,
	ApiErrorCodeUnsupportedMediaType,
	ApiErrorCodeMethodNotAllowed,
	ApiErrorCodeBackgroundProcessNotFound,
	ApiErrorCodeBodyTooLarge,
	ApiErrorCodePromptTextTooLarge,
	ApiErrorCodeDiagnosticsExportFailed,
	ApiErrorCodePricingNoSource,
	ApiErrorCodeBackupInvalid,
	ApiErrorCodeBackupIncomplete,
	ApiErrorCodeBackupIncompatible,
	ApiErrorCodeBackupUnavailable,
	ApiErrorCodeStoreIncompatible,
	ApiErrorCodeExportFormatInvalid,
	ApiErrorCodeCheckpointNotFound,
	ApiErrorCodeApprovalGrantNotFound,
	ApiErrorCodeSessionNotIdle,
	ApiErrorCodePromptRecoveryStale,
	ApiErrorCodeRewindAnchorNotFound,
	ApiErrorCodeRewindAnchorIneligible,
	ApiErrorCodeRewindBlocked,
	ApiErrorCodeRewindPlanChanged,
	ApiErrorCodeRewindModeUnsupported,
	ApiErrorCodeCloneFailed,
	ApiErrorCodeFolderExists,
	ApiErrorCodeFolderNotEmpty,
	ApiErrorCodeProjectMutationInProgress,
	ApiErrorCodePromotionConflict,
	ApiErrorCodePromotionNotFound,
	ApiErrorCodeDraftRootImmutable,
	ApiErrorCodeProjectBusy,
	ApiErrorCodeCheckpointNotPending,
	ApiErrorCodeDelegationNotFound,
	ApiErrorCodeDelegationLegNotFound,
	ApiErrorCodeFeedbackNotPending,
	ApiErrorCodeFeedbackResponseRequired,
	ApiErrorCodeFileBriefingDisabled,
	ApiErrorCodeFileBriefingNotFound,
	ApiErrorCodeFileBriefingUnavailable,
	ApiErrorCodeSourceVersionUnavailable,
	ApiErrorCodeChoiceTransitionNotFound,
	ApiErrorCodeChoiceTransitionActorDenied,
	ApiErrorCodeChoiceTransitionNotArmed,
	ApiErrorCodeChoiceTransitionPendingInput,
	ApiErrorCodeDecisionChoiceInvalid,
	ApiErrorCodeNotChoicePhase,
	ApiErrorCodeGitCheckoutFailed,
	ApiErrorCodeGitCommitFailed,
	ApiErrorCodeGitDiscardFailed,
	ApiErrorCodeGitInitFailed,
	ApiErrorCodeGitPullFailed,
	ApiErrorCodeGitPushFailed,
	ApiErrorCodeGitNoChanges,
	ApiErrorCodeGitDraftFailed,
	ApiErrorCodeGitRepoNotFound,
	ApiErrorCodeGitStashFailed,
	ApiErrorCodeWorktreeNotBound,
	ApiErrorCodeWorktreeAlreadyBound,
	ApiErrorCodeWorktreeBranchExists,
	ApiErrorCodeWorktreeDirty,
	ApiErrorCodeWorktreeStale,
	ApiErrorCodeWorktreeLandBlocked,
	ApiErrorCodeInternalError,
	ApiErrorCodeInvalidJson,
	ApiErrorCodeInvalidPath,
	ApiErrorCodeWriteRootIsFilesystemRoot,
	ApiErrorCodeWriteRootIsHome,
	ApiErrorCodeWriteRootNotAbsolute,
	ApiErrorCodeWriteRootUnderSecretStore,
	ApiErrorCodeBlueprintContentConflict,
	ApiErrorCodeIdempotencyConflict,
	ApiErrorCodeInvalidArguments,
	ApiErrorCodeInvalidQuery,
	ApiErrorCodeCommandDisabled,
	ApiErrorCodeChoiceSourceNotFound,
	ApiErrorCodeChoiceSourceFailed,
	ApiErrorCodeChoiceSourceInvalid,
	ApiErrorCodeContributionSourceUnavailable,
	ApiErrorCodeSearchSourceNotFound,
	ApiErrorCodeContributionSearchFailed,
	ApiErrorCodeContributionSearchInvalid,
	ApiErrorCodeOperationOutputInvalid,
	ApiErrorCodeSourceMutationDiverged,
	ApiErrorCodeSourceHistoryChanged,
	ApiErrorCodeWorkflowRunNotActive,
	ApiErrorCodeCursorGenerationExpired,
	ApiErrorCodeEventReplayUnavailable,
	ApiErrorCodeInvalidRequest,
	ApiErrorCodeProviderCatalogUnavailable,
	ApiErrorCodeInvalidWorkflowTransition,
	ApiErrorCodeInvalidWorkflowTarget,
	ApiErrorCodeInvalidWorkflowRevision,
	ApiErrorCodeInvalidWorkflowReplacementTarget,
	ApiErrorCodeMessageNotFound,
	ApiErrorCodeNotFound,
	ApiErrorCodePathNotFound,
	ApiErrorCodePersistNotConfirmed,
	ApiErrorCodePhaseGateUnmet,
	ApiErrorCodeBlueprintNotDraft,
	ApiErrorCodeBlueprintNotEditable,
	ApiErrorCodeBlueprintNotFound,
	ApiErrorCodeBlueprintPathTaken,
	ApiErrorCodeBlueprintRunActive,
	ApiErrorCodeDetectionPackNotRemovable,
	ApiErrorCodeDetectionPackIdCollision,
	ApiErrorCodeBlueprintLaunchIncompatible,
	ApiErrorCodeBlueprintLaunchUnsupported,
	ApiErrorCodeHumanApprovalNotReady,
	ApiErrorCodeProjectNotFound,
	ApiErrorCodeExtensionSuggestionChanged,
	ApiErrorCodeExtensionSuggestionInvalid,
	ApiErrorCodeOverlayFormatUnsupported,
	ApiErrorCodeOverlayFormatInvalid,
	ApiErrorCodeProjectApprovalsNeedRepair,
	ApiErrorCodeRootNotFound,
	ApiErrorCodeRootBusy,
	ApiErrorCodeDuplicateRoot,
	ApiErrorCodeDuplicateRootLabel,
	ApiErrorCodeProjectRemovalAssessmentChanged,
	ApiErrorCodeProjectRemovalOperationConflict,
	ApiErrorCodeExtensionStateChanged,
	ApiErrorCodeExtensionCandidateRejected,
	ApiErrorCodeContributionsUnavailable,
	ApiErrorCodeCommandNotFound,
	ApiErrorCodeInvocationScopeMismatch,
	ApiErrorCodeContributionFrameChanged,
	ApiErrorCodeCommandUnavailable,
	ApiErrorCodeContributionNotAuthorized,
	ApiErrorCodeMcpCallFailed,
	ApiErrorCodePathMissing,
	ApiErrorCodeTrustSurfaceOff,
	ApiErrorCodeArtifactEmpty,
	ApiErrorCodeArtifactTooLarge,
	ApiErrorCodeArtifactForeign,
	ApiErrorCodeArtifactUnavailable,
	ApiErrorCodeArtifactDeleted,
	ApiErrorCodeArtifactNotFound,
	ApiErrorCodeBackupRestorePending,
	ApiErrorCodeRecordingDurationInvalid,
	ApiErrorCodeRecordingStartInvalid,
	ApiErrorCodeUserImageNotVisible,
	ApiErrorCodeUnsupportedAttachment,
	ApiErrorCodeAttachmentTooLarge,
	ApiErrorCodeAttachmentUndecodable,
	ApiErrorCodeAttachmentNotFound,
	ApiErrorCodeAttachmentUnavailable,
	ApiErrorCodeReferenceOutOfJail,
	ApiErrorCodeAttachmentScannedNoText,
	ApiErrorCodeNoProjectRoot,
	ApiErrorCodeSourcePathDenied,
	ApiErrorCodeSourcePathProtected,
	ApiErrorCodeSourceMoveIncomplete,
	ApiErrorCodeSourcePathBusy,
	ApiErrorCodeSourceRecoveryFailed,
	ApiErrorCodeSourceNotFound,
	ApiErrorCodeSourceBinaryDenied,
	ApiErrorCodeSourceReadOnly,
	ApiErrorCodeSourceBinary,
	ApiErrorCodeUnsupportedEncoding,
	ApiErrorCodeSourceRawNotImage,
	ApiErrorCodeSourceRawTooLarge,
	ApiErrorCodeSourceWorkspaceMismatch,
	ApiErrorCodeSourceWriteConflict,
	ApiErrorCodeSourcePermissionChangeFailed,
	ApiErrorCodeEditorRevisionConflict,
	ApiErrorCodeEditorReplicaEpoch,
	ApiErrorCodeEditorReplicaIdentity,
	ApiErrorCodeEditorRootDetached,
	ApiErrorCodeSourcePresentationEffectChanged,
	ApiErrorCodeSourceAlreadyExists,
	ApiErrorCodeSourceCrossRoot,
	ApiErrorCodeSourceNotEmpty,
	ApiErrorCodeSourceInventoryPending,
	ApiErrorCodeSourceTrashFailed,
	ApiErrorCodeSourceUnavailable,
	ApiErrorCodeProjectPolicyDenied,
	ApiErrorCodeProviderNotFound,
	ApiErrorCodeProviderInUse,
	ApiErrorCodeProviderNotConfigured,
	ApiErrorCodeProviderEmptyCompletion,
	ApiErrorCodeProviderResponseInterrupted,
	ApiErrorCodeProviderContextTooSmall,
	ApiErrorCodeProviderToolCallsUnsupported,
	ApiErrorCodeProviderToolCallsInProse,
	ApiErrorCodeProviderRateLimited,
	ApiErrorCodeProviderOverloaded,
	ApiErrorCodeProviderServerError,
	ApiErrorCodeThinkingOverrideUnavailable,
	ApiErrorCodeProviderRequestRejected,
	ApiErrorCodeProviderUnreachable,
	ApiErrorCodeProviderSilent,
	ApiErrorCodeModelRefused,
	ApiErrorCodeModelCatalogUnreachable,
	ApiErrorCodeModelCatalogRefreshFailed,
	ApiErrorCodeMcpProviderUnreachable,
	ApiErrorCodeMcpSyncFailed,
	ApiErrorCodeMcpToolPinUnreadable,
	ApiErrorCodeMcpIdRequired,
	ApiErrorCodeMcpTransportRequired,
	ApiErrorCodeMcpTransportConflict,
	ApiErrorCodeMcpProviderNotFound,
	ApiErrorCodeMcpUpdateEmpty,
	ApiErrorCodeMcpOauthUnavailable,
	ApiErrorCodeMcpOauthFailed,
	ApiErrorCodeMcpOauthNotSupported,
	ApiErrorCodeMcpOauthRegistrationRequired,
	ApiErrorCodeMcpRecipeNotFound,
	ApiErrorCodeMcpPersistFailed,
	ApiErrorCodeRemoteRequiresHttps,
	ApiErrorCodeInvalidUrl,
	ApiErrorCodeProjectStdioForbidden,
	ApiErrorCodeProjectHeadersForbidden,
	ApiErrorCodeProjectRemoteForbidden,
	ApiErrorCodeProjectEnableForbidden,
	ApiErrorCodeOverlayUnknownField,
	ApiErrorCodeUnreadableLayer,
	ApiErrorCodeRateLimited,
	ApiErrorCodeQueueRevisionConflict,
	ApiErrorCodeQueueEmpty,
	ApiErrorCodeQueueSendPending,
	ApiErrorCodeQueueSendReserved,
	ApiErrorCodeQueueNoSendToCancel,
	ApiErrorCodeScanNotComplete,
	ApiErrorCodeScanNotFound,
	ApiErrorCodeNoScannerAvailable,
	ApiErrorCodeInvalidEntry,
	ApiErrorCodeCommunityDriverForbidden,
	ApiErrorCodeCommunityParserForbidden,
	ApiErrorCodeMapperMissing,
	ApiErrorCodeProjectFieldsForbidden,
	ApiErrorCodeArgvProjectPathForbidden,
	ApiErrorCodeArgvShellForbidden,
	ApiErrorCodeDuplicateId,
	ApiErrorCodeSearchQueryInvalid,
	ApiErrorCodeSearchPatternInvalid,
	ApiErrorCodeSearchExportInvalidFormat,
	ApiErrorCodeSearchExportSarifScope,
	ApiErrorCodeSecurityDisabled,
	ApiErrorCodeGroundingEscalated,
	ApiErrorCodeSessionSpendCeilingReached,
	ApiErrorCodePromptFailed,
	ApiErrorCodeTurnCloseoutToolCall,
	ApiErrorCodeHostFault,
	ApiErrorCodeWorkerCloseoutExhausted,
	ApiErrorCodeWorkerExecuteFailed,
	ApiErrorCodeWorkerWorkspaceDiskFull,
	ApiErrorCodeWorkerOwnerUnsettled,
	ApiErrorCodeWorkerWorkspaceUnavailable,
	ApiErrorCodeSessionArchived,
	ApiErrorCodeSessionNotFound,
	ApiErrorCodeSessionNotPinned,
	ApiErrorCodeSessionPreparationFailed,
	ApiErrorCodeSessionPreparing,
	ApiErrorCodeSessionStopping,
	ApiErrorCodeSessionWorkflowNotFound,
	ApiErrorCodeUnauthorized,
	ApiErrorCodeForbidden,
	ApiErrorCodeWorkerNotFound,
	ApiErrorCodeWorkerNotCancelable,
	ApiErrorCodeLegNotPending,
	ApiErrorCodeDecisionNotPending,
	ApiErrorCodeWorkflowActive,
	ApiErrorCodeWorkflowRevisionConflict,
	ApiErrorCodeWorkflowReplacementTargetRequired,
	ApiErrorCodeWorkflowStartRequiresHumanApproval,
	ApiErrorCodeBlueprintDraftRequired,
	ApiErrorCodeWorkflowNotFound,
	ApiErrorCodeWorkflowNotRunnable,
	ApiErrorCodeWorkflowVersionUnavailable,
	ApiErrorCodeWorkflowRunNotFound,
	ApiErrorCodeReportNotFound,
	ApiErrorCodeManagedSecretRevoked,
	ApiErrorCodeManagedSecretAgentUseExpired,
	ApiErrorCodePresenceUnavailable,
	ApiErrorCodePresenceDenied,
	ApiErrorCodePresenceRequired,
	ApiErrorCodePresenceNotRequired,
	ApiErrorCodePresenceChallengeNotFound,
	ApiErrorCodeManagedSecretValueChanged,
	ApiErrorCodeManagedSecretValueUnavailable,
	ApiErrorCodeAuthUnavailable,
	ApiErrorCodeRecoverySnapshotInvalid,
	ApiErrorCodeSourceTextTooLarge,
	ApiErrorCodeSourceContentTooLarge,
	ApiErrorCodeSourceVersionChanged,
	ApiErrorCodeSourcePathAmbiguous,
	ApiErrorCodeFileOperationUnavailable,
	ApiErrorCodeFileOperationCapacity,
	ApiErrorCodeFileOperationNotCancelable,
	ApiErrorCodeIgnoreFileChanged,
	ApiErrorCodeStockPackImmutable,
	ApiErrorCodeMessageReferencesChanged,
	ApiErrorCodeChatContentChanged,
	ApiErrorCodeHistoryPreviewChanged,
	ApiErrorCodePricingSourceInvalid,
	ApiErrorCodePricingSourceUnreachable,
	ApiErrorCodePricingSourceNotFound,
	ApiErrorCodePricingSourceDisabled,
	ApiErrorCodeSandboxSocketPathInvalid,
	ApiErrorCodeSandboxSocketPathNotFound,
	ApiErrorCodeSandboxSocketPathNotSocket,
	ApiErrorCodeSandboxSocketPathRefused,
	ApiErrorCodeSandboxSocketPathLimit,
	ApiErrorCodeSandboxSocketPathChanged,
	ApiErrorCodeAskUserRejected,
	ApiErrorCodeWorkflowValidationFailed,
	ApiErrorCodeManagedSecretNotFound,
	ApiErrorCodeSourceHistoryNotFound,
	ApiErrorCodeSourcePresentationNotFound,
	ApiErrorCodeSourcePinNotFound,
	ApiErrorCodeSourceEffectNotFound,
	ApiErrorCodeSourceVersionNotFound,
	ApiErrorCodeSourceCommitNotFound,
	ApiErrorCodeSourceFileNotFound,
	ApiErrorCodeGitMovementNotFound,
	ApiErrorCodeEditorDocumentNotFound,
	ApiErrorCodeFileOperationNotFound,
	ApiErrorCodeResearchProviderNotFound,
	ApiErrorCodeResearchCredentialNotFound,
	ApiErrorCodeScannerNotFound,
	ApiErrorCodeScannerCatalogEntryNotFound,
	ApiErrorCodeDetectionPackNotFound,
	ApiErrorCodeHostResourceNotFound,
	ApiErrorCodeIgnoreEntryNotFound,
	ApiErrorCodeSecretReviewNotFound,
	ApiErrorCodeExtensionPackNotFound,
	ApiErrorCodeExtensionUnitNotFound,
	ApiErrorCodeExtensionMetaPackNotFound,
	ApiErrorCodeExtensionProfileNotFound,
	ApiErrorCodeExtensionSuggestionNotFound,
	ApiErrorCodeProjectRemovalNotFound,
	ApiErrorCodeChatContentNotFound,
	ApiErrorCodeManualLlmRequestNotFound,
	ApiErrorCodePreparationReceiptNotFound,
	ApiErrorCodeHistoryProtectionNotFound,
}

// AllApiErrorCodeValues returns every ApiErrorCode in vocab order.
func AllApiErrorCodeValues() []ApiErrorCode {
	return append([]ApiErrorCode(nil), allApiErrorCodeValues...)
}

// HTTPStatus returns the HTTP status declared for c. A value outside the
// vocabulary answers 500: no handler may invent a code.
func (c ApiErrorCode) HTTPStatus() int {
	switch c {
	case ApiErrorCodeInvalidPageCursor,
		ApiErrorCodePricingNoSource,
		ApiErrorCodeBackupInvalid,
		ApiErrorCodeExportFormatInvalid,
		ApiErrorCodeInvalidJson,
		ApiErrorCodeInvalidPath,
		ApiErrorCodeWriteRootIsFilesystemRoot,
		ApiErrorCodeWriteRootIsHome,
		ApiErrorCodeWriteRootNotAbsolute,
		ApiErrorCodeWriteRootUnderSecretStore,
		ApiErrorCodeInvalidArguments,
		ApiErrorCodeInvalidQuery,
		ApiErrorCodeInvalidRequest,
		ApiErrorCodeInvalidWorkflowTarget,
		ApiErrorCodeInvalidWorkflowRevision,
		ApiErrorCodeInvalidWorkflowReplacementTarget,
		ApiErrorCodeBlueprintLaunchIncompatible,
		ApiErrorCodeBlueprintLaunchUnsupported,
		ApiErrorCodeExtensionCandidateRejected,
		ApiErrorCodeInvocationScopeMismatch,
		ApiErrorCodePathMissing,
		ApiErrorCodeArtifactEmpty,
		ApiErrorCodeRecordingDurationInvalid,
		ApiErrorCodeRecordingStartInvalid,
		ApiErrorCodeUnsupportedAttachment,
		ApiErrorCodeAttachmentUndecodable,
		ApiErrorCodeAttachmentNotFound,
		ApiErrorCodeReferenceOutOfJail,
		ApiErrorCodeSourceCrossRoot,
		ApiErrorCodeMcpIdRequired,
		ApiErrorCodeMcpTransportRequired,
		ApiErrorCodeMcpTransportConflict,
		ApiErrorCodeMcpUpdateEmpty,
		ApiErrorCodeMcpOauthNotSupported,
		ApiErrorCodeMcpOauthRegistrationRequired,
		ApiErrorCodeRemoteRequiresHttps,
		ApiErrorCodeInvalidUrl,
		ApiErrorCodeProjectStdioForbidden,
		ApiErrorCodeProjectHeadersForbidden,
		ApiErrorCodeProjectRemoteForbidden,
		ApiErrorCodeProjectEnableForbidden,
		ApiErrorCodeOverlayUnknownField,
		ApiErrorCodeUnreadableLayer,
		ApiErrorCodeInvalidEntry,
		ApiErrorCodeCommunityDriverForbidden,
		ApiErrorCodeCommunityParserForbidden,
		ApiErrorCodeMapperMissing,
		ApiErrorCodeProjectFieldsForbidden,
		ApiErrorCodeArgvProjectPathForbidden,
		ApiErrorCodeArgvShellForbidden,
		ApiErrorCodeSearchQueryInvalid,
		ApiErrorCodeSearchPatternInvalid,
		ApiErrorCodeSearchExportInvalidFormat,
		ApiErrorCodeSearchExportSarifScope,
		ApiErrorCodeBlueprintDraftRequired,
		ApiErrorCodeSandboxSocketPathInvalid,
		ApiErrorCodeSandboxSocketPathNotFound,
		ApiErrorCodeSandboxSocketPathNotSocket,
		ApiErrorCodeSandboxSocketPathRefused,
		ApiErrorCodeSandboxSocketPathLimit,
		ApiErrorCodeSandboxSocketPathChanged:
		return 400
	case ApiErrorCodeUnauthorized:
		return 401
	case ApiErrorCodeChoiceTransitionActorDenied,
		ApiErrorCodePersistNotConfirmed,
		ApiErrorCodeContributionNotAuthorized,
		ApiErrorCodeArtifactForeign,
		ApiErrorCodeSourcePathDenied,
		ApiErrorCodeSourcePathProtected,
		ApiErrorCodeSourceReadOnly,
		ApiErrorCodeProjectPolicyDenied,
		ApiErrorCodeForbidden,
		ApiErrorCodeWorkflowStartRequiresHumanApproval,
		ApiErrorCodePresenceDenied,
		ApiErrorCodePresenceRequired:
		return 403
	case ApiErrorCodeSourceViewNotFound,
		ApiErrorCodeBackgroundProcessNotFound,
		ApiErrorCodeCheckpointNotFound,
		ApiErrorCodeApprovalGrantNotFound,
		ApiErrorCodeRewindAnchorNotFound,
		ApiErrorCodePromotionNotFound,
		ApiErrorCodeDelegationNotFound,
		ApiErrorCodeDelegationLegNotFound,
		ApiErrorCodeFileBriefingNotFound,
		ApiErrorCodeChoiceTransitionNotFound,
		ApiErrorCodeGitRepoNotFound,
		ApiErrorCodeChoiceSourceNotFound,
		ApiErrorCodeSearchSourceNotFound,
		ApiErrorCodeMessageNotFound,
		ApiErrorCodeNotFound,
		ApiErrorCodePathNotFound,
		ApiErrorCodeBlueprintNotFound,
		ApiErrorCodeProjectNotFound,
		ApiErrorCodeRootNotFound,
		ApiErrorCodeCommandNotFound,
		ApiErrorCodeArtifactNotFound,
		ApiErrorCodeSourceNotFound,
		ApiErrorCodeProviderNotFound,
		ApiErrorCodeMcpProviderNotFound,
		ApiErrorCodeMcpRecipeNotFound,
		ApiErrorCodeScanNotFound,
		ApiErrorCodeSessionNotFound,
		ApiErrorCodeSessionWorkflowNotFound,
		ApiErrorCodeWorkerNotFound,
		ApiErrorCodeWorkflowNotFound,
		ApiErrorCodeWorkflowRunNotFound,
		ApiErrorCodeReportNotFound,
		ApiErrorCodePresenceChallengeNotFound,
		ApiErrorCodePricingSourceNotFound,
		ApiErrorCodeManagedSecretNotFound,
		ApiErrorCodeSourceHistoryNotFound,
		ApiErrorCodeSourcePresentationNotFound,
		ApiErrorCodeSourcePinNotFound,
		ApiErrorCodeSourceEffectNotFound,
		ApiErrorCodeSourceVersionNotFound,
		ApiErrorCodeSourceCommitNotFound,
		ApiErrorCodeSourceFileNotFound,
		ApiErrorCodeGitMovementNotFound,
		ApiErrorCodeEditorDocumentNotFound,
		ApiErrorCodeFileOperationNotFound,
		ApiErrorCodeResearchProviderNotFound,
		ApiErrorCodeResearchCredentialNotFound,
		ApiErrorCodeScannerNotFound,
		ApiErrorCodeScannerCatalogEntryNotFound,
		ApiErrorCodeDetectionPackNotFound,
		ApiErrorCodeHostResourceNotFound,
		ApiErrorCodeIgnoreEntryNotFound,
		ApiErrorCodeSecretReviewNotFound,
		ApiErrorCodeExtensionPackNotFound,
		ApiErrorCodeExtensionUnitNotFound,
		ApiErrorCodeExtensionMetaPackNotFound,
		ApiErrorCodeExtensionProfileNotFound,
		ApiErrorCodeExtensionSuggestionNotFound,
		ApiErrorCodeProjectRemovalNotFound,
		ApiErrorCodeChatContentNotFound,
		ApiErrorCodeManualLlmRequestNotFound,
		ApiErrorCodePreparationReceiptNotFound,
		ApiErrorCodeHistoryProtectionNotFound:
		return 404
	case ApiErrorCodeMethodNotAllowed:
		return 405
	case ApiErrorCodeSourceViewRevisionChanged,
		ApiErrorCodeSourceViewPreparing,
		ApiErrorCodeTrustReviewChanged,
		ApiErrorCodeBackupIncomplete,
		ApiErrorCodeBackupIncompatible,
		ApiErrorCodeSessionNotIdle,
		ApiErrorCodePromptRecoveryStale,
		ApiErrorCodeRewindBlocked,
		ApiErrorCodeRewindPlanChanged,
		ApiErrorCodeFolderExists,
		ApiErrorCodeFolderNotEmpty,
		ApiErrorCodeProjectMutationInProgress,
		ApiErrorCodePromotionConflict,
		ApiErrorCodeDraftRootImmutable,
		ApiErrorCodeProjectBusy,
		ApiErrorCodeCheckpointNotPending,
		ApiErrorCodeFeedbackNotPending,
		ApiErrorCodeFileBriefingDisabled,
		ApiErrorCodeChoiceTransitionNotArmed,
		ApiErrorCodeChoiceTransitionPendingInput,
		ApiErrorCodeNotChoicePhase,
		ApiErrorCodeWorktreeNotBound,
		ApiErrorCodeWorktreeAlreadyBound,
		ApiErrorCodeWorktreeBranchExists,
		ApiErrorCodeWorktreeDirty,
		ApiErrorCodeWorktreeStale,
		ApiErrorCodeWorktreeLandBlocked,
		ApiErrorCodeBlueprintContentConflict,
		ApiErrorCodeIdempotencyConflict,
		ApiErrorCodeCommandDisabled,
		ApiErrorCodeContributionSourceUnavailable,
		ApiErrorCodeSourceMutationDiverged,
		ApiErrorCodeSourceHistoryChanged,
		ApiErrorCodeWorkflowRunNotActive,
		ApiErrorCodeCursorGenerationExpired,
		ApiErrorCodeEventReplayUnavailable,
		ApiErrorCodeInvalidWorkflowTransition,
		ApiErrorCodePhaseGateUnmet,
		ApiErrorCodeBlueprintNotDraft,
		ApiErrorCodeBlueprintNotEditable,
		ApiErrorCodeBlueprintPathTaken,
		ApiErrorCodeBlueprintRunActive,
		ApiErrorCodeDetectionPackNotRemovable,
		ApiErrorCodeDetectionPackIdCollision,
		ApiErrorCodeHumanApprovalNotReady,
		ApiErrorCodeExtensionSuggestionChanged,
		ApiErrorCodeExtensionSuggestionInvalid,
		ApiErrorCodeOverlayFormatUnsupported,
		ApiErrorCodeOverlayFormatInvalid,
		ApiErrorCodeProjectApprovalsNeedRepair,
		ApiErrorCodeRootBusy,
		ApiErrorCodeDuplicateRoot,
		ApiErrorCodeDuplicateRootLabel,
		ApiErrorCodeProjectRemovalAssessmentChanged,
		ApiErrorCodeProjectRemovalOperationConflict,
		ApiErrorCodeExtensionStateChanged,
		ApiErrorCodeContributionFrameChanged,
		ApiErrorCodeCommandUnavailable,
		ApiErrorCodeTrustSurfaceOff,
		ApiErrorCodeBackupRestorePending,
		ApiErrorCodeNoProjectRoot,
		ApiErrorCodeSourcePathBusy,
		ApiErrorCodeSourceWorkspaceMismatch,
		ApiErrorCodeSourceWriteConflict,
		ApiErrorCodeEditorRevisionConflict,
		ApiErrorCodeEditorReplicaEpoch,
		ApiErrorCodeEditorReplicaIdentity,
		ApiErrorCodeEditorRootDetached,
		ApiErrorCodeSourcePresentationEffectChanged,
		ApiErrorCodeSourceAlreadyExists,
		ApiErrorCodeSourceNotEmpty,
		ApiErrorCodeSourceInventoryPending,
		ApiErrorCodeProviderInUse,
		ApiErrorCodeProviderNotConfigured,
		ApiErrorCodeQueueRevisionConflict,
		ApiErrorCodeQueueEmpty,
		ApiErrorCodeQueueSendPending,
		ApiErrorCodeQueueSendReserved,
		ApiErrorCodeQueueNoSendToCancel,
		ApiErrorCodeScanNotComplete,
		ApiErrorCodeNoScannerAvailable,
		ApiErrorCodeDuplicateId,
		ApiErrorCodeSecurityDisabled,
		ApiErrorCodeGroundingEscalated,
		ApiErrorCodeSessionSpendCeilingReached,
		ApiErrorCodeSessionArchived,
		ApiErrorCodeSessionNotPinned,
		ApiErrorCodeSessionPreparing,
		ApiErrorCodeSessionStopping,
		ApiErrorCodeWorkerNotCancelable,
		ApiErrorCodeLegNotPending,
		ApiErrorCodeDecisionNotPending,
		ApiErrorCodeWorkflowActive,
		ApiErrorCodeWorkflowRevisionConflict,
		ApiErrorCodeWorkflowReplacementTargetRequired,
		ApiErrorCodeWorkflowNotRunnable,
		ApiErrorCodeWorkflowVersionUnavailable,
		ApiErrorCodeManagedSecretRevoked,
		ApiErrorCodeManagedSecretAgentUseExpired,
		ApiErrorCodePresenceNotRequired,
		ApiErrorCodeManagedSecretValueChanged,
		ApiErrorCodeManagedSecretValueUnavailable,
		ApiErrorCodeRecoverySnapshotInvalid,
		ApiErrorCodeSourceVersionChanged,
		ApiErrorCodeSourcePathAmbiguous,
		ApiErrorCodeFileOperationUnavailable,
		ApiErrorCodeFileOperationNotCancelable,
		ApiErrorCodeIgnoreFileChanged,
		ApiErrorCodeStockPackImmutable,
		ApiErrorCodeMessageReferencesChanged,
		ApiErrorCodeChatContentChanged,
		ApiErrorCodeHistoryPreviewChanged,
		ApiErrorCodePricingSourceDisabled,
		ApiErrorCodeAskUserRejected:
		return 409
	case ApiErrorCodeArtifactUnavailable,
		ApiErrorCodeArtifactDeleted:
		return 410
	case ApiErrorCodeSourceViewFrameTooLarge,
		ApiErrorCodeBodyTooLarge,
		ApiErrorCodePromptTextTooLarge,
		ApiErrorCodeArtifactTooLarge,
		ApiErrorCodeAttachmentTooLarge,
		ApiErrorCodeSourceRawTooLarge,
		ApiErrorCodeSourceTextTooLarge,
		ApiErrorCodeSourceContentTooLarge:
		return 413
	case ApiErrorCodeUnsupportedMediaType,
		ApiErrorCodeSourceBinaryDenied,
		ApiErrorCodeSourceBinary,
		ApiErrorCodeUnsupportedEncoding,
		ApiErrorCodeSourceRawNotImage:
		return 415
	case ApiErrorCodeRewindAnchorIneligible,
		ApiErrorCodeRewindModeUnsupported,
		ApiErrorCodeFeedbackResponseRequired,
		ApiErrorCodeSourceVersionUnavailable,
		ApiErrorCodeDecisionChoiceInvalid,
		ApiErrorCodeGitCheckoutFailed,
		ApiErrorCodeGitCommitFailed,
		ApiErrorCodeGitDiscardFailed,
		ApiErrorCodeGitInitFailed,
		ApiErrorCodeGitPullFailed,
		ApiErrorCodeGitPushFailed,
		ApiErrorCodeGitNoChanges,
		ApiErrorCodeGitStashFailed,
		ApiErrorCodeUserImageNotVisible,
		ApiErrorCodeAttachmentScannedNoText,
		ApiErrorCodeSourcePermissionChangeFailed,
		ApiErrorCodeProviderContextTooSmall,
		ApiErrorCodeProviderToolCallsUnsupported,
		ApiErrorCodeThinkingOverrideUnavailable,
		ApiErrorCodeModelRefused,
		ApiErrorCodeWorkflowValidationFailed:
		return 422
	case ApiErrorCodeRateLimited,
		ApiErrorCodeFileOperationCapacity:
		return 429
	case ApiErrorCodeDiagnosticsExportFailed,
		ApiErrorCodeInternalError,
		ApiErrorCodeSourceMoveIncomplete,
		ApiErrorCodeSourceRecoveryFailed,
		ApiErrorCodeSourceTrashFailed,
		ApiErrorCodeMcpToolPinUnreadable,
		ApiErrorCodeMcpPersistFailed,
		ApiErrorCodePromptFailed,
		ApiErrorCodeTurnCloseoutToolCall,
		ApiErrorCodeHostFault,
		ApiErrorCodeWorkerCloseoutExhausted,
		ApiErrorCodeWorkerExecuteFailed,
		ApiErrorCodeWorkerOwnerUnsettled,
		ApiErrorCodeSessionPreparationFailed:
		return 500
	case ApiErrorCodeCloneFailed,
		ApiErrorCodeChoiceSourceFailed,
		ApiErrorCodeChoiceSourceInvalid,
		ApiErrorCodeContributionSearchFailed,
		ApiErrorCodeContributionSearchInvalid,
		ApiErrorCodeOperationOutputInvalid,
		ApiErrorCodeMcpCallFailed,
		ApiErrorCodeProviderEmptyCompletion,
		ApiErrorCodeProviderResponseInterrupted,
		ApiErrorCodeProviderToolCallsInProse,
		ApiErrorCodeProviderServerError,
		ApiErrorCodeProviderRequestRejected,
		ApiErrorCodeProviderUnreachable,
		ApiErrorCodeModelCatalogRefreshFailed,
		ApiErrorCodeMcpSyncFailed,
		ApiErrorCodeMcpOauthFailed,
		ApiErrorCodePricingSourceInvalid,
		ApiErrorCodePricingSourceUnreachable:
		return 502
	case ApiErrorCodeSourceViewCapacity,
		ApiErrorCodeProjectInventoryUnavailable,
		ApiErrorCodeSourceAnalysisIncomplete,
		ApiErrorCodeSourceAnalysisUnavailable,
		ApiErrorCodeBackupUnavailable,
		ApiErrorCodeStoreIncompatible,
		ApiErrorCodeFileBriefingUnavailable,
		ApiErrorCodeGitDraftFailed,
		ApiErrorCodeProviderCatalogUnavailable,
		ApiErrorCodeContributionsUnavailable,
		ApiErrorCodeAttachmentUnavailable,
		ApiErrorCodeSourceUnavailable,
		ApiErrorCodeProviderRateLimited,
		ApiErrorCodeProviderOverloaded,
		ApiErrorCodeModelCatalogUnreachable,
		ApiErrorCodeMcpProviderUnreachable,
		ApiErrorCodeMcpOauthUnavailable,
		ApiErrorCodeWorkerWorkspaceUnavailable,
		ApiErrorCodePresenceUnavailable,
		ApiErrorCodeAuthUnavailable:
		return 503
	case ApiErrorCodeProviderSilent:
		return 504
	case ApiErrorCodeWorkerWorkspaceDiskFull:
		return 507
	default:
		return 500
	}
}
