// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/ElevatedAccessEffect.yaml

package api

// ElevatedAccessEffect — Authority beyond a major confinement boundary.
type ElevatedAccessEffect string

const (
	ElevatedAccessEffectDirectNetwork  ElevatedAccessEffect = "direct_network"
	ElevatedAccessEffectHostExecution  ElevatedAccessEffect = "host_execution"
	ElevatedAccessEffectProcessControl ElevatedAccessEffect = "process_control"
	ElevatedAccessEffectLocalService   ElevatedAccessEffect = "local_service"
)

var allElevatedAccessEffectValues = []ElevatedAccessEffect{
	ElevatedAccessEffectDirectNetwork,
	ElevatedAccessEffectHostExecution,
	ElevatedAccessEffectProcessControl,
	ElevatedAccessEffectLocalService,
}

// AllElevatedAccessEffectValues returns every ElevatedAccessEffect in vocab order.
func AllElevatedAccessEffectValues() []ElevatedAccessEffect {
	return append([]ElevatedAccessEffect(nil), allElevatedAccessEffectValues...)
}
