// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/FindingDisposition.yaml

package api

// FindingDisposition is a closed wire enum from docs/openapi/vocab.
type FindingDisposition string

const (
	FindingDispositionFix          FindingDisposition = "fix"
	FindingDispositionFP           FindingDisposition = "fp"
	FindingDispositionDefer        FindingDisposition = "defer"
	FindingDispositionAcceptedRisk FindingDisposition = "accepted_risk"
	FindingDispositionHuman        FindingDisposition = "human"
)

var allFindingDispositionValues = []FindingDisposition{
	FindingDispositionFix,
	FindingDispositionFP,
	FindingDispositionDefer,
	FindingDispositionAcceptedRisk,
	FindingDispositionHuman,
}

// AllFindingDispositionValues returns every FindingDisposition in vocab order.
func AllFindingDispositionValues() []FindingDisposition {
	return append([]FindingDisposition(nil), allFindingDispositionValues...)
}
