// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/FindingLedgerState.yaml

package api

// FindingLedgerState — Whether a finding is currently reported, and when it is not, whether its absence is evidence of anything.
type FindingLedgerState string

const (
	// FindingLedgerOpen the scanner's authoritative set still reports the finding.
	FindingLedgerOpen FindingLedgerState = "open"
	// FindingLedgerReopened the series recorded the finding as fixed and then
	// observed it again.
	FindingLedgerReopened FindingLedgerState = "reopened"
	// FindingLedgerFixed the finding left under complete coverage and an unchanged
	// scanner execution identity. Engine evidence of a change, never proof of
	// correctness.
	FindingLedgerFixed FindingLedgerState = "fixed"
	// FindingLedgerNotObserved the finding left under bounded or partial coverage,
	// so its absence establishes nothing.
	FindingLedgerNotObserved FindingLedgerState = "not_observed"
	// FindingLedgerIgnored an entry in the project's ignore file matches the
	// finding and has not expired. The scanner still reports it; the project
	// decided not to act.
	FindingLedgerIgnored FindingLedgerState = "ignored"
	// FindingLedgerUnverified the finding left while the scanner's execution
	// identity was moving, so the pass behind its absence no longer applies. The
	// next full pass restores authority.
	FindingLedgerUnverified FindingLedgerState = "unverified"
)

var allFindingLedgerStateValues = []FindingLedgerState{
	FindingLedgerOpen,
	FindingLedgerReopened,
	FindingLedgerFixed,
	FindingLedgerNotObserved,
	FindingLedgerIgnored,
	FindingLedgerUnverified,
}

// AllFindingLedgerStateValues returns every FindingLedgerState in vocab order.
func AllFindingLedgerStateValues() []FindingLedgerState {
	return append([]FindingLedgerState(nil), allFindingLedgerStateValues...)
}
