// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/FindingIgnoreJustification.yaml

package api

// FindingIgnoreJustification — The OpenVEX justification for an advisory a project has judged not to apply, carried unchanged so an ignore exports as a VEX statement.
type FindingIgnoreJustification string

const (
	// FindingIgnoreJustificationComponentNotPresent the vulnerable component is
	// not in the artifact at all.
	FindingIgnoreJustificationComponentNotPresent FindingIgnoreJustification = "component_not_present"
	// FindingIgnoreJustificationVulnerableCodeNotPresent the component is present
	// but the vulnerable code was removed.
	FindingIgnoreJustificationVulnerableCodeNotPresent FindingIgnoreJustification = "vulnerable_code_not_present"
	// FindingIgnoreJustificationVulnerableCodeNotInExecutePath the vulnerable code
	// is present but nothing reaches it.
	FindingIgnoreJustificationVulnerableCodeNotInExecutePath FindingIgnoreJustification = "vulnerable_code_not_in_execute_path"
	// FindingIgnoreJustificationVulnerableCodeCannotBeControlledByAdversary the
	// vulnerable code runs but no adversary-controlled input reaches it.
	FindingIgnoreJustificationVulnerableCodeCannotBeControlledByAdversary FindingIgnoreJustification = "vulnerable_code_cannot_be_controlled_by_adversary"
	// FindingIgnoreJustificationInlineMitigationsAlreadyExist a mitigation in this
	// project already blocks the exploit.
	FindingIgnoreJustificationInlineMitigationsAlreadyExist FindingIgnoreJustification = "inline_mitigations_already_exist"
)

var allFindingIgnoreJustificationValues = []FindingIgnoreJustification{
	FindingIgnoreJustificationComponentNotPresent,
	FindingIgnoreJustificationVulnerableCodeNotPresent,
	FindingIgnoreJustificationVulnerableCodeNotInExecutePath,
	FindingIgnoreJustificationVulnerableCodeCannotBeControlledByAdversary,
	FindingIgnoreJustificationInlineMitigationsAlreadyExist,
}

// AllFindingIgnoreJustificationValues returns every FindingIgnoreJustification in vocab order.
func AllFindingIgnoreJustificationValues() []FindingIgnoreJustification {
	return append([]FindingIgnoreJustification(nil), allFindingIgnoreJustificationValues...)
}
