// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/LocalDataBucketId.yaml

package api

// LocalDataBucketId — Closed set of rebuildable local-data bucket ids.
type LocalDataBucketId string

const (
	LocalDataBucketWebIndex           LocalDataBucketId = "web_index"
	LocalDataBucketSourceObservations LocalDataBucketId = "source_observations"
	LocalDataBucketSourceCatalog      LocalDataBucketId = "source_catalog"
	LocalDataBucketFetchCache         LocalDataBucketId = "fetch_cache"
	LocalDataBucketOSVCache           LocalDataBucketId = "osv_cache"
	LocalDataBucketModelfeed          LocalDataBucketId = "modelfeed"
	LocalDataBucketPricingCache       LocalDataBucketId = "pricing_cache"
	LocalDataBucketBrowserCache       LocalDataBucketId = "browser_cache"
	LocalDataBucketExtensionCache     LocalDataBucketId = "extension_cache"
	LocalDataBucketDebugLogs          LocalDataBucketId = "debug_logs"
	LocalDataBucketScanScratch        LocalDataBucketId = "scan_scratch"
	LocalDataBucketWorkerBranches     LocalDataBucketId = "worker_branches"
	LocalDataBucketSessionScratch     LocalDataBucketId = "session_scratch"
)

var allLocalDataBucketIdValues = []LocalDataBucketId{
	LocalDataBucketWebIndex,
	LocalDataBucketSourceObservations,
	LocalDataBucketSourceCatalog,
	LocalDataBucketFetchCache,
	LocalDataBucketOSVCache,
	LocalDataBucketModelfeed,
	LocalDataBucketPricingCache,
	LocalDataBucketBrowserCache,
	LocalDataBucketExtensionCache,
	LocalDataBucketDebugLogs,
	LocalDataBucketScanScratch,
	LocalDataBucketWorkerBranches,
	LocalDataBucketSessionScratch,
}

// AllLocalDataBucketIdValues returns every LocalDataBucketId in vocab order.
func AllLocalDataBucketIdValues() []LocalDataBucketId {
	return append([]LocalDataBucketId(nil), allLocalDataBucketIdValues...)
}
