// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/NoticeTier.yaml

package api

// NoticeTier is a closed wire enum from docs/openapi/vocab.
type NoticeTier string

const (
	// NoticeTierCatastrophic blocks the whole window from boot. No in-app fix
	// exists, so navigation and onboarding are unreachable until the condition
	// clears.
	NoticeTierCatastrophic NoticeTier = "catastrophic"
	// NoticeTierNonCatastrophic renders at one scope while the app keeps working.
	NoticeTierNonCatastrophic NoticeTier = "non_catastrophic"
)

var allNoticeTierValues = []NoticeTier{
	NoticeTierCatastrophic,
	NoticeTierNonCatastrophic,
}

// AllNoticeTierValues returns every NoticeTier in vocab order.
func AllNoticeTierValues() []NoticeTier {
	return append([]NoticeTier(nil), allNoticeTierValues...)
}
