// Code generated by codegen-client-notices. DO NOT EDIT.

package api

const (
	NoticeCodeAttachmentScannedNoText      NoticeCode = "attachment_scanned_no_text"
	NoticeCodeGroundingEscalated           NoticeCode = "grounding_escalated"
	NoticeCodeHostFault                    NoticeCode = "host_fault"
	NoticeCodeModelRefused                 NoticeCode = "model_refused"
	NoticeCodeProjectMutationInProgress    NoticeCode = "project_mutation_in_progress"
	NoticeCodePromptFailed                 NoticeCode = "prompt_failed"
	NoticeCodeProviderContextTooSmall      NoticeCode = "provider_context_too_small"
	NoticeCodeProviderEmptyCompletion      NoticeCode = "provider_empty_completion"
	NoticeCodeProviderNotConfigured        NoticeCode = "provider_not_configured"
	NoticeCodeProviderOverloaded           NoticeCode = "provider_overloaded"
	NoticeCodeProviderRateLimited          NoticeCode = "provider_rate_limited"
	NoticeCodeProviderRequestRejected      NoticeCode = "provider_request_rejected"
	NoticeCodeProviderResponseInterrupted  NoticeCode = "provider_response_interrupted"
	NoticeCodeProviderServerError          NoticeCode = "provider_server_error"
	NoticeCodeProviderSilent               NoticeCode = "provider_silent"
	NoticeCodeProviderToolCallsInProse     NoticeCode = "provider_tool_calls_in_prose"
	NoticeCodeProviderToolCallsUnsupported NoticeCode = "provider_tool_calls_unsupported"
	NoticeCodeProviderUnreachable          NoticeCode = "provider_unreachable"
	NoticeCodeSessionPreparationFailed     NoticeCode = "session_preparation_failed"
	NoticeCodeSessionSpendCeilingReached   NoticeCode = "session_spend_ceiling_reached"
	NoticeCodeThinkingOverrideUnavailable  NoticeCode = "thinking_override_unavailable"
	NoticeCodeTurnCloseoutToolCall         NoticeCode = "turn_closeout_tool_call"
	NoticeCodeUserImageNotVisible          NoticeCode = "user_image_not_visible"
	NoticeCodeWorkflowActive               NoticeCode = "workflow_active"
	NoticeCodeWorkflowNotRunnable          NoticeCode = "workflow_not_runnable"
	NoticeCodeWorkflowVersionUnavailable   NoticeCode = "workflow_version_unavailable"
	NoticeCodeWorktreeStale                NoticeCode = "worktree_stale"
)

// NewSessionHostError constructs a typed host notice.
func NewSessionHostError(code NoticeCode) SessionHostError { return SessionHostError{Code: code} }
