// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/ProgressState.yaml

package api

// ProgressState — State of one checklist row. Derived by the host from the coordinator's markdown markers; the coordinator never writes these strings directly.
type ProgressState string

const (
	// ProgressStatePending fires for `- [ ]` — authored and not yet checked off.
	// Rows are ordered by the coordinator's document, which is a plan, not a claim
	// about what is executing: the first pending row is not necessarily the one
	// being worked.
	ProgressStatePending ProgressState = "pending"
	// ProgressStateDone fires for `- [x]` — checked off.
	ProgressStateDone ProgressState = "done"
	// ProgressStateNa fires for `- [~]` or `- [-]` — dropped from the run
	// without being done.
	ProgressStateNa ProgressState = "na"
)

var allProgressStateValues = []ProgressState{
	ProgressStatePending,
	ProgressStateDone,
	ProgressStateNa,
}

// AllProgressStateValues returns every ProgressState in vocab order.
func AllProgressStateValues() []ProgressState {
	return append([]ProgressState(nil), allProgressStateValues...)
}
