// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/ScanCategory.yaml

package api

// ScanCategory is a closed wire enum from docs/openapi/vocab.
type ScanCategory string

const (
	ScanCategorySecurity  ScanCategory = "security"
	ScanCategorySAST      ScanCategory = "sast"
	ScanCategorySCA       ScanCategory = "sca"
	ScanCategoryContainer ScanCategory = "container"
	ScanCategorySecret    ScanCategory = "secret"
	ScanCategoryLint      ScanCategory = "lint"
	ScanCategoryTypes     ScanCategory = "types"
	ScanCategoryStyle     ScanCategory = "style"
	ScanCategoryLicense   ScanCategory = "license"
	ScanCategoryCustom    ScanCategory = "custom"
)

var allScanCategoryValues = []ScanCategory{
	ScanCategorySecurity,
	ScanCategorySAST,
	ScanCategorySCA,
	ScanCategoryContainer,
	ScanCategorySecret,
	ScanCategoryLint,
	ScanCategoryTypes,
	ScanCategoryStyle,
	ScanCategoryLicense,
	ScanCategoryCustom,
}

// AllScanCategoryValues returns every ScanCategory in vocab order.
func AllScanCategoryValues() []ScanCategory {
	return append([]ScanCategory(nil), allScanCategoryValues...)
}
