// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/SourceTipState.yaml

package api

// SourceTipState is a closed wire enum from docs/openapi/vocab.
type SourceTipState string

const (
	SourceTipStateContent SourceTipState = "content"
	SourceTipStateAbsent  SourceTipState = "absent"
)

var allSourceTipStateValues = []SourceTipState{
	SourceTipStateContent,
	SourceTipStateAbsent,
}

// AllSourceTipStateValues returns every SourceTipState in vocab order.
func AllSourceTipStateValues() []SourceTipState {
	return append([]SourceTipState(nil), allSourceTipStateValues...)
}
