// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/SourceChangeOrigin.yaml

package api

// SourceChangeOrigin is a closed wire enum from docs/openapi/vocab.
type SourceChangeOrigin string

const (
	SourceChangeOriginAgent    SourceChangeOrigin = "agent"
	SourceChangeOriginUser     SourceChangeOrigin = "user"
	SourceChangeOriginExternal SourceChangeOrigin = "external"
)

var allSourceChangeOriginValues = []SourceChangeOrigin{
	SourceChangeOriginAgent,
	SourceChangeOriginUser,
	SourceChangeOriginExternal,
}

// AllSourceChangeOriginValues returns every SourceChangeOrigin in vocab order.
func AllSourceChangeOriginValues() []SourceChangeOrigin {
	return append([]SourceChangeOrigin(nil), allSourceChangeOriginValues...)
}
