// Code generated by codegen-wire-enums. DO NOT EDIT.
// Source: docs/openapi/vocab/SourceGitChangeKind.yaml

package api

// SourceGitChangeKind is a closed wire enum from docs/openapi/vocab.
type SourceGitChangeKind string

const (
	// SourceGitChangeCheckout HEAD moved by a branch switch or explicit checkout.
	SourceGitChangeCheckout SourceGitChangeKind = "checkout"
	// SourceGitChangeCommit A commit landed on the current branch.
	SourceGitChangeCommit SourceGitChangeKind = "commit"
	// SourceGitChangeAmend The branch tip was rewritten by commit --amend.
	SourceGitChangeAmend SourceGitChangeKind = "amend"
	// SourceGitChangeMerge A merge moved the branch tip.
	SourceGitChangeMerge SourceGitChangeKind = "merge"
	// SourceGitChangeRebase A rebase rewrote the branch.
	SourceGitChangeRebase SourceGitChangeKind = "rebase"
	// SourceGitChangePull A pull advanced the branch from its upstream.
	SourceGitChangePull SourceGitChangeKind = "pull"
	// SourceGitChangeReset The branch tip was reset to another commit.
	SourceGitChangeReset SourceGitChangeKind = "reset"
	// SourceGitChangeCherryPick A cherry-pick applied a commit onto the branch.
	SourceGitChangeCherryPick SourceGitChangeKind = "cherry_pick"
	// SourceGitChangeRevert A revert commit landed on the branch.
	SourceGitChangeRevert SourceGitChangeKind = "revert"
	// SourceGitChangeClone The repository's initial clone reflog entry.
	SourceGitChangeClone SourceGitChangeKind = "clone"
	// SourceGitChangeRepoAppeared A root that had no repository now has one.
	SourceGitChangeRepoAppeared SourceGitChangeKind = "repo_appeared"
	// SourceGitChangeRepoGone A root's repository was removed or became
	// unreadable.
	SourceGitChangeRepoGone SourceGitChangeKind = "repo_gone"
	// SourceGitChangeOther A reflog action outside the closed set; detail carries
	// the raw action.
	SourceGitChangeOther SourceGitChangeKind = "other"
	// SourceGitChangeUnknown HEAD moved but the reflog could not explain the
	// movement.
	SourceGitChangeUnknown SourceGitChangeKind = "unknown"
)

var allSourceGitChangeKindValues = []SourceGitChangeKind{
	SourceGitChangeCheckout,
	SourceGitChangeCommit,
	SourceGitChangeAmend,
	SourceGitChangeMerge,
	SourceGitChangeRebase,
	SourceGitChangePull,
	SourceGitChangeReset,
	SourceGitChangeCherryPick,
	SourceGitChangeRevert,
	SourceGitChangeClone,
	SourceGitChangeRepoAppeared,
	SourceGitChangeRepoGone,
	SourceGitChangeOther,
	SourceGitChangeUnknown,
}

// AllSourceGitChangeKindValues returns every SourceGitChangeKind in vocab order.
func AllSourceGitChangeKindValues() []SourceGitChangeKind {
	return append([]SourceGitChangeKind(nil), allSourceGitChangeKindValues...)
}
