// Command codegen-contribution-inventory projects the stock contribution pack.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lycaon/lycaon/internal/catalogview"
	"github.com/lycaon/lycaon/internal/contribframe"
	"github.com/lycaon/lycaon/internal/contribution"
	"github.com/lycaon/lycaon/internal/extpacks"
	"github.com/lycaon/lycaon/internal/mcp"
)

const stockPackID = "painted-wolf/platform"

const packContributionsRel = "config/packs/painted-wolf/platform/contributions"

var generatedRel = map[string]string{
	"handlers": "../lycaon-den/src/contributions/native-ui-handlers.generated.ts",
	"frame":    "../lycaon-den/src/contributions/stock-frame.generated.ts",
}

func main() {
	root := flag.String("root", ".", "repo-relative Go module root")
	check := flag.Bool("check", false, "fail when generated output is stale")
	flag.Parse()

	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, "codegen-contribution-inventory:", err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	units, err := loadUnits(filepath.Join(root, packContributionsRel))
	if err != nil {
		return err
	}
	set, err := contribution.Compile(contribution.CompileInput{
		Units: units,
		UnitProvider: func(string) (string, bool) {
			return stockPackID, true
		},
		PackPresent:  func(string) bool { return true },
		ProviderRank: func(string) contribution.ProviderRank { return contribution.RankStock },
	})
	if err != nil {
		return fmt.Errorf("compile stock contributions: %w", err)
	}

	frame, err := contribframe.Build(
		&catalogview.View{
			Catalog:       &extpacks.EffectiveCatalog{Revision: "stock"},
			Contributions: set,
		},
		&mcp.ResourceGeneration{Revision: "stock"},
	)
	if err != nil {
		return fmt.Errorf("build stock frame: %w", err)
	}

	frameJSON, err := json.MarshalIndent(contribframe.Project(frame), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal stock frame: %w", err)
	}

	outputs := map[string][]byte{
		"handlers": handlersFile(set),
		"frame":    frameFile(frameJSON),
	}
	for key, body := range outputs {
		path := filepath.Join(root, generatedRel[key])
		if check {
			current, err := os.ReadFile(path) // #nosec G304 -- generated path from the Taskfile
			if err != nil {
				return fmt.Errorf("read %s: %w", path, err)
			}
			if !bytes.Equal(current, body) {
				return fmt.Errorf("%s is stale; run ./task codegen:contribution-inventory", path)
			}
			continue
		}
		if err := os.WriteFile(path, body, 0o600); err != nil { // #nosec G306 -- generated artifact
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// loadUnits reads declarations under the stock contribution root.
func loadUnits(dir string) ([]contribution.Input, error) {
	var units []contribution.Input
	for _, kind := range contribution.Kinds() {
		kindDir := filepath.Join(dir, string(kind))
		entries, err := os.ReadDir(kindDir)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", kindDir, err)
		}
		for _, entry := range entries {
			if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
				continue
			}
			path := filepath.Join(kindDir, entry.Name())
			body, err := os.ReadFile(path) // #nosec G304 -- bundled pack path from the Taskfile
			if err != nil {
				return nil, fmt.Errorf("read %s: %w", path, err)
			}
			stem := strings.TrimSuffix(entry.Name(), ".yaml")
			units = append(units, contribution.Input{
				UnitID:         fmt.Sprintf("contributions/%s/%s", kind, stem),
				Kind:           kind,
				ProviderPackID: stockPackID,
				Body:           body,
				Origin:         path,
			})
		}
	}
	sort.Slice(units, func(i, j int) bool { return units[i].UnitID < units[j].UnitID })
	return units, nil
}

func handlersFile(set *contribution.Set) []byte {
	handlers := map[string]struct{}{}
	for _, command := range set.Commands() {
		if command.Action.Kind == contribution.ActionNativeUI && command.Action.Handler != "" {
			handlers[command.Action.Handler] = struct{}{}
		}
	}
	ids := make([]string, 0, len(handlers))
	for id := range handlers {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var b bytes.Buffer
	b.WriteString("// Generated by cmd/codegen-contribution-inventory. Do not edit by hand.\n")
	b.WriteString("// Stock native handler ids.\n")
	b.WriteString("export const NATIVE_UI_HANDLER_IDS: readonly string[] = [\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "  %q,\n", id)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("const HANDLER_ID_SET = new Set<string>(NATIVE_UI_HANDLER_IDS);\n\n")
	b.WriteString("/** Whether an id is a compiled stock handler id. */\n")
	b.WriteString("export function isNativeUIHandlerId(id: string): boolean {\n")
	b.WriteString("  return HANDLER_ID_SET.has(id);\n")
	b.WriteString("}\n")
	return b.Bytes()
}

func frameFile(frameJSON []byte) []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by cmd/codegen-contribution-inventory. Do not edit by hand.\n")
	b.WriteString("// Stock contribution frame.\n")
	b.WriteString(`import type { ContributionFrameResponse } from "../api/types.ts";` + "\n\n")
	b.WriteString("export const STOCK_FRAME: ContributionFrameResponse = ")
	b.Write(frameJSON)
	b.WriteString(";\n")
	return b.Bytes()
}
